export const MEMORY_CANDIDATE_STATUSES = ["pending", "quarantined", "rejected", "approved", "promoted"] as const;
export const MEMORY_ITEM_STATUSES = ["active", "stale", "revoked", "expired"] as const;
export type MemoryCandidateStatus = typeof MEMORY_CANDIDATE_STATUSES[number];
export type MemoryItemStatus = typeof MEMORY_ITEM_STATUSES[number];
export type MemoryCandidate = { candidateId: string; status: MemoryCandidateStatus; scope: string; version: number; updatedAt: string; request: Record<string, unknown>; quarantineReasons: string[] };
export type MemoryAuthorityItem = { item: { memoryItemId: string; status: MemoryItemStatus; scope: string; currentRevision: number; subject: Record<string, unknown> }; revision: { revision: number; contentHash: string; sourceId: string; sourceRevision: number; applicability: string[]; markings: string[]; effectiveAt: string } };
export type KnowledgeQueryResult = { status: "complete" | "degraded" | "blocked"; citations: Record<string, unknown>[]; chunks: { content: string; tokenCount: number; citation: Record<string, unknown> }[]; blockedReasons: string[]; assembledTokens: number };

function record(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError(`${label} 响应格式无效`); return value as Record<string, unknown>; }
function text(value: unknown, label: string): string { if (typeof value !== "string" || !value.trim()) throw new TypeError(`${label} 缺失`); return value; }
function integer(value: unknown, label: string): number { if (!Number.isSafeInteger(value) || (value as number) < 1) throw new TypeError(`${label} 无效`); return value as number; }
function strings(value: unknown, label: string): string[] { if (!Array.isArray(value) || value.some(v => typeof v !== "string" || !v.trim())) throw new TypeError(`${label} 无效`); return value as string[]; }
function enumValue<T extends readonly string[]>(value: unknown, allowed: T, label: string): T[number] { const result = text(value, label); if (!allowed.includes(result)) throw new TypeError(`${label} 未知`); return result as T[number]; }
function sha(value: unknown, label: string): string { const result = text(value, label); if (!/^[0-9a-f]{64}$/.test(result)) throw new TypeError(`${label} 不是 sha256`); return result; }

export function parseMemoryCandidate(value: unknown): MemoryCandidate { const v = record(value, "Candidate"); return { candidateId: text(v.candidateId, "candidateId"), status: enumValue(v.status, MEMORY_CANDIDATE_STATUSES, "status"), scope: text(v.scope, "scope"), version: integer(v.version, "version"), updatedAt: text(v.updatedAt, "updatedAt"), request: record(v.request, "request"), quarantineReasons: strings(v.quarantineReasons, "quarantineReasons") }; }
export function parseMemoryCandidates(value: unknown): MemoryCandidate[] { if (!Array.isArray(value)) throw new TypeError("Candidate 列表响应格式无效"); return value.map(parseMemoryCandidate); }
export function parseMemoryAuthorityItem(value: unknown): MemoryAuthorityItem { const v = record(value, "Memory"); const item = record(v.item, "item"); const revision = record(v.revision, "revision"); const currentRevision = integer(item.currentRevision, "currentRevision"); const exactRevision = integer(revision.revision, "revision"); if (currentRevision !== exactRevision) throw new TypeError("Memory current revision 不一致"); return { item: { memoryItemId: text(item.memoryItemId, "memoryItemId"), status: enumValue(item.status, MEMORY_ITEM_STATUSES, "memory status"), scope: text(item.scope, "memory scope"), currentRevision, subject: record(item.subject, "subject") }, revision: { revision: exactRevision, contentHash: sha(revision.contentHash, "contentHash"), sourceId: text(revision.sourceId, "sourceId"), sourceRevision: integer(revision.sourceRevision, "sourceRevision"), applicability: strings(revision.applicability, "applicability"), markings: strings(revision.markings, "markings"), effectiveAt: text(revision.effectiveAt, "effectiveAt") } }; }
export function parseMemoryAuthorityItems(value: unknown): MemoryAuthorityItem[] { if (!Array.isArray(value)) throw new TypeError("Memory 列表响应格式无效"); return value.map(parseMemoryAuthorityItem); }
export function parseKnowledgeQueryResult(value: unknown): KnowledgeQueryResult { const v = record(value, "KnowledgeQuery"); const status = enumValue(v.status, ["complete", "degraded", "blocked"] as const, "query status"); if (!Array.isArray(v.citations) || !Array.isArray(v.chunks)) throw new TypeError("citation/chunk 无效"); const reasons = strings(v.blockedReasons, "blockedReasons"); const tokens = typeof v.assembledTokens === "number" && Number.isSafeInteger(v.assembledTokens) && v.assembledTokens >= 0 ? v.assembledTokens : (() => { throw new TypeError("assembledTokens 无效"); })(); const chunks = v.chunks.map((raw, i) => { const chunk = record(raw, `chunk[${i}]`); return { content: text(chunk.content, "content"), tokenCount: integer(chunk.tokenCount, "tokenCount"), citation: record(chunk.citation, "citation") }; }); if (v.citations.length !== chunks.length || tokens !== chunks.reduce((sum, chunk) => sum + chunk.tokenCount, 0)) throw new TypeError("citation/chunk/token 不一致"); if (status === "blocked" && (chunks.length || !reasons.length)) throw new TypeError("blocked 结果无效"); return { status, citations: v.citations.map((c, i) => record(c, `citation[${i}]`)), chunks, blockedReasons: reasons, assembledTokens: tokens }; }
