import { getApiBase } from "../apiBase";
import { tenantAuthHeaders } from "../tenant";
import type { AnalystViewResponse, ContentCampaignViewResponse, CreatorContributionViewResponse, CreatorGrowthViewResponse, CustomerViewResponse, DispatchControlObservation, EcommerceWorkshopApiErrorBody, EcommerceWorkshopModuleListResponse, EcommerceWorkshopModuleReadinessResponse, MediaStudioViewResponse, ModuleHandoffCompileInput, ModuleHandoffCompileResponse, OperationCommandObservationResponse, OperationCommandReadinessResponse, OperationsViewResponse, PriceGovernanceViewResponse, ResponsibilityAssignmentObservation, SourceReadinessEnvelope, TaskCockpitActionReceiptResponse, TaskCockpitApprovalReviewResponse, TaskCockpitCheckpointPageResponse, TaskCockpitCoreQuery, TaskCockpitCoreResponse, TaskCockpitProductionContextResponse, TaskCockpitResponsibilityHandoffResponse, TaskCockpitRunDetailQuery, TaskCockpitSkillContributionResponse, TaskCockpitStepPageResponse, WorkshopSharedContextResponse } from "./contracts";
import { parseAnalystView, parseContentCampaignView, parseCreatorContributionView, parseCreatorGrowthView, parseCustomerView, parseDispatchControlObservation, parseEcommerceWorkshopApiError, parseEcommerceWorkshopModuleList, parseEcommerceWorkshopModuleReadiness, parseMediaStudioView, parseModuleHandoffCompile, parseOperationCommandObservation, parseOperationCommandReadiness, parseOperationsView, parsePriceGovernanceView, parseResponsibilityAssignmentObservation, parseSourceReadinessEnvelope, parseTaskCockpitActionReceipts, parseTaskCockpitApprovalReview, parseTaskCockpitCheckpoints, parseTaskCockpitCore, parseTaskCockpitProductionContext, parseTaskCockpitResponsibilityHandoffs, parseTaskCockpitSkillContributions, parseTaskCockpitSteps, parseWorkshopSharedContext } from "./parser";

type FetchImplementation = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
export type EcommerceWorkshopClientOptions = { fetch?: FetchImplementation; getBaseUrl?: () => string; getAuthHeaders?: () => Record<string, string> };
export class EcommerceWorkshopClientError extends Error {
  constructor(message: string, readonly options: { status: number; body: EcommerceWorkshopApiErrorBody; operationId: string }) { super(message); this.name = "EcommerceWorkshopClientError"; }
  get status(): number { return this.options.status; }
  get body(): EcommerceWorkshopApiErrorBody { return this.options.body; }
  get operationId(): string { return this.options.operationId; }
}
const MODULE_ID = /^ecommerce\.[a-z0-9]+(?:[.-][a-z0-9]+)*$/;
const RUN_ID = /^[^\s/\\\u0000]{1,200}$/;
const TASK_ID = /^[^\s/\\\u0000]{1,200}$/;
const COMMAND_OBSERVATION_REF = /^[^\s/\\\u0000]{1,300}$/;
const SHARED_CONTEXT_ID = /^[A-Za-z0-9_-]{32,128}$/;
const TASK_STATUSES = new Set(["pending", "planning", "awaiting_approval", "approved", "executing", "paused", "completed", "failed", "cancelled", "rolled_back"]);
function queryString(query: TaskCockpitRunDetailQuery & { status?: string }): string {
  const parameters = new URLSearchParams();
  if (query.status !== undefined) { if (!TASK_STATUSES.has(query.status)) throw new TypeError("status 无效"); parameters.set("status", query.status); }
  if (query.limit !== undefined) { if (!Number.isSafeInteger(query.limit) || query.limit < 1 || query.limit > 100) throw new TypeError("limit 无效"); parameters.set("limit", String(query.limit)); }
  if (query.cursor !== undefined) { if (!query.cursor || query.cursor !== query.cursor.trim() || query.cursor.length > 4096 || query.cursor.includes("\u0000")) throw new TypeError("cursor 无效"); parameters.set("cursor", query.cursor); }
  const value = parameters.toString(); return value ? `?${value}` : "";
}
export class EcommerceWorkshopClient {
  private readonly fetchImpl: FetchImplementation; private readonly baseUrl: () => string; private readonly authHeaders: () => Record<string, string>;
  constructor(options: EcommerceWorkshopClientOptions = {}) { this.fetchImpl = options.fetch ?? globalThis.fetch.bind(globalThis); this.baseUrl = options.getBaseUrl ?? getApiBase; this.authHeaders = options.getAuthHeaders ?? tenantAuthHeaders; }
  private async get(operationId: string, path: string): Promise<unknown> {
    let response: Response; try { response = await this.fetchImpl(`${this.baseUrl().replace(/\/$/, "")}${path}`, { method: "GET", headers: { ...this.authHeaders(), Accept: "application/json" } }); } catch (cause) { const message = cause instanceof Error ? cause.message : String(cause); throw new EcommerceWorkshopClientError(message, { status: 0, body: { code: "NETWORK", message, details: null, traceId: "" }, operationId }); }
    const payload: unknown = await response.json().catch(() => undefined); if (!response.ok) { const body = parseEcommerceWorkshopApiError(payload, response.statusText || `HTTP ${response.status}`); throw new EcommerceWorkshopClientError(body.message, { status: response.status, body, operationId }); } if (payload === undefined) throw new EcommerceWorkshopClientError("canonical API returned non-JSON success", { status: 0, body: { code: "INVALID_SUCCESS_RESPONSE", message: "canonical API returned non-JSON success", details: null, traceId: "" }, operationId }); return payload;
  }
  private async post(operationId: string, path: string, body: unknown): Promise<unknown> {
    let response: Response; try { response = await this.fetchImpl(`${this.baseUrl().replace(/\/$/, "")}${path}`, { method: "POST", headers: { ...this.authHeaders(), Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify(body) }); } catch (cause) { const message = cause instanceof Error ? cause.message : String(cause); throw new EcommerceWorkshopClientError(message, { status: 0, body: { code: "NETWORK", message, details: null, traceId: "" }, operationId }); }
    const payload: unknown = await response.json().catch(() => undefined); if (!response.ok) { const parsed = parseEcommerceWorkshopApiError(payload, response.statusText || `HTTP ${response.status}`); throw new EcommerceWorkshopClientError(parsed.message, { status: response.status, body: parsed, operationId }); } if (payload === undefined) throw new EcommerceWorkshopClientError("canonical API returned non-JSON success", { status: 0, body: { code: "INVALID_SUCCESS_RESPONSE", message: "canonical API returned non-JSON success", details: null, traceId: "" }, operationId }); return payload;
  }
  async listModules(): Promise<EcommerceWorkshopModuleListResponse> { return parseEcommerceWorkshopModuleList(await this.get("ecommerceWorkshopModulesList", "/v1/ecommerce-workshop/modules")); }
  async getModuleReadiness(moduleId: string): Promise<EcommerceWorkshopModuleReadinessResponse> { if (!MODULE_ID.test(moduleId)) throw new TypeError("moduleId 无效"); return parseEcommerceWorkshopModuleReadiness(await this.get("ecommerceWorkshopModuleReadinessGet", `/v1/ecommerce-workshop/modules/${encodeURIComponent(moduleId)}/readiness`)); }
  async getSourceReadiness(): Promise<SourceReadinessEnvelope> { return parseSourceReadinessEnvelope(await this.get("ecommerceWorkshopSourceReadinessGet", "/v1/ecommerce-workshop/source-readiness")); }
  async getOperationsView(): Promise<OperationsViewResponse> { return parseOperationsView(await this.get("ecommerceWorkshopOperationsViewGet", "/v1/ecommerce-workshop/views/operations")); }
  async getContentCampaignView(): Promise<ContentCampaignViewResponse> { return parseContentCampaignView(await this.get("ecommerceWorkshopContentCampaignViewGet", "/v1/ecommerce-workshop/views/content-campaign")); }
  async getCreatorGrowthView(): Promise<CreatorGrowthViewResponse> { return parseCreatorGrowthView(await this.get("ecommerceWorkshopCreatorGrowthViewGet", "/v1/ecommerce-workshop/views/creator-growth")); }
  async getCreatorContributionView(): Promise<CreatorContributionViewResponse> { return parseCreatorContributionView(await this.get("ecommerceWorkshopCreatorContributionViewGet", "/v1/ecommerce-workshop/views/creator-growth/contributions")); }
  async getMediaStudioView(): Promise<MediaStudioViewResponse> { return parseMediaStudioView(await this.get("ecommerceWorkshopMediaStudioViewGet", "/v1/ecommerce-workshop/views/media-studio")); }
  async getAnalystView(): Promise<AnalystViewResponse> { return parseAnalystView(await this.get("ecommerceWorkshopAnalystViewGet", "/v1/ecommerce-workshop/views/analyst")); }
  async getPriceGovernanceView(): Promise<PriceGovernanceViewResponse> { return parsePriceGovernanceView(await this.get("ecommerceWorkshopPriceGovernanceViewGet", "/v1/ecommerce-workshop/views/price-governance")); }
  async getCustomerView(): Promise<CustomerViewResponse> { return parseCustomerView(await this.get("ecommerceWorkshopCustomerViewGet", "/v1/ecommerce-workshop/views/customer")); }
  async getSharedContext(contextId: string): Promise<WorkshopSharedContextResponse> { if (!SHARED_CONTEXT_ID.test(contextId)) throw new TypeError("contextId 无效"); return parseWorkshopSharedContext(await this.get("ecommerceWorkshopSharedContextGet", `/v1/ecommerce-workshop/contexts/${encodeURIComponent(contextId)}`), contextId); }
  async getOperationCommandReadiness(): Promise<OperationCommandReadinessResponse> { return parseOperationCommandReadiness(await this.get("ecommerceWorkshopOperationCommandReadinessGet", "/v1/ecommerce-workshop/commands/operations/readiness")); }
  async getOperationCommandObservation(proposalId: string, leaseId: string): Promise<OperationCommandObservationResponse> { if (!COMMAND_OBSERVATION_REF.test(proposalId) || !COMMAND_OBSERVATION_REF.test(leaseId)) throw new TypeError("operation command observation ref 无效"); return parseOperationCommandObservation(await this.get("ecommerceWorkshopOperationCommandObservationGet", `/v1/ecommerce-workshop/commands/operations/observations/${encodeURIComponent(proposalId)}/leases/${encodeURIComponent(leaseId)}`), undefined, proposalId, leaseId); }
  async getTaskCockpitCore(query: TaskCockpitCoreQuery = {}): Promise<TaskCockpitCoreResponse> { return parseTaskCockpitCore(await this.get("ecommerceWorkshopTaskCockpitCoreGet", `/v1/ecommerce-workshop/views/task-cockpit${queryString(query)}`)); }
  async listTaskCockpitRunSteps(runId: string, query: TaskCockpitRunDetailQuery = {}): Promise<TaskCockpitStepPageResponse> { if (!RUN_ID.test(runId)) throw new TypeError("runId 无效"); return parseTaskCockpitSteps(await this.get("ecommerceWorkshopTaskCockpitRunStepsList", `/v1/ecommerce-workshop/views/task-cockpit/runs/${encodeURIComponent(runId)}/steps${queryString(query)}`)); }
  async listTaskCockpitRunCheckpoints(runId: string, query: TaskCockpitRunDetailQuery = {}): Promise<TaskCockpitCheckpointPageResponse> { if (!RUN_ID.test(runId)) throw new TypeError("runId 无效"); return parseTaskCockpitCheckpoints(await this.get("ecommerceWorkshopTaskCockpitRunCheckpointsList", `/v1/ecommerce-workshop/views/task-cockpit/runs/${encodeURIComponent(runId)}/checkpoints${queryString(query)}`)); }
  async getTaskCockpitRunProductionContext(runId: string): Promise<TaskCockpitProductionContextResponse> { if (!RUN_ID.test(runId)) throw new TypeError("runId 无效"); return parseTaskCockpitProductionContext(await this.get("ecommerceWorkshopTaskCockpitRunProductionContextGet", `/v1/ecommerce-workshop/views/task-cockpit/runs/${encodeURIComponent(runId)}/production-context`)); }
  async getTaskCockpitRunResponsibilityHandoffs(runId: string): Promise<TaskCockpitResponsibilityHandoffResponse> { if (!RUN_ID.test(runId)) throw new TypeError("runId 无效"); return parseTaskCockpitResponsibilityHandoffs(await this.get("ecommerceWorkshopTaskCockpitRunResponsibilityHandoffsGet", `/v1/ecommerce-workshop/views/task-cockpit/runs/${encodeURIComponent(runId)}/responsibility-handoffs`)); }
  async getResponsibilityAssignmentObservation(runId: string): Promise<ResponsibilityAssignmentObservation> { if (!RUN_ID.test(runId)) throw new TypeError("runId 无效"); return parseResponsibilityAssignmentObservation(await this.get("aipResponsibilityAssignmentObservationGet", `/v1/aip/responsibility-assignments/runs/${encodeURIComponent(runId)}/observation`)); }
  async getDispatchControlObservation(taskId: string): Promise<DispatchControlObservation> { if (!TASK_ID.test(taskId)) throw new TypeError("taskId 无效"); return parseDispatchControlObservation(await this.get("aipDispatchControlTaskObservationGet", `/v1/aip/dispatch-control/tasks/${encodeURIComponent(taskId)}/observation`)); }
  async compileTaskCockpitRunHandoff(runId: string, input: ModuleHandoffCompileInput): Promise<ModuleHandoffCompileResponse> { if (!RUN_ID.test(runId)) throw new TypeError("runId 无效"); return parseModuleHandoffCompile(await this.post("ecommerceWorkshopTaskCockpitRunHandoffCompile", `/v1/ecommerce-workshop/views/task-cockpit/runs/${encodeURIComponent(runId)}/handoffs/compile`, input)); }
  async getTaskCockpitRunApprovalReview(runId: string): Promise<TaskCockpitApprovalReviewResponse> { if (!RUN_ID.test(runId)) throw new TypeError("runId 无效"); return parseTaskCockpitApprovalReview(await this.get("ecommerceWorkshopTaskCockpitRunApprovalReviewIssuesGet", `/v1/ecommerce-workshop/views/task-cockpit/runs/${encodeURIComponent(runId)}/approval-review-issues`)); }
  async getTaskCockpitRunActionReceipts(runId: string): Promise<TaskCockpitActionReceiptResponse> { if (!RUN_ID.test(runId)) throw new TypeError("runId 无效"); return parseTaskCockpitActionReceipts(await this.get("ecommerceWorkshopTaskCockpitRunActionReceiptsGet", `/v1/ecommerce-workshop/views/task-cockpit/runs/${encodeURIComponent(runId)}/action-receipts`)); }
  async getTaskCockpitRunSkillContributions(runId: string): Promise<TaskCockpitSkillContributionResponse> { if (!RUN_ID.test(runId)) throw new TypeError("runId 无效"); return parseTaskCockpitSkillContributions(await this.get("ecommerceWorkshopTaskCockpitRunSkillContributionsGet", `/v1/ecommerce-workshop/views/task-cockpit/runs/${encodeURIComponent(runId)}/skill-contributions`)); }
}
export const ecommerceWorkshopClient = new EcommerceWorkshopClient();
