export const ECOMMERCE_WORKSHOP_SCHEMA_VERSION = "aos.ecommerce-workshop/v1" as const;

export type WorkshopReadiness = "available" | "degraded" | "disabled" | "blocked" | "unknown";
export type WorkshopDependencyState = WorkshopReadiness;
export type WorkshopDependencyType = "object" | "capability" | "aip_feature" | "data_scope" | "permission" | "registry" | "installation";

export type WorkshopTenant = { orgId: string; projectId: string };
export type WorkshopInstallationRef = {
  installationId: string;
  revision: number;
  compositionId: string;
  lockRevision: number;
  lockHash: string;
  overlayRevision: string;
};
export type WorkshopModuleRef = {
  publisher: string;
  bundleId: string;
  version: string;
  bundleContentHash: string;
  moduleArtifactRef: string;
  moduleArtifactHash: string;
};
export type WorkshopDependencyRef = {
  resourceType: string;
  resourceId: string;
  revision: string | null;
  contentHash: string | null;
  authority: string;
};
export type WorkshopReadinessBlocker = {
  dependencyType: WorkshopDependencyType;
  dependencyId: string;
  state: WorkshopDependencyState;
  reasonCode: string;
  recoverable: boolean;
  requiredAction: string;
  ref: WorkshopDependencyRef | null;
};
export type WorkshopPermissions = {
  roles: string[];
  markings: string[];
  dataScopes: string[];
  actionTypes: string[];
};
export type EcommerceWorkshopModule = {
  moduleId: string;
  displayName: string;
  menuLabel: string;
  route: string;
  slot: "workshop.primary.ecommerce";
  order: number;
  installationRef: WorkshopInstallationRef;
  moduleRef: WorkshopModuleRef;
  readiness: WorkshopReadiness;
  blockers: WorkshopReadinessBlocker[];
  permissions: WorkshopPermissions;
  requiredObjects: string[];
  requiredCapabilities: string[];
  requiredAipFeatures: string[];
  viewRefs: string[];
  evalPackRefs: string[];
  productionContractRefs: string[];
  responsibilityTemplateRefs: string[];
  impactCalculatorRefs: string[];
  legacyAssetRefs: string[];
  legacyRoutes: string[];
  minimumRuntimeVersion: string;
  lastReceiptRef: WorkshopDependencyRef | null;
};
export type EcommerceWorkshopModuleListResponse = {
  schemaVersion: typeof ECOMMERCE_WORKSHOP_SCHEMA_VERSION;
  tenant: WorkshopTenant;
  evaluatedAt: string;
  dataCutoff: string | null;
  items: EcommerceWorkshopModule[];
  count: number;
};
export type EcommerceWorkshopModuleReadinessResponse = {
  schemaVersion: typeof ECOMMERCE_WORKSHOP_SCHEMA_VERSION;
  tenant: WorkshopTenant;
  evaluatedAt: string;
  dataCutoff: string | null;
  item: EcommerceWorkshopModule;
};

export type EcommerceWorkshopApiErrorBody = {
  code: string;
  message: string;
  details: Record<string, unknown> | null;
  traceId: string;
};

export const SOURCE_READINESS_SCHEMA_VERSION = "aos.source-readiness/v1" as const;
export type SourceReadinessStatus = "ready" | "empty" | "degraded" | "unknown" | "stale" | "failed" | "blocked" | "forbidden";
export type SourceReadinessObservationStatus = "succeeded" | "failed" | "running" | "unknown";
export type SourceReadinessPolicyStatus = "pass" | "fail" | "unknown";
export type SourceReadinessExactRef = { resourceType: string; resourceId: string; revision: string; contentHash: string; authority: string };
export type SourceReadinessLatestRun = { runId: string | null; status: SourceReadinessObservationStatus; scheduledFor: string | null; startedAt: string | null; finishedAt: string | null; rowsWritten: number | null; errorCode: string | null };
export type SourceReadinessCounts = { sourceTotal: number | null; sourceActive: number | null; sourceDeleted: number | null; projectionTotal: number | null; unexplainedDelta: number | null };
export type SourceReadinessPolicyObservation = { status: SourceReadinessPolicyStatus; ruleRef: SourceReadinessExactRef | null; summary: string | null };
export type SourceReadinessItem = {
  schemaVersion: typeof SOURCE_READINESS_SCHEMA_VERSION;
  tenant: WorkshopTenant;
  sourceId: string;
  pipelineId: string;
  objectType: string;
  status: SourceReadinessStatus;
  checkedAt: string;
  observedAt: string | null;
  sourceEventAt: string | null;
  projectedAt: string | null;
  dataCutoff: string | null;
  freshnessExpiresAt: string | null;
  sourceConfigRef: SourceReadinessExactRef | null;
  mappingRef: SourceReadinessExactRef | null;
  schemaRef: SourceReadinessExactRef | null;
  maskingPolicyRef: SourceReadinessExactRef | null;
  freshnessPolicyRef: SourceReadinessExactRef | null;
  qualityPolicyRef: SourceReadinessExactRef | null;
  reconciliationPolicyRef: SourceReadinessExactRef | null;
  queryCapabilityRef: SourceReadinessExactRef | null;
  latestRun: SourceReadinessLatestRun;
  counts: SourceReadinessCounts;
  quality: SourceReadinessPolicyObservation;
  reconciliation: SourceReadinessPolicyObservation;
  reasons: string[];
  blockers: string[];
};
export type SourceReadinessEnvelope = {
  schemaVersion: typeof SOURCE_READINESS_SCHEMA_VERSION;
  tenant: WorkshopTenant;
  checkedAt: string;
  cutoffAt: string;
  status: SourceReadinessStatus;
  sources: SourceReadinessItem[];
  receiptRef: SourceReadinessExactRef | null;
};

export const TASK_COCKPIT_SCHEMA_VERSION = "aos.ecommerce-workshop.task-cockpit/v1" as const;
export type TaskCockpitTaskStatus = "pending" | "planning" | "awaiting_approval" | "approved" | "executing" | "paused" | "completed" | "failed" | "cancelled" | "rolled_back";
export type TaskCockpitRunStatus = "queued" | "running" | "pausing" | "paused" | "succeeded" | "failed" | "cancelled" | "unknown";
export type TaskCockpitStepStatus = "queued" | "running" | "succeeded" | "failed" | "skipped" | "unknown";
export type TaskCockpitPage = { limit: number; count: number; hasMore: boolean; nextCursor: string | null };
export type TaskCockpitBlocker = { code: string; severity: "warning" | "blocking"; dependency: string; requiredAction: string };
export type TaskCockpitRun = { runId: string; planRevisionId: string; status: TaskCockpitRunStatus; version: number; startedAt: string | null; finishedAt: string | null; createdAt: string; updatedAt: string };
export type TaskCockpitTask = { taskId: string; taskType: string; title: string; status: TaskCockpitTaskStatus; priority: number; version: number; currentPlanRevisionId: string | null; createdAt: string; updatedAt: string; run: TaskCockpitRun | null };
export type TaskCockpitStep = { stepRunId: string; stepKey: string; attempt: number; status: TaskCockpitStepStatus; tokenCount: number; costAmount: string; hasInputRefs: boolean; hasOutputRefs: boolean; hasError: boolean; leaseOwner: string | null; leaseExpiresAt: string | null; fence: number | null; assignmentLeaseId: string | null; inputHash: string | null; providerRequestFingerprint: string | null; safePoint: boolean; reconcileRequired: boolean; createdAt: string; updatedAt: string };
export type TaskCockpitCheckpoint = { checkpointId: string; sequence: number; schemaVersion: number; stepKey: string | null; stateHash: string; artifactCount: number; attempt: number | null; planRevisionId: string | null; inputHash: string | null; providerRequestFingerprint: string | null; dependencySnapshotHash: string | null; resumeReadiness: "checkpoint_exact" | "legacy_unverified"; createdAt: string };
export type TaskCockpitExactRevisionRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type TaskCockpitStageCompilation = { stageId: string; title: string; dependsOn: string[]; requiredSlotIds: string[]; applicabilityResult: "applicable" | "not_applicable"; evaluatedProfile: string };
export type TaskCockpitCoreResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; taskCutoff: string; stateConsistency: "current_state_per_page"; readiness: "degraded"; blockers: TaskCockpitBlocker[]; items: TaskCockpitTask[]; page: TaskCockpitPage };
export type TaskCockpitStepPageResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; evaluatedAt: string; membershipCutoff: string; stateConsistency: "current_state_per_page"; items: TaskCockpitStep[]; page: TaskCockpitPage };
export type TaskCockpitCheckpointPageResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; evaluatedAt: string; membershipCutoff: string; stateConsistency: "current_state_per_page"; items: TaskCockpitCheckpoint[]; page: TaskCockpitPage };
export type TaskCockpitProductionContextResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; planRef: TaskCockpitExactRevisionRef; stageTemplateRef: TaskCockpitExactRevisionRef; responsibilityPlanRef: TaskCockpitExactRevisionRef; compilerVersion: "w2c.v1"; stages: TaskCockpitStageCompilation[]; applicableStageIds: string[]; notApplicableStageIds: string[] };
export type TaskCockpitAssigneeResolutionReceipt = { receiptId: string; subjectId: string; kind: "agent_instance" | "human_principal" | "tool_binding" | "provider_capability_binding"; resourceId: string; version: number; status: "resolved" | "blocked"; blockerCodes: string[]; contentHash: string; snapshotHash: string | null; expiresAt: string | null; requiredCapabilityCount: number; bindingCount: number; snapshotStatus: "exact_fresh" | "legacy_unverified" | "blocked" | "stale"; createdAt: string };
export type TaskCockpitStructuralAssignee = { kind: TaskCockpitAssigneeResolutionReceipt["kind"]; resourceId: string; version: number; operationalReadiness: "unverified" | "resolved_at_observation" | "blocked_at_observation"; resolutionReceipts: TaskCockpitAssigneeResolutionReceipt[] };
export type TaskCockpitResponsibilitySlot = { slotId: string; responsibilityType: string; requiredCapabilityIds: string[]; returnStage: string; assignee: TaskCockpitStructuralAssignee };
export type TaskCockpitHandoffDecision = { decisionId: string; revision: number; decision: "accepted" | "rejected" | "request_more" | "returned"; reasonCode: string | null; gapCodes: string[]; contentHash: string; createdAt: string };
export type TaskCockpitHandoff = { handoffId: string; status: "issued" | "consumed" | "expired" | "revoked"; version: number; senderInstanceRef: TaskCockpitExactRevisionRef; receiverInstanceRef: TaskCockpitExactRevisionRef; expiresAt: string; consumedAt: string | null; createdAt: string; decisions: TaskCockpitHandoffDecision[] };
export type TaskCockpitResponsibilityHandoffResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; responsibilityPlanRef: TaskCockpitExactRevisionRef; profile: string; lifecycle: "draft" | "frozen" | "withdrawn" | "superseded"; compilationReadiness: "ready_at_compile"; compiledRequiredSlotIds: string[]; slots: TaskCockpitResponsibilitySlot[]; handoffs: TaskCockpitHandoff[] };
export type ResponsibilityRuntimeRef = { resourceType: "TaskRun" | "StepRun"; resourceId: string; version: number };
export type ResponsibilityAssigneeRef = { kind: TaskCockpitAssigneeResolutionReceipt["kind"]; resourceId: string; version: number };
export type ResponsibilityAssignmentBlocker = { code: string; dependency: string; requiredAction: string };
export type ResponsibilityAssignmentLease = { leaseId: string; taskRunRef: ResponsibilityRuntimeRef; stepRunRef: ResponsibilityRuntimeRef; attempt: number; owner: ResponsibilityAssigneeRef; fence: number; expiresAt: string };
export type ResponsibilityTakeoverRequest = { tenant: WorkshopTenant; requestId: string; taskRunRef: ResponsibilityRuntimeRef; stepRunRef: ResponsibilityRuntimeRef; attempt: number; sourceOwner: ResponsibilityAssigneeRef; targetOwner: ResponsibilityAssigneeRef; resolutionReceiptId: string; expectedFence: number; reasonCode: string; safetyState: "safe_checkpoint" | "active_lease" | "provider_outcome_unknown" | "step_terminal"; status: "pending" | "blocked"; blockers: ResponsibilityAssignmentBlocker[]; maker: string; createdAt: string; contentHash: string };
export type ResponsibilityTakeoverDecision = { tenant: WorkshopTenant; decisionId: string; requestId: string; revision: number; decision: "approved" | "rejected"; reasonCode: string; checker: string; assignmentLease: ResponsibilityAssignmentLease | null; createdAt: string; contentHash: string };
export type ResponsibilityAssignmentObservation = { tenant: WorkshopTenant; runRef: ResponsibilityRuntimeRef; takeoverRequests: ResponsibilityTakeoverRequest[]; takeoverDecisions: ResponsibilityTakeoverDecision[]; assignmentLeases: ResponsibilityAssignmentLease[]; evaluatedAt: string };
export type DispatchRuntimeRef = { resourceType: "Task" | "TaskRun" | "StepRun"; resourceId: string; version: number };
export type DispatchCommandKind = "module_handoff" | "responsibility_successor" | "runtime_takeover";
export type DispatchControlBlocker = { code: string; dependency: string; requiredAction: string };
export type DispatchCommandTarget = { commandKind: DispatchCommandKind; routeIdentity: "aip.module-handoff.issue" | "aip.responsibility.successor" | "aip.responsibility.takeover"; routePath: string; requiredPermission: string };
export type DispatchIntentObservation = { tenant: WorkshopTenant; intentId: string; revision: number; taskRef: DispatchRuntimeRef; taskRunRef: DispatchRuntimeRef | null; stepRunRef: DispatchRuntimeRef | null; responsibilityPlanRef: TaskCockpitExactRevisionRef | null; command: DispatchCommandTarget; sourceIdentity: string; targetIdentity: string; sourceSlotId: string | null; targetSlotId: string | null; expectedFence: number | null; reasonCode: string; policyRef: TaskCockpitExactRevisionRef; diff: Record<string, unknown>; impact: Record<string, unknown>; readiness: "ready" | "blocked"; blockers: DispatchControlBlocker[]; maker: string; createdAt: string; contentHash: string };
export type DispatchConfirmationObservation = { tenant: WorkshopTenant; confirmationId: string; intentId: string; intentRevision: number; intentContentHash: string; command: DispatchCommandTarget; invocationState: "canonical_command_required"; checker: string; createdAt: string; contentHash: string };
export type TaskPriorityDecisionObservation = { tenant: WorkshopTenant; decisionId: string; revision: number; taskRefBefore: DispatchRuntimeRef; taskRefAfter: DispatchRuntimeRef; oldPriority: number; newPriority: number; reasonCode: string; policyRef: TaskCockpitExactRevisionRef; actor: string; createdAt: string; contentHash: string };
export type DispatchControlObservation = { tenant: WorkshopTenant; taskRef: DispatchRuntimeRef; dispatchIntents: DispatchIntentObservation[]; confirmations: DispatchConfirmationObservation[]; priorityDecisions: TaskPriorityDecisionObservation[]; evaluatedAt: string };
export type ModuleHandoffCompileInput = { handoffId: string; taskRef: ResourceRef; runRef: ResourceRef; sourceModuleId: string; targetModuleId: string; sourceSlotId: string; targetSlotId: string; purpose: string; requestedOutcome: string; objectRefs: ResourceRef[]; artifactRefs: ResourceRef[]; evidenceRefs: ResourceRef[]; context: Record<string, unknown>; allowedContextFields: string[]; markings: string[]; expiresAt: string; correlationRef: ResourceRef | null };
export type ModuleHandoffCompileBlocker = { code: string; dependency: string; requiredAction: string };
export type ModuleHandoffCompileResponse = { schemaVersion: "aos.ecommerce-workshop.module-handoff-compile/v1"; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; responsibilityPlanRef: TaskCockpitExactRevisionRef; sourceModuleId: string; targetModuleId: string; sourceSlotId: string; targetSlotId: string; readiness: "ready" | "blocked"; blockers: ModuleHandoffCompileBlocker[]; issueCommand: IssueHandoffInput | null; sideEffects: { handoffsIssued: 0; tokensMinted: 0; decisionsCreated: 0; agentRunsStarted: 0 } };
export type TaskCockpitApprovalNavigation = { routeIdentity: "aip.task-plan" | "aip.action-drafts"; routePath: string; targetRef: TaskCockpitExactRevisionRef; commandReadiness: "read_only_fact" | "destination_reauthorization_required"; requiredPermission: string; blockerCodes: string[]; returnFocusToken: string };
export type TaskCockpitPlanApproval = { planRef: TaskCockpitExactRevisionRef; approvalStatus: "draft" | "approved" | "superseded" | "rejected"; approvedBy: string | null; approvedAt: string | null; navigation: TaskCockpitApprovalNavigation };
export type TaskCockpitApprovalDecision = { approvalEventId: string; proposalVersion: number; proposalHash: string; decision: "approved" | "rejected"; actorId: string; expiresAt: string | null; createdAt: string };
export type TaskCockpitActionApproval = { proposalRef: TaskCockpitExactRevisionRef; actionTypeId: string; status: "proposed" | "drafted" | "approved" | "rejected" | "expired" | "leased" | "executing" | "applied" | "failed" | "unknown" | "reconciled" | "compensated"; expiresAt: string; decisions: TaskCockpitApprovalDecision[]; navigation: TaskCockpitApprovalNavigation };
export type TaskCockpitReviewIssueEvent = { eventId: string; sequence: number; eventType: "opened" | "resolved" | "returned" | "superseded"; issueVersion: number; payloadHash: string; payload: Record<string, unknown> | null; payloadReadiness: "exact" | "legacy_unavailable"; actor: string; createdAt: string };
export type TaskCockpitReviewImpactDecision = { stepKey: string; action: "invalidate" | "reuse"; reason: string };
export type TaskCockpitReviewReturnLineage = { decisionId: string; issueVersion: number; runId: string; stepKey: string; stepRunId: string; attempt: number; decisionHash: string; impactDecisions: TaskCockpitReviewImpactDecision[]; impactReadiness: "exact" | "legacy_unavailable"; createdAt: string };
export type TaskCockpitReviewIssue = { issueId: string; version: number; status: "open" | "resolved" | "returned" | "superseded"; severity: "info" | "warning" | "error" | "critical"; ruleRef: TaskCockpitExactRevisionRef; artifactId: string; artifactHash: string; evalReportRef: TaskCockpitExactRevisionRef; returnStage: string; evidenceCount: number; lineageReadiness: "attempt_exact" | "attempt_unresolved"; returnLineage: TaskCockpitReviewReturnLineage | null; events: TaskCockpitReviewIssueEvent[] };
export type TaskCockpitApprovalReviewResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; planApproval: TaskCockpitPlanApproval; actionApprovals: TaskCockpitActionApproval[]; reviewIssues: TaskCockpitReviewIssue[]; actionApprovalCount: number; reviewIssueCount: number; unresolvedAttemptCount: number };
export type TaskCockpitActionReceipt = { receiptId: string; receiptKind: "initial" | "reconcile"; status: "accepted" | "applied" | "failed" | "unknown" | "reconciled"; leaseId: string; requestFingerprint: string; providerRequestPresent: boolean; evidenceCount: number; supersedesReceiptId: string | null; resolvedStatus: "applied" | "failed" | null; createdAt: string };
export type TaskCockpitActionExecution = { proposalRef: TaskCockpitExactRevisionRef; actionTypeId: string; proposalStatus: "proposed" | "drafted" | "approved" | "rejected" | "expired" | "leased" | "executing" | "applied" | "failed" | "unknown" | "reconciled" | "compensated"; leaseId: string | null; attempt: number | null; receipts: TaskCockpitActionReceipt[]; reconciliationState: "not_started" | "not_required" | "required" | "resolved" };
export type TaskCockpitActionReceiptResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; executions: TaskCockpitActionExecution[]; proposalCount: number; receiptCount: number; unknownReceiptCount: number; reconcileRequiredCount: number; reconciledReceiptCount: number };
export type TaskCockpitResourceRef = { resourceType: string; resourceId: string; revision: string | null; authority: string };
export type TaskCockpitSkillContributionReadiness = { status: "available" | "degraded" | "disabled" | "blocked" | "unknown" | "stale"; freshness: "fresh" | "stale" | "unverified"; reasonCodes: string[]; bindingStatus: "provisioning" | "active" | "suspended" | "revoked"; lastVerifiedAt: string | null; expiresAt: string | null };
export type TaskCockpitSkillRunProjection = { status: "queued" | "running" | "paused" | "succeeded" | "failed" | "cancelled" | "unknown"; startedAt: string | null; updatedAt: string; waitingFor: string[] };
export type TaskCockpitSkillContribution = { contributionId: string; taskRunRef: TaskCockpitResourceRef; agentRunRef: TaskCockpitResourceRef; moduleId: "ecommerce.task-cockpit"; roleRef: TaskCockpitExactRevisionRef; assigneeRef: TaskCockpitExactRevisionRef; skillRevisionRef: TaskCockpitExactRevisionRef; bindingRef: TaskCockpitResourceRef; logicRevisionRef: TaskCockpitExactRevisionRef; displayName: string; purpose: string; responsibility: string; readiness: TaskCockpitSkillContributionReadiness; runProjection: TaskCockpitSkillRunProjection; inputRefs: TaskCockpitResourceRef[]; outputArtifactRefs: TaskCockpitResourceRef[]; assumptions: string[]; uncertainties: string[]; conflicts: string[]; missingInputs: string[]; allowedCommands: [] };
export type TaskCockpitSkillContributionResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; projectionStatus: "ready" | "blocked"; blockerCodes: string[]; items: TaskCockpitSkillContribution[] };
export type TaskCockpitCoreQuery = { status?: TaskCockpitTaskStatus; limit?: number; cursor?: string };
export type TaskCockpitRunDetailQuery = { limit?: number; cursor?: string };

export const OPERATIONS_SCHEMA_VERSION = "aos.ecommerce-workshop.operations-view/v1" as const;
export type OperationsSliceId = "orders" | "orderLines" | "inventory" | "shipments" | "payments" | "aftersaleEvents" | "operationCases";
export type OperationsSliceStatus = "ready" | "blocked";
export type OperationsAuthorityRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type OperationsBlocker = { code: string; dependency: string; requiredAction: string };
export type OperationsCountLedger = { sourceTotal: number; attached: number; unmatched: number; conflicted: number };
export type OperationsSlice = { sliceId: OperationsSliceId; status: OperationsSliceStatus; dataCutoff: string; authorityRefs: OperationsAuthorityRef[]; blockers: OperationsBlocker[]; countLedger: OperationsCountLedger };
export type OperationsPage = { limit: number; count: number; hasMore: boolean; nextCursor: string | null };
export type OperationsViewResponse = { schemaVersion: typeof OPERATIONS_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; slices: OperationsSlice[]; page: OperationsPage };

export const CONTENT_CAMPAIGN_SCHEMA_VERSION = "aos.ecommerce-workshop.content-campaign-view/v1" as const;
export type ContentCampaignSliceId = "plan" | "calendar" | "content";
export type ContentCampaignAuthorityRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type ContentCampaignArtifactRef = { artifactId: string; contentHash: string };
export type ContentVariantProjection = ContentCampaignAuthorityRef & { resourceType: "ContentVariant"; revision: 1; intentRef: ContentCampaignAuthorityRef; masterArtifactRef: ContentCampaignArtifactRef; variantArtifactRef: ContentCampaignArtifactRef; relationId: string; relationType: "variant_of" };
export type ContentCampaignItem = ContentCampaignAuthorityRef | ContentVariantProjection;
export type ContentCampaignBlocker = { code: string; dependency: string; requiredAction: string };
export type ContentCampaignCountLedger = { eligible: number; attached: number; unmatched: number; conflicted: number };
export type ContentCampaignSlice = { sliceId: ContentCampaignSliceId; status: "ready" | "blocked"; dataCutoff: string; authorityRefs: ContentCampaignAuthorityRef[]; items: ContentCampaignItem[]; blockers: ContentCampaignBlocker[]; countLedger: ContentCampaignCountLedger };
export type ContentCampaignPage = { limit: number; count: number; hasMore: false; nextCursor: null };
export type ContentCampaignViewResponse = { schemaVersion: typeof CONTENT_CAMPAIGN_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; slices: ContentCampaignSlice[]; page: ContentCampaignPage };

export const CREATOR_GROWTH_SCHEMA_VERSION = "aos.ecommerce-workshop.creator-growth-view/v1" as const;
export type CreatorBusinessStage = "candidate" | "outreach" | "contract" | "delivery" | "relationship";
export type CreatorWorkflowPhase = "discovery" | "evidence" | "matching" | "batch_prepare" | "start";
export type CreatorGrowthRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string; workflowPhase: CreatorWorkflowPhase; businessStage: CreatorBusinessStage; piiRefs: string[] };
export type CreatorGrowthBlocker = { code: string; dependency: string; requiredAction: string };
export type CreatorGrowthLedger = { input: number; eligible: number; excluded: number; needsReview: number; unknown: number; deduplicated: number };
export type CreatorGrowthSlice = { businessStage: CreatorBusinessStage; workflowPhases: CreatorWorkflowPhase[]; status: "ready" | "blocked"; dataCutoff: string; authorityRefs: CreatorGrowthRef[]; blockers: CreatorGrowthBlocker[]; countLedger: CreatorGrowthLedger };
export type CreatorGrowthViewResponse = { schemaVersion: typeof CREATOR_GROWTH_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; slices: CreatorGrowthSlice[]; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };
export const CREATOR_PREPARE_SCHEMA_VERSION = "aos.ecommerce-workshop.creator-prepare/v1" as const;
export type CreatorPrepareExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type CreatorPrepareBatchItem = { candidateRef: CreatorPrepareExactRef; evidenceBundleRef: CreatorPrepareExactRef; matchObservationRef: CreatorPrepareExactRef; matchDecisionRef: CreatorPrepareExactRef; disposition: "eligible" | "excluded" | "needs_review" | "unknown" | "deduplicated"; reasonCodes: string[]; frequencyEligible: boolean; capacityEligible: boolean; budgetEligible: boolean };
export type CreatorBatchPreparation = { tenant: WorkshopTenant; batchId: string; revision: number; version: number; lifecycle: "prepared" | "frozen" | "stale"; exactRefs: Record<string, CreatorPrepareExactRef>; skillRefs: CreatorPrepareExactRef[]; items: CreatorPrepareBatchItem[]; itemHashes: string[]; ledger: CreatorGrowthLedger; externalEffectCount: 0; actionProposalCount: 0; executionLeaseCount: 0; priorContentHash: string | null; contentHash: string; createdBy: string; createdAt: string };
export type CreatorContributionViewResponse = { schemaVersion: typeof CREATOR_PREPARE_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; atomicSkillRefs: CreatorPrepareExactRef[]; logicRef: CreatorPrepareExactRef | null; primaryColleague: "导购顾问"; collaboratorColleagues: string[]; latestBatch: CreatorBatchPreparation | null; blockers: string[]; allowedCommands: ("PREPARE_CREATOR_BATCH" | "FREEZE_CREATOR_BATCH")[]; externalEffectsAllowed: false };
export const CREATOR_LIFECYCLE_SCHEMA_VERSION = "aos.ecommerce-workshop.creator-lifecycle/v1" as const;
export type CreatorActionKind = "outreach-message" | "sample-shipment" | "contract-signature" | "commission-change";
export type CreatorLaneOutcome = "prepared" | "accepted" | "applied" | "failed" | "unknown" | "disputed";
export type CreatorActionLaneBinding = { candidateRef: CreatorPrepareExactRef; actionKind: CreatorActionKind; actionTypeRef: CreatorPrepareExactRef; impactPreviewRef: CreatorPrepareExactRef; adapterCapabilityRef: CreatorPrepareExactRef; accountBindingRef: CreatorPrepareExactRef; budgetReservationRef: CreatorPrepareExactRef; approvalPolicyRef: CreatorPrepareExactRef; laneId: string; bindingHash: string; outcome: CreatorLaneOutcome; actionReceiptRef: CreatorPrepareExactRef | null; resolvedOutcome: CreatorLaneOutcome | null };
export type CreatorStartLedger = { eligibleItems: number; lanes: number; prepared: number; accepted: number; applied: number; failed: number; unknown: number; disputed: number; completed: number };
export type CreatorBatchStartDecision = { tenant: WorkshopTenant; decisionId: string; revision: number; version: number; lifecycle: "governance_prepared"; batchRef: CreatorPrepareExactRef; batchItemHashes: string[]; lanes: CreatorActionLaneBinding[]; ledger: CreatorStartLedger; operationalBlockers: string[]; externalEffectCount: 0; contentHash: string; startedBy: string; startedAt: string };
export type CreatorContractRevision = { tenant: WorkshopTenant; collaborationId: string; revision: number; candidateRef: CreatorPrepareExactRef; startDecisionRef: CreatorPrepareExactRef; priorContractRef: CreatorPrepareExactRef | null; termsHash: string; monetaryTermsRef: CreatorPrepareExactRef; lifecycle: "draft" | "reviewed" | "signed_observed" | "cancelled"; diffFields: string[]; actionReceiptRef: CreatorPrepareExactRef | null; contentHash: string; createdBy: string; createdAt: string };
export type CreatorDeliveryObservation = { tenant: WorkshopTenant; observationId: string; collaborationId: string; contractRef: CreatorPrepareExactRef; deliveryRef: CreatorPrepareExactRef; evidenceBundleRef: CreatorPrepareExactRef; sequence: number; status: "expected" | "in_transit" | "received" | "accepted" | "disputed"; contentHash: string; observedAt: string };
export type CreatorRelationshipRevision = { tenant: WorkshopTenant; relationshipId: string; revision: number; collaborationId: string; contractRef: CreatorPrepareExactRef; deliveryObservationRefs: CreatorPrepareExactRef[]; maturityPolicyRef: CreatorPrepareExactRef; maturityWindowEndsAt: string; status: "preliminary" | "mature" | "at_risk"; contentHash: string; createdAt: string };
export type CreatorLifecycleViewResponse = { schemaVersion: typeof CREATOR_LIFECYCLE_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; latestStart: CreatorBatchStartDecision | null; ledger: CreatorStartLedger; contracts: CreatorContractRevision[]; deliveries: CreatorDeliveryObservation[]; relationships: CreatorRelationshipRevision[]; blockers: string[]; allowedCommands: "START_CREATOR_BATCH_GOVERNANCE"[]; externalEffectsAllowed: false };

export const MEDIA_STUDIO_SCHEMA_VERSION = "aos.ecommerce-workshop.media-studio-view/v1" as const;
export type MediaStudioSliceId = "context" | "execution" | "delivery";
export type MediaReadinessAxis = "module" | "capability" | "assignee" | "provider" | "budget" | "publication";
export type MediaReadinessStatus = "ready" | "blocked" | "target" | "unknown" | "conflict" | "not_applicable";
export type MediaExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type MediaBlocker = { code: string; dependency: string; requiredAction: string };
export type MediaAxisReadiness = { axis: MediaReadinessAxis; status: MediaReadinessStatus; exactRef: MediaExactRef | null; targetContractRef: string | null; gaps: string[]; blockers: MediaBlocker[] };
export type MediaCountLedger = { denominator: number; ready: number; target: number; blocked: number; unknown: number; conflict: number; notApplicable: number };
export type MediaStudioSlice = { sliceId: MediaStudioSliceId; status: "ready" | "blocked"; dataCutoff: string; readinessAxes: MediaAxisReadiness[]; authorityRefs: MediaExactRef[]; blockers: MediaBlocker[]; countLedger: MediaCountLedger };
export type MediaStudioViewResponse = { schemaVersion: typeof MEDIA_STUDIO_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; slices: MediaStudioSlice[]; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };

export const ANALYST_SCHEMA_VERSION = "aos.ecommerce-workshop.analyst-view/v1" as const;
export type AnalystViewId = "overview" | "drivers" | "diagnosis" | "plan" | "effects" | "evidence" | "quality";
export type AnalystReadinessAxis = "metric_query" | "model" | "eval" | "plan_materialization" | "professional_handoff";
export type AnalystReadinessStatus = "ready" | "blocked" | "unknown" | "not_applicable";
export type AnalystExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type AnalystBlocker = { code: string; dependency: string; requiredAction: string };
export type AnalystAxisReadiness = { axis: AnalystReadinessAxis; status: AnalystReadinessStatus; exactRef: AnalystExactRef | null; blockers: AnalystBlocker[] };
export type AnalystMetricValue = { metricId: string; status: "ready" | "unknown" | "blocked" | "conflict"; definitionRef: AnalystExactRef | null; observationRef: AnalystExactRef | null; value: number | null; unit: string | null; grain: string | null; window: string | null; timezone: string | null; cohortFilter: string | null; numerator: number | null; denominator: number | null; sourceRunRef: AnalystExactRef | null; qualityRef: AnalystExactRef | null; reconciliationRef: AnalystExactRef | null; lineageId: string | null; blockers: AnalystBlocker[] };
export type AnalystCountLedger = { denominator: number; ready: number; unknown: number; blocked: number; conflict: number };
export type AnalystViewSlice = { viewId: AnalystViewId; status: "ready" | "blocked"; resourceRevision: number; dataCutoff: string; readinessAxes: AnalystAxisReadiness[]; metrics: AnalystMetricValue[]; authorityRefs: AnalystExactRef[]; blockers: AnalystBlocker[]; countLedger: AnalystCountLedger };
export type AnalystViewResponse = { schemaVersion: typeof ANALYST_SCHEMA_VERSION; tenant: WorkshopTenant; resourceRevision: number; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; views: AnalystViewSlice[]; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };

export const PRICE_GOVERNANCE_SCHEMA_VERSION = "aos.ecommerce-workshop.price-governance-view/v1" as const;
export type PriceGovernanceViewId = "governance" | "competitor" | "schedule";
export type PriceReadinessAxis = "collection" | "match" | "policy_case" | "notification" | "advice_handoff" | "repricing";
export type PriceReadinessStatus = "ready" | "blocked" | "unknown" | "not_applicable" | "disabled";
export type PriceExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type PriceBlocker = { code: string; dependency: string; requiredAction: string };
export type PriceAxisReadiness = { axis: PriceReadinessAxis; status: PriceReadinessStatus; exactRef: PriceExactRef | null; blockers: PriceBlocker[] };
export type PriceQuoteBasis = { basis: "list" | "landed"; skuRef: PriceExactRef; bundleRef: PriceExactRef | null; quantity: number; unit: string; currency: string; tax: "included" | "excluded" | "unknown"; shipping: "included" | "excluded" | "unknown"; promotionCondition: string; effectiveFrom: string; effectiveUntil: string | null };
export type PriceObservation = { observationRef: PriceExactRef; market: string; amount: number | null; quoteBasis: PriceQuoteBasis; observedAt: string; freshness: "fresh" | "stale" | "unknown"; license: "allowed" | "denied" | "unknown"; comparability: "comparable" | "not_comparable" | "unknown"; matchStatus: "confirmed" | "preliminary" | "not_matched" | "unknown"; originalRefs: PriceExactRef[]; mergedOriginalRefs: PriceExactRef[]; blockers: PriceBlocker[] };
export type PriceCountLedger = { input: number; eligible: number; excluded: number; needsReview: number; unknown: number; deduplicated: number };
export type PriceGovernanceViewSlice = { viewId: PriceGovernanceViewId; status: "ready" | "blocked"; resourceRevision: number; dataCutoff: string; readinessAxes: PriceAxisReadiness[]; observations: PriceObservation[]; authorityRefs: PriceExactRef[]; blockers: PriceBlocker[]; countLedger: PriceCountLedger };
export type PriceGovernanceViewResponse = { schemaVersion: typeof PRICE_GOVERNANCE_SCHEMA_VERSION; tenant: WorkshopTenant; resourceRevision: number; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; views: PriceGovernanceViewSlice[]; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };
export const PRICE_RESEARCH_SCHEMA_VERSION = "aos.ecommerce-workshop.price-research/v1" as const;
export type PriceResearchBatchLedger = PriceCountLedger;
export type PriceResearchBatchSummary = { batchId: string; revision: number; version: number; lifecycle: "prepared" | "frozen" | "stale"; exactRefs: Record<string, PriceExactRef>; skillRefs: PriceExactRef[]; itemCount: number; itemHashes: string[]; ledger: PriceResearchBatchLedger; providerCallCount: 0; researchJobCount: 0; notificationCount: 0; actionProposalCount: 0; repricingCount: 0; externalEffectCount: 0; priorContentHash: string | null; contentHash: string; createdBy: string; createdAt: string };
export type PriceResearchContributionViewResponse = { schemaVersion: typeof PRICE_RESEARCH_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; atomicSkillRefs: PriceExactRef[]; logicRef: PriceExactRef | null; primaryColleague: "数据参谋"; collaboratorColleagues: ["活动策划师", "导购顾问"]; latestBatch: PriceResearchBatchSummary | null; blockers: string[]; allowedCommands: ("PREPARE_PRICE_RESEARCH_BATCH" | "FREEZE_PRICE_RESEARCH_BATCH")[]; externalEffectsAllowed: false };
export const PRICE_DISPOSITION_SCHEMA_VERSION = "aos.ecommerce-workshop.price-disposition/v1" as const;
export type PriceDispositionKind = "internal_advice" | "external_notice" | "module_handoff" | "repricing";
export type PriceDispositionOutcome = "prepared" | "adopted" | "rejected" | "accepted" | "applied" | "failed" | "unknown" | "disputed";
export type PriceDispositionSummary = { dispositionId: string; revision: number; version: number; lifecycle: "prepared" | "frozen" | "stale"; kind: PriceDispositionKind; executionAllowed: false; providerCallCount: 0; notificationSendCount: 0; repricingCount: 0; externalEffectCount: 0 };
export type PriceDispositionObservationSummary = { observationId: string; outcome: PriceDispositionOutcome; resolvedOutcome: PriceDispositionOutcome | null; observedAt: string };
export type PriceDispositionContributionViewResponse = { schemaVersion: typeof PRICE_DISPOSITION_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; atomicSkillIds: ["compile-price-case", "prepare-price-advice", "prepare-price-notice", "prepare-price-handoff", "evaluate-reprice-specialized-gate"]; logicId: "ecommerce-price-governance"; primaryColleague: "数据参谋"; collaboratorColleagues: ["活动策划师", "导购顾问"]; caseCount: number; dispositionCounts: Record<PriceDispositionKind, number>; latestDisposition: PriceDispositionSummary | null; latestObservation: PriceDispositionObservationSummary | null; blockers: string[]; allowedCommands: ("COMPILE_PRICE_CASE" | "CREATE_PRICE_DISPOSITION_CONTRACT" | "PREPARE_PRICE_DISPOSITION" | "FREEZE_PRICE_DISPOSITION" | "RECORD_PRICE_DISPOSITION_OBSERVATION")[]; repricingEnabled: false; externalEffectsAllowed: false };

export const CUSTOMER_VIEW_SCHEMA_VERSION = "aos.ecommerce-workshop.customer-view/v1" as const;
export type CustomerViewId = "customer" | "segment" | "journey" | "dialogue";
export type CustomerReadinessAxis = "customer_lite" | "consent" | "segment" | "journey" | "dialogue" | "outreach_batch";
export type CustomerReadinessStatus = "ready" | "blocked" | "unknown" | "not_applicable";
export type CustomerExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type CustomerBlocker = { code: string; dependency: string; requiredAction: string };
export type CustomerAxisReadiness = { axis: CustomerReadinessAxis; status: CustomerReadinessStatus; exactRef: CustomerExactRef | null; blockers: CustomerBlocker[] };
export type CustomerProjection = { customerRef: CustomerExactRef; purpose: string; disclosure: "allowed" | "blocked" | "unknown"; freshness: "fresh" | "stale" | "unknown"; quality: "pass" | "fail" | "unknown"; consent: "granted" | "withdrawn" | "expired" | "conflict" | "unknown"; retention: "active" | "expired" | "unknown"; kAnonymitySatisfied: boolean | null; originalRefs: CustomerExactRef[]; blockers: CustomerBlocker[] };
export type CustomerCountLedger = { input: number; eligible: number; excluded: number; unknown: number; deduplicated: number };
export type CustomerViewSlice = { viewId: CustomerViewId; status: "ready" | "blocked"; resourceRevision: number; dataCutoff: string; readinessAxes: CustomerAxisReadiness[]; items: CustomerProjection[]; authorityRefs: CustomerExactRef[]; blockers: CustomerBlocker[]; countLedger: CustomerCountLedger };
export type CustomerViewResponse = { schemaVersion: typeof CUSTOMER_VIEW_SCHEMA_VERSION; tenant: WorkshopTenant; resourceRevision: number; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; views: CustomerViewSlice[]; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };
export const CUSTOMER_LIFECYCLE_SCHEMA_VERSION = "aos.ecommerce-workshop.customer-lifecycle/v1" as const;
export type CustomerDialogueBatchLedger = { input: number; eligible: number; excluded: number; needsReview: number; unknown: number; deduplicated: number };
export type CustomerDialogueBatchSummary = { batchId: string; revision: number; version: number; lifecycle: "prepared" | "frozen" | "stale"; ledger: CustomerDialogueBatchLedger; contactResolutionCount: 0; actionCount: 0; providerCallCount: 0; sendCount: 0; externalEffectCount: 0; contentHash: string; createdAt: string };
export type CustomerLifecycleContributionViewResponse = { schemaVersion: typeof CUSTOMER_LIFECYCLE_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; atomicSkillIds: ["build-evidence-pack", "segment-entities", "consent-and-purpose-check", "needs-discovery", "customer-journey-plan", "response-or-outreach-draft", "verify-claims", "review-outcomes"]; logicId: "ecommerce-customer-relationship"; primaryColleague: "私域管家"; collaboratorColleagues: ["内容官", "客服专员", "导购顾问", "数据参谋"]; consentPolicyCount: number; segmentCount: number; journeyCount: number; dialogueCount: number; latestBatch: CustomerDialogueBatchSummary | null; blockers: string[]; allowedCommands: ("CREATE_CUSTOMER_CONSENT_POLICY" | "CREATE_CUSTOMER_SEGMENT" | "CREATE_CUSTOMER_JOURNEY" | "CREATE_CUSTOMER_DIALOGUE" | "PREPARE_CUSTOMER_DIALOGUE_BATCH" | "FREEZE_CUSTOMER_DIALOGUE_BATCH")[]; contactResolutionAllowed: false; startAllowed: false; sendAllowed: false; externalEffectsAllowed: false };
export const CUSTOMER_CONTACT_SCHEMA_VERSION = "aos.ecommerce-workshop.customer-contact-governance/v1" as const;
export type CustomerContactLedger = { frozenEligible: number; reserved: number; skippedWithdrawn: number; cancelled: number; accepted: number; applied: number; failed: number; unknown: number; disputed: number };
export type CustomerContactStartSummary = { decisionId: string; revision: number; lifecycle: "governance_prepared"; startSequence: number; itemCount: number; ledger: CustomerContactLedger; operationalBlockers: string[]; contactResolutionCount: 0; providerCallCount: 0; sendCount: 0; externalEffectCount: 0; contentHash: string; startedAt: string };
export type CustomerContactContributionViewResponse = { schemaVersion: typeof CUSTOMER_CONTACT_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; atomicSkillIds: ["build-evidence-pack", "segment-entities", "consent-and-purpose-check", "needs-discovery", "customer-journey-plan", "response-or-outreach-draft", "verify-claims", "review-outcomes"]; logicId: "ecommerce-customer-relationship"; primaryColleague: "私域管家"; collaboratorColleagues: ["内容官", "客服专员", "导购顾问", "数据参谋"]; latestStart: CustomerContactStartSummary | null; ledger: CustomerContactLedger; frequencyPolicyCount: number; withdrawalCount: number; blockers: string[]; allowedCommands: ("CREATE_CUSTOMER_FREQUENCY_POLICY" | "RECORD_CUSTOMER_CONSENT_WITHDRAWAL" | "START_CUSTOMER_DIALOGUE_BATCH_GOVERNANCE" | "RECORD_CUSTOMER_DISPATCH_OBSERVATION")[]; permitRedemptionAllowed: false; contactResolutionAllowed: false; providerDispatchAllowed: false; sendAllowed: false; externalEffectsAllowed: false };

export const THREE_MODULE_CLOSURE_SCHEMA_VERSION = "aos.ecommerce-workshop.three-module-closure/v1" as const;
export type ThreeModuleId = "creator" | "price" | "customer";
export type ThreeModuleExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type ThreeModuleClosureLedger = { total: number; inProgress: number; succeeded: number; failed: number; unknown: number; disputed: number; skipped: number; state: "empty" | "in_progress" | "completed" | "failed" | "partial" | "unknown" };
export type ThreeModuleClosureSummary = { closureId: string; revision: 1; module: ThreeModuleId; sourceRef: ThreeModuleExactRef; items: { itemKey: string; originalStatus: string; canonicalOutcome: "in_progress" | "succeeded" | "failed" | "unknown" | "disputed" | "skipped"; originalRef: ThreeModuleExactRef; receiptRef: ThreeModuleExactRef | null }[]; ledger: ThreeModuleClosureLedger; contentHash: string; compiledBy: string; compiledAt: string };
export type ThreeModuleUsageSummary = { bindingId: string; closureRef: ThreeModuleExactRef; usageReceiptRef: ThreeModuleExactRef; lineageId: string; quality: "measured" | "estimated" | "unknown"; quantity: number | null; unit: string; adjustmentTotal: number; settlement: "measured" | "estimated" | "unknown"; contentHash: string; boundAt: string };
export type ThreeModuleEffectSummary = { bindingId: string; closureRef: ThreeModuleExactRef; effectReviewRef: ThreeModuleExactRef; maturityStatus: "immature" | "mature" | "insufficient" | "unknown"; accepted: boolean; effectCompleted: boolean; sampleCount: number; minSample: number; cutoffAt: string; observedAt: string; contentHash: string; boundAt: string };
export type ThreeModuleHandoffSummary = { bindingId: string; closureRef: ThreeModuleExactRef; handoffRef: ThreeModuleExactRef; transportStatus: string; businessDecision: "accepted" | "rejected" | "request_more" | "returned" | null; taskRef: Record<string, unknown>; taskRunRef: Record<string, unknown>; disclosureRefCount: number; contentHash: string; boundAt: string };
export type ThreeModuleClosureContributionViewResponse = { schemaVersion: typeof THREE_MODULE_CLOSURE_SCHEMA_VERSION; tenant: WorkshopTenant; module: ThreeModuleId; evaluatedAt: string; atomicSkillIds: string[]; logicId: string; primaryColleague: string; collaboratorColleagues: string[]; latestClosure: ThreeModuleClosureSummary | null; latestUsage: ThreeModuleUsageSummary | null; latestEffect: ThreeModuleEffectSummary | null; latestHandoff: ThreeModuleHandoffSummary | null; blockers: string[]; allowedCommands: ["COMPILE_THREE_MODULE_CLOSURE", "BIND_CANONICAL_USAGE", "BIND_CANONICAL_EFFECT_REVIEW", "BIND_CANONICAL_HANDOFF"]; handoffConsumeAllowed: false; memoryPromotionAllowed: false; externalEffectsAllowed: false };

export const OPERATION_COMMAND_READINESS_SCHEMA_VERSION = "aos.ecommerce-workshop.operation-command-readiness/v1" as const;
export type OperationCommandId = "classify" | "createCase" | "changeMembership" | "manageSla" | "automationKill" | "refund";
export type OperationCommandBlocker = { code: string; dependency: string; requiredAction: string };
export type OperationCommandDescriptor = { commandId: OperationCommandId; label: string; status: "ready" | "blocked"; risk: "controlled" | "high"; sideEffect: "internalAuthority" | "external"; blockers: OperationCommandBlocker[] };
export type OperationCommandReadinessResponse = { schemaVersion: typeof OPERATION_COMMAND_READINESS_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; commands: OperationCommandDescriptor[] };

export const OPERATION_COMMAND_OBSERVATION_SCHEMA_VERSION = "aos.ecommerce-workshop.operation-command-observation/v1" as const;
export type ObservableOperationCommandId = Exclude<OperationCommandId, "refund">;
export type OperationCommandObservationStatus = "notStarted" | "accepted" | "applied" | "failed" | "unknown" | "reconciled";
export type OperationCommandObservationResponse = {
  schemaVersion: typeof OPERATION_COMMAND_OBSERVATION_SCHEMA_VERSION;
  tenant: WorkshopTenant;
  proposalId: string;
  leaseId: string;
  commandId: ObservableOperationCommandId;
  status: OperationCommandObservationStatus;
  proposalHash: string;
  receiptId: string | null;
  requestFingerprint: string | null;
  operationReceiptId: string | null;
  replayAllowed: false;
};

export const SHARED_CONTEXT_SCHEMA_VERSION = "aos.ecommerce-workshop.shared-context/v1" as const;
export type WorkshopSharedRef = { authority: string; resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string | null };
export type WorkshopSharedBlocker = { code: string; dependency: string; requiredAction: string };
export type WorkshopSharedContext = {
  contextId: string;
  status: "ready" | "blocked" | "expired" | "forbidden" | "stale" | "unknown";
  sourceModuleId: string | null;
  sourceViewId: string | null;
  sourceRoute: string | null;
  primaryRef: WorkshopSharedRef | null;
  relatedRefs: WorkshopSharedRef[];
  purpose: string | null;
  permissionDecisionRef: WorkshopSharedRef | null;
  disclosurePolicyRef: WorkshopSharedRef | null;
  markings: string[];
  disclosure: "allowed" | "blocked" | "unknown";
  evaluatedAt: string;
  dataCutoff: string | null;
  expiresAt: string;
  freshness: "fresh" | "stale" | "unknown";
  readiness: "ready" | "blocked" | "unknown";
  filterSummary: string | null;
  lineageRefs: WorkshopSharedRef[];
  blockers: WorkshopSharedBlocker[];
};
export type WorkshopTimelineEvent = { eventKey: string; eventType: "task" | "handoff" | "action" | "evidence" | "receipt" | "usage" | "effect"; sourceRef: WorkshopSharedRef; authoritySequence: number; occurredAt: string; recordedAt: string; actorKind: "system" | "human" | "agent"; safeSummary: string; status: string; reasonCode: string | null; causationRef: string | null; correlationRef: string | null; attempt: number | null; receiptRef: WorkshopSharedRef | null; originalRefs: WorkshopSharedRef[]; late: boolean; duplicate: boolean; superseded: boolean; unknown: boolean; reconciled: boolean; stale: boolean };
export type WorkshopNavigationTarget = { targetId: string; status: "available" | "forbidden" | "expired" | "uninstalled" | "disabled" | "stale" | "unresolved"; moduleId: string | null; viewId: string | null; route: string | null; subjectRef: WorkshopSharedRef | null; filterSummary: string | null; focusAnchor: string | null; scrollAnchor: string | null; blockers: WorkshopSharedBlocker[] };
export type WorkshopSharedContextResponse = { schemaVersion: typeof SHARED_CONTEXT_SCHEMA_VERSION; tenant: WorkshopTenant; context: WorkshopSharedContext; timeline: WorkshopTimelineEvent[]; navigationTargets: WorkshopNavigationTarget[]; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };
import type { IssueHandoffInput, ResourceRef } from "../aipAgentControl/contracts";
