export const ECOMMERCE_WORKSHOP_SCHEMA_VERSION = "aos.ecommerce-workshop/v1" as const;

export type WorkshopReadiness = "available" | "degraded" | "disabled" | "blocked" | "unknown";
export type WorkshopDependencyState = WorkshopReadiness;
export type WorkshopDependencyType = "object" | "capability" | "aip_feature" | "data_scope" | "permission" | "registry" | "installation";

export type WorkshopTenant = { orgId: string; projectId: string };
export type WorkshopInstallationRef = {
  installationId: string;
  revision: number;
  compositionId: string;
  lockRevision: number;
  lockHash: string;
  overlayRevision: string;
};
export type WorkshopModuleRef = {
  publisher: string;
  bundleId: string;
  version: string;
  bundleContentHash: string;
  moduleArtifactRef: string;
  moduleArtifactHash: string;
};
export type WorkshopDependencyRef = {
  resourceType: string;
  resourceId: string;
  revision: string | null;
  contentHash: string | null;
  authority: string;
};
export type WorkshopReadinessBlocker = {
  dependencyType: WorkshopDependencyType;
  dependencyId: string;
  state: WorkshopDependencyState;
  reasonCode: string;
  recoverable: boolean;
  requiredAction: string;
  ref: WorkshopDependencyRef | null;
};
export type WorkshopPermissions = {
  roles: string[];
  markings: string[];
  dataScopes: string[];
  actionTypes: string[];
};
export type EcommerceWorkshopModule = {
  moduleId: string;
  displayName: string;
  menuLabel: string;
  route: string;
  slot: "workshop.primary.ecommerce";
  order: number;
  installationRef: WorkshopInstallationRef;
  moduleRef: WorkshopModuleRef;
  readiness: WorkshopReadiness;
  blockers: WorkshopReadinessBlocker[];
  permissions: WorkshopPermissions;
  requiredObjects: string[];
  requiredCapabilities: string[];
  requiredAipFeatures: string[];
  viewRefs: string[];
  evalPackRefs: string[];
  productionContractRefs: string[];
  responsibilityTemplateRefs: string[];
  impactCalculatorRefs: string[];
  legacyAssetRefs: string[];
  legacyRoutes: string[];
  minimumRuntimeVersion: string;
  lastReceiptRef: WorkshopDependencyRef | null;
};
export type EcommerceWorkshopModuleListResponse = {
  schemaVersion: typeof ECOMMERCE_WORKSHOP_SCHEMA_VERSION;
  tenant: WorkshopTenant;
  evaluatedAt: string;
  dataCutoff: string | null;
  items: EcommerceWorkshopModule[];
  count: number;
};
export type EcommerceWorkshopModuleReadinessResponse = {
  schemaVersion: typeof ECOMMERCE_WORKSHOP_SCHEMA_VERSION;
  tenant: WorkshopTenant;
  evaluatedAt: string;
  dataCutoff: string | null;
  item: EcommerceWorkshopModule;
};

export type EcommerceWorkshopApiErrorBody = {
  code: string;
  message: string;
  details: Record<string, unknown> | null;
  traceId: string;
};

export const SOURCE_READINESS_SCHEMA_VERSION = "aos.source-readiness/v1" as const;
export type SourceReadinessStatus = "ready" | "empty" | "degraded" | "unknown" | "stale" | "failed" | "blocked" | "forbidden";
export type SourceReadinessObservationStatus = "succeeded" | "failed" | "running" | "unknown";
export type SourceReadinessPolicyStatus = "pass" | "fail" | "unknown";
export type SourceReadinessExactRef = { resourceType: string; resourceId: string; revision: string; contentHash: string; authority: string };
export type SourceReadinessLatestRun = { runId: string | null; status: SourceReadinessObservationStatus; scheduledFor: string | null; startedAt: string | null; finishedAt: string | null; rowsWritten: number | null; errorCode: string | null };
export type SourceReadinessCounts = { sourceTotal: number | null; sourceActive: number | null; sourceDeleted: number | null; projectionTotal: number | null; unexplainedDelta: number | null };
export type SourceReadinessPolicyObservation = { status: SourceReadinessPolicyStatus; ruleRef: SourceReadinessExactRef | null; summary: string | null };
export type SourceReadinessItem = {
  schemaVersion: typeof SOURCE_READINESS_SCHEMA_VERSION;
  tenant: WorkshopTenant;
  sourceId: string;
  pipelineId: string;
  objectType: string;
  status: SourceReadinessStatus;
  checkedAt: string;
  observedAt: string | null;
  sourceEventAt: string | null;
  projectedAt: string | null;
  dataCutoff: string | null;
  freshnessExpiresAt: string | null;
  sourceConfigRef: SourceReadinessExactRef | null;
  mappingRef: SourceReadinessExactRef | null;
  schemaRef: SourceReadinessExactRef | null;
  maskingPolicyRef: SourceReadinessExactRef | null;
  freshnessPolicyRef: SourceReadinessExactRef | null;
  qualityPolicyRef: SourceReadinessExactRef | null;
  reconciliationPolicyRef: SourceReadinessExactRef | null;
  queryCapabilityRef: SourceReadinessExactRef | null;
  latestRun: SourceReadinessLatestRun;
  counts: SourceReadinessCounts;
  quality: SourceReadinessPolicyObservation;
  reconciliation: SourceReadinessPolicyObservation;
  reasons: string[];
  blockers: string[];
};
export type SourceReadinessEnvelope = {
  schemaVersion: typeof SOURCE_READINESS_SCHEMA_VERSION;
  tenant: WorkshopTenant;
  checkedAt: string;
  cutoffAt: string;
  status: SourceReadinessStatus;
  sources: SourceReadinessItem[];
  receiptRef: SourceReadinessExactRef | null;
};

export const TASK_COCKPIT_SCHEMA_VERSION = "aos.ecommerce-workshop.task-cockpit/v1" as const;
export const DISPATCH_SCENARIO_SCHEMA_VERSION = "aos.ecommerce-workshop.dispatch-scenario/v1" as const;
export type DispatchScenarioStageId = "task_graph" | "dispatch_intent" | "handoff" | "receiver_decision" | "request_more_or_return" | "takeover" | "owner_timeline";
export type DispatchScenarioOutcomeAxisId = "dispatch_decision_recorded" | "receiver_reauthorized" | "single_active_owner" | "takeover_decided" | "execution_reconciled";
export type DispatchScenarioExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type DispatchScenarioBlocker = { code: string; dependency: string; requiredAction: string };
export type DispatchScenarioRoleBinding = { roleRef: DispatchScenarioExactRef; assigneeRef: DispatchScenarioExactRef; skillBindingRef: DispatchScenarioExactRef };
export type DispatchScenarioComposition = { atomicSkillRefs: DispatchScenarioExactRef[]; logicRevisionRef: DispatchScenarioExactRef; roleBindings: DispatchScenarioRoleBinding[] };
export type DispatchScenarioStage = { stageId: DispatchScenarioStageId; status: "ready" | "blocked" | "unknown"; exactRefs: DispatchScenarioExactRef[]; contribution: string; blockers: DispatchScenarioBlocker[] };
export type DispatchScenarioDecisionLedger = { tasksExpected: number; tasksObserved: number; handoffsExpected: number; handoffsObserved: number; decisionsExpected: number; decisionsRecorded: number; accepted: number; rejected: number; requestMore: number; returned: number; takeoverRequested: number; takeoverDecided: number; activeOwnerCount: number };
export type DispatchScenarioOutcomeAxis = { axisId: DispatchScenarioOutcomeAxisId; status: "ready" | "blocked" | "unknown"; exactRef: DispatchScenarioExactRef | null; blocker: DispatchScenarioBlocker | null };
export type DispatchScenarioContribution = { schemaVersion: typeof DISPATCH_SCENARIO_SCHEMA_VERSION; status: "blocked"; rootTaskGraphRef: DispatchScenarioExactRef | null; rootTaskRunRef: DispatchScenarioExactRef | null; dispatchBindingHash: string | null; composition: DispatchScenarioComposition | null; evaluatedAt: string; stages: DispatchScenarioStage[]; ledger: DispatchScenarioDecisionLedger; outcomeAxes: DispatchScenarioOutcomeAxis[]; blockers: DispatchScenarioBlocker[]; commands: { dispatch: false; decideHandoff: false; requestTakeover: false; approveTakeover: false; mutateOwner: false }; externalEffectsAllowed: false };
export const BATCH_SCENARIO_SCHEMA_VERSION = "aos.ecommerce-workshop.batch-scenario/v1" as const;
export type BatchScenarioStageId = "prepare_root" | "impact_cost_preview" | "explicit_start" | "child_dispatch" | "partial_outcomes" | "unknown_reconcile" | "restart_rebuild";
export type BatchScenarioOutcomeAxisId = "business_item" | "external_action" | "usage_settlement" | "effect_maturity" | "handoff_decision";
export type BatchScenarioExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type BatchScenarioBlocker = { code: string; dependency: string; requiredAction: string };
export type BatchScenarioRoleBinding = { roleRef: BatchScenarioExactRef; assigneeRef: BatchScenarioExactRef; skillBindingRef: BatchScenarioExactRef };
export type BatchScenarioComposition = { atomicSkillRefs: BatchScenarioExactRef[]; logicRevisionRef: BatchScenarioExactRef; roleBindings: BatchScenarioRoleBinding[] };
export type BatchScenarioPreparationDecision = { itemKey: string; disposition: "included" | "excluded" | "blocked" | "unknown"; originalRefs: BatchScenarioExactRef[]; decisionRef: BatchScenarioExactRef; reasonCodes: string[] };
export type BatchScenarioChildOutcome = { itemKey: string; status: "succeeded" | "failed" | "cancelled" | "unknown" | "reconciled"; requestFingerprint: string; attemptRef: BatchScenarioExactRef; authorityRefs: BatchScenarioExactRef[]; reconcileReceiptRefs: BatchScenarioExactRef[]; automaticRetryAllowed: false };
export type BatchScenarioStage = { stageId: BatchScenarioStageId; status: "ready" | "blocked" | "unknown"; exactRefs: BatchScenarioExactRef[]; contribution: string; blockers: BatchScenarioBlocker[] };
export type BatchScenarioLedger = { frozenTotal: number; included: number; excluded: number; blocked: number; preparationUnknown: number; childrenExpected: number; childrenObserved: number; succeeded: number; failed: number; cancelled: number; childUnknown: number; reconciled: number; reconcileReceiptsObserved: number };
export type BatchScenarioOutcomeAxis = { axisId: BatchScenarioOutcomeAxisId; status: "succeeded" | "partial" | "failed" | "cancelled" | "blocked" | "unknown" | "reconciled" | "not_started"; exactRefs: BatchScenarioExactRef[]; blockers: BatchScenarioBlocker[] };
export type BatchScenarioContribution = { schemaVersion: typeof BATCH_SCENARIO_SCHEMA_VERSION; status: "blocked"; batchPreparationRevisionRef: BatchScenarioExactRef | null; batchStartDecisionRef: BatchScenarioExactRef | null; batchStartBindingHash: string | null; composition: BatchScenarioComposition | null; evaluatedAt: string; preparationDecisions: BatchScenarioPreparationDecision[]; childOutcomes: BatchScenarioChildOutcome[]; stages: BatchScenarioStage[]; ledger: BatchScenarioLedger; outcomeAxes: BatchScenarioOutcomeAxis[]; sideEffectLedger: { prepareExternalCalls: 0; providerCalls: 0; actionAttempts: 0; externalEffects: 0 }; blockers: BatchScenarioBlocker[]; commands: { prepare: false; start: false; cancel: false; reconcile: false }; automaticRetryAllowed: false; externalEffectsAllowed: false; releaseAllowed: false };
export const LEARNING_SCENARIO_SCHEMA_VERSION = "aos.ecommerce-workshop.learning-scenario/v1" as const;
export type LearningScenarioStageId = "effect_review" | "maturity" | "memory_candidate" | "governance" | "promotion" | "knowledge_query" | "revocation_impact";
export type LearningScenarioOutcomeAxisId = "effect_mature" | "candidate_governed" | "knowledge_promoted" | "future_query_authorized" | "revocation_impact_recorded";
export type LearningScenarioExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type LearningScenarioBlocker = { code: string; dependency: string; requiredAction: string };
export type LearningScenarioRoleBinding = { roleRef: LearningScenarioExactRef; assigneeRef: LearningScenarioExactRef; skillBindingRef: LearningScenarioExactRef };
export type LearningScenarioComposition = { atomicSkillRefs: LearningScenarioExactRef[]; logicRevisionRef: LearningScenarioExactRef; roleBindings: LearningScenarioRoleBinding[] };
export type LearningScenarioStage = { stageId: LearningScenarioStageId; status: "ready" | "blocked" | "unknown"; exactRefs: LearningScenarioExactRef[]; contribution: string; blockers: LearningScenarioBlocker[] };
export type LearningScenarioLedger = { reviewsExpected: number; reviewsObserved: number; candidatesExpected: number; candidatesObserved: number; promotionsExpected: number; promotionsObserved: number; citationsExpected: number; citationsObserved: number; historicalExposures: number; retainedExposures: number; impactRefsExpected: number; impactRefsObserved: number };
export type LearningScenarioOutcomeAxis = { axisId: LearningScenarioOutcomeAxisId; status: "ready" | "blocked" | "unknown"; exactRef: LearningScenarioExactRef | null; blocker: LearningScenarioBlocker | null };
export type LearningScenarioContribution = { schemaVersion: typeof LEARNING_SCENARIO_SCHEMA_VERSION; status: "blocked"; rootEffectReviewRef: LearningScenarioExactRef | null; maturityPolicyRef: LearningScenarioExactRef | null; learningBindingHash: string | null; composition: LearningScenarioComposition | null; evaluatedAt: string; stages: LearningScenarioStage[]; ledger: LearningScenarioLedger; outcomeAxes: LearningScenarioOutcomeAxis[]; blockers: LearningScenarioBlocker[]; commands: { submitCandidate: false; approveCandidate: false; promoteCandidate: false; publishWiki: false; revokeKnowledge: false }; externalEffectsAllowed: false };
export const FULL_VIDEO_SCENARIO_SCHEMA_VERSION = "aos.ecommerce-workshop.full-video-scenario/v1" as const;
export type FullVideoStageId = "brief_profile" | "compile_start" | "script_art" | "storyboard_capture" | "post_review" | "publish_delivery" | "settlement_effect";
export type FullVideoResponsibilityId = "media.producer" | "media.director" | "media.screenwriter" | "media.art" | "media.storyboard" | "media.capture" | "media.post" | "media.review";
export type FullVideoFaultId = "crash_before_submit" | "crash_after_submit_before_receipt" | "lease_fence_loss" | "webhook_ordering" | "timeout_cancel_late_result" | "checkpoint_drift" | "capacity_budget_race" | "restart_partition" | "malicious_artifact";
export type FullVideoExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type FullVideoBlocker = { code: string; dependency: string; requiredAction: string };
export type FullVideoRoleBinding = { roleRef: FullVideoExactRef; assigneeRef: FullVideoExactRef; skillBindingRef: FullVideoExactRef };
export type FullVideoComposition = { atomicSkillRefs: FullVideoExactRef[]; logicRevisionRef: FullVideoExactRef; roleBindings: FullVideoRoleBinding[] };
export type FullVideoResponsibility = { responsibilityId: FullVideoResponsibilityId; label: string; status: "assigned" | "blocked" | "unknown"; assigneeRef: FullVideoExactRef | null; skillBindingRef: FullVideoExactRef | null; independentReviewRequired: boolean; blocker: FullVideoBlocker | null };
export type FullVideoStage = { stageId: FullVideoStageId; status: "ready" | "blocked" | "unknown"; exactRefs: FullVideoExactRef[]; contribution: string; blocker: FullVideoBlocker | null };
export type FullVideoFaultRecovery = { faultId: FullVideoFaultId; status: "ready" | "blocked" | "unknown"; recoveryDecision: string; authorityRefs: FullVideoExactRef[]; blocker: FullVideoBlocker | null; automaticRetryAllowed: false };
export type FullVideoLedger = { responsibilitiesExpected: 8; responsibilitiesObserved: number; stagesExpected: 7; stagesObserved: number; attemptsExpected: number; attemptsObserved: number; artifactsExpected: number; artifactsObserved: number; mediaGatesExpected: 4; mediaGatesObserved: number; faultCasesExpected: 9; faultCasesObserved: number; usageBucketsExpected: number; usageBucketsObserved: number };
export type FullVideoScenarioContribution = { schemaVersion: typeof FULL_VIDEO_SCENARIO_SCHEMA_VERSION; status: "blocked"; rootBriefRef: FullVideoExactRef | null; taskRunRef: FullVideoExactRef | null; fullProductionBindingHash: string | null; composition: FullVideoComposition | null; evaluatedAt: string; responsibilities: FullVideoResponsibility[]; stages: FullVideoStage[]; faultRecovery: FullVideoFaultRecovery[]; ledger: FullVideoLedger; blockers: FullVideoBlocker[]; commands: { prepare: false; start: false; resume: false; takeover: false; cancel: false; reconcile: false; publish: false; settle: false }; externalEffectsAllowed: false; releaseAllowed: false };
export type TaskCockpitTaskStatus = "pending" | "planning" | "awaiting_approval" | "approved" | "executing" | "paused" | "completed" | "failed" | "cancelled" | "rolled_back";
export type TaskCockpitRunStatus = "queued" | "running" | "pausing" | "paused" | "succeeded" | "failed" | "cancelled" | "unknown";
export type TaskCockpitStepStatus = "queued" | "running" | "succeeded" | "failed" | "skipped" | "unknown";
export type TaskCockpitPage = { limit: number; count: number; hasMore: boolean; nextCursor: string | null };
export type TaskCockpitBlocker = { code: string; severity: "warning" | "blocking"; dependency: string; requiredAction: string };
export type TaskCockpitRun = { runId: string; planRevisionId: string; status: TaskCockpitRunStatus; version: number; startedAt: string | null; finishedAt: string | null; createdAt: string; updatedAt: string };
export type TaskCockpitTask = { taskId: string; taskType: string; title: string; status: TaskCockpitTaskStatus; priority: number; version: number; currentPlanRevisionId: string | null; createdAt: string; updatedAt: string; run: TaskCockpitRun | null };
export type TaskCockpitStep = { stepRunId: string; stepKey: string; attempt: number; status: TaskCockpitStepStatus; tokenCount: number; costAmount: string; hasInputRefs: boolean; hasOutputRefs: boolean; hasError: boolean; leaseOwner: string | null; leaseExpiresAt: string | null; fence: number | null; assignmentLeaseId: string | null; inputHash: string | null; providerRequestFingerprint: string | null; safePoint: boolean; reconcileRequired: boolean; createdAt: string; updatedAt: string };
export type TaskCockpitCheckpoint = { checkpointId: string; sequence: number; schemaVersion: number; stepKey: string | null; stateHash: string; artifactCount: number; attempt: number | null; planRevisionId: string | null; inputHash: string | null; providerRequestFingerprint: string | null; dependencySnapshotHash: string | null; resumeReadiness: "checkpoint_exact" | "legacy_unverified"; createdAt: string };
export type TaskCockpitExactRevisionRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type TaskCockpitStageCompilation = { stageId: string; title: string; dependsOn: string[]; requiredSlotIds: string[]; applicabilityResult: "applicable" | "not_applicable"; evaluatedProfile: string };
export type TaskCockpitCoreResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; taskCutoff: string; stateConsistency: "current_state_per_page"; readiness: "degraded"; blockers: TaskCockpitBlocker[]; items: TaskCockpitTask[]; page: TaskCockpitPage };
export type TaskCockpitStepPageResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; evaluatedAt: string; membershipCutoff: string; stateConsistency: "current_state_per_page"; items: TaskCockpitStep[]; page: TaskCockpitPage };
export type TaskCockpitCheckpointPageResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; evaluatedAt: string; membershipCutoff: string; stateConsistency: "current_state_per_page"; items: TaskCockpitCheckpoint[]; page: TaskCockpitPage };
export type TaskCockpitProductionContextResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; planRef: TaskCockpitExactRevisionRef; stageTemplateRef: TaskCockpitExactRevisionRef; responsibilityPlanRef: TaskCockpitExactRevisionRef; compilerVersion: "w2c.v1"; stages: TaskCockpitStageCompilation[]; applicableStageIds: string[]; notApplicableStageIds: string[] };
export type TaskCockpitAssigneeResolutionReceipt = { receiptId: string; subjectId: string; kind: "agent_instance" | "human_principal" | "tool_binding" | "provider_capability_binding"; resourceId: string; version: number; status: "resolved" | "blocked"; blockerCodes: string[]; contentHash: string; snapshotHash: string | null; expiresAt: string | null; requiredCapabilityCount: number; bindingCount: number; snapshotStatus: "exact_fresh" | "legacy_unverified" | "blocked" | "stale"; createdAt: string };
export type TaskCockpitStructuralAssignee = { kind: TaskCockpitAssigneeResolutionReceipt["kind"]; resourceId: string; version: number; operationalReadiness: "unverified" | "resolved_at_observation" | "blocked_at_observation"; resolutionReceipts: TaskCockpitAssigneeResolutionReceipt[] };
export type TaskCockpitResponsibilitySlot = { slotId: string; responsibilityType: string; requiredCapabilityIds: string[]; returnStage: string; assignee: TaskCockpitStructuralAssignee };
export type TaskCockpitHandoffDecision = { decisionId: string; revision: number; decision: "accepted" | "rejected" | "request_more" | "returned"; reasonCode: string | null; gapCodes: string[]; contentHash: string; createdAt: string };
export type TaskCockpitHandoff = { handoffId: string; status: "issued" | "consumed" | "expired" | "revoked"; version: number; senderInstanceRef: TaskCockpitExactRevisionRef; receiverInstanceRef: TaskCockpitExactRevisionRef; expiresAt: string; consumedAt: string | null; createdAt: string; decisions: TaskCockpitHandoffDecision[] };
export type TaskCockpitResponsibilityHandoffResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; responsibilityPlanRef: TaskCockpitExactRevisionRef; profile: string; lifecycle: "draft" | "frozen" | "withdrawn" | "superseded"; compilationReadiness: "ready_at_compile"; compiledRequiredSlotIds: string[]; slots: TaskCockpitResponsibilitySlot[]; handoffs: TaskCockpitHandoff[] };
export type ResponsibilityRuntimeRef = { resourceType: "TaskRun" | "StepRun"; resourceId: string; version: number };
export type ResponsibilityAssigneeRef = { kind: TaskCockpitAssigneeResolutionReceipt["kind"]; resourceId: string; version: number };
export type ResponsibilityAssignmentBlocker = { code: string; dependency: string; requiredAction: string };
export type ResponsibilityAssignmentLease = { leaseId: string; taskRunRef: ResponsibilityRuntimeRef; stepRunRef: ResponsibilityRuntimeRef; attempt: number; owner: ResponsibilityAssigneeRef; fence: number; expiresAt: string };
export type ResponsibilityTakeoverRequest = { tenant: WorkshopTenant; requestId: string; taskRunRef: ResponsibilityRuntimeRef; stepRunRef: ResponsibilityRuntimeRef; attempt: number; sourceOwner: ResponsibilityAssigneeRef; targetOwner: ResponsibilityAssigneeRef; resolutionReceiptId: string; expectedFence: number; reasonCode: string; safetyState: "safe_checkpoint" | "active_lease" | "provider_outcome_unknown" | "step_terminal"; status: "pending" | "blocked"; blockers: ResponsibilityAssignmentBlocker[]; maker: string; createdAt: string; contentHash: string };
export type ResponsibilityTakeoverDecision = { tenant: WorkshopTenant; decisionId: string; requestId: string; revision: number; decision: "approved" | "rejected"; reasonCode: string; checker: string; assignmentLease: ResponsibilityAssignmentLease | null; createdAt: string; contentHash: string };
export type ResponsibilityAssignmentObservation = { tenant: WorkshopTenant; runRef: ResponsibilityRuntimeRef; takeoverRequests: ResponsibilityTakeoverRequest[]; takeoverDecisions: ResponsibilityTakeoverDecision[]; assignmentLeases: ResponsibilityAssignmentLease[]; evaluatedAt: string };
export type DispatchRuntimeRef = { resourceType: "Task" | "TaskRun" | "StepRun"; resourceId: string; version: number };
export type DispatchCommandKind = "module_handoff" | "responsibility_successor" | "runtime_takeover";
export type DispatchControlBlocker = { code: string; dependency: string; requiredAction: string };
export type DispatchCommandTarget = { commandKind: DispatchCommandKind; routeIdentity: "aip.module-handoff.issue" | "aip.responsibility.successor" | "aip.responsibility.takeover"; routePath: string; requiredPermission: string };
export type DispatchIntentObservation = { tenant: WorkshopTenant; intentId: string; revision: number; taskRef: DispatchRuntimeRef; taskRunRef: DispatchRuntimeRef | null; stepRunRef: DispatchRuntimeRef | null; responsibilityPlanRef: TaskCockpitExactRevisionRef | null; command: DispatchCommandTarget; sourceIdentity: string; targetIdentity: string; sourceSlotId: string | null; targetSlotId: string | null; expectedFence: number | null; reasonCode: string; policyRef: TaskCockpitExactRevisionRef; diff: Record<string, unknown>; impact: Record<string, unknown>; readiness: "ready" | "blocked"; blockers: DispatchControlBlocker[]; maker: string; createdAt: string; contentHash: string };
export type DispatchConfirmationObservation = { tenant: WorkshopTenant; confirmationId: string; intentId: string; intentRevision: number; intentContentHash: string; command: DispatchCommandTarget; invocationState: "canonical_command_required"; checker: string; createdAt: string; contentHash: string };
export type TaskPriorityDecisionObservation = { tenant: WorkshopTenant; decisionId: string; revision: number; taskRefBefore: DispatchRuntimeRef; taskRefAfter: DispatchRuntimeRef; oldPriority: number; newPriority: number; reasonCode: string; policyRef: TaskCockpitExactRevisionRef; actor: string; createdAt: string; contentHash: string };
export type DispatchControlObservation = { tenant: WorkshopTenant; taskRef: DispatchRuntimeRef; dispatchIntents: DispatchIntentObservation[]; confirmations: DispatchConfirmationObservation[]; priorityDecisions: TaskPriorityDecisionObservation[]; evaluatedAt: string };
export type ModuleHandoffCompileInput = { handoffId: string; taskRef: ResourceRef; runRef: ResourceRef; sourceModuleId: string; targetModuleId: string; sourceSlotId: string; targetSlotId: string; purpose: string; requestedOutcome: string; objectRefs: ResourceRef[]; artifactRefs: ResourceRef[]; evidenceRefs: ResourceRef[]; context: Record<string, unknown>; allowedContextFields: string[]; markings: string[]; expiresAt: string; correlationRef: ResourceRef | null };
export type ModuleHandoffCompileBlocker = { code: string; dependency: string; requiredAction: string };
export type ModuleHandoffCompileResponse = { schemaVersion: "aos.ecommerce-workshop.module-handoff-compile/v1"; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; responsibilityPlanRef: TaskCockpitExactRevisionRef; sourceModuleId: string; targetModuleId: string; sourceSlotId: string; targetSlotId: string; readiness: "ready" | "blocked"; blockers: ModuleHandoffCompileBlocker[]; issueCommand: IssueHandoffInput | null; sideEffects: { handoffsIssued: 0; tokensMinted: 0; decisionsCreated: 0; agentRunsStarted: 0 } };
export type TaskCockpitApprovalNavigation = { routeIdentity: "aip.task-plan" | "aip.action-drafts"; routePath: string; targetRef: TaskCockpitExactRevisionRef; commandReadiness: "read_only_fact" | "destination_reauthorization_required"; requiredPermission: string; blockerCodes: string[]; returnFocusToken: string };
export type TaskCockpitPlanApproval = { planRef: TaskCockpitExactRevisionRef; approvalStatus: "draft" | "approved" | "superseded" | "rejected"; approvedBy: string | null; approvedAt: string | null; navigation: TaskCockpitApprovalNavigation };
export type TaskCockpitApprovalDecision = { approvalEventId: string; proposalVersion: number; proposalHash: string; decision: "approved" | "rejected"; actorId: string; expiresAt: string | null; createdAt: string };
export type TaskCockpitActionApproval = { proposalRef: TaskCockpitExactRevisionRef; actionTypeId: string; status: "proposed" | "drafted" | "approved" | "rejected" | "expired" | "leased" | "executing" | "applied" | "failed" | "unknown" | "reconciled" | "compensated"; expiresAt: string; decisions: TaskCockpitApprovalDecision[]; navigation: TaskCockpitApprovalNavigation };
export type TaskCockpitReviewIssueEvent = { eventId: string; sequence: number; eventType: "opened" | "resolved" | "returned" | "superseded"; issueVersion: number; payloadHash: string; payload: Record<string, unknown> | null; payloadReadiness: "exact" | "legacy_unavailable"; actor: string; createdAt: string };
export type TaskCockpitReviewImpactDecision = { stepKey: string; action: "invalidate" | "reuse"; reason: string };
export type TaskCockpitReviewReturnLineage = { decisionId: string; issueVersion: number; runId: string; stepKey: string; stepRunId: string; attempt: number; decisionHash: string; impactDecisions: TaskCockpitReviewImpactDecision[]; impactReadiness: "exact" | "legacy_unavailable"; createdAt: string };
export type TaskCockpitReviewIssue = { issueId: string; version: number; status: "open" | "resolved" | "returned" | "superseded"; severity: "info" | "warning" | "error" | "critical"; ruleRef: TaskCockpitExactRevisionRef; artifactId: string; artifactHash: string; evalReportRef: TaskCockpitExactRevisionRef; returnStage: string; evidenceCount: number; lineageReadiness: "attempt_exact" | "attempt_unresolved"; returnLineage: TaskCockpitReviewReturnLineage | null; events: TaskCockpitReviewIssueEvent[] };
export type TaskCockpitApprovalReviewResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; planApproval: TaskCockpitPlanApproval; actionApprovals: TaskCockpitActionApproval[]; reviewIssues: TaskCockpitReviewIssue[]; actionApprovalCount: number; reviewIssueCount: number; unresolvedAttemptCount: number };
export type TaskCockpitActionReceipt = { receiptId: string; receiptKind: "initial" | "reconcile"; status: "accepted" | "applied" | "failed" | "unknown" | "reconciled"; leaseId: string; requestFingerprint: string; providerRequestPresent: boolean; evidenceCount: number; supersedesReceiptId: string | null; resolvedStatus: "applied" | "failed" | null; createdAt: string };
export type TaskCockpitActionExecution = { proposalRef: TaskCockpitExactRevisionRef; actionTypeId: string; proposalStatus: "proposed" | "drafted" | "approved" | "rejected" | "expired" | "leased" | "executing" | "applied" | "failed" | "unknown" | "reconciled" | "compensated"; leaseId: string | null; attempt: number | null; receipts: TaskCockpitActionReceipt[]; reconciliationState: "not_started" | "not_required" | "required" | "resolved" };
export type TaskCockpitActionReceiptResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; executions: TaskCockpitActionExecution[]; proposalCount: number; receiptCount: number; unknownReceiptCount: number; reconcileRequiredCount: number; reconciledReceiptCount: number };
export type TaskCockpitResourceRef = { resourceType: string; resourceId: string; revision: string | null; authority: string };
export type TaskCockpitSkillContributionReadiness = { status: "available" | "degraded" | "disabled" | "blocked" | "unknown" | "stale"; freshness: "fresh" | "stale" | "unverified"; reasonCodes: string[]; bindingStatus: "provisioning" | "active" | "suspended" | "revoked"; lastVerifiedAt: string | null; expiresAt: string | null };
export type TaskCockpitSkillRunProjection = { status: "queued" | "running" | "paused" | "succeeded" | "failed" | "cancelled" | "unknown"; startedAt: string | null; updatedAt: string; waitingFor: string[] };
export type TaskCockpitSkillContribution = { contributionId: string; taskRunRef: TaskCockpitResourceRef; agentRunRef: TaskCockpitResourceRef; moduleId: "ecommerce.task-cockpit"; roleRef: TaskCockpitExactRevisionRef; assigneeRef: TaskCockpitExactRevisionRef; skillRevisionRef: TaskCockpitExactRevisionRef; bindingRef: TaskCockpitResourceRef; logicRevisionRef: TaskCockpitExactRevisionRef; displayName: string; purpose: string; responsibility: string; readiness: TaskCockpitSkillContributionReadiness; runProjection: TaskCockpitSkillRunProjection; inputRefs: TaskCockpitResourceRef[]; outputArtifactRefs: TaskCockpitResourceRef[]; assumptions: string[]; uncertainties: string[]; conflicts: string[]; missingInputs: string[]; allowedCommands: [] };
export type TaskCockpitSkillContributionResponse = { schemaVersion: typeof TASK_COCKPIT_SCHEMA_VERSION; tenant: WorkshopTenant; runId: string; taskId: string; evaluatedAt: string; projectionStatus: "ready" | "blocked"; blockerCodes: string[]; items: TaskCockpitSkillContribution[] };
export type TaskCockpitCoreQuery = { status?: TaskCockpitTaskStatus; limit?: number; cursor?: string };
export type TaskCockpitRunDetailQuery = { limit?: number; cursor?: string };

export const OPERATIONS_SCHEMA_VERSION = "aos.ecommerce-workshop.operations-view/v1" as const;
export type OperationsSliceId = "orders" | "orderLines" | "inventory" | "shipments" | "payments" | "aftersaleEvents" | "operationCases";
export type OperationsSliceStatus = "ready" | "blocked";
export type OperationsAuthorityRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type OperationsBlocker = { code: string; dependency: string; requiredAction: string };
export type OperationsCountLedger = { sourceTotal: number; attached: number; unmatched: number; conflicted: number };
export type OperationsSlice = { sliceId: OperationsSliceId; status: OperationsSliceStatus; dataCutoff: string; authorityRefs: OperationsAuthorityRef[]; blockers: OperationsBlocker[]; countLedger: OperationsCountLedger };
export type OperationsPage = { limit: number; count: number; hasMore: boolean; nextCursor: string | null };
export type OperationsViewResponse = { schemaVersion: typeof OPERATIONS_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; slices: OperationsSlice[]; page: OperationsPage };

export const CONTENT_CAMPAIGN_SCHEMA_VERSION = "aos.ecommerce-workshop.content-campaign-view/v1" as const;
export type ContentCampaignSliceId = "plan" | "calendar" | "content";
export type ContentCampaignAuthorityRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type ContentCampaignArtifactRef = { artifactId: string; contentHash: string };
export type ContentVariantProjection = ContentCampaignAuthorityRef & { resourceType: "ContentVariant"; revision: 1; intentRef: ContentCampaignAuthorityRef; masterArtifactRef: ContentCampaignArtifactRef; variantArtifactRef: ContentCampaignArtifactRef; relationId: string; relationType: "variant_of" };
export type ContentCampaignItem = ContentCampaignAuthorityRef | ContentVariantProjection;
export type ContentCampaignBlocker = { code: string; dependency: string; requiredAction: string };
export type ContentCampaignCountLedger = { eligible: number; attached: number; unmatched: number; conflicted: number };
export type ContentCampaignSlice = { sliceId: ContentCampaignSliceId; status: "ready" | "blocked"; dataCutoff: string; authorityRefs: ContentCampaignAuthorityRef[]; items: ContentCampaignItem[]; blockers: ContentCampaignBlocker[]; countLedger: ContentCampaignCountLedger };
export type ContentCampaignPage = { limit: number; count: number; hasMore: false; nextCursor: null };
export type ContentCampaignViewResponse = { schemaVersion: typeof CONTENT_CAMPAIGN_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; slices: ContentCampaignSlice[]; page: ContentCampaignPage };

export const CREATOR_GROWTH_SCHEMA_VERSION = "aos.ecommerce-workshop.creator-growth-view/v1" as const;
export type CreatorBusinessStage = "candidate" | "outreach" | "contract" | "delivery" | "relationship";
export type CreatorWorkflowPhase = "discovery" | "evidence" | "matching" | "batch_prepare" | "start";
export type CreatorGrowthRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string; workflowPhase: CreatorWorkflowPhase; businessStage: CreatorBusinessStage; piiRefs: string[] };
export type CreatorGrowthBlocker = { code: string; dependency: string; requiredAction: string };
export type CreatorGrowthLedger = { input: number; eligible: number; excluded: number; needsReview: number; unknown: number; deduplicated: number };
export type CreatorGrowthSlice = { businessStage: CreatorBusinessStage; workflowPhases: CreatorWorkflowPhase[]; status: "ready" | "blocked"; dataCutoff: string; authorityRefs: CreatorGrowthRef[]; blockers: CreatorGrowthBlocker[]; countLedger: CreatorGrowthLedger };
export type CreatorGrowthViewResponse = { schemaVersion: typeof CREATOR_GROWTH_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; slices: CreatorGrowthSlice[]; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };
export const CREATOR_PREPARE_SCHEMA_VERSION = "aos.ecommerce-workshop.creator-prepare/v1" as const;
export type CreatorPrepareExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type CreatorPrepareBatchItem = { candidateRef: CreatorPrepareExactRef; evidenceBundleRef: CreatorPrepareExactRef; matchObservationRef: CreatorPrepareExactRef; matchDecisionRef: CreatorPrepareExactRef; disposition: "eligible" | "excluded" | "needs_review" | "unknown" | "deduplicated"; reasonCodes: string[]; frequencyEligible: boolean; capacityEligible: boolean; budgetEligible: boolean };
export type CreatorBatchPreparation = { tenant: WorkshopTenant; batchId: string; revision: number; version: number; lifecycle: "prepared" | "frozen" | "stale"; exactRefs: Record<string, CreatorPrepareExactRef>; skillRefs: CreatorPrepareExactRef[]; items: CreatorPrepareBatchItem[]; itemHashes: string[]; ledger: CreatorGrowthLedger; externalEffectCount: 0; actionProposalCount: 0; executionLeaseCount: 0; priorContentHash: string | null; contentHash: string; createdBy: string; createdAt: string };
export type CreatorContributionViewResponse = { schemaVersion: typeof CREATOR_PREPARE_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; atomicSkillRefs: CreatorPrepareExactRef[]; logicRef: CreatorPrepareExactRef | null; primaryColleague: "导购顾问"; collaboratorColleagues: string[]; latestBatch: CreatorBatchPreparation | null; blockers: string[]; allowedCommands: ("PREPARE_CREATOR_BATCH" | "FREEZE_CREATOR_BATCH")[]; externalEffectsAllowed: false };
export const CREATOR_LIFECYCLE_SCHEMA_VERSION = "aos.ecommerce-workshop.creator-lifecycle/v1" as const;
export type CreatorActionKind = "outreach-message" | "sample-shipment" | "contract-signature" | "commission-change";
export type CreatorLaneOutcome = "prepared" | "accepted" | "applied" | "failed" | "unknown" | "disputed";
export type CreatorActionLaneBinding = { candidateRef: CreatorPrepareExactRef; actionKind: CreatorActionKind; actionTypeRef: CreatorPrepareExactRef; impactPreviewRef: CreatorPrepareExactRef; adapterCapabilityRef: CreatorPrepareExactRef; accountBindingRef: CreatorPrepareExactRef; budgetReservationRef: CreatorPrepareExactRef; approvalPolicyRef: CreatorPrepareExactRef; laneId: string; bindingHash: string; outcome: CreatorLaneOutcome; actionReceiptRef: CreatorPrepareExactRef | null; resolvedOutcome: CreatorLaneOutcome | null };
export type CreatorStartLedger = { eligibleItems: number; lanes: number; prepared: number; accepted: number; applied: number; failed: number; unknown: number; disputed: number; completed: number };
export type CreatorBatchStartDecision = { tenant: WorkshopTenant; decisionId: string; revision: number; version: number; lifecycle: "governance_prepared"; batchRef: CreatorPrepareExactRef; batchItemHashes: string[]; lanes: CreatorActionLaneBinding[]; ledger: CreatorStartLedger; operationalBlockers: string[]; externalEffectCount: 0; contentHash: string; startedBy: string; startedAt: string };
export type CreatorContractRevision = { tenant: WorkshopTenant; collaborationId: string; revision: number; candidateRef: CreatorPrepareExactRef; startDecisionRef: CreatorPrepareExactRef; priorContractRef: CreatorPrepareExactRef | null; termsHash: string; monetaryTermsRef: CreatorPrepareExactRef; lifecycle: "draft" | "reviewed" | "signed_observed" | "cancelled"; diffFields: string[]; actionReceiptRef: CreatorPrepareExactRef | null; contentHash: string; createdBy: string; createdAt: string };
export type CreatorDeliveryObservation = { tenant: WorkshopTenant; observationId: string; collaborationId: string; contractRef: CreatorPrepareExactRef; deliveryRef: CreatorPrepareExactRef; evidenceBundleRef: CreatorPrepareExactRef; sequence: number; status: "expected" | "in_transit" | "received" | "accepted" | "disputed"; contentHash: string; observedAt: string };
export type CreatorRelationshipRevision = { tenant: WorkshopTenant; relationshipId: string; revision: number; collaborationId: string; contractRef: CreatorPrepareExactRef; deliveryObservationRefs: CreatorPrepareExactRef[]; maturityPolicyRef: CreatorPrepareExactRef; maturityWindowEndsAt: string; status: "preliminary" | "mature" | "at_risk"; contentHash: string; createdAt: string };
export type CreatorLifecycleViewResponse = { schemaVersion: typeof CREATOR_LIFECYCLE_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; latestStart: CreatorBatchStartDecision | null; ledger: CreatorStartLedger; contracts: CreatorContractRevision[]; deliveries: CreatorDeliveryObservation[]; relationships: CreatorRelationshipRevision[]; blockers: string[]; allowedCommands: "START_CREATOR_BATCH_GOVERNANCE"[]; externalEffectsAllowed: false };

export const MEDIA_STUDIO_LEGACY_SCHEMA_VERSION = "aos.ecommerce-workshop.media-studio-view/v1" as const;
export const MEDIA_STUDIO_PROVIDER_SCHEMA_VERSION = "aos.ecommerce-workshop.media-studio-view/v2" as const;
export const MEDIA_STUDIO_FINANCE_SCHEMA_VERSION = "aos.ecommerce-workshop.media-studio-view/v3" as const;
export const MEDIA_STUDIO_SCHEMA_VERSION = "aos.ecommerce-workshop.media-studio-view/v4" as const;
export const MEDIA_STUDIO_PUBLISH_SCHEMA_VERSION = "aos.ecommerce-workshop.media-studio-view/v5" as const;
export const MEDIA_STUDIO_CUMULATIVE_SCHEMA_VERSION = "aos.ecommerce-workshop.media-studio-view/v6" as const;
export const MEDIA_STUDIO_LIFECYCLE_SCHEMA_VERSION = "aos.ecommerce-workshop.media-studio-lifecycle/v1" as const;
export const MEDIA_PUBLISH_SCHEMA_VERSION = "aos.ecommerce-workshop.media-publish-contribution/v1" as const;
export const MEDIA_CUMULATIVE_SCHEMA_VERSION = "aos.ecommerce-workshop.media-cumulative-gates/v1" as const;
export type MediaStudioSliceId = "context" | "execution" | "delivery";
export type MediaReadinessAxis = "module" | "capability" | "assignee" | "provider" | "budget" | "publication";
export type MediaReadinessStatus = "ready" | "blocked" | "target" | "unknown" | "conflict" | "not_applicable";
export type MediaExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type MediaBlocker = { code: string; dependency: string; requiredAction: string };
export type MediaAxisReadiness = { axis: MediaReadinessAxis; status: MediaReadinessStatus; exactRef: MediaExactRef | null; targetContractRef: string | null; gaps: string[]; blockers: MediaBlocker[] };
export type MediaCountLedger = { denominator: number; ready: number; target: number; blocked: number; unknown: number; conflict: number; notApplicable: number };
export type MediaStudioSlice = { sliceId: MediaStudioSliceId; status: "ready" | "blocked"; dataCutoff: string; readinessAxes: MediaAxisReadiness[]; authorityRefs: MediaExactRef[]; blockers: MediaBlocker[]; countLedger: MediaCountLedger };
export type MediaProviderExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type MediaProviderJobContribution = { jobId: string; status: "prepared" | "submitted" | "running" | "cancel_requested" | "unknown" | "succeeded" | "failed" | "cancelled"; sequence: number; atomicCapabilityRef: MediaProviderExactRef; logicRef: MediaProviderExactRef; colleagueBindingRef: MediaProviderExactRef; modelRef: MediaProviderExactRef; providerRef: MediaProviderExactRef; adapterRef: MediaProviderExactRef; scanRefs: MediaProviderExactRef[]; primaryColleague: "内容官"; collaboratorColleagues: string[]; blockerCodes: string[]; externalEffectsAllowed: false };
export type MediaFinanceBucketContribution = { currency: string; measuredMinor: number; estimatedMinor: number; unknownCount: number; adjustmentMinor: number; refundMinor: number; residualMinor: number | null };
export type MediaFinanceContribution = { financeId: string; jobId: string; version: number; attemptBindingHash: string; capacityReservationRef: MediaProviderExactRef; budgetReservationRef: MediaProviderExactRef; projectedMinMinor: number; projectedMaxMinor: number; projectedCurrency: string; reservationsActive: boolean; cancelOutcome: "requested" | "accepted" | "too_late" | "unknown" | null; feeConclusion: "no_charge" | "chargeable" | "unknown"; settlementStatus: "pending" | "settled" | "disputed" | "written_off"; currencyBuckets: MediaFinanceBucketContribution[]; blockerCodes: string[]; externalEffectsAllowed: false };
export type MediaLifecycleNodeId = "prepare" | "freeze_confirm" | "compile_approve" | "start_run" | "review_return" | "deliver_publish" | "reconcile_effect";
export type MediaContributionStatus = "ready" | "active" | "blocked" | "not_started" | "unknown" | "conflict" | "not_applicable";
export type MediaLifecycleAuthorityRef = { resourceType: string; resourceId: string; revision: number; contentHash: string | null };
export type MediaLifecycleNodeContribution = { nodeId: MediaLifecycleNodeId; label: string; status: MediaContributionStatus; authorityRefs: MediaLifecycleAuthorityRef[]; blockerCodes: string[]; observedAt: string | null };
export type MediaResponsibilityContribution = { slotId: string; label: string; responsibilityType: string; status: "assigned" | "blocked"; requiredCapabilityIds: string[]; assigneeKind: string | null; assigneeId: string | null; assigneeVersion: number | null; resolutionReceiptId: string | null; blockerCodes: string[] };
export type MediaStageContribution = { stageId: string; taskRunId: string; attempt: number; status: string; capabilityRef: MediaLifecycleAuthorityRef; colleagueBindingRef: MediaLifecycleAuthorityRef; providerRef: MediaLifecycleAuthorityRef; providerJobId: string; blockerCodes: string[]; externalEffectsAllowed: false };
export type MediaArtifactFamilyContribution = { familyId: string; version: number; topologyStatus: string; memberCount: number; conflictCount: number; gateSetCount: number; latestGateReadiness: string | null; issueCount: number };
export type MediaReviewIssueContribution = { issueId: string; version: number; status: string; severity: string; artifactId: string; artifactHash: string; returnStage: string; returnDecisionCount: number };
export type MediaCommandCapability = { commandId: string; allowed: false; reasonCode: string; expectedVersion: number | null; requiredExactRefs: MediaLifecycleAuthorityRef[] };
export type MediaStudioLifecycleContribution = { schemaVersion: typeof MEDIA_STUDIO_LIFECYCLE_SCHEMA_VERSION; contextId: string; contextRevision: number; contextHash: string; taskId: string; status: "ready" | "partial" | "blocked" | "conflict"; lifecycle: MediaLifecycleNodeContribution[]; responsibilities: MediaResponsibilityContribution[]; stages: MediaStageContribution[]; artifactFamilies: MediaArtifactFamilyContribution[]; reviewIssues: MediaReviewIssueContribution[]; commandCapabilities: MediaCommandCapability[]; blockerCodes: string[]; externalEffectsAllowed: false };
export type MediaPublishExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type MediaPublishCandidateContribution = { familyId: string; familyVersion: number; variantRef: MediaPublishExactRef; gateSetRef: MediaPublishExactRef; platform: string; profile: string };
export type MediaPublishImpactContribution = { previewRef: MediaPublishExactRef; actionBindingHash: string; readiness: "ready" | "blocked"; expiresAt: string; atomicSkillRefs: MediaPublishExactRef[]; logicRef: MediaPublishExactRef; colleagueBindingRefs: MediaPublishExactRef[] };
export type MediaPublishActionContribution = { proposalId: string; proposalVersion: number; proposalHash: string; status: string; actionBindingHash: string; approvalCount: number; leaseId: string | null; attemptId: string | null };
export type MediaPublishReceiptContribution = { receiptId: string; receiptKind: string; status: string; providerOutcome: string | null; reconciliationStatus: string; requestFingerprint: string; responseHash: string | null; actionBindingHash: string; usageReceiptCount: number; lineageAttached: boolean };
export type MediaPublishHandoffRequirement = { status: "not_required" | "required" | "unresolved"; reasonCode: string; requiredFacts: string[]; minimalDisclosure: true; completionReceiptRequired: true; completionAllowed: false };
export type MediaPublishContribution = { schemaVersion: typeof MEDIA_PUBLISH_SCHEMA_VERSION; candidate: MediaPublishCandidateContribution; impact: MediaPublishImpactContribution; action: MediaPublishActionContribution; receipt: MediaPublishReceiptContribution | null; handoff: MediaPublishHandoffRequirement; blockerCodes: string[]; externalEffectsAllowed: false };
export type MediaCumulativeGateId = "contract_green" | "service_green" | "database_restart_green" | "tenant_rls_green" | "browser_positive_green" | "browser_negative_green" | "security_green" | "fault_injection_green" | "provider_adapter_green" | "publish_canary_green" | "operational_ready";
export type MediaCumulativeEvidenceRef = { resourceType: "DeliveryReceipt" | "EvidencePack"; resourceId: string; revision: string; contentHash: string };
export type MediaCumulativeGate = { gateId: MediaCumulativeGateId; status: "ready" | "blocked" | "unknown" | "stale"; evidenceRef: MediaCumulativeEvidenceRef | null; reasonCode: string; observedAt: string | null; externalEffectsObserved: false };
export type MediaCumulativeGateSet = { schemaVersion: typeof MEDIA_CUMULATIVE_SCHEMA_VERSION; releaseRevision: string; evaluatedAt: string; gates: MediaCumulativeGate[]; overallStatus: "blocked"; blockerCodes: string[]; externalEffectsAllowed: false; releaseAllowed: false };
export type MediaStudioViewResponse = { schemaVersion: typeof MEDIA_STUDIO_CUMULATIVE_SCHEMA_VERSION | typeof MEDIA_STUDIO_PUBLISH_SCHEMA_VERSION | typeof MEDIA_STUDIO_SCHEMA_VERSION | typeof MEDIA_STUDIO_FINANCE_SCHEMA_VERSION | typeof MEDIA_STUDIO_PROVIDER_SCHEMA_VERSION | typeof MEDIA_STUDIO_LEGACY_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; slices: MediaStudioSlice[]; providerJobsStatus: "ready" | "blocked"; providerJobs: MediaProviderJobContribution[]; providerJobBlockers: MediaBlocker[]; mediaFinanceStatus: "ready" | "blocked"; mediaFinance: MediaFinanceContribution[]; mediaFinanceBlockers: MediaBlocker[]; lifecycleStatus: "ready" | "blocked"; lifecycle: MediaStudioLifecycleContribution | null; lifecycleBlockers: MediaBlocker[]; publishStatus: "ready" | "blocked"; publishContributions: MediaPublishContribution[]; publishBlockers: MediaBlocker[]; cumulativeGateSet?: MediaCumulativeGateSet | null; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };

export const ANALYST_SCHEMA_VERSION = "aos.ecommerce-workshop.analyst-view/v1" as const;
export const ANALYST_SCENARIO_SCHEMA_VERSION = "aos.ecommerce-workshop.analyst-view/v2" as const;
export const GROWTH_SCENARIO_SCHEMA_VERSION = "aos.ecommerce-workshop.growth-scenario/v1" as const;
export type GrowthScenarioStageId = "insight" | "growth_plan" | "content" | "creator" | "media" | "publication" | "effect_review" | "memory_candidate";
export type GrowthScenarioOutcomeAxisId = "provider_applied" | "usage_settled" | "effect_mature" | "memory_governed";
export type GrowthScenarioExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type GrowthScenarioBlocker = { code: string; dependency: string; requiredAction: string };
export type GrowthScenarioStage = { stageId: GrowthScenarioStageId; status: "ready" | "blocked" | "unknown"; exactRefs: GrowthScenarioExactRef[]; contribution: string; blockers: GrowthScenarioBlocker[] };
export type GrowthScenarioLedger = { tasksExpected: number; tasksObserved: number; handoffsExpected: number; handoffsObserved: number; outcomesExpected: number; outcomesReady: number; outcomesBlocked: number; outcomesUnknown: number };
export type GrowthScenarioOutcomeAxis = { axisId: GrowthScenarioOutcomeAxisId; status: "ready" | "blocked" | "unknown"; exactRef: GrowthScenarioExactRef | null; blocker: GrowthScenarioBlocker | null };
export type GrowthScenarioContribution = { schemaVersion: typeof GROWTH_SCENARIO_SCHEMA_VERSION; status: "blocked"; rootPlanRef: GrowthScenarioExactRef | null; scenarioBindingHash: string | null; evaluatedAt: string; stages: GrowthScenarioStage[]; ledger: GrowthScenarioLedger; outcomeAxes: GrowthScenarioOutcomeAxis[]; blockers: GrowthScenarioBlocker[]; commands: { materialize: false; dispatch: false; publish: false; promoteMemory: false }; externalEffectsAllowed: false };
export type AnalystViewId = "overview" | "drivers" | "diagnosis" | "plan" | "effects" | "evidence" | "quality";
export type AnalystReadinessAxis = "metric_query" | "model" | "eval" | "plan_materialization" | "professional_handoff";
export type AnalystReadinessStatus = "ready" | "blocked" | "unknown" | "not_applicable";
export type AnalystExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type AnalystBlocker = { code: string; dependency: string; requiredAction: string };
export type AnalystAxisReadiness = { axis: AnalystReadinessAxis; status: AnalystReadinessStatus; exactRef: AnalystExactRef | null; blockers: AnalystBlocker[] };
export type AnalystMetricValue = { metricId: string; status: "ready" | "unknown" | "blocked" | "conflict"; definitionRef: AnalystExactRef | null; observationRef: AnalystExactRef | null; value: number | null; unit: string | null; grain: string | null; window: string | null; timezone: string | null; cohortFilter: string | null; numerator: number | null; denominator: number | null; sourceRunRef: AnalystExactRef | null; qualityRef: AnalystExactRef | null; reconciliationRef: AnalystExactRef | null; lineageId: string | null; blockers: AnalystBlocker[] };
export type AnalystCountLedger = { denominator: number; ready: number; unknown: number; blocked: number; conflict: number };
export type AnalystViewSlice = { viewId: AnalystViewId; status: "ready" | "blocked"; resourceRevision: number; dataCutoff: string; readinessAxes: AnalystAxisReadiness[]; metrics: AnalystMetricValue[]; authorityRefs: AnalystExactRef[]; blockers: AnalystBlocker[]; countLedger: AnalystCountLedger };
export type AnalystViewResponse = { schemaVersion: typeof ANALYST_SCHEMA_VERSION | typeof ANALYST_SCENARIO_SCHEMA_VERSION; tenant: WorkshopTenant; resourceRevision: number; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; views: AnalystViewSlice[]; growthScenario?: GrowthScenarioContribution | null; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };

export const PRICE_GOVERNANCE_SCHEMA_VERSION = "aos.ecommerce-workshop.price-governance-view/v1" as const;
export const PRICE_GOVERNANCE_REMEDY_SCHEMA_VERSION = "aos.ecommerce-workshop.price-governance-view/v2" as const;
export const REMEDY_SCENARIO_SCHEMA_VERSION = "aos.ecommerce-workshop.remedy-scenario/v1" as const;
export type PriceGovernanceViewId = "governance" | "competitor" | "schedule";
export type PriceReadinessAxis = "collection" | "match" | "policy_case" | "notification" | "advice_handoff" | "repricing";
export type PriceReadinessStatus = "ready" | "blocked" | "unknown" | "not_applicable" | "disabled";
export type PriceExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type PriceBlocker = { code: string; dependency: string; requiredAction: string };
export type PriceAxisReadiness = { axis: PriceReadinessAxis; status: PriceReadinessStatus; exactRef: PriceExactRef | null; blockers: PriceBlocker[] };
export type PriceQuoteBasis = { basis: "list" | "landed"; skuRef: PriceExactRef; bundleRef: PriceExactRef | null; quantity: number; unit: string; currency: string; tax: "included" | "excluded" | "unknown"; shipping: "included" | "excluded" | "unknown"; promotionCondition: string; effectiveFrom: string; effectiveUntil: string | null };
export type PriceObservation = { observationRef: PriceExactRef; market: string; amount: number | null; quoteBasis: PriceQuoteBasis; observedAt: string; freshness: "fresh" | "stale" | "unknown"; license: "allowed" | "denied" | "unknown"; comparability: "comparable" | "not_comparable" | "unknown"; matchStatus: "confirmed" | "preliminary" | "not_matched" | "unknown"; originalRefs: PriceExactRef[]; mergedOriginalRefs: PriceExactRef[]; blockers: PriceBlocker[] };
export type PriceCountLedger = { input: number; eligible: number; excluded: number; needsReview: number; unknown: number; deduplicated: number };
export type PriceGovernanceViewSlice = { viewId: PriceGovernanceViewId; status: "ready" | "blocked"; resourceRevision: number; dataCutoff: string; readinessAxes: PriceAxisReadiness[]; observations: PriceObservation[]; authorityRefs: PriceExactRef[]; blockers: PriceBlocker[]; countLedger: PriceCountLedger };
export type RemedyScenarioStageId = "price_observation" | "match_decision" | "price_case" | "affected_orders" | "operation_case" | "customer_handoff" | "contact_permit" | "action_outcomes" | "effect_review";
export type RemedyScenarioOutcomeAxisId = "repricing_applied" | "refund_compensation_submitted" | "customer_message_accepted" | "operation_case_resolved" | "effect_mature";
export type RemedyScenarioExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string };
export type RemedyScenarioBlocker = { code: string; dependency: string; requiredAction: string };
export type RemedyScenarioStage = { stageId: RemedyScenarioStageId; status: "ready" | "blocked" | "unknown"; exactRefs: RemedyScenarioExactRef[]; contribution: string; blockers: RemedyScenarioBlocker[] };
export type RemedyScenarioLedger = { affectedOrdersExpected: number; affectedOrdersObserved: number; eligibleCustomersExpected: number; eligibleCustomersObserved: number; actionsExpected: number; actionsReady: number; actionsBlocked: number; actionsUnknown: number };
export type RemedyScenarioOutcomeAxis = { axisId: RemedyScenarioOutcomeAxisId; status: "ready" | "blocked" | "unknown"; exactRef: RemedyScenarioExactRef | null; blocker: RemedyScenarioBlocker | null };
export type RemedyScenarioContribution = { schemaVersion: typeof REMEDY_SCENARIO_SCHEMA_VERSION; status: "blocked"; rootCaseRef: RemedyScenarioExactRef | null; remedyBindingHash: string | null; evaluatedAt: string; stages: RemedyScenarioStage[]; ledger: RemedyScenarioLedger; outcomeAxes: RemedyScenarioOutcomeAxis[]; blockers: RemedyScenarioBlocker[]; commands: { reprice: false; refundOrCompensate: false; sendMessage: false; resolveCase: false }; protectedContactResolved: false; externalEffectsAllowed: false };
export type PriceGovernanceViewResponse = { schemaVersion: typeof PRICE_GOVERNANCE_SCHEMA_VERSION | typeof PRICE_GOVERNANCE_REMEDY_SCHEMA_VERSION; tenant: WorkshopTenant; resourceRevision: number; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; views: PriceGovernanceViewSlice[]; remedyScenario?: RemedyScenarioContribution | null; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };
export const PRICE_RESEARCH_SCHEMA_VERSION = "aos.ecommerce-workshop.price-research/v1" as const;
export type PriceResearchBatchLedger = PriceCountLedger;
export type PriceResearchBatchSummary = { batchId: string; revision: number; version: number; lifecycle: "prepared" | "frozen" | "stale"; exactRefs: Record<string, PriceExactRef>; skillRefs: PriceExactRef[]; itemCount: number; itemHashes: string[]; ledger: PriceResearchBatchLedger; providerCallCount: 0; researchJobCount: 0; notificationCount: 0; actionProposalCount: 0; repricingCount: 0; externalEffectCount: 0; priorContentHash: string | null; contentHash: string; createdBy: string; createdAt: string };
export type PriceResearchContributionViewResponse = { schemaVersion: typeof PRICE_RESEARCH_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; atomicSkillRefs: PriceExactRef[]; logicRef: PriceExactRef | null; primaryColleague: "数据参谋"; collaboratorColleagues: ["活动策划师", "导购顾问"]; latestBatch: PriceResearchBatchSummary | null; blockers: string[]; allowedCommands: ("PREPARE_PRICE_RESEARCH_BATCH" | "FREEZE_PRICE_RESEARCH_BATCH")[]; externalEffectsAllowed: false };
export const PRICE_DISPOSITION_SCHEMA_VERSION = "aos.ecommerce-workshop.price-disposition/v1" as const;
export type PriceDispositionKind = "internal_advice" | "external_notice" | "module_handoff" | "repricing";
export type PriceDispositionOutcome = "prepared" | "adopted" | "rejected" | "accepted" | "applied" | "failed" | "unknown" | "disputed";
export type PriceDispositionSummary = { dispositionId: string; revision: number; version: number; lifecycle: "prepared" | "frozen" | "stale"; kind: PriceDispositionKind; executionAllowed: false; providerCallCount: 0; notificationSendCount: 0; repricingCount: 0; externalEffectCount: 0 };
export type PriceDispositionObservationSummary = { observationId: string; outcome: PriceDispositionOutcome; resolvedOutcome: PriceDispositionOutcome | null; observedAt: string };
export type PriceDispositionContributionViewResponse = { schemaVersion: typeof PRICE_DISPOSITION_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; atomicSkillIds: ["compile-price-case", "prepare-price-advice", "prepare-price-notice", "prepare-price-handoff", "evaluate-reprice-specialized-gate"]; logicId: "ecommerce-price-governance"; primaryColleague: "数据参谋"; collaboratorColleagues: ["活动策划师", "导购顾问"]; caseCount: number; dispositionCounts: Record<PriceDispositionKind, number>; latestDisposition: PriceDispositionSummary | null; latestObservation: PriceDispositionObservationSummary | null; blockers: string[]; allowedCommands: ("COMPILE_PRICE_CASE" | "CREATE_PRICE_DISPOSITION_CONTRACT" | "PREPARE_PRICE_DISPOSITION" | "FREEZE_PRICE_DISPOSITION" | "RECORD_PRICE_DISPOSITION_OBSERVATION")[]; repricingEnabled: false; externalEffectsAllowed: false };

export const CUSTOMER_VIEW_SCHEMA_VERSION = "aos.ecommerce-workshop.customer-view/v1" as const;
export type CustomerViewId = "customer" | "segment" | "journey" | "dialogue";
export type CustomerReadinessAxis = "customer_lite" | "consent" | "segment" | "journey" | "dialogue" | "outreach_batch";
export type CustomerReadinessStatus = "ready" | "blocked" | "unknown" | "not_applicable";
export type CustomerExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type CustomerBlocker = { code: string; dependency: string; requiredAction: string };
export type CustomerAxisReadiness = { axis: CustomerReadinessAxis; status: CustomerReadinessStatus; exactRef: CustomerExactRef | null; blockers: CustomerBlocker[] };
export type CustomerProjection = { customerRef: CustomerExactRef; purpose: string; disclosure: "allowed" | "blocked" | "unknown"; freshness: "fresh" | "stale" | "unknown"; quality: "pass" | "fail" | "unknown"; consent: "granted" | "withdrawn" | "expired" | "conflict" | "unknown"; retention: "active" | "expired" | "unknown"; kAnonymitySatisfied: boolean | null; originalRefs: CustomerExactRef[]; blockers: CustomerBlocker[] };
export type CustomerCountLedger = { input: number; eligible: number; excluded: number; unknown: number; deduplicated: number };
export type CustomerViewSlice = { viewId: CustomerViewId; status: "ready" | "blocked"; resourceRevision: number; dataCutoff: string; readinessAxes: CustomerAxisReadiness[]; items: CustomerProjection[]; authorityRefs: CustomerExactRef[]; blockers: CustomerBlocker[]; countLedger: CustomerCountLedger };
export type CustomerViewResponse = { schemaVersion: typeof CUSTOMER_VIEW_SCHEMA_VERSION; tenant: WorkshopTenant; resourceRevision: number; evaluatedAt: string; dataCutoff: string; readiness: "degraded"; views: CustomerViewSlice[]; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };
export const CUSTOMER_LIFECYCLE_SCHEMA_VERSION = "aos.ecommerce-workshop.customer-lifecycle/v1" as const;
export type CustomerDialogueBatchLedger = { input: number; eligible: number; excluded: number; needsReview: number; unknown: number; deduplicated: number };
export type CustomerDialogueBatchSummary = { batchId: string; revision: number; version: number; lifecycle: "prepared" | "frozen" | "stale"; ledger: CustomerDialogueBatchLedger; contactResolutionCount: 0; actionCount: 0; providerCallCount: 0; sendCount: 0; externalEffectCount: 0; contentHash: string; createdAt: string };
export type CustomerLifecycleContributionViewResponse = { schemaVersion: typeof CUSTOMER_LIFECYCLE_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; atomicSkillIds: ["build-evidence-pack", "segment-entities", "consent-and-purpose-check", "needs-discovery", "customer-journey-plan", "response-or-outreach-draft", "verify-claims", "review-outcomes"]; logicId: "ecommerce-customer-relationship"; primaryColleague: "私域管家"; collaboratorColleagues: ["内容官", "客服专员", "导购顾问", "数据参谋"]; consentPolicyCount: number; segmentCount: number; journeyCount: number; dialogueCount: number; latestBatch: CustomerDialogueBatchSummary | null; blockers: string[]; allowedCommands: ("CREATE_CUSTOMER_CONSENT_POLICY" | "CREATE_CUSTOMER_SEGMENT" | "CREATE_CUSTOMER_JOURNEY" | "CREATE_CUSTOMER_DIALOGUE" | "PREPARE_CUSTOMER_DIALOGUE_BATCH" | "FREEZE_CUSTOMER_DIALOGUE_BATCH")[]; contactResolutionAllowed: false; startAllowed: false; sendAllowed: false; externalEffectsAllowed: false };
export const CUSTOMER_CONTACT_SCHEMA_VERSION = "aos.ecommerce-workshop.customer-contact-governance/v1" as const;
export type CustomerContactLedger = { frozenEligible: number; reserved: number; skippedWithdrawn: number; cancelled: number; accepted: number; applied: number; failed: number; unknown: number; disputed: number };
export type CustomerContactStartSummary = { decisionId: string; revision: number; lifecycle: "governance_prepared"; startSequence: number; itemCount: number; ledger: CustomerContactLedger; operationalBlockers: string[]; contactResolutionCount: 0; providerCallCount: 0; sendCount: 0; externalEffectCount: 0; contentHash: string; startedAt: string };
export type CustomerContactContributionViewResponse = { schemaVersion: typeof CUSTOMER_CONTACT_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; atomicSkillIds: ["build-evidence-pack", "segment-entities", "consent-and-purpose-check", "needs-discovery", "customer-journey-plan", "response-or-outreach-draft", "verify-claims", "review-outcomes"]; logicId: "ecommerce-customer-relationship"; primaryColleague: "私域管家"; collaboratorColleagues: ["内容官", "客服专员", "导购顾问", "数据参谋"]; latestStart: CustomerContactStartSummary | null; ledger: CustomerContactLedger; frequencyPolicyCount: number; withdrawalCount: number; blockers: string[]; allowedCommands: ("CREATE_CUSTOMER_FREQUENCY_POLICY" | "RECORD_CUSTOMER_CONSENT_WITHDRAWAL" | "START_CUSTOMER_DIALOGUE_BATCH_GOVERNANCE" | "RECORD_CUSTOMER_DISPATCH_OBSERVATION")[]; permitRedemptionAllowed: false; contactResolutionAllowed: false; providerDispatchAllowed: false; sendAllowed: false; externalEffectsAllowed: false };

export const THREE_MODULE_CLOSURE_SCHEMA_VERSION = "aos.ecommerce-workshop.three-module-closure/v1" as const;
export type ThreeModuleId = "creator" | "price" | "customer";
export type ThreeModuleExactRef = { resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string };
export type ThreeModuleClosureLedger = { total: number; inProgress: number; succeeded: number; failed: number; unknown: number; disputed: number; skipped: number; state: "empty" | "in_progress" | "completed" | "failed" | "partial" | "unknown" };
export type ThreeModuleClosureSummary = { closureId: string; revision: 1; module: ThreeModuleId; sourceRef: ThreeModuleExactRef; items: { itemKey: string; originalStatus: string; canonicalOutcome: "in_progress" | "succeeded" | "failed" | "unknown" | "disputed" | "skipped"; originalRef: ThreeModuleExactRef; receiptRef: ThreeModuleExactRef | null }[]; ledger: ThreeModuleClosureLedger; contentHash: string; compiledBy: string; compiledAt: string };
export type ThreeModuleUsageSummary = { bindingId: string; closureRef: ThreeModuleExactRef; usageReceiptRef: ThreeModuleExactRef; lineageId: string; quality: "measured" | "estimated" | "unknown"; quantity: number | null; unit: string; adjustmentTotal: number; settlement: "measured" | "estimated" | "unknown"; contentHash: string; boundAt: string };
export type ThreeModuleEffectSummary = { bindingId: string; closureRef: ThreeModuleExactRef; effectReviewRef: ThreeModuleExactRef; maturityStatus: "immature" | "mature" | "insufficient" | "unknown"; accepted: boolean; effectCompleted: boolean; sampleCount: number; minSample: number; cutoffAt: string; observedAt: string; contentHash: string; boundAt: string };
export type ThreeModuleHandoffSummary = { bindingId: string; closureRef: ThreeModuleExactRef; handoffRef: ThreeModuleExactRef; transportStatus: string; businessDecision: "accepted" | "rejected" | "request_more" | "returned" | null; taskRef: Record<string, unknown>; taskRunRef: Record<string, unknown>; disclosureRefCount: number; contentHash: string; boundAt: string };
export type ThreeModuleClosureContributionViewResponse = { schemaVersion: typeof THREE_MODULE_CLOSURE_SCHEMA_VERSION; tenant: WorkshopTenant; module: ThreeModuleId; evaluatedAt: string; atomicSkillIds: string[]; logicId: string; primaryColleague: string; collaboratorColleagues: string[]; latestClosure: ThreeModuleClosureSummary | null; latestUsage: ThreeModuleUsageSummary | null; latestEffect: ThreeModuleEffectSummary | null; latestHandoff: ThreeModuleHandoffSummary | null; blockers: string[]; allowedCommands: ["COMPILE_THREE_MODULE_CLOSURE", "BIND_CANONICAL_USAGE", "BIND_CANONICAL_EFFECT_REVIEW", "BIND_CANONICAL_HANDOFF"]; handoffConsumeAllowed: false; memoryPromotionAllowed: false; externalEffectsAllowed: false };

export const OPERATION_COMMAND_READINESS_SCHEMA_VERSION = "aos.ecommerce-workshop.operation-command-readiness/v1" as const;
export type OperationCommandId = "classify" | "createCase" | "changeMembership" | "manageSla" | "automationKill" | "refund";
export type OperationCommandBlocker = { code: string; dependency: string; requiredAction: string };
export type OperationCommandDescriptor = { commandId: OperationCommandId; label: string; status: "ready" | "blocked"; risk: "controlled" | "high"; sideEffect: "internalAuthority" | "external"; blockers: OperationCommandBlocker[] };
export type OperationCommandReadinessResponse = { schemaVersion: typeof OPERATION_COMMAND_READINESS_SCHEMA_VERSION; tenant: WorkshopTenant; evaluatedAt: string; commands: OperationCommandDescriptor[] };

export const OPERATION_COMMAND_OBSERVATION_SCHEMA_VERSION = "aos.ecommerce-workshop.operation-command-observation/v1" as const;
export type ObservableOperationCommandId = Exclude<OperationCommandId, "refund">;
export type OperationCommandObservationStatus = "notStarted" | "accepted" | "applied" | "failed" | "unknown" | "reconciled";
export type OperationCommandObservationResponse = {
  schemaVersion: typeof OPERATION_COMMAND_OBSERVATION_SCHEMA_VERSION;
  tenant: WorkshopTenant;
  proposalId: string;
  leaseId: string;
  commandId: ObservableOperationCommandId;
  status: OperationCommandObservationStatus;
  proposalHash: string;
  receiptId: string | null;
  requestFingerprint: string | null;
  operationReceiptId: string | null;
  replayAllowed: false;
};

export const SHARED_CONTEXT_SCHEMA_VERSION = "aos.ecommerce-workshop.shared-context/v1" as const;
export type WorkshopSharedRef = { authority: string; resourceType: string; resourceId: string; revision: number; contentHash: string; receiptId: string | null };
export type WorkshopSharedBlocker = { code: string; dependency: string; requiredAction: string };
export type WorkshopSharedContext = {
  contextId: string;
  status: "ready" | "blocked" | "expired" | "forbidden" | "stale" | "unknown";
  sourceModuleId: string | null;
  sourceViewId: string | null;
  sourceRoute: string | null;
  primaryRef: WorkshopSharedRef | null;
  relatedRefs: WorkshopSharedRef[];
  purpose: string | null;
  permissionDecisionRef: WorkshopSharedRef | null;
  disclosurePolicyRef: WorkshopSharedRef | null;
  markings: string[];
  disclosure: "allowed" | "blocked" | "unknown";
  evaluatedAt: string;
  dataCutoff: string | null;
  expiresAt: string;
  freshness: "fresh" | "stale" | "unknown";
  readiness: "ready" | "blocked" | "unknown";
  filterSummary: string | null;
  lineageRefs: WorkshopSharedRef[];
  blockers: WorkshopSharedBlocker[];
};
export type WorkshopTimelineEvent = { eventKey: string; eventType: "task" | "handoff" | "action" | "evidence" | "receipt" | "usage" | "effect"; sourceRef: WorkshopSharedRef; authoritySequence: number; occurredAt: string; recordedAt: string; actorKind: "system" | "human" | "agent"; safeSummary: string; status: string; reasonCode: string | null; causationRef: string | null; correlationRef: string | null; attempt: number | null; receiptRef: WorkshopSharedRef | null; originalRefs: WorkshopSharedRef[]; late: boolean; duplicate: boolean; superseded: boolean; unknown: boolean; reconciled: boolean; stale: boolean };
export type WorkshopNavigationTarget = { targetId: string; status: "available" | "forbidden" | "expired" | "uninstalled" | "disabled" | "stale" | "unresolved"; moduleId: string | null; viewId: string | null; route: string | null; subjectRef: WorkshopSharedRef | null; filterSummary: string | null; focusAnchor: string | null; scrollAnchor: string | null; blockers: WorkshopSharedBlocker[] };
export type WorkshopSharedContextResponse = { schemaVersion: typeof SHARED_CONTEXT_SCHEMA_VERSION; tenant: WorkshopTenant; context: WorkshopSharedContext; timeline: WorkshopTimelineEvent[]; navigationTargets: WorkshopNavigationTarget[]; page: { limit: 100; count: number; hasMore: false; nextCursor: null } };
import type { IssueHandoffInput, ResourceRef } from "../aipAgentControl/contracts";
