import { describe, expect, it } from "vitest";

import { EcommerceWorkshopClient } from "./client";

const payload = { schemaVersion: "aos.ecommerce-workshop.customer-lifecycle/v1", tenant: { orgId: "org-org", projectId: "dev-project" }, evaluatedAt: "2026-08-25T08:00:00Z", atomicSkillIds: ["build-evidence-pack", "segment-entities", "consent-and-purpose-check", "needs-discovery", "customer-journey-plan", "response-or-outreach-draft", "verify-claims", "review-outcomes"], logicId: "ecommerce-customer-relationship", primaryColleague: "私域管家", collaboratorColleagues: ["内容官", "客服专员", "导购顾问", "数据参谋"], consentPolicyCount: 1, segmentCount: 1, journeyCount: 1, dialogueCount: 1, latestBatch: null, blockers: ["CUSTOMER_DIALOGUE_BATCH_NOT_AVAILABLE"], allowedCommands: ["CREATE_CUSTOMER_CONSENT_POLICY", "CREATE_CUSTOMER_SEGMENT", "CREATE_CUSTOMER_JOURNEY", "CREATE_CUSTOMER_DIALOGUE", "PREPARE_CUSTOMER_DIALOGUE_BATCH", "FREEZE_CUSTOMER_DIALOGUE_BATCH"], contactResolutionAllowed: false, startAllowed: false, sendAllowed: false, externalEffectsAllowed: false };
const buildClient = (value: unknown, calls: Array<{ input: RequestInfo | URL; init?: RequestInit }> = []) => new EcommerceWorkshopClient({ fetch: async (input, init) => { calls.push({ input, init }); return new Response(JSON.stringify(value), { status: 200, headers: { "Content-Type": "application/json" } }); }, getBaseUrl: () => "http://example.test", getAuthHeaders: () => ({}) });

describe("customer lifecycle contribution client", () => {
  it("只读取 tenant-scoped 贡献视图并保留 Skill 到数字同事链", async () => { const calls: Array<{ input: RequestInfo | URL; init?: RequestInit }> = []; const result = await buildClient(payload, calls).getCustomerLifecycleContributionView(); expect(result.atomicSkillIds).toHaveLength(8); expect(result.logicId).toBe("ecommerce-customer-relationship"); expect(result.primaryColleague).toBe("私域管家"); expect(result.sendAllowed).toBe(false); expect(calls[0]?.init?.method).toBe("GET"); expect(String(calls[0]?.input)).toContain("/v1/ecommerce-workshop/views/customer/contributions"); });
  it("拒绝任何发送能力漂移", async () => { await expect(buildClient({ ...payload, sendAllowed: true }).getCustomerLifecycleContributionView()).rejects.toThrow(); });
  it("拒绝批次内泄露联系方式字段", async () => { const batch = { tenant: payload.tenant, batchId: "batch-1", revision: 1, version: 1, lifecycle: "prepared", segmentRef: {}, journeyRef: {}, dialogueRef: {}, consentPolicyRef: {}, frequencyPolicyRef: {}, channelCapabilityRef: {}, items: [{ customerId: "customer-1", mobile: "masked" }], itemHashes: ["a".repeat(64)], ledger: { input: 1, eligible: 1, excluded: 0, needsReview: 0, unknown: 0, deduplicated: 0 }, bindingHash: "a".repeat(64), contactResolutionCount: 0, actionCount: 0, providerCallCount: 0, sendCount: 0, externalEffectCount: 0, priorContentHash: null, contentHash: "a".repeat(64), createdBy: "tester", createdAt: payload.evaluatedAt }; await expect(buildClient({ ...payload, latestBatch: batch, blockers: [] }).getCustomerLifecycleContributionView()).rejects.toThrow(/PII|provider payload/); });
});
