import { describe, expect, it } from "vitest";

import { EcommerceWorkshopClient } from "./client";

const payload = { schemaVersion: "aos.ecommerce-workshop.customer-contact-governance/v1", tenant: { orgId: "org-org", projectId: "dev-project" }, evaluatedAt: "2026-08-25T08:00:00Z", atomicSkillIds: ["build-evidence-pack", "segment-entities", "consent-and-purpose-check", "needs-discovery", "customer-journey-plan", "response-or-outreach-draft", "verify-claims", "review-outcomes"], logicId: "ecommerce-customer-relationship", primaryColleague: "私域管家", collaboratorColleagues: ["内容官", "客服专员", "导购顾问", "数据参谋"], latestStart: null, ledger: { frozenEligible: 0, reserved: 0, skippedWithdrawn: 0, cancelled: 0, accepted: 0, applied: 0, failed: 0, unknown: 0, disputed: 0 }, frequencyPolicyCount: 0, withdrawalCount: 0, blockers: ["CUSTOMER_CONTACT_GOVERNANCE_NOT_PREPARED"], allowedCommands: ["CREATE_CUSTOMER_FREQUENCY_POLICY", "RECORD_CUSTOMER_CONSENT_WITHDRAWAL", "START_CUSTOMER_DIALOGUE_BATCH_GOVERNANCE", "RECORD_CUSTOMER_DISPATCH_OBSERVATION"], permitRedemptionAllowed: false, contactResolutionAllowed: false, providerDispatchAllowed: false, sendAllowed: false, externalEffectsAllowed: false };
function buildClient(body: unknown, calls: Array<{ input: RequestInfo | URL; init?: RequestInit }> = []) { return new EcommerceWorkshopClient({ getBaseUrl: () => "http://127.0.0.1:8000", getAuthHeaders: () => ({ "X-Org-Id": "org-org", "X-Project-Id": "dev-project" }), fetch: async (input, init) => { calls.push({ input, init }); return new Response(JSON.stringify(body), { status: 200, headers: { "Content-Type": "application/json" } }); } }); }

describe("customer contact contribution client", () => {
  it("只读取治理贡献视图并保留 Skill 到数字同事链", async () => { const calls: Array<{ input: RequestInfo | URL; init?: RequestInit }> = []; const result = await buildClient(payload, calls).getCustomerContactContributionView(); expect(result.atomicSkillIds).toHaveLength(8); expect(result.logicId).toBe("ecommerce-customer-relationship"); expect(result.primaryColleague).toBe("私域管家"); expect(result.permitRedemptionAllowed).toBe(false); expect(result.providerDispatchAllowed).toBe(false); expect(calls[0]?.init?.method).toBe("GET"); expect(String(calls[0]?.input)).toContain("/v1/ecommerce-workshop/views/customer/contact-contributions"); });
  it("拒绝 Permit 兑换或发送能力漂移", async () => { await expect(buildClient({ ...payload, permitRedemptionAllowed: true }).getCustomerContactContributionView()).rejects.toThrow(); await expect(buildClient({ ...payload, sendAllowed: true }).getCustomerContactContributionView()).rejects.toThrow(); });
  it("拒绝 Start 明细泄露联系方式字段", async () => { const latestStart = { tenant: payload.tenant, decisionId: "start-1", revision: 1, lifecycle: "governance_prepared", batchRef: {}, startSequence: 1, exactRefs: {}, items: [{ itemKey: "customer-1", mobile: "masked" }], ledger: { frozenEligible: 1, reserved: 1, skippedWithdrawn: 0, cancelled: 0, accepted: 0, applied: 0, failed: 0, unknown: 0, disputed: 0 }, operationalBlockers: ["CUSTOMER_CONTACT_PERMIT_REDEMPTION_NOT_AUTHORIZED"], contactResolutionCount: 0, providerCallCount: 0, sendCount: 0, externalEffectCount: 0, contentHash: "a".repeat(64), startedBy: "tester", startedAt: payload.evaluatedAt }; await expect(buildClient({ ...payload, latestStart, ledger: latestStart.ledger, blockers: latestStart.operationalBlockers }).getCustomerContactContributionView()).rejects.toThrow(/PII|provider payload/); });
  it("拒绝不守恒的治理 ledger", async () => { await expect(buildClient({ ...payload, ledger: { ...payload.ledger, frozenEligible: 1 } }).getCustomerContactContributionView()).rejects.toThrow(/不守恒/); });
});
