import { describe, expect, it } from "vitest";
import { EcommerceWorkshopClient } from "./client";

const cutoff = "2026-08-24T08:00:00Z";
const blocker = { code: "PRICE_AUTHORITY_NOT_AVAILABLE", dependency: "price", requiredAction: "attach exact licensed authority" };
const payload = { schemaVersion: "aos.ecommerce-workshop.price-governance-view/v1", tenant: { orgId: "org-org", projectId: "dev-project" }, resourceRevision: 3, evaluatedAt: cutoff, dataCutoff: cutoff, readiness: "degraded", views: ["governance", "competitor", "schedule"].map((viewId) => ({ viewId, status: "blocked", resourceRevision: 3, dataCutoff: cutoff, readinessAxes: ["collection", "match", "policy_case", "notification", "advice_handoff", "repricing"].map((axis) => axis === "repricing" ? { axis, status: "disabled", exactRef: null, blockers: [{ code: "PRICE_REPRICING_DISABLED", dependency: "R4", requiredAction: "complete specialized gate" }] } : { axis, status: "blocked", exactRef: null, blockers: [blocker] }), observations: [], authorityRefs: [], blockers: [{ ...blocker, code: `PRICE_${viewId.toUpperCase()}_AUTHORITY_NOT_AVAILABLE` }], countLedger: { input: 0, eligible: 0, excluded: 0, needsReview: 0, unknown: 0, deduplicated: 0 } })), page: { limit: 100, count: 0, hasMore: false, nextCursor: null } };

describe("price governance strict client", () => {
  it("只调用 tenant-scoped GET 并保留 repricing disabled", async () => { const calls: Array<{ input: RequestInfo | URL; init?: RequestInit }> = []; const client = new EcommerceWorkshopClient({ fetch: async (input, init) => { calls.push({ input, init }); return new Response(JSON.stringify(payload), { status: 200, headers: { "Content-Type": "application/json" } }); }, getBaseUrl: () => "http://example.test", getAuthHeaders: () => ({}) }); const result = await client.getPriceGovernanceView(); expect(result.views).toHaveLength(3); expect(result.views[0]?.readinessAxes[5]?.status).toBe("disabled"); expect(calls[0]?.init?.method).toBe("GET"); expect(String(calls[0]?.input)).toContain("/v1/ecommerce-workshop/views/price-governance"); });
  it("拒绝把 unknown 报价伪装为 0", async () => { const drift: Record<string, any> = structuredClone(payload); const ref = { resourceType: "PriceObservation", resourceId: "obs-1", revision: 1, contentHash: `sha256:${"a".repeat(64)}`, receiptId: "receipt-1" }; drift.views[0]!.observations = [{ observationRef: ref, market: "market", amount: 0, quoteBasis: { basis: "landed", skuRef: { ...ref, resourceType: "Sku" }, bundleRef: null, quantity: 1, unit: "piece", currency: "CNY", tax: "included", shipping: "included", promotionCondition: "none", effectiveFrom: cutoff, effectiveUntil: null }, observedAt: cutoff, freshness: "unknown", license: "unknown", comparability: "unknown", matchStatus: "unknown", originalRefs: [{ ...ref, resourceType: "PriceOriginal" }], mergedOriginalRefs: [], blockers: [blocker] }]; drift.views[0]!.countLedger = { input: 1, eligible: 0, excluded: 0, needsReview: 0, unknown: 1, deduplicated: 0 }; drift.page.count = 1; const client = new EcommerceWorkshopClient({ fetch: async () => new Response(JSON.stringify(drift), { status: 200, headers: { "Content-Type": "application/json" } }), getBaseUrl: () => "http://example.test", getAuthHeaders: () => ({}) }); await expect(client.getPriceGovernanceView()).rejects.toThrow(); });
});
