import { useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent } from "react";
import { Link } from "react-router-dom";
import { PageChrome } from "../../components/PageChrome";
import { aipClient } from "../../api/aip/client";
import { createAssistThread, getAssistThreadHistory, listAssistSubjects, newIdempotencyKey, streamAssistTurn, type AssistEvent, type AssistSubject, type AssistSubjectOption, type AssistThread, type AssistThreadHistory, type ResourceRef, type TaskRunControlResult } from "../../api/aipWorkbench";
import { aipTasksSdk, type RunControlResult, type TaskTimeline } from "../../api/aipTasks";
import { businessDisplayName } from "../../lib/aipChineseLabels";
import { buildExactContextHref } from "../../lib/aipExactContext";

function ref(search: URLSearchParams, prefix: string, expectedType: string): ResourceRef | null { const resourceId = search.get(`${prefix}Id`), revision = search.get(`${prefix}Revision`), authority = search.get(`${prefix}Authority`); return resourceId && revision && authority ? { resourceType: expectedType, resourceId, revision, authority } : null; }
export function subjectFromSearch(search: URLSearchParams): AssistSubject | null { const taskRef = ref(search, "task", "Task"), taskRunRef = ref(search, "taskRun", "TaskRun"), agentRunRef = ref(search, "agentRun", "AgentRun"), resultRef = ref(search, "queryResult", "QueryResultRevision"), cutoffAt = search.get("cutoffAt"); if (!taskRef || !taskRunRef || !agentRunRef || !cutoffAt || Number.isNaN(Date.parse(cutoffAt))) return null; return { taskRef, taskRunRef, agentRunRef, selectionRefs: resultRef ? [resultRef] : [], cutoffAt: new Date(cutoffAt).toISOString() }; }

type RecentTask = { id: string; title: string; status: string; version: number; updatedAt: string };
export function recentTaskBusinessTitle(title: string): string { const clean = String(title || "").replace(/^\s*(?:(?:R\d[\w.-]*|D\d[\w.-]*|W-?[A-Z0-9][\w.-]*|P\d[\w.-]*|AIP-[A-Z0-9.-]+)\s*[·:：—-]?\s*)+/i, "").replace(/\bv\d+\b/gi, "").replace(/\bProvider\b/gi, "模型服务").replace(/\s+/g, " ").trim(); return businessDisplayName(clean, "历史真实任务"); }
function recentTasksFromResponse(value: unknown): RecentTask[] { if (!value || typeof value !== "object" || !Array.isArray((value as { items?: unknown }).items)) return []; return (value as { items: unknown[] }).items.flatMap((raw) => { if (!raw || typeof raw !== "object") return []; const item = raw as Record<string, unknown>; const id = String(item.id || "").trim(), title = String(item.title || "").trim(), status = String(item.status || "").trim(), version = Number(item.version), updatedAt = String(item.updatedAt || ""); if (!id || !title || !["approved", "executing", "paused"].includes(status) || !Number.isInteger(version) || version < 1 || Number.isNaN(Date.parse(updatedAt))) return []; return [{ id, title, status, version, updatedAt }]; }).sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt)).slice(0, 5); }
function positiveRevision(value: string): number | null { const parsed = Number(value); return Number.isInteger(parsed) && parsed > 0 ? parsed : null; }
function activateToggle(event: KeyboardEvent<HTMLButtonElement>, action: () => void) { if (event.key !== "Enter" && event.key !== " ") return; event.preventDefault(); action(); }
function statusName(value: string): string { return ({ queued: "排队中", running: "运行中", paused: "已暂停", succeeded: "已完成", failed: "运行失败", cancelled: "已取消", approved: "已批准", executing: "执行中", completed: "已完成", draft: "草稿", superseded: "已替换", rejected: "未通过" } as Record<string, string>)[value] ?? businessDisplayName(value, "待核对"); }
function sameSubject(left: AssistSubject, right: AssistSubject): boolean { return ["taskRef", "taskRunRef", "agentRunRef"].every((key) => { const a = left[key as keyof AssistSubject] as ResourceRef, b = right[key as keyof AssistSubject] as ResourceRef; return a.resourceType === b.resourceType && a.resourceId === b.resourceId && a.revision === b.revision && a.authority === b.authority; }) && left.cutoffAt === right.cutoffAt; }
function writeSubjectToUrl(subject: AssistSubject, threadId?: string): void { const url = new URL(window.location.href); for (const [prefix, value] of [["task", subject.taskRef], ["taskRun", subject.taskRunRef], ["agentRun", subject.agentRunRef]] as const) { url.searchParams.set(`${prefix}Id`, value.resourceId); url.searchParams.set(`${prefix}Revision`, value.revision); url.searchParams.set(`${prefix}Authority`, value.authority); } url.searchParams.set("cutoffAt", subject.cutoffAt); if (threadId) url.searchParams.set("threadId", threadId); else url.searchParams.delete("threadId"); window.history.replaceState({}, "", `${url.pathname}${url.search}${url.hash}`); }

type AssistPageClient = { createThread: typeof createAssistThread; getHistory?: typeof getAssistThreadHistory; listSubjects?: () => Promise<AssistSubjectOption[]>; streamTurn: typeof streamAssistTurn; newKey: typeof newIdempotencyKey; timeline?: (runId: string) => Promise<TaskTimeline>; controlRun?: (operation: "pause" | "resume" | "cancel", timeline: TaskTimeline, reason: string) => Promise<RunControlResult>; cancelTaskRun?: (runId: string, body: { expectedRunVersion: number; expectedTaskVersion: number; reason: string }, key?: string) => Promise<TaskRunControlResult>; listRecentTasks?: () => Promise<RecentTask[]>; };
const defaultClient: AssistPageClient = { createThread: createAssistThread, getHistory: getAssistThreadHistory, listSubjects: async () => (await listAssistSubjects()).items, streamTurn: streamAssistTurn, newKey: newIdempotencyKey, timeline: (runId) => aipTasksSdk.timeline(runId), controlRun: (operation, timeline, reason) => aipTasksSdk.control(operation, timeline, reason), listRecentTasks: async () => recentTasksFromResponse(await aipClient.request<unknown>("listTasks")) };

function EventCard({ event }: { event: AssistEvent }) { if (event.eventType === "start") return <div style={system}>问题已受理</div>; if (event.eventType === "context") return <div style={system}><strong>业务上下文已冻结</strong><p>本轮回答使用同一数据截止时间和权威引用。</p><details><summary>审计详情</summary><code>{event.context?.contextHash.slice(0, 16)} · {event.context && new Date(event.context.cutoffAt).toLocaleString()}</code></details></div>; if (event.eventType === "delta") return <div style={answer}>{event.content}</div>; if (event.eventType === "proposal") return <div style={system}><strong>已形成待审方案</strong><details><summary>审计详情</summary><code>{event.proposalRef?.resourceType}/{event.proposalRef?.resourceId}@{event.proposalRef?.revision}</code></details></div>; if (event.eventType === "done") return <div style={system}><strong>本轮协作已完成</strong><p>用量记录 {event.usageRefs.length} 项 · 谱系记录 {event.lineageRefs.length} 项</p></div>; return <div role="alert" style={blocked}><strong>本轮未形成可用回答</strong><p>{event.blocker?.message || "运行时返回错误"}</p><p>{event.blocker?.retryable ? "修复依赖后可重新提问。" : "请先完成页面给出的缺失条件。"}</p><details><summary>审计详情</summary><code>{event.blocker?.code || event.eventType.toUpperCase()}</code></details></div>; }

export function AipAssistPage({ client = defaultClient }: { client?: AssistPageClient } = {}) {
  const initialSearch = useMemo(() => new URLSearchParams(window.location.search), []), [subject, setSubject] = useState<AssistSubject | null>(() => subjectFromSearch(initialSearch));
  const [subjectOptions, setSubjectOptions] = useState<AssistSubjectOption[]>([]), [selectedSubjectId, setSelectedSubjectId] = useState(""), [recentTasks, setRecentTasks] = useState<RecentTask[]>([]), [loadingOptions, setLoadingOptions] = useState(false), [optionError, setOptionError] = useState("");
  const [thread, setThread] = useState<AssistThread | null>(null), [history, setHistory] = useState<AssistThreadHistory | null>(null), [events, setEvents] = useState<AssistEvent[]>([]), [timeline, setTimeline] = useState<TaskTimeline | null>(null);
  const [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [focus, setFocus] = useState(false), [contextOpen, setContextOpen] = useState(true), [controlBusy, setControlBusy] = useState(false), [messageRefs, setMessageRefs] = useState<ResourceRef[]>([]), [legacyCancelResult, setLegacyCancelResult] = useState<TaskRunControlResult | null>(null);
  const pending = useRef<{ message: string; threadKey: string; turnKey: string } | null>(null), sendInFlight = useRef(false), controlInFlight = useRef(false), cancelKey = useRef<string | null>(null);

  useEffect(() => { if (subject) return; let active = true; setLoadingOptions(true); const load = client.listSubjects ? client.listSubjects() : client.listRecentTasks ? client.listRecentTasks().then((items) => { if (active) setRecentTasks(items); return []; }) : Promise.resolve([]); void load.then((items) => { if (active) { setSubjectOptions(items); setOptionError(""); } }).catch((cause) => { if (active) setOptionError(cause instanceof Error ? cause.message : String(cause)); }).finally(() => { if (active) setLoadingOptions(false); }); return () => { active = false; }; }, [client, subject]);
  useEffect(() => { if (!subject || !client.timeline) { setTimeline(null); return; } let active = true; void client.timeline(subject.taskRunRef.resourceId).then((value) => { if (active) setTimeline(value); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : String(cause)); }); return () => { active = false; }; }, [client, subject]);
  useEffect(() => { const threadId = initialSearch.get("threadId"); if (!threadId || !subject || !client.getHistory) return; let active = true; void client.getHistory(threadId).then((value) => { if (!active) return; if (!sameSubject(value.thread.subject, subject)) throw new Error("对话线程与当前任务运行不一致"); setThread(value.thread); setHistory(value); setEvents(value.turns.flatMap((item) => item.events)); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : String(cause)); }); return () => { active = false; }; }, [client, initialSearch, subject]);

  function chooseSubject(id: string) { setSelectedSubjectId(id); const item = subjectOptions.find((option) => option.subject.agentRunRef.resourceId === id); if (!item) return; setSubject(item.subject); setThread(null); setHistory(null); setEvents([]); setMessageRefs([]); writeSubjectToUrl(item.subject); }
  async function ensureThread(threadKey: string): Promise<AssistThread> { if (thread) return thread; if (!subject) throw new Error("请选择一个真实任务运行"); const created = await client.createThread({ ...subject, title: `${subjectOptions.find((item) => item.subject.agentRunRef.resourceId === subject.agentRunRef.resourceId)?.taskTitle || "任务"}协作线程` }, threadKey); setThread(created); writeSubjectToUrl(subject, created.threadId); return created; }
  async function refreshHistory(activeThread: AssistThread) { if (!client.getHistory) return; const value = await client.getHistory(activeThread.threadId); setHistory(value); setThread(value.thread); setEvents(value.turns.flatMap((item) => item.events)); }
  async function submit(event: FormEvent) { event.preventDefault(); const clean = message.trim(); if (clean.length < 2 || sendInFlight.current || !subject) return; sendInFlight.current = true; const request = pending.current?.message === clean ? pending.current : { message: clean, threadKey: client.newKey(), turnKey: client.newKey() }; pending.current = request; setBusy(true); setError(null); try { const active = await ensureThread(request.threadKey); const streamed = await client.streamTurn(active.threadId, { message: clean, referenceRefs: messageRefs, attachmentRefs: [], expectedThreadVersion: active.version, cutoffAt: active.subject.cutoffAt }, request.turnKey); setEvents((current) => [...current, ...streamed]); const next = { ...active, version: active.version + 1 }; setThread(next); setMessage(""); setMessageRefs([]); pending.current = null; await refreshHistory(next); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { sendInFlight.current = false; setBusy(false); } }
  async function control(operation: "pause" | "resume" | "cancel") { if (!subject || controlInFlight.current) return; controlInFlight.current = true; setControlBusy(true); setError(null); try { if (timeline && client.controlRun) { await client.controlRun(operation, timeline, `任务协作助手用户${operation === "pause" ? "暂停" : operation === "resume" ? "恢复" : "取消"}`); if (client.timeline) setTimeline(await client.timeline(subject.taskRunRef.resourceId)); } else if (operation === "cancel" && client.cancelTaskRun) { const taskVersion = positiveRevision(subject.taskRef.revision), runVersion = positiveRevision(subject.taskRunRef.revision); if (!taskVersion || !runVersion) throw new Error("任务或任务运行版本不能通过并发安全校验"); const key = cancelKey.current || client.newKey(); cancelKey.current = key; const result = await client.cancelTaskRun(subject.taskRunRef.resourceId, { expectedRunVersion: runVersion, expectedTaskVersion: taskVersion, reason: "AIP Assist 用户取消" }, key); setLegacyCancelResult(result); cancelKey.current = null; } else throw new Error("当前运行控制上下文未完成读取"); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { controlInFlight.current = false; setControlBusy(false); } }

  const option = subjectOptions.find((item) => item.subject.agentRunRef.resourceId === subject?.agentRunRef.resourceId), runStatus = timeline?.run.status ?? option?.runStatus ?? "";
  const canPause = runStatus === "running", canResume = runStatus === "paused", hasLegacyCancel = Boolean(client.cancelTaskRun && subject && positiveRevision(subject.taskRef.revision) && positiveRevision(subject.taskRunRef.revision)), showCancel = Boolean(subject && (client.cancelTaskRun || ["queued", "running", "paused"].includes(runStatus))), canCancel = !legacyCancelResult && (["queued", "running", "paused"].includes(runStatus) || hasLegacyCancel), controlReceipts = timeline?.evidence.filter((item) => item.evidence_type === "run.control" || item.evidenceType === "run.control") ?? [];
  const taskRunLineagePath = subject && positiveRevision(subject.taskRunRef.revision) ? buildExactContextHref("/aip/lineage", { params: new URLSearchParams({ rootType: "task_run", rootId: subject.taskRunRef.resourceId }), refs: { taskRun: subject.taskRunRef }, cutoffAt: subject.cutoffAt, returnTo: `${window.location.pathname}${window.location.search}` }) : null, participants = history?.participants ?? (thread ? [thread.createdBy] : []);

  return <PageChrome title="任务协作助手" lede="在一个真实任务运行中持续提问、查看计划和证据，并安全控制运行。">
    {!subject && <section className="card" style={{ padding: 18, marginBottom: 14 }} data-testid="assist-subject-picker"><h2>选择正在协作的真实任务</h2><p style={muted}>这里只列出已建立任务、任务运行和智能体运行精确关系的当前租户任务。</p>{loadingOptions ? <p>正在读取任务运行…</p> : optionError ? <div role="alert" style={blocked}>任务运行读取失败：{optionError}</div> : subjectOptions.length ? <select aria-label="选择真实任务运行" value={selectedSubjectId} onChange={(event) => chooseSubject(event.target.value)}><option value="">请选择任务</option>{subjectOptions.map((item) => <option key={item.subject.agentRunRef.resourceId} value={item.subject.agentRunRef.resourceId}>{recentTaskBusinessTitle(item.taskTitle)} · {statusName(item.runStatus)}</option>)}</select> : recentTasks.length ? <><h3>选择最近真实任务</h3>{recentTasks.map((item) => <div key={item.id} className="notice"><strong>{recentTaskBusinessTitle(item.title)}</strong><p>当前状态：{statusName(item.status)} · 最近更新 {new Date(item.updatedAt).toLocaleString()}</p><Link to={buildExactContextHref("/aip/logic", { refs: { task: { resourceType: "Task", resourceId: item.id, revision: String(item.version), authority: "aip-task-store" } }, returnTo: "/aip/assist" })}>建立安全运行 →</Link></div>)}<p>选择任务只确定业务任务；还需从真实运行流程补齐任务运行和智能体运行引用。</p></> : <div style={empty}><h3>当前没有可协作的任务运行</h3><p>可从业务逻辑编排创建合法的只读或沙箱运行，完成后将自动出现在这里。</p><Link to="/aip/logic" style={ctaLink}>创建业务任务运行</Link></div>}<div style={{ display: "flex", gap: 10, marginTop: 14 }}><input aria-label="向当前智能体运行提问" disabled placeholder="选择真实任务运行后开始协作" style={input} /><button type="button" disabled>发送</button></div><p data-testid="assist-lineage-blocked" style={muted}>选择真实任务运行后可查看完整谱系。</p></section>}
    {subject && <><div data-testid="assist-ops-stats" style={statsGrid}>{[{ label: "业务任务", value: recentTaskBusinessTitle(option?.taskTitle || timeline?.task.title || "当前任务") }, { label: "负责人", value: option?.owner || timeline?.task.createdBy.actorId || "当前运行账户" }, { label: "任务状态", value: statusName(timeline?.task.status || option?.taskStatus || "") }, { label: "运行状态", value: statusName(runStatus) }, { label: "参与者", value: `${participants.length} 位` }, { label: "协作记录", value: `${history?.turns.length ?? 0} 轮` }].map((item) => <div key={item.label} className="card" style={{ padding: "10px 12px" }}><div style={label}>{item.label}</div><div style={{ fontSize: 16, fontWeight: 700 }}>{item.value}</div></div>)}</div>
      <div style={toolbar}><button type="button" aria-expanded={contextOpen} onClick={() => setContextOpen((value) => !value)} onKeyDown={(event) => activateToggle(event, () => setContextOpen((value) => !value))}>{contextOpen ? "收起上下文" : "展开上下文"}</button><button type="button" aria-pressed={focus} onClick={() => setFocus((value) => !value)} onKeyDown={(event) => activateToggle(event, () => setFocus((value) => !value))}>{focus ? "退出专注" : "专注模式"}</button>{canPause && <button type="button" onClick={() => void control("pause")} disabled={controlBusy}>暂停运行</button>}{canResume && <button type="button" onClick={() => void control("resume")} disabled={controlBusy}>恢复运行</button>}{showCancel && <button type="button" onClick={() => void control("cancel")} disabled={!canCancel || controlBusy} title={!canCancel && !legacyCancelResult ? "任务或任务运行版本不能通过并发安全校验" : undefined}>取消任务运行</button>}{taskRunLineagePath ? <Link to={taskRunLineagePath} data-testid="assist-jump-lineage" style={ctaLink}>查看完整谱系 →</Link> : <span data-testid="assist-lineage-blocked" style={muted}>缺少合法任务运行版本，暂不能查看谱系</span>}<button type="button" onClick={() => { setSubject(null); setThread(null); setHistory(null); setEvents([]); const url = new URL(window.location.href); url.search = ""; window.history.replaceState({}, "", url.pathname); }}>切换任务</button></div>
      {error && <div role="alert" style={blocked}><strong>操作没有完成</strong><p>{error}</p><p>页面保留当前任务和已持久化记录，可修正后重试。</p></div>}{legacyCancelResult && <div role="status" style={system}>任务运行已取消 · 版本 {legacyCancelResult.run.version}</div>}
      <div style={{ display: "grid", gridTemplateColumns: `${focus || !contextOpen ? "0" : "360px"} minmax(0,1fr)`, gap: 16, minHeight: 650 }}><aside style={{ ...panel, display: focus || !contextOpen ? "none" : "grid", alignContent: "start", gap: 16, overflow: "hidden" }} aria-label="任务运行详情"><section><h3>任务概况</h3><p><strong>{recentTaskBusinessTitle(option?.taskTitle || timeline?.task.title || "当前任务")}</strong></p><p style={muted}>{option?.taskDescription || timeline?.task.description || "围绕当前任务运行持续协作。"}</p><dl style={facts}><div><dt>来源</dt><dd>{option?.source || "AIP 任务运行权威"}</dd></div><div><dt>最近更新</dt><dd>{new Date(option?.updatedAt || timeline?.run.updatedAt || subject.cutoffAt).toLocaleString()}</dd></div><div><dt>数据截止</dt><dd>{new Date(subject.cutoffAt).toLocaleString()}</dd></div></dl></section><section><h3>参与者</h3>{participants.length ? <ul>{participants.map((item) => <li key={item}>{businessDisplayName(item, "运行参与者")}</li>)}</ul> : <p style={muted}>发送第一条消息后记录参与者。</p>}</section><section><h3>计划与审批</h3>{timeline ? <><p>{timeline.plan.steps.length} 个计划步骤 · {statusName(timeline.plan.approvalStatus)}</p><ol>{timeline.plan.steps.map((step) => <li key={step.stepKey}>{businessDisplayName(step.title, "业务步骤")}</li>)}</ol></> : <p style={muted}>正在读取计划。</p>}</section><details><summary>精确引用与事件游标（审计用）</summary><RefFact label="任务" value={subject.taskRef} /><RefFact label="任务运行" value={subject.taskRunRef} /><RefFact label="智能体运行" value={subject.agentRunRef} /><p><code>{history?.eventCursor || "0:0"}</code></p></details></aside>
        <section aria-label="当前任务协作" style={{ ...panel, display: "grid", gridTemplateRows: "1fr auto", gap: 16 }}><section style={{ overflow: "auto", display: "grid", alignContent: "start", gap: 12 }} aria-label="协作对话记录">{!events.length && !error ? <div style={empty}><h3>开始围绕当前任务协作</h3><p>可询问计划进度、证据、异常、下一步和审批边界；刷新页面仍可恢复记录。</p></div> : events.map((item, index) => <EventCard key={`${item.turnId}:${item.sequence}:${index}`} event={item} />)}</section><form onSubmit={(event) => void submit(event)} style={{ display: "grid", gap: 10 }}><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><span style={label}>引用本轮上下文：</span>{[subject.taskRef, subject.taskRunRef, subject.agentRunRef].map((item) => { const selected = messageRefs.some((value) => value.resourceType === item.resourceType && value.resourceId === item.resourceId); return <button key={item.resourceType} type="button" aria-pressed={selected} onClick={() => setMessageRefs((values) => selected ? values.filter((value) => value.resourceId !== item.resourceId) : [...values, item])}>{selected ? "✓ " : "+ "}{item.resourceType === "Task" ? "业务任务" : item.resourceType === "TaskRun" ? "任务运行" : "智能体运行"}</button>; })}</div><div style={{ display: "flex", gap: 10 }}><input aria-label="向当前智能体运行提问" value={message} onChange={(event) => setMessage(event.target.value)} disabled={busy} placeholder="输入经营问题、补充条件或要求查看证据…" style={input} /><button type="submit" disabled={busy || message.trim().length < 2} style={{ ...primary, opacity: busy || message.trim().length < 2 ? .5 : 1 }}>{busy ? "处理中…" : "发送"}</button></div></form></section></div>
      <section className="card" style={{ padding: 18, marginTop: 16 }} aria-label="任务运行资产与审计"><h2>计划、产物、证据与运行审计</h2><div style={assetGrid}><Asset title="执行步骤" count={timeline?.steps.length} empty="尚无步骤运行记录" /><Asset title="业务产物" count={timeline?.artifacts.length} empty="尚无业务产物" /><Asset title="证据" count={timeline?.evidence.length} empty="尚无证据记录" /><Asset title="控制回执" count={controlReceipts.length} empty="本次尚未执行运行控制" /><Asset title="用量与成本" count={events.flatMap((event) => event.usageRefs).length} empty="暂无可核算用量记录" /><Asset title="谱系" count={events.flatMap((event) => event.lineageRefs).length} empty="暂无服务端谱系记录" /></div></section></>}
  </PageChrome>;
}

function RefFact({ label: name, value }: { label: string; value: ResourceRef }) { return <div><strong>{name}</strong><p style={muted}>{value.resourceId}@{value.revision}<br />{value.authority}</p></div>; }
function Asset({ title, count, empty: emptyText }: { title: string; count: number | undefined; empty: string }) { return <article><span style={label}>{title}</span><strong style={{ display: "block", fontSize: 22 }}>{count ?? "—"}</strong><small>{count ? "已从当前运行权威读取" : emptyText}</small></article>; }
const panel = { background: "var(--aos-surface, #fff)", border: "1px solid var(--aos-border, #dbe2ea)", borderRadius: 10, padding: 18 }, muted = { color: "var(--aos-text-secondary, #64748b)", overflowWrap: "anywhere" as const }, label = { fontSize: 12, color: "var(--aos-text-secondary, #64748b)" }, input = { flex: 1, padding: "12px 14px", border: "1px solid var(--aos-border, #cbd5e1)", borderRadius: 8, background: "var(--aos-surface, transparent)", color: "inherit" }, primary = { background: "var(--aos-accent, #2563eb)", color: "white", border: 0, borderRadius: 8, padding: "10px 18px" }, empty = { display: "grid", placeContent: "center", textAlign: "center" as const, minHeight: 220, color: "var(--aos-text-secondary, #64748b)" }, system = { padding: 12, color: "var(--aos-text-secondary, #475569)", background: "var(--aos-surface-hover, #f8fafc)", border: "1px solid var(--aos-border, #e2e8f0)", borderRadius: 8, overflowWrap: "anywhere" as const }, answer = { padding: 14, background: "var(--aos-accent-light, #eff6ff)", border: "1px solid var(--aos-accent-border, #bfdbfe)", borderRadius: 8, whiteSpace: "pre-wrap" as const }, blocked = { padding: 12, color: "var(--aos-amber, #92400e)", background: "var(--aos-amber-bg, #fffbeb)", border: "1px solid var(--aos-amber-border, #f59e0b)", borderRadius: 8, overflowWrap: "anywhere" as const }, ctaLink = { display: "inline-block", padding: "6px 10px", borderRadius: 6, background: "var(--aos-accent, #2563eb)", color: "#fff", textDecoration: "none", fontSize: 13 }, statsGrid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(140px,1fr))", gap: 10, marginBottom: 12 }, toolbar = { display: "flex", gap: 8, marginBottom: 12, flexWrap: "wrap" as const }, facts = { display: "grid", gap: 8, margin: 0 }, assetGrid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: 10 };
