// @vitest-environment jsdom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const sdk = vi.hoisted(() => ({
  listBriefs: vi.fn(), listBundles: vi.fn(), listEvalContracts: vi.fn(), listResponsibilityPlans: vi.fn(),
  listStageTemplates: vi.fn(), listArtifactFamilies: vi.fn(), listArtifactRelations: vi.fn(), listReviewIssues: vi.fn(),
  listMediaGateProfiles:vi.fn(),listMediaGateSets:vi.fn(),listContractMigrationDecisions:vi.fn(),
  listProductionContexts:vi.fn(),listImpactPreviews:vi.fn(),listProductionStartDecisions:vi.fn(),
  listProfileRecommendations:vi.fn(),listProfileConfirmations:vi.fn(),confirmMediaProfile:vi.fn(),
  freezeBrief: vi.fn(), freezeEvalContract: vi.fn(), diffEvalContract:vi.fn(), freezeResponsibilityPlan: vi.fn(),
  freezeStageTemplate: vi.fn(),freezeImpactPreview:vi.fn(),startProduction:vi.fn(), compileStageTemplate: vi.fn(), resolveReviewIssue: vi.fn(), returnReviewIssue: vi.fn(),
}));
const actionSdk = vi.hoisted(() => ({ list: vi.fn() }));
const agentControl = vi.hoisted(() => ({ listCapabilities: vi.fn() }));
const apiGetMock = vi.hoisted(() => vi.fn(async (): Promise<{ items: unknown[] }> => ({ items: [] })));
vi.mock("../../api/aipProductionContracts", () => ({ aipProductionContracts: sdk }));
vi.mock("../../api/aipActions", () => ({ aipActionsSdk: actionSdk }));
vi.mock("../../api/aipAgentControl", () => ({ aipAgentControl: agentControl }));
vi.mock("../../api/client", () => ({
  apiGet: apiGetMock,
  apiPost: vi.fn(),
}));
import { ProductionContractsPage } from "./ProductionContractsPage";

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
const tenant={orgId:"org-org",projectId:"dev-project"},hash="a".repeat(64),exact=(resourceType:string,resourceId:string)=>({resourceType,resourceId,revision:1,contentHash:hash});
describe("ProductionContractsPage W2-B authority state",()=>{
  let host:HTMLDivElement,root:Root;
  beforeEach(()=>{window.history.replaceState({},"","/aip/production-contracts");host=document.createElement("div");document.body.appendChild(host);root=createRoot(host);Object.values(sdk).forEach(mock=>mock.mockReset());actionSdk.list.mockReset();agentControl.listCapabilities.mockReset();apiGetMock.mockReset();apiGetMock.mockResolvedValue({items:[]});actionSdk.list.mockResolvedValue({items:[],count:0});agentControl.listCapabilities.mockResolvedValue({tenant,items:[],count:0,availableCount:0});sdk.listBriefs.mockResolvedValue({tenant,items:[],count:0});sdk.listBundles.mockResolvedValue({tenant,items:[],count:0});sdk.listResponsibilityPlans.mockResolvedValue({tenant,items:[],count:0});sdk.listStageTemplates.mockResolvedValue({tenant,items:[],count:0});sdk.listArtifactFamilies.mockResolvedValue({tenant,items:[],count:0});sdk.listMediaGateProfiles.mockResolvedValue({tenant,items:[],count:0});sdk.listMediaGateSets.mockResolvedValue({tenant,items:[],count:0});sdk.listContractMigrationDecisions.mockResolvedValue({tenant,items:[],count:0});sdk.listArtifactRelations.mockResolvedValue({tenant,items:[],count:0});sdk.listReviewIssues.mockResolvedValue({tenant,items:[],count:0});sdk.listProductionContexts.mockResolvedValue({tenant,items:[],count:0});sdk.listImpactPreviews.mockResolvedValue({tenant,items:[],count:0});sdk.listProductionStartDecisions.mockResolvedValue({tenant,items:[],count:0});sdk.listProfileRecommendations.mockResolvedValue({tenant,items:[],count:0});sdk.listProfileConfirmations.mockResolvedValue({tenant,items:[],count:0});});
  afterEach(()=>{act(()=>root.unmount());host.remove();});
  it("展示四类权威空态且不伪造职责模板",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);expect(host.textContent).toContain("职责计划");expect(host.textContent).toContain("职责模板权威未接入前保持关闭");});
  it("默认按真实业务任务汇总版本、依赖、消费方和退出状态，不再展示失效创建按钮",async()=>{
    sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});
    sdk.listBriefs.mockResolvedValue({tenant,count:1,items:[{tenant,briefId:"brief-1",taskId:"task-1",revision:3,version:4,briefType:"skill_publish",schemaRef:{resourceType:"Schema",resourceId:"brief",revision:"1",authority:"aip"},spec:{title:"发布商品卖点提炼技能"},contentHash:hash,lifecycle:"frozen",createdBy:"user:dev",createdAt:"2026-08-30T01:00:00Z"}]});
    await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);
    const overview=host.querySelector('[data-testid="production-business-overview"]');
    expect(overview?.textContent).toContain("发布商品卖点提炼技能");expect(overview?.textContent).toContain("当前修订 3");expect(overview?.textContent).toContain("执行计划、数字同事与工作台任务流");expect(overview?.textContent).toContain("当前版本有效");
    expect(host.textContent).not.toContain("创建契约（需真实依赖）");expect(host.querySelector('a[href="/aip/assist?taskId=task-1"]')).not.toBeNull();
  });
  it("从任务、逻辑或数字同事进入时保留可回跳的来源上下文",async()=>{window.history.replaceState({},"","/aip/production-contracts?taskId=task-1&logicId=logic-1&agentId=agent-1");sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);const context=host.querySelector('[data-testid="production-source-context"]');expect(context?.textContent).toContain("已保留来源上下文");expect(context?.querySelector('a[href="/aip/logic/logic-1"]')).not.toBeNull();expect(context?.querySelector('a[href="/aip/agents?agentId=agent-1"]')).not.toBeNull();});
  it("只读展示 W6-02 职责档位治理链且不自动改档或合并",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});const schemaRef={resourceType:"Schema",resourceId:"schema-1",revision:"1",authority:"aip"};sdk.listResponsibilityPlans.mockResolvedValue({tenant,count:1,items:[{tenant,planId:"plan-1",revision:1,version:1,profile:"STANDARD",templateRef:exact("ResponsibilityTemplateRevision","template-standard"),slots:[{slotId:"operator",responsibilityType:"operation",requiredCapabilityIds:["commerce.read"],inputSchemaRef:schemaRef,outputSchemaRef:schemaRef,gateRefs:[],returnStage:"review",assignee:{kind:"agent_instance",resourceId:"agent-1",version:1}}],mergeDecisions:[],profileRecommendationRef:exact("ProfileRecommendationRevision","recommendation-1"),profileConfirmationId:"confirmation-1",mergePolicyRef:exact("MergePolicyRevision","policy-1"),mergeDecisionReceiptIds:[],coverage:"complete",uncoveredSlots:[],contentHash:hash,lifecycle:"frozen",readiness:"ready",blockers:[],createdBy:"user:dev",createdAt:"2026-08-25T01:00:00Z"}]});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);const governance=host.querySelector('[data-testid="profile-governance-plan-1"]');expect(governance?.textContent).toContain("建议、确认与合并策略共同固定");expect(governance?.textContent).toContain("本页只读展示，不自动改档或合并");expect(host.textContent).toContain("confirmation-1");});
  it("展示三档预计成本、未知不归零，并用服务端摘要提交人工确认",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});const known=(profile:"LITE"|"STANDARD",amount:string)=>({profile,currency:"CNY",componentCount:1,priceSnapshotRefs:[exact("ModelPriceSnapshotRevision",`price-${profile}`)],lowerAmount:amount,upperAmount:amount,assumptions:["按当前任务范围"],unknownCodes:[],confidence:"high",expiresAt:"2099-08-26T00:00:00Z"});const unknown={profile:"FULL",currency:"CNY",componentCount:1,priceSnapshotRefs:[],lowerAmount:null,upperAmount:null,assumptions:[],unknownCodes:["PRICE_SNAPSHOT_UNAVAILABLE"],confidence:"unknown",expiresAt:"2099-08-26T00:00:00Z"};const recommendation={tenant,recommendationId:"recommendation-1",revision:1,subjectRef:exact("TaskBriefRevision","brief-1"),recommendedProfile:"STANDARD",candidateTemplateRefs:{LITE:exact("ResponsibilityTemplateRevision","lite"),STANDARD:exact("ResponsibilityTemplateRevision","standard"),FULL:exact("ResponsibilityTemplateRevision","full")},selectedTemplateRef:exact("ResponsibilityTemplateRevision","standard"),policyRef:exact("MergePolicyRevision","policy-1"),riskLevel:1,channelCount:2,reasonCodes:["POLICY_FLOOR_STANDARD"],unknownCodes:[],dependencyRefs:[exact("TaskBriefRevision","brief-1")],projectedCostRanges:[known("LITE","1.25"),known("STANDARD","2.50"),unknown],projectedDuration:{lowerSeconds:60,upperSeconds:120,assumptions:[],unknownCodes:[]},assumptions:["任务范围不变"],confidence:"medium",readiness:"ready",blockers:[],snapshotHash:hash,contentHash:hash,expiresAt:"2099-08-26T00:00:00Z",createdBy:"user:dev",createdAt:"2026-08-25T01:00:00Z"};sdk.listProfileRecommendations.mockResolvedValue({tenant,items:[recommendation],count:1});sdk.confirmMediaProfile.mockResolvedValue({});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);expect(host.textContent).toContain("原子 Skill 成本快照经 Logic 与策略");expect(host.textContent).toContain("CNY 2.50–2.50");expect(host.textContent).toContain("未知（不以 0 代替） · PRICE_SNAPSHOT_UNAVAILABLE");const confirm=[...host.querySelectorAll("button")].find(item=>item.textContent==="确认建议档位与预计区间") as HTMLButtonElement;expect(confirm.disabled).toBe(false);await act(async()=>confirm.click());expect(sdk.confirmMediaProfile).toHaveBeenCalledWith({recommendationId:"recommendation-1",recommendationRevision:1,recommendationHash:hash,selectedProfile:"STANDARD",reason:"接受当前建议与预计成本区间"},expect.stringMatching(/^w7-ui-profile-confirm-/),hash);});
  it("阻断的评测契约显示原因并禁止冻结",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,count:1,items:[{tenant,contractId:"eval-1",revision:1,version:1,suiteRef:exact("EvalSuiteRevision","suite-1"),publicationRef:null,releaseGateRef:null,artifactSchemaRef:{resourceType:"Schema",resourceId:"artifact",revision:"1",authority:"aip"},severityThresholds:{critical:0.9},gatePolicy:{},returnMapping:{fail:"review"},overridePolicy:{},contentHash:hash,lifecycle:"draft",readiness:"blocked",blockers:[{code:"PUBLICATION_REF_REQUIRED",message:"缺少发布事实",resourceRef:null}],createdBy:"user:dev",createdAt:"2026-08-14T00:00:00Z"}]});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);expect(host.textContent).toContain("PUBLICATION_REF_REQUIRED");const button=[...host.querySelectorAll("button")].find(item=>item.textContent==="冻结评测契约") as HTMLButtonElement;expect(button.disabled).toBe(true);expect(sdk.freezeEvalContract).not.toHaveBeenCalled();});
  it("只展示服务端返回的评测契约权威差异",async()=>{
    sdk.listEvalContracts.mockResolvedValue({tenant,count:1,items:[{tenant,contractId:"eval-1",revision:2,version:2,suiteRef:exact("EvalSuiteRevision","suite-1"),publicationRef:exact("PublicationEvent","pub-1"),releaseGateRef:exact("ReleaseGateDecision","gate-1"),artifactSchemaRef:{resourceType:"Schema",resourceId:"artifact",revision:"1",authority:"aip"},severityThresholds:{critical:0.9},gatePolicy:{mode:"all"},returnMapping:{fail:"review"},overridePolicy:{allowed:false},contentHash:hash,lifecycle:"frozen",readiness:"ready",blockers:[],createdBy:"user:dev",createdAt:"2026-08-14T00:00:00Z"}]});
    sdk.diffEvalContract.mockResolvedValue({tenant,contractId:"eval-1",fromRevision:1,toRevision:2,fromContentHash:"b".repeat(64),toContentHash:hash,changes:[{field:"gate_policy",label:"门禁策略",before:{mode:"any"},after:{mode:"all"},impact:"旧批准不可继承"}],changeCount:1,summary:"共 1 项语义变更"});
    await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);
    const button=[...host.querySelectorAll("button")].find(item=>item.textContent==="查看与上一修订的权威差异") as HTMLButtonElement;
    await act(async()=>button.click());
    expect(sdk.diffEvalContract).toHaveBeenCalledWith("eval-1",1,2);
    expect(host.querySelector('[aria-label="评测契约权威差异"]')?.textContent).toContain("门禁策略");
    expect(host.textContent).toContain("差异由服务端生成，本页不重算");
  });
  it("展示三类生产契约权威真实空态",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);expect(host.textContent).toContain("阶段模板");expect(host.textContent).toContain("尚无阶段模板");expect(host.textContent).toContain("尚无产物关系");expect(host.textContent).toContain("尚无评审问题");});
  it("只读展示 Artifact Family 分叉、Master Variant 和独立批准执行轴",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});const artifactRef=(artifactId:string)=>({artifactId,contentHash:hash});const lineage=[exact("StageTemplateRevision","stage-1")];sdk.listArtifactFamilies.mockResolvedValue({tenant,count:1,items:[{tenant,familyId:"family-1",version:4,currentRevision:4,manifestRef:artifactRef("manifest-1"),members:[{artifactRef:artifactRef("master-1"),familyRevision:2,role:"master",artifactType:"media_asset",profile:"STANDARD",platform:"douyin",renditionSpecHash:hash,lineageRefs:lineage,masterRef:null,supersedesRef:null,approvalStatus:"unknown",executionStatus:"unknown",createdAt:"2026-08-25T01:00:00Z"},{artifactRef:artifactRef("variant-a"),familyRevision:3,role:"variant",artifactType:"media_asset",profile:"STANDARD",platform:"douyin",renditionSpecHash:hash,lineageRefs:lineage,masterRef:artifactRef("master-1"),supersedesRef:null,approvalStatus:"unknown",executionStatus:"unknown",createdAt:"2026-08-25T01:01:00Z"},{artifactRef:artifactRef("variant-b"),familyRevision:4,role:"variant",artifactType:"media_asset",profile:"STANDARD",platform:"douyin",renditionSpecHash:hash,lineageRefs:lineage,masterRef:artifactRef("master-1"),supersedesRef:null,approvalStatus:"unknown",executionStatus:"unknown",createdAt:"2026-08-25T01:02:00Z"}],candidateGroups:[{selectionKey:`variant:media_asset:STANDARD:douyin:${hash}`,role:"variant",artifactType:"media_asset",profile:"STANDARD",platform:"douyin",renditionSpecHash:hash,candidates:[artifactRef("variant-a"),artifactRef("variant-b")],selectedRef:null,status:"conflict"}],selectionDecisions:[],topologyStatus:"conflict",updatedAt:"2026-08-25T01:02:00Z"}]});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);const family=host.querySelector('[data-testid="artifact-family-family-1"]');expect(family?.textContent).toContain("存在并发分叉");expect(family?.textContent).toContain("r2 · Master");expect(family?.textContent).toContain("Variant");expect(family?.textContent).toContain("批准：未知（未从家族状态推断）");expect(family?.textContent).toContain("执行：未知（未从家族状态推断）");expect(family?.textContent).toContain("必须显式选择");});
  it("只读展示四门同源贡献与失败关闭，不伪造批准",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});sdk.listMediaGateProfiles.mockResolvedValue({tenant,count:1,items:[{tenant,profileId:"profile-1",revision:1,sourceBundleRef:exact("BundleManifestRevision","bundle-1"),signatureRef:exact("BundleSignatureVerification","signature-1"),policyRef:exact("MediaGatePolicyRevision","policy-1"),gates:[],contentHash:hash,createdBy:"user:dev",createdAt:"2026-08-25T01:00:00Z"}]});const attempt={resourceType:"StepRunAttempt",runId:"run-1",stepKey:"render",stepRunId:"step-run-1",attempt:2,inputHash:hash};const result=(gateId:string,outcome:"passed"|"failed",issueRef:null|{resourceType:"ReviewIssue";resourceId:string;version:number})=>({gateId,outcome,evalReportRef:exact("EvalReportRevision",`report-${gateId}`),ruleRef:exact("EvalRuleRevision",`rule-${gateId}`),issueRef,overrideRef:null,datasetRef:{id:"dataset-1"},judgeRef:{id:"judge-1"},gatePassed:outcome==="passed"});sdk.listMediaGateSets.mockResolvedValue({tenant,count:1,items:[{tenant,gateSetId:"gate-set-1",reviewCycleId:"cycle-1",artifactRef:{artifactId:"variant-1",contentHash:hash},familyId:"family-1",variantProfile:"STANDARD",variantPlatform:"douyin",renditionSpecHash:hash,evalContractRef:exact("EvalContractRevision","contract-1"),gateProfileRef:exact("MediaGateProfileRevision","profile-1"),policyRef:exact("MediaGatePolicyRevision","policy-1"),cutoffAt:"2026-08-25T01:00:00Z",stageAttemptRef:attempt,gateResults:[result("media.fact","passed",null),result("media.brand","passed",null),result("media.copyright","failed",{resourceType:"ReviewIssue",resourceId:"issue-1",version:1}),result("media.platform","passed",null)],contractMigrationRef:null,readiness:"blocked",eligibleForApproval:false,blockerCodes:["MEDIA_GATE_COPYRIGHT_FAILED"],contentHash:hash,actor:"reviewer",createdAt:"2026-08-25T01:00:00Z"}]});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);const view=host.querySelector('[data-testid="media-gate-set-gate-set-1"]');expect(view?.textContent).toContain("事实门");expect(view?.textContent).toContain("版权门");expect(view?.textContent).toContain("ReviewIssue issue-1@v1");expect(view?.textContent).toContain("MEDIA_GATE_COPYRIGHT_FAILED");expect(view?.textContent).not.toContain("已批准");});
  it("从真实 Bundle exact refs 打开受控证据抽屉且不伪造贡献归因",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});sdk.listBundles.mockResolvedValue({tenant,count:1,items:[{tenant,bundleId:"bundle-1",revision:1,briefRef:exact("TaskBriefRevision","brief-1"),subjectRefs:[],cutoffAt:"2026-08-25T01:00:00Z",itemRefs:[exact("Evidence","evidence-1")],coverage:"complete",missing:[],conflicts:[],uncertainties:[],freshness:"fresh",marking:["public"],licenseSummary:{},contentHash:hash,lifecycle:"frozen",createdBy:"user:dev",createdAt:"2026-08-25T01:00:00Z",revoked:false,revokeReason:null}]});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);const open=[...host.querySelectorAll("button")].find(item=>item.textContent==="查看受控证据披露") as HTMLButtonElement;await act(async()=>open.click());expect(host.querySelector('[role="dialog"]')?.getAttribute("aria-label")).toBe("受控证据披露");expect(host.textContent).toContain("evidence-1");expect(host.textContent).toContain("按服务端决策逐层展示证据");expect(host.textContent).toContain("原子技能待核对");expect(host.textContent).toContain("查看安全摘要");});
  it("评审处置禁用态给出精确失败关闭原因",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);const resolve=[...host.querySelectorAll("button")].find(item=>item.textContent==="标记已解决") as HTMLButtonElement;expect(resolve.disabled).toBe(true);expect(resolve.title).toBe("请选择待处置问题并填写处置原因");expect(sdk.resolveReviewIssue).not.toHaveBeenCalled();});
  it("阻断的阶段模板显示来源原因且不允许冻结或编译",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});sdk.listStageTemplates.mockResolvedValue({tenant,count:1,items:[{tenant,templateId:"stage-1",revision:1,version:1,profile:"ecommerce-standard",sourceBundleRef:exact("AssetBundleRevision","bundle-1"),stages:[{stageId:"analysis",title:"分析",dependsOn:[],applicability:{kind:"always",profiles:[]},requiredSlotIds:["analyst"],inputSchemaRef:{resourceType:"Schema",resourceId:"in",revision:"1",authority:"aip"},outputSchemaRef:{resourceType:"Schema",resourceId:"out",revision:"1",authority:"aip"},gateRefs:[],checkpointPolicy:{},retryPolicy:{},compensationPolicy:{}}],contentHash:hash,lifecycle:"draft",sealedBy:null,sealedAt:null,sealHash:null,readiness:"blocked",blockers:[{code:"STAGE_SOURCE_AUTHORITY_UNAVAILABLE",message:"缺少权威解析器",resourceRef:exact("AssetBundleRevision","bundle-1")}],createdBy:"user:dev",createdAt:"2026-08-14T00:00:00Z"}]});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);expect(host.textContent).toContain("STAGE_SOURCE_AUTHORITY_UNAVAILABLE");const freeze=[...host.querySelectorAll("button")].find(item=>item.textContent==="冻结阶段模板") as HTMLButtonElement;expect(freeze.disabled).toBe(true);const compile=[...host.querySelectorAll("button")].find(item=>item.textContent==="编译为执行计划草稿") as HTMLButtonElement;expect(compile.disabled).toBe(true);});
  it("受治理阶段编译自动提交完整 exact refs 并只展示 Plan 草稿摘要",async()=>{
    sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});
    const planRef=exact("ResponsibilityPlanRevision","plan-1"),recommendationRef=exact("ProfileRecommendationRevision","recommendation-1"),policyRef=exact("MergePolicyRevision","policy-1");
    sdk.listStageTemplates.mockResolvedValue({tenant,count:1,items:[{tenant,templateId:"stage-1",revision:1,version:1,profile:"STANDARD",sourceBundleRef:exact("AssetBundleRevision","bundle-1"),stages:[],contentHash:hash,lifecycle:"frozen",sealedBy:"user:dev",sealedAt:"2026-08-25T01:00:00Z",sealHash:hash,readiness:"ready",blockers:[],createdBy:"user:dev",createdAt:"2026-08-25T01:00:00Z"}]});
    sdk.listResponsibilityPlans.mockResolvedValue({tenant,count:1,items:[{tenant,planId:"plan-1",revision:1,version:1,profile:"STANDARD",templateRef:exact("ResponsibilityTemplateRevision","template-1"),slots:[{slotId:"operator",responsibilityType:"operation",requiredCapabilityIds:["commerce.read"],inputSchemaRef:{resourceType:"Schema",resourceId:"in",revision:"1",authority:"aip"},outputSchemaRef:{resourceType:"Schema",resourceId:"out",revision:"1",authority:"aip"},gateRefs:[],returnStage:"review",assignee:{kind:"agent_instance",resourceId:"agent-1",version:1}}],mergeDecisions:[],profileRecommendationRef:recommendationRef,profileConfirmationId:"confirmation-1",mergePolicyRef:policyRef,mergeDecisionReceiptIds:[],coverage:"complete",uncoveredSlots:[],contentHash:hash,lifecycle:"frozen",readiness:"ready",blockers:[],createdBy:"user:dev",createdAt:"2026-08-25T01:00:00Z"}]});
    const context={tenant,contextId:"context-1",revision:1,taskId:"task-1",briefRef:exact("TaskBriefRevision","brief-1"),evidenceBundleRef:exact("EvidenceBundleRevision","evidence-1"),evalContractRef:exact("EvalContractRevision","eval-1"),responsibilityPlanRef:planRef,productionProfileRef:null,preparationRef:null,profile:"STANDARD",dependencySnapshot:[],dependencySnapshotHash:hash,contentHash:hash,lifecycle:"frozen",readiness:"ready",blockers:[],createdBy:"user:dev",createdAt:"2026-08-25T01:00:00Z"};
    sdk.listProductionContexts.mockResolvedValue({tenant,count:1,items:[context]});
    sdk.listProfileRecommendations.mockResolvedValue({tenant,count:1,items:[{tenant,recommendationId:"recommendation-1",revision:1,subjectRef:context.briefRef,recommendedProfile:"STANDARD",candidateTemplateRefs:{LITE:exact("ResponsibilityTemplateRevision","lite"),STANDARD:exact("ResponsibilityTemplateRevision","standard"),FULL:exact("ResponsibilityTemplateRevision","full")},selectedTemplateRef:exact("ResponsibilityTemplateRevision","standard"),policyRef,riskLevel:1,channelCount:1,reasonCodes:["POLICY_STANDARD"],unknownCodes:[],dependencyRefs:[],projectedCostRanges:[],projectedDuration:null,assumptions:[],confidence:"high",readiness:"ready",blockers:[],snapshotHash:hash,contentHash:hash,expiresAt:"2099-08-26T00:00:00Z",createdBy:"user:dev",createdAt:"2026-08-25T01:00:00Z"}]});
    sdk.listProfileConfirmations.mockResolvedValue({tenant,count:1,items:[{confirmationId:"confirmation-1",recommendationId:"recommendation-1",recommendationRevision:1,recommendationHash:hash,selectedProfile:"STANDARD",policyRef}]});
    agentControl.listCapabilities.mockResolvedValue({tenant,count:1,availableCount:1,items:[{capabilityId:"commerce.read",revision:2,displayName:"读取商品",lifecycle:"published",aliases:[],riskLevel:"R0",readiness:"available",readinessReasons:[],contentHash:hash}]});
    sdk.compileStageTemplate.mockResolvedValue({tenant,taskId:"task-1",templateRef:exact("StageTemplateRevision","stage-1"),responsibilityPlanRef:planRef,productionContextRef:exact("ProductionContextRevision","context-1"),planRef:exact("PlanRevision","compiled-plan"),compilerVersion:"w7c.v1",inputHash:hash,compilationHash:hash,normalizedStageIds:["analysis"],applicableStageIds:["analysis"],notApplicableStageIds:[],createdAt:"2026-08-25T01:00:00Z"});
    await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);
    const choose=async(aria:string,value:string)=>{const select=host.querySelector(`[aria-label="${aria}"]`) as HTMLSelectElement;await act(async()=>{select.value=value;select.dispatchEvent(new Event("change",{bubbles:true}));});};
    await choose("阶段模板修订","stage-1");await choose("职责计划修订","plan-1");await choose("编译生产上下文修订","context-1");
    const task=host.querySelector('[aria-label="编译真实 Task ID"]') as HTMLInputElement;const inputSetter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;await act(async()=>{inputSetter?.call(task,"task-1");task.dispatchEvent(new Event("input",{bubbles:true}));});
    expect(host.querySelector('[data-testid="governed-compile-ready"]')?.textContent).toContain("1 项原子 Capability");
    const compile=[...host.querySelectorAll("button")].find(item=>item.textContent==="编译为执行计划草稿") as HTMLButtonElement;expect(compile.disabled).toBe(false);await act(async()=>compile.click());
    expect(sdk.compileStageTemplate).toHaveBeenCalledWith("stage-1",expect.objectContaining({briefRef:context.briefRef,evidenceBundleRef:context.evidenceBundleRef,evalContractRef:context.evalContractRef,profileRecommendationRef:recommendationRef,profileConfirmationId:"confirmation-1",mergePolicyRef:policyRef,capabilityRefs:{"commerce.read":{resourceType:"CapabilityRevision",resourceId:"commerce.read",revision:2,contentHash:hash}}}),expect.stringMatching(/^w7-ui-stage-compile-/));
    expect(host.querySelector('[data-testid="stage-compilation-result"]')?.textContent).toContain("未创建任务运行");
  });
  it("展示生产启动空态并明确不伪造运行成功",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);expect(host.textContent).toContain("尚无影响预览");expect(host.textContent).toContain("没有提交过组合门，不等于运行成功");expect(host.querySelector('[data-testid="start-logic-empty"]')?.textContent).toContain("尚无已发布业务逻辑");const start=[...host.querySelectorAll("button")].find(item=>item.textContent==="通过组合门并创建任务运行记录") as HTMLButtonElement;expect(start.disabled).toBe(true);});
  it("展示影响预览未知项、阻断与启动禁用原因",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});const source={resourceType:"Metric",resourceId:"m1",revision:"1",authority:"aip"},known={quality:"measured",value:{count:1},sourceRefs:[source],cutoffAt:"2026-08-14T00:00:00Z",details:{}},unknown={quality:"unknown",value:null,sourceRefs:[],cutoffAt:null,details:{}};sdk.listImpactPreviews.mockResolvedValue({tenant,count:1,items:[{tenant,previewId:"preview-1",revision:1,version:1,taskId:"task-1",planRef:exact("PlanRevision","plan-1"),briefRef:exact("TaskBriefRevision","brief-1"),evidenceBundleRef:exact("EvidenceBundleRevision","bundle-1"),evalContractRef:exact("EvalContractRevision","eval-1"),responsibilityPlanRef:exact("ResponsibilityPlanRevision","responsibility-1"),stageTemplateRef:exact("StageTemplateRevision","stage-1"),modelRouteRef:null,runtimePolicyRef:null,bindingRefs:[],capabilityRef:null,accountRef:null,impact:{objectScope:known,channelScope:known,cost:unknown,budget:unknown,risks:known,reversibility:known,approvalChain:known,rateCapacityKill:known},expiresAt:"2099-08-15T00:00:00Z",contentHash:hash,dependencySnapshotHash:hash,actionBindingHash:hash,lifecycle:"draft",readiness:"blocked",blockers:[{code:"ROUTE_REQUIRED",message:"缺少路由",resourceRef:null}],frozenBy:null,frozenAt:null,createdBy:"user:dev",createdAt:"2026-08-14T00:00:00Z"}]});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);expect(host.textContent).toContain("未知（不以 0 代替）");expect(host.textContent).toContain("ROUTE_REQUIRED");expect(host.textContent).toContain("请选择影响预览的精确修订");});
  it("已启动决策只声明任务运行记录并展示生产上下文，不伪造智能体已运行",async()=>{sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});sdk.listProductionStartDecisions.mockResolvedValue({tenant,count:1,items:[{tenant,decisionId:"decision-1",status:"started",taskId:"task-1",productionContextRef:exact("ProductionContextRevision","context-1"),planRef:exact("PlanRevision","plan-1"),previewRef:exact("ImpactPreviewRevision","preview-1"),actionProposalRef:{proposalId:"proposal-1",version:1,proposalHash:hash},dependencySnapshotHash:hash,blockers:[],taskRunRef:{resourceType:"TaskRun",resourceId:"run-1",revision:"1",authority:"aip-task-store"},createdBy:"user:dev",createdAt:"2026-08-14T00:00:00Z"}]});await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);expect(host.textContent).toContain("已创建任务运行记录（尚未启动智能体）");expect(host.textContent).toContain("context-1@1");expect(host.textContent).not.toContain("智能体已运行");});
  it("只列出同 Task 同 Preview 的 approved Proposal，并自动提交 exact version/hash",async()=>{
    sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});
    const known={quality:"measured",value:{count:1},sourceRefs:[{resourceType:"Metric",resourceId:"m1",revision:"1",authority:"aip"}],cutoffAt:"2026-08-14T00:00:00Z",details:{}};
    const preview={tenant,previewId:"preview-1",revision:1,version:2,taskId:"task-1",planRef:exact("PlanRevision","plan-1"),productionContextRef:exact("ProductionContextRevision","context-1"),briefRef:exact("TaskBriefRevision","brief-1"),evidenceBundleRef:exact("EvidenceBundleRevision","bundle-1"),evalContractRef:exact("EvalContractRevision","eval-1"),responsibilityPlanRef:exact("ResponsibilityPlanRevision","responsibility-1"),stageTemplateRef:exact("StageTemplateRevision","stage-1"),modelRouteRef:exact("ModelRouteRevision","route-1"),runtimePolicyRef:exact("RuntimePolicyRevision","policy-1"),bindingRefs:[exact("CapabilityBindingRevision","binding-1")],capabilityRef:exact("CapabilityRevision","capability-1"),accountRef:null,impact:{objectScope:known,channelScope:known,cost:known,budget:known,risks:known,reversibility:known,approvalChain:known,rateCapacityKill:known},expiresAt:"2099-08-15T00:00:00Z",contentHash:hash,dependencySnapshotHash:hash,actionBindingHash:hash,lifecycle:"frozen",readiness:"ready",blockers:[],frozenBy:"user:dev",frozenAt:"2026-08-14T00:00:00Z",createdBy:"user:dev",createdAt:"2026-08-14T00:00:00Z"};
    sdk.listImpactPreviews.mockResolvedValue({tenant,count:1,items:[preview]});
    sdk.listProductionContexts.mockResolvedValue({tenant,count:1,items:[{tenant,contextId:"context-1",revision:1,taskId:"task-1",briefRef:preview.briefRef,evidenceBundleRef:preview.evidenceBundleRef,evalContractRef:preview.evalContractRef,responsibilityPlanRef:preview.responsibilityPlanRef,productionProfileRef:null,preparationRef:null,profile:"ecommerce-standard",dependencySnapshot:[],dependencySnapshotHash:hash,contentHash:hash,lifecycle:"frozen",readiness:"ready",blockers:[],createdBy:"user:dev",createdAt:"2026-08-14T00:00:00Z"}]});
    const proposal=(id:string,status:string,previewRef:ReturnType<typeof exact>|null)=>({id,actionType:{actionTypeId:"publish_content",revisionHash:hash,objectType:"ContentDraft"},taskId:"task-1",runId:null,objectRef:null,impactPreviewRef:previewRef,purpose:"发布草稿",riskLevel:"R2",payload:{},proposalHash:hash,status,expiresAt:"2099-08-16T00:00:00Z",version:3,createdBy:{actorType:"user",actorId:"maker"},createdAt:"2026-08-14T00:00:00Z",updatedAt:"2026-08-14T00:00:00Z"});
    const draft=(id:string)=>({id:`draft-${id}`,proposalId:id,proposalVersion:3,proposalHash:hash,diff:{},evidenceRefs:[],status:"approved",createdAt:"2026-08-14T00:00:00Z"});
    actionSdk.list.mockResolvedValue({count:2,items:[{proposal:proposal("proposal-ready","approved",exact("ImpactPreviewRevision","preview-1")),draft:draft("proposal-ready"),approvals:[]},{proposal:proposal("proposal-wrong","drafted",exact("ImpactPreviewRevision","preview-1")),draft:draft("proposal-wrong"),approvals:[]}]});
    apiGetMock.mockResolvedValue({items:[{id:"logic-1",name:"已发布逻辑",revision:2,graph_hash:hash,published_version:1,persisted:true}]});
    sdk.startProduction.mockResolvedValue({});
    await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);
    const choose=async(labelText:string,value:string)=>{const labelEl=[...host.querySelectorAll("label")].find(item=>item.textContent?.startsWith(labelText));const select=labelEl?.querySelector("select") as HTMLSelectElement;await act(async()=>{select.value=value;select.dispatchEvent(new Event("change",{bubbles:true}));});};
    await choose("影响预览","preview-1");
    expect((host.querySelector('[data-testid="start-action-proposal-select"]') as HTMLSelectElement).options).toHaveLength(2);
    expect(host.textContent).not.toContain("proposal-wrong@v3");
    await choose("生产上下文","context-1");
    await choose("执行提案","proposal-ready");
    await choose("已发布业务逻辑","logic-1");
    expect(host.querySelector('[data-testid="start-action-proposal-exact"]')?.textContent).toContain("proposal-ready");
    const start=[...host.querySelectorAll("button")].find(item=>item.textContent==="通过组合门并创建任务运行记录") as HTMLButtonElement;
    expect(start.disabled).toBe(false);
    await act(async()=>start.click());
    expect(sdk.startProduction).toHaveBeenCalledWith(expect.objectContaining({actionProposalRef:{proposalId:"proposal-ready",version:3,proposalHash:hash},previewRef:exact("ImpactPreviewRevision","preview-1"),logicGraphId:"logic-1",logicRevision:2,logicGraphHash:hash}),expect.stringMatching(/^w2-ui-production-start-/));
  });
  it("生产上下文与影响预览固定修订不一致时保持启动门关闭",async()=>{
    sdk.listEvalContracts.mockResolvedValue({tenant,items:[],count:0});
    const known={quality:"measured",value:{count:1},sourceRefs:[{resourceType:"Metric",resourceId:"m1",revision:"1",authority:"aip"}],cutoffAt:"2026-08-14T00:00:00Z",details:{}};
    sdk.listImpactPreviews.mockResolvedValue({tenant,count:1,items:[{tenant,previewId:"preview-1",revision:1,version:1,taskId:"task-1",planRef:exact("PlanRevision","plan-1"),productionContextRef:exact("ProductionContextRevision","context-pinned"),briefRef:exact("TaskBriefRevision","brief-1"),evidenceBundleRef:exact("EvidenceBundleRevision","bundle-1"),evalContractRef:exact("EvalContractRevision","eval-1"),responsibilityPlanRef:exact("ResponsibilityPlanRevision","responsibility-1"),stageTemplateRef:exact("StageTemplateRevision","stage-1"),modelRouteRef:exact("ModelRouteRevision","route-1"),runtimePolicyRef:exact("RuntimePolicyRevision","policy-1"),bindingRefs:[],capabilityRef:null,accountRef:null,impact:{objectScope:known,channelScope:known,cost:known,budget:known,risks:known,reversibility:known,approvalChain:known,rateCapacityKill:known},expiresAt:"2099-08-15T00:00:00Z",contentHash:hash,dependencySnapshotHash:hash,actionBindingHash:hash,lifecycle:"frozen",readiness:"ready",blockers:[],frozenBy:"user:dev",frozenAt:"2026-08-14T00:00:00Z",createdBy:"user:dev",createdAt:"2026-08-14T00:00:00Z"}]});
    sdk.listProductionContexts.mockResolvedValue({tenant,count:1,items:[{tenant,contextId:"context-other",revision:1,taskId:"task-1",briefRef:exact("TaskBriefRevision","brief-1"),evidenceBundleRef:exact("EvidenceBundleRevision","bundle-1"),evalContractRef:exact("EvalContractRevision","eval-1"),responsibilityPlanRef:exact("ResponsibilityPlanRevision","responsibility-1"),productionProfileRef:null,preparationRef:null,profile:"standard",dependencySnapshot:[],dependencySnapshotHash:hash,contentHash:hash,lifecycle:"frozen",readiness:"ready",blockers:[],createdBy:"user:dev",createdAt:"2026-08-14T00:00:00Z"}]});
    await act(async()=>root.render(<ProductionContractsPage/>));await act(async()=>undefined);
    const choose=async(labelText:string,value:string)=>{const labelEl=[...host.querySelectorAll("label")].find(item=>item.textContent?.startsWith(labelText));const select=labelEl?.querySelector("select") as HTMLSelectElement;await act(async()=>{select.value=value;select.dispatchEvent(new Event("change",{bubbles:true}));});};
    await choose("影响预览","preview-1");await choose("生产上下文","context-other");
    expect(host.textContent).toContain("所选生产上下文与影响预览固定的精确修订不一致");
    expect(sdk.startProduction).not.toHaveBeenCalled();
  });
});
