import type { ExactRuntimeRef, ModelRuntimeOverview, RuntimeAssetSummary, RuntimeCapacityPoolSummary, RuntimeEvalGateSummary, RuntimeLifecycle, RuntimeReadiness, RuntimeResolution } from "./contracts";

function object(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} 必须是对象`); return value as Record<string, unknown>; }
function array(value: unknown, label: string): unknown[] { if (!Array.isArray(value)) throw new Error(`${label} 必须是数组`); return value; }
function string(value: unknown, label: string): string { if (typeof value !== "string" || !value.trim()) throw new Error(`${label} 必须是非空字符串`); return value; }
function integer(value: unknown, label: string, min = 0): number { if (typeof value !== "number" || !Number.isInteger(value) || value < min) throw new Error(`${label} 必须是大于等于 ${min} 的整数`); return value; }
function enumeration<T extends string>(value: unknown, label: string, values: readonly T[]): T { const result = string(value, label) as T; if (!values.includes(result)) throw new Error(`${label} 非法`); return result; }
function sha(value: unknown, label: string): string { const result = string(value, label); if (!/^[0-9a-f]{64}$/.test(result)) throw new Error(`${label} 非 SHA-256`); return result; }
function iso(value: unknown, label: string): string { const result = string(value, label); if (Number.isNaN(Date.parse(result))) throw new Error(`${label} 非时间`); return result; }

function ref(value: unknown, label: string): ExactRuntimeRef { const raw = object(value, label); return { assetType: string(raw.assetType, `${label}.assetType`), assetId: string(raw.assetId, `${label}.assetId`), revision: integer(raw.revision, `${label}.revision`, 1), contentHash: sha(raw.contentHash, `${label}.contentHash`) }; }
function asset(value: unknown, label: string): RuntimeAssetSummary { const raw = object(value, label); return { ref: ref(raw.ref, `${label}.ref`), lifecycle: enumeration<RuntimeLifecycle>(raw.lifecycle, `${label}.lifecycle`, ["draft", "validated", "active", "suspended", "revoked"]), dependencyRefs: array(raw.dependencyRefs, `${label}.dependencyRefs`).map((item, index) => ref(item, `${label}.dependencyRefs[${index}]`)) }; }
function gate(value: unknown, label: string): RuntimeEvalGateSummary { const raw = object(value, label); return { ref: ref(raw.ref, `${label}.ref`), status: enumeration(raw.status, `${label}.status`, ["passed", "failed", "blocked", "unknown"] as const) }; }
function pool(value: unknown, label: string): RuntimeCapacityPoolSummary { const raw = object(value, label); return { poolId: string(raw.poolId, `${label}.poolId`), revision: integer(raw.revision, `${label}.revision`, 1), contentHash: sha(raw.contentHash, `${label}.contentHash`), routeRef: ref(raw.routeRef, `${label}.routeRef`), modelRef: ref(raw.modelRef, `${label}.modelRef`), providerRef: ref(raw.providerRef, `${label}.providerRef`), maxConcurrency: integer(raw.maxConcurrency, `${label}.maxConcurrency`, 1), maxTokenUnits: integer(raw.maxTokenUnits, `${label}.maxTokenUnits`, 1), tokenUnitPerReservation: integer(raw.tokenUnitPerReservation, `${label}.tokenUnitPerReservation`, 1), leaseSeconds: integer(raw.leaseSeconds, `${label}.leaseSeconds`, 1), activeReservations: integer(raw.activeReservations, `${label}.activeReservations`), reservedTokenUnits: integer(raw.reservedTokenUnits, `${label}.reservedTokenUnits`), lifecycle: enumeration<RuntimeLifecycle>(raw.lifecycle, `${label}.lifecycle`, ["draft", "validated", "active", "suspended", "revoked"]) }; }
function resolution(value: unknown, label: string): RuntimeResolution { const raw = object(value, label); const nullable = (item: unknown, nested: string) => item === null ? null : ref(item, nested); const result = { route: ref(raw.route, `${label}.route`), policy: ref(raw.policy, `${label}.policy`), readiness: enumeration<RuntimeReadiness>(raw.readiness, `${label}.readiness`, ["ready", "blocked", "unknown"]), selectedModel: nullable(raw.selectedModel, `${label}.selectedModel`), selectedProvider: nullable(raw.selectedProvider, `${label}.selectedProvider`), selectedPriceSnapshot: nullable(raw.selectedPriceSnapshot, `${label}.selectedPriceSnapshot`), blockerCodes: array(raw.blockerCodes, `${label}.blockerCodes`).map((item, index) => string(item, `${label}.blockerCodes[${index}]`)), resolvedAt: iso(raw.resolvedAt, `${label}.resolvedAt`) }; if (result.readiness === "ready" && (!result.selectedModel || !result.selectedProvider || !result.selectedPriceSnapshot || result.blockerCodes.length)) throw new Error(`${label} ready 合同不完整`); if (result.readiness !== "ready" && (!result.blockerCodes.length || result.selectedModel || result.selectedProvider || result.selectedPriceSnapshot)) throw new Error(`${label} blocked/unknown 合同不诚实`); return result; }

export function parseModelRuntimeOverview(value: unknown): ModelRuntimeOverview {
  const raw = object(value, "ModelRuntimeOverview"); const tenant = object(raw.tenant, "tenant");
  const map = <T>(key: string, parser: (item: unknown, label: string) => T) => array(raw[key], key).map((item, index) => parser(item, `${key}[${index}]`));
  return { tenant: { orgId: string(tenant.orgId, "tenant.orgId"), projectId: string(tenant.projectId, "tenant.projectId") }, providers: map("providers", asset), models: map("models", asset), routes: map("routes", asset), policies: map("policies", asset), priceSnapshots: map("priceSnapshots", asset), evalGates: map("evalGates", gate), capacityPools: map("capacityPools", pool), resolutions: map("resolutions", resolution), generatedAt: iso(raw.generatedAt, "generatedAt") };
}
