#Requires -Version 5.1
<#
  T0.9 — inventory P0 open-source refs (align clone_aos_deps.ps1 / 22).
  Does NOT clone (avoids SSH hang). Missing dirs → WARN or -Strict FAIL.

  Usage (from aos-platform):
    .\scripts\ci\record-aos-deps.ps1
    .\scripts\ci\record-aos-deps.ps1 -Strict
#>
param(
  [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
  [string]$RefsRoot = "C:\work\projects\wchat\mybuddy-v01",
  [string]$OutFile = "",
  [switch]$Strict
)

$ErrorActionPreference = "Stop"
if (-not $OutFile) {
  $OutFile = Join-Path $Root "deploy\dev\aos-deps-inventory.md"
}

$expected = @(
  @{ Tier = "P0"; Rel = "refs\ocr\PaddleOCR"; Note = "OCR reference; not in customer package" },
  @{ Tier = "P0"; Rel = "refs\objstore\minio"; Note = "AGPL server - refs only" },
  @{ Tier = "P0"; Rel = "refs\objstore-sdk\minio-py"; Note = "MinIO Python SDK (Apache)" }
)

$lines = New-Object System.Collections.Generic.List[string]
[void]$lines.Add("# AOS deps inventory (T0.9 / Dev only)")
[void]$lines.Add("")
[void]$lines.Add("> Generated by ``scripts/ci/record-aos-deps.ps1`` - **not** for customer dist")
[void]$lines.Add("> Refs root: ``$RefsRoot``")
[void]$lines.Add("> Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
[void]$lines.Add("")
[void]$lines.Add("| Tier | Path | Status | Note |")
[void]$lines.Add("| --- | --- | --- | --- |")

$missing = @()
foreach ($e in $expected) {
  $full = Join-Path $RefsRoot $e.Rel
  $ok = Test-Path $full
  $status = if ($ok) { "OK" } else { "MISSING" }
  if (-not $ok) { $missing += $e.Rel }
  [void]$lines.Add("| $($e.Tier) | ``$($e.Rel)`` | $status | $($e.Note) |")
}

[void]$lines.Add("")
[void]$lines.Add("## Clone hint")
[void]$lines.Add("")
[void]$lines.Add('```powershell')
[void]$lines.Add("cd $RefsRoot")
[void]$lines.Add(".\clone_aos_deps.ps1 -Tier P0")
[void]$lines.Add('```')
[void]$lines.Add("")
[void]$lines.Add("P1/P2 optional: ``-Tier P1`` / ``-Tier All`` - see doc 22.")
[void]$lines.Add("")

$outDir = Split-Path $OutFile -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }
# UTF-8 with BOM for Windows markdown tools
$utf8Bom = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllLines($OutFile, $lines.ToArray(), $utf8Bom)

Write-Host "Wrote $OutFile"
if ($missing.Count -gt 0) {
  Write-Host "MISSING ($($missing.Count)):"
  $missing | ForEach-Object { Write-Host "  $_" }
  if ($Strict) {
    Write-Error "T0.9 Strict: P0 refs missing"
    exit 1
  }
  Write-Host "T0.9 WARN: missing P0 dirs (non-strict)"
  exit 0
}

Write-Host "T0.9 PASS: P0 refs present"
exit 0
