#Requires -Version 5.1
<#
  T0.10+ — optional syft / trivy hardening (scheme 54).
  Prefer PATH tools; else Docker images. Missing tools → SKIP (exit 0)
  unless -RequireTools.

  Usage (from aos-platform):
    .\scripts\ci\run-syft-trivy.ps1
    .\scripts\ci\run-syft-trivy.ps1 -Strict
    .\scripts\ci\run-syft-trivy.ps1 -RequireTools
#>
param(
  [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
  [switch]$Strict,
  [switch]$RequireTools,
  [switch]$SkipDockerPull
)

$ErrorActionPreference = "Stop"
$outDir = Join-Path $Root "deploy\dev"
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

$syftOut = Join-Path $outDir "sbom-syft.json"
$trivyOut = Join-Path $outDir "trivy-fs.json"
$reportMd = Join-Path $outDir "syft-trivy-report.md"

function Test-Cmd([string]$Name) {
  return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function ConvertTo-DockerBindPath([string]$WinPath) {
  # This repo's docker.cmd = `wsl -d Ubuntu -- docker`. Bind must be a
  # path visible inside that Linux VM (/mnt/<drive>/...), not /c/... or
  # C:\... (those mount empty or fail "invalid mode").
  $full = (Resolve-Path $WinPath).Path
  if ($full -match '^[A-Za-z]:') {
    $drive = $full.Substring(0, 1).ToLower()
    $rest = ($full.Substring(2) -replace '\\', '/')
    return "/mnt/$drive$rest"
  }
  return ($full -replace '\\', '/')
}

function Test-Docker() {
  try {
    $null = & docker version --format "{{.Server.Version}}" 2>$null
    return ($LASTEXITCODE -eq 0)
  } catch { return $false }
}

function Test-DockerBindUsable([string]$BindPath) {
  # Probe: empty mount = remote/WSL path wrong → treat docker scans as unavailable.
  $prev = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  $vol = ($BindPath + ':/src')
  $out = & docker run --rm -v $vol alpine test -d /src/apps 2>&1
  $ok = ($LASTEXITCODE -eq 0)
  $ErrorActionPreference = $prev
  return $ok
}

function Get-JsonBlob([string]$Text, [string]$Marker) {
  $idx = $Text.IndexOf($Marker)
  if ($idx -lt 0) { return $null }
  # walk back to nearest '{'
  $start = $Text.LastIndexOf('{', $idx)
  if ($start -lt 0) { $start = $Text.IndexOf('{') }
  if ($start -lt 0) { return $null }
  return $Text.Substring($start).Trim()
}

$hasSyft = Test-Cmd "syft"
$hasTrivy = Test-Cmd "trivy"
$hasDocker = Test-Docker
$dockerBind = $null
$dockerBindOk = $false
if ($hasDocker -and (-not $hasSyft -or -not $hasTrivy)) {
  $dockerBind = ConvertTo-DockerBindPath $Root
  $dockerBindOk = Test-DockerBindUsable $dockerBind
  if (-not $dockerBindOk) {
    Write-Host "WARN: Docker up but bind '$dockerBind' unusable (empty/wrong). Docker scan mode disabled."
  }
}

$canSyft = $hasSyft -or $dockerBindOk
$canTrivy = $hasTrivy -or $dockerBindOk

$lines = New-Object System.Collections.Generic.List[string]
[void]$lines.Add("# syft / trivy report (Dev only)")
[void]$lines.Add("")
[void]$lines.Add("> Generated by ``scripts/ci/run-syft-trivy.ps1``")
[void]$lines.Add("> Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
[void]$lines.Add("")
[void]$lines.Add("| Tool | Available | Mode |")
[void]$lines.Add("| --- | --- | --- |")
[void]$lines.Add("| syft | $hasSyft | $(if ($hasSyft) { 'PATH' } elseif ($dockerBindOk) { 'docker' } else { 'none' }) |")
[void]$lines.Add("| trivy | $hasTrivy | $(if ($hasTrivy) { 'PATH' } elseif ($dockerBindOk) { 'docker' } else { 'none' }) |")
[void]$lines.Add("| docker | $hasDocker | bind=$(if ($dockerBindOk) { $dockerBind } else { 'n/a' }) |")
[void]$lines.Add("")

if (-not $canSyft -and -not $canTrivy) {
  [void]$lines.Add("## Result")
  [void]$lines.Add("")
  [void]$lines.Add("SKIP: neither PATH tools nor usable Docker bind available.")
  [void]$lines.Add("")
  $utf8 = New-Object System.Text.UTF8Encoding $true
  [System.IO.File]::WriteAllLines($reportMd, $lines.ToArray(), $utf8)
  Write-Host "SKIP: syft/trivy not available (no PATH, no usable Docker bind). Wrote $reportMd"
  if ($RequireTools) {
    Write-Error "RequireTools: install syft/trivy or fix Docker bind (/mnt/<drive>/... for WSL docker)"
    exit 1
  }
  exit 0
}

$hits = New-Object System.Collections.Generic.List[string]
$web = Join-Path $Root "apps\web"
$api = Join-Path $Root "services\aos-api"
$denied = @(
  Get-Content (Join-Path $PSScriptRoot "agpl-denied-images.txt") |
    Where-Object { $_ -and -not $_.StartsWith("#") }
)

# --- syft ---
if ($canSyft) {
  Write-Host "Running syft..."
  $targets = @()
  if (Test-Path $web) { $targets += $web }
  if (Test-Path $api) { $targets += $api }
  $tmpParts = @()
  $i = 0
  foreach ($t in $targets) {
    $i++
    $part = Join-Path $outDir ("sbom-syft-part-{0}.json" -f $i)
    if ($hasSyft) {
      & syft "dir:$t" -o cyclonedx-json="$part" 2>&1 | Out-Host
    } else {
      $rel = $t.Substring($Root.Length).TrimStart("\", "/")
      $relUnix = ($rel -replace "\\", "/")
      if (-not $SkipDockerPull) {
        & docker pull anchore/syft:v1.19.0 2>&1 | Out-Host
      }
      $prev = $ErrorActionPreference
      $ErrorActionPreference = "Continue"
      $vol = ($dockerBind + ':/src')
      $json = & docker run --rm -v $vol anchore/syft:v1.19.0 "dir:/src/$relUnix" -o cyclonedx-json 2>&1
      $code = $LASTEXITCODE
      $ErrorActionPreference = $prev
      if ($code -ne 0) {
        Write-Host ($json | Out-String)
        throw "syft docker failed exit=$code"
      }
      $text = ($json | Out-String)
      $blob = Get-JsonBlob $text '"bomFormat"'
      if (-not $blob) { $blob = Get-JsonBlob $text '{' }
      if (-not $blob) { $blob = $text }
      Set-Content -Path $part -Value $blob -Encoding UTF8
    }
    if (Test-Path $part) { $tmpParts += $part }
  }
  if ($tmpParts.Count -ge 1) {
    # Keep first part as primary artifact; note multi-target in report
    Copy-Item $tmpParts[0] $syftOut -Force
    [void]$lines.Add("## syft")
    [void]$lines.Add("")
    [void]$lines.Add("Wrote ``deploy/dev/sbom-syft.json`` (primary from $($tmpParts.Count) target(s)).")
    [void]$lines.Add("")
    Write-Host "OK syft -> $syftOut"
  } else {
    [void]$lines.Add("## syft")
    [void]$lines.Add("")
    [void]$lines.Add("WARN: syft produced no output.")
    [void]$lines.Add("")
    $hits.Add("SYFT_EMPTY")
  }
} else {
  [void]$lines.Add("## syft")
  [void]$lines.Add("")
  [void]$lines.Add("SKIP")
  [void]$lines.Add("")
}

# --- trivy fs (license + vuln summary; AGPL name hit) ---
if ($canTrivy) {
  Write-Host "Running trivy fs..."
  $scanRoot = $Root
  try {
    if ($hasTrivy) {
      & trivy fs --scanners vuln,license --skip-dirs node_modules,.git,deploy/dev,.venv,dist --format json -o $trivyOut $scanRoot 2>&1 | Out-Host
    } else {
      if (-not $SkipDockerPull) {
        & docker pull aquasec/trivy:0.58.1 2>&1 | Out-Host
      }
      $null = & docker volume create aos-trivy-cache 2>$null
      # Write JSON into bind-mounted deploy/dev (avoid capturing huge stdout; timeout kills hangs)
      $outName = "trivy-fs.json"
      $volSrc = ($dockerBind + ':/src')
      $prev = $ErrorActionPreference
      $ErrorActionPreference = "Continue"
      $trivyJob = Start-Job -ScriptBlock {
        param($VolSrc, $OutName)
        $outPath = "/src/deploy/dev/$OutName"
        & docker run --rm `
          -v $VolSrc `
          -v "aos-trivy-cache:/root/.cache/" `
          aquasec/trivy:0.58.1 `
          fs --scanners license `
          --skip-dirs "node_modules,.git,deploy,.venv,dist" `
          --format json `
          -o $outPath `
          /src/apps
      } -ArgumentList $volSrc, $outName
      $finished = Wait-Job $trivyJob -Timeout 180
      if (-not $finished) {
        Write-Warning "trivy docker timed out after 180s — skipping artifact"
        Stop-Job $trivyJob -ErrorAction SilentlyContinue
        Remove-Job $trivyJob -Force -ErrorAction SilentlyContinue
      } else {
        $jobOut = Receive-Job $trivyJob 2>&1 | Out-String
        Remove-Job $trivyJob -Force -ErrorAction SilentlyContinue
        if (-not (Test-Path $trivyOut)) {
          # fallback: try extract JSON from job output
          $blob = Get-JsonBlob $jobOut '"SchemaVersion"'
          if (-not $blob) { $blob = Get-JsonBlob $jobOut '"Results"' }
          if ($blob) {
            Set-Content -Path $trivyOut -Value $blob -Encoding UTF8
          } else {
            Write-Host "trivy: no JSON written; head:"
            Write-Host ($jobOut.Substring(0, [Math]::Min(400, $jobOut.Length)))
          }
        }
      }
      $ErrorActionPreference = $prev
    }
  } catch {
    Write-Warning "trivy failed: $_"
  }
  if (Test-Path $trivyOut) {
    [void]$lines.Add("## trivy")
    [void]$lines.Add("")
    [void]$lines.Add("Wrote ``deploy/dev/trivy-fs.json``")
    $raw = Get-Content -Raw $trivyOut -ErrorAction SilentlyContinue
    if ($raw) {
      foreach ($d in $denied) {
        # Ignore hits under deploy/dev path strings
        $idx = 0
        while (($idx = $raw.IndexOf($d, $idx, [StringComparison]::OrdinalIgnoreCase)) -ge 0) {
          $window = $raw.Substring([Math]::Max(0, $idx - 200), [Math]::Min(400, $raw.Length - [Math]::Max(0, $idx - 200)))
          if ($window -notmatch 'deploy[/\\]dev') {
            $hits.Add("TRIVY_DENIED_IMAGE :: $d")
            break
          }
          $idx += $d.Length
        }
      }
      # Count Results if present
      if ($raw -match '"Results"') {
        [void]$lines.Add("")
        [void]$lines.Add("Report contains Results (see JSON for CVE/license details).")
      }
    }
    [void]$lines.Add("")
    Write-Host "OK trivy -> $trivyOut"
  } else {
    [void]$lines.Add("## trivy")
    [void]$lines.Add("")
    [void]$lines.Add("WARN: trivy produced no output.")
    [void]$lines.Add("")
    $hits.Add("TRIVY_EMPTY")
  }
} else {
  [void]$lines.Add("## trivy")
  [void]$lines.Add("")
  [void]$lines.Add("SKIP")
  [void]$lines.Add("")
}

[void]$lines.Add("## Hits")
[void]$lines.Add("")
if ($hits.Count -eq 0) {
  [void]$lines.Add("none")
} else {
  foreach ($h in $hits) { [void]$lines.Add("- $h") }
}
[void]$lines.Add("")
[void]$lines.Add("## HA Keycloak")
[void]$lines.Add("")
[void]$lines.Add("Not in this knife. Use Dev profile oidc (docs 50); HA remains B-TX3-01.")
[void]$lines.Add("")

$utf8Bom = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllLines($reportMd, $lines.ToArray(), $utf8Bom)
Write-Host "Wrote $reportMd"

if ($hits.Count -gt 0) {
  Write-Host "HITS ($($hits.Count)):"
  $hits | ForEach-Object { Write-Host "  $_" }
  if ($Strict) {
    Write-Error "syft/trivy Strict: hits found"
    exit 1
  }
  Write-Host "WARN: non-strict (exit 0)"
  exit 0
}

Write-Host "PASS: syft/trivy gate clean (or SKIP partial)"
exit 0
