export const AIP_OPERATIONS = {
  listCapabilities: { method: "GET", path: "/v1/aip/capabilities", mutation: false },
  tripCircuit: { method: "POST", path: "/v1/aip/circuit/trip", mutation: true },
  listDrafts: { method: "GET", path: "/v1/aip/drafts", mutation: false },
  getDraft: { method: "GET", path: "/v1/aip/drafts/{draft_id}", mutation: false },
  approveDraft: { method: "POST", path: "/v1/aip/drafts/{draft_id}/approve", mutation: true },
  rejectDraft: { method: "POST", path: "/v1/aip/drafts/{draft_id}/reject", mutation: true },
  listEvals: { method: "GET", path: "/v1/aip/evals", mutation: false },
  listInsights: { method: "GET", path: "/v1/aip/insights", mutation: false },
  listTools: { method: "GET", path: "/v1/aip/tools", mutation: false },
  createTask: { method: "POST", path: "/v1/aip/tasks", mutation: true },
  listTasks: { method: "GET", path: "/v1/aip/tasks", mutation: false },
  getTask: { method: "GET", path: "/v1/aip/tasks/{task_id}", mutation: false },
  createPlanRevision: { method: "POST", path: "/v1/aip/tasks/{task_id}/plans", mutation: true },
  approvePlanRevision: { method: "POST", path: "/v1/aip/tasks/{task_id}/plans/{revision}/approve", mutation: true },
  createTaskRun: { method: "POST", path: "/v1/aip/tasks/{task_id}/runs", mutation: true },
  listTaskRunsByLogic: { method: "GET", path: "/v1/aip/task-runs?logic_graph_id={logic_graph_id}&limit={limit}", mutation: false },
  getTaskRun: { method: "GET", path: "/v1/aip/task-runs/{run_id}", mutation: false },
  getTaskRunTimeline: { method: "GET", path: "/v1/aip/task-runs/{run_id}/timeline", mutation: false },
  startTaskRun: { method: "POST", path: "/v1/aip/task-runs/{run_id}/start", mutation: true },
  pauseTaskRun: { method: "POST", path: "/v1/aip/task-runs/{run_id}/pause", mutation: true },
  resumeTaskRun: { method: "POST", path: "/v1/aip/task-runs/{run_id}/resume", mutation: true },
  cancelTaskRun: { method: "POST", path: "/v1/aip/task-runs/{run_id}/cancel", mutation: true },
  rollbackTaskRun: { method: "POST", path: "/v1/aip/task-runs/{run_id}/rollback", mutation: true },
  listActionProposals: { method: "GET", path: "/v1/aip/action-proposals?limit={limit}", mutation: false },
  getActionProposal: { method: "GET", path: "/v1/aip/action-proposals/{proposal_id}", mutation: false },
  getActionProposalTimeline: { method: "GET", path: "/v1/aip/action-proposals/{proposal_id}/timeline", mutation: false },
  getActionExecution: { method: "GET", path: "/v1/aip/action-proposals/{proposal_id}/execution", mutation: false },
  decideActionProposal: { method: "POST", path: "/v1/aip/action-proposals/{proposal_id}/decision", mutation: true },
  acquireActionLease: { method: "POST", path: "/v1/aip/action-proposals/{proposal_id}/lease", mutation: true },
  executeActionLease: { method: "POST", path: "/v1/aip/action-leases/{lease_id}/execute", mutation: true },
  reconcileActionReceipt: { method: "POST", path: "/v1/aip/action-receipts/{receipt_id}/reconcile", mutation: true },
} as const;

export type AipOperationId = keyof typeof AIP_OPERATIONS;
