import { useEffect, useRef, useState } from "react";

import { EcommerceWorkshopClientError, ecommerceWorkshopClient, type AnalystViewId, type AnalystViewResponse, type LearningScenarioContribution } from "../../api/ecommerceWorkshop";
import type { InvestigationReadClient } from "../../api/ecommerceInvestigation";
import { AsyncStateBoundary, type AsyncState } from "./AsyncStateBoundary";
import { AsyncJobDrawer, type AsyncJobLoader } from "./AsyncJobDrawer";
import { BusinessInvestigationTab } from "./BusinessInvestigationTab";
import {
  isBusinessInvestigationReadEnabled,
  resolveBusinessInvestigationFeatureFlags,
  type BusinessInvestigationFeatureFlags,
} from "./businessInvestigationFeatureFlags";
import { ContributionLineage } from "./production";

type Client = Pick<typeof ecommerceWorkshopClient, "getAnalystView"> & Partial<Pick<typeof ecommerceWorkshopClient, "getAnalystLearningScenario">>;
type Phase = "loading" | "ready" | "empty" | "forbidden" | "failed";
type LearningScenarioState = { phase: "idle" | "loading" | "ready" | "failed"; response: LearningScenarioContribution | null };
type AnalystTabId = "investigation" | AnalystViewId;
const LABELS: Record<AnalystViewId, string> = { overview: "经营总览", drivers: "驱动因素", diagnosis: "问题诊断", plan: "增长计划", effects: "效果复盘", evidence: "证据链", quality: "数据质量" };
const CONTRIBUTIONS: Record<AnalystViewId, string> = {
  overview: "汇总同一截止面的经营指标与 authority readiness",
  drivers: "以显式 observation/correlation/attribution 边界解释驱动因素",
  diagnosis: "组合 DecisionSummary 的证据链、归因路径与不确定性",
  plan: "消费 approved exact GrowthPlanRevision；不在页面物化 Task",
  effects: "读取成熟度受控的 EffectReview；unknown 不显示为 0",
  evidence: "串联 exact metric、evidence、method 与 eval refs",
  quality: "披露分母、缺失、冲突、cutoff 与失败关闭原因",
};
const SCENARIO_LABELS = { insight: "洞察", growth_plan: "GrowthPlan", content: "内容", creator: "达人", media: "媒体", publication: "发布", effect_review: "效果复盘", memory_candidate: "记忆候选" } as const;
const LEARNING_STAGE_LABELS = { effect_review: "效果复盘", maturity: "成熟度", memory_candidate: "记忆候选", governance: "治理审查", promotion: "知识晋升", knowledge_query: "查询复验", revocation_impact: "撤销影响" } as const;
const stateFor = (phase: Phase): AsyncState => phase === "ready" || phase === "empty" ? "ready" : phase;

export function AnalystPage({ client = ecommerceWorkshopClient, investigationClient, loadAsyncJobs, featureFlags = resolveBusinessInvestigationFeatureFlags() }: { client?: Client; investigationClient?: InvestigationReadClient; loadAsyncJobs?: AsyncJobLoader; featureFlags?: BusinessInvestigationFeatureFlags }) {
  const investigationEnabled = isBusinessInvestigationReadEnabled(featureFlags);
  const [phase, setPhase] = useState<Phase>("loading"); const [response, setResponse] = useState<AnalystViewResponse | null>(null); const [selected, setSelected] = useState<AnalystTabId>(investigationEnabled ? "investigation" : "overview"); const [learningScenario, setLearningScenario] = useState<LearningScenarioState>({ phase: "idle", response: null }); const request = useRef(0); const learningRequest = useRef(0);
  const load = () => { const id = ++request.current; setPhase("loading"); setResponse(null); const learningId = ++learningRequest.current; if (client.getAnalystLearningScenario) { setLearningScenario({ phase: "loading", response: null }); void client.getAnalystLearningScenario().then((next) => { if (learningId === learningRequest.current) setLearningScenario({ phase: "ready", response: next }); }, () => { if (learningId === learningRequest.current) setLearningScenario({ phase: "failed", response: null }); }); } else { setLearningScenario({ phase: "idle", response: null }); } void client.getAnalystView().then((next) => { if (id !== request.current) return; setResponse(next); setSelected(investigationEnabled ? "investigation" : next.views.find((item) => item.status === "blocked")?.viewId ?? "overview"); setPhase(next.page.count === 0 && next.views.every((item) => item.status === "ready") ? "empty" : "ready"); }, (error: unknown) => { if (id === request.current) setPhase(error instanceof EcommerceWorkshopClientError && (error.status === 401 || error.status === 403) ? "forbidden" : "failed"); }); };
  useEffect(() => { load(); return () => { request.current += 1; learningRequest.current += 1; }; }, [client, investigationEnabled]);
  const view = selected === "investigation" ? undefined : response?.views.find((item) => item.viewId === selected); const readyMetrics = response?.views.reduce((sum, item) => sum + item.countLedger.ready, 0) ?? 0; const totalMetrics = response?.views.reduce((sum, item) => sum + item.countLedger.denominator, 0) ?? 0;
  const content = response ? <div className="analyst-read-model">
    <section className="analyst-hero"><div><span>经营参谋 · 增长指挥中心</span><h2>用同一截止面的指标、证据与质量理解经营变化</h2><p>Observation ≠ attribution ≠ causal claim；只展示决策摘要、证据链、归因路径、关键假设和不确定性。</p></div><strong>只读</strong></section>
    <section className="creator-growth-axis"><div><span>只读视图</span><strong>7</strong></div><div><span>可信指标</span><strong>{readyMetrics}/{totalMetrics}</strong></div><div><span>资源 revision</span><strong>r{response.resourceRevision}</strong></div><div><span>写入口</span><strong>0</strong></div></section>
    {response.growthScenario ? <section className="content-campaign-items" aria-label="GrowthPlan跨域同链贡献">
      <header><strong>洞察 → GrowthPlan → 内容 → 达人 → 媒体 → 发布 → 复盘</strong><span>{response.growthScenario.status}</span></header>
      <article className="content-campaign-item"><header><strong>{response.growthScenario.rootPlanRef?.resourceId ?? "等待 exact GrowthPlan 根"}</strong><span>{response.growthScenario.scenarioBindingHash ? `binding ${response.growthScenario.scenarioBindingHash.slice(0, 14)}…` : "binding 未建立"}</span></header>
        <p>原子 Skill → Logic 编排 → 数字同事绑定 → 工作台贡献；页面只消费 exact refs，不复制业务真源。</p>
        <div className="media-command-grid">{response.growthScenario.stages.map((stage) => <article className={`is-${stage.status}`} key={stage.stageId}><strong>{SCENARIO_LABELS[stage.stageId]}</strong><span>{stage.status}</span><small>{stage.contribution}</small></article>)}</div>
        <section className="content-campaign-ledger"><div><span>Task</span><strong>{response.growthScenario.ledger.tasksObserved}/{response.growthScenario.ledger.tasksExpected}</strong></div><div><span>Handoff</span><strong>{response.growthScenario.ledger.handoffsObserved}/{response.growthScenario.ledger.handoffsExpected}</strong></div><div><span>Outcome ready</span><strong>{response.growthScenario.ledger.outcomesReady}/{response.growthScenario.ledger.outcomesExpected}</strong></div><div><span>写入口</span><strong>0</strong></div></section>
        <div className="analyst-readiness-grid">{response.growthScenario.outcomeAxes.map((axis) => <article className={`is-${axis.status}`} key={axis.axisId}><strong>{axis.axisId}</strong><span>{axis.status}</span><p>{axis.exactRef ? `${axis.exactRef.resourceType} · r${axis.exactRef.revision}` : axis.blocker?.code}</p></article>)}</div>
        <small>Provider applied、Usage settled、Effect mature、Memory governed 四轴独立 · 外部副作用关闭 · 不自动晋升 Wiki</small>
      </article>
    </section> : null}
    {learningScenario.phase === "loading" ? <section className="analyst-learning-scenario is-loading" aria-label="W8-04 学习治理贡献" role="status"><strong>正在独立读取学习治理场景…</strong><p>不从页面本地状态推导成熟、批准、晋升或撤销结果。</p></section> : null}
    {learningScenario.phase === "failed" ? <section className="analyst-learning-scenario is-failed" aria-label="W8-04 学习治理贡献" role="alert"><strong>学习治理场景读取失败</strong><p>原有 Analyst v2 保持可用；Candidate、Wiki 与撤销命令均不开放。</p></section> : null}
    {learningScenario.phase === "ready" && learningScenario.response ? <section className="analyst-learning-scenario is-blocked" aria-label="W8-04 学习治理贡献">
      <header><div><span>W8-04 · GET-only</span><h2>EffectReview → MemoryCandidate → Wiki 治理与撤销</h2></div><strong>运营失败关闭</strong></header>
      <p>原子 Skill → Logic 编排 → 数字同事绑定 → 工作台贡献视图；成熟、治理批准、晋升、知识有效性、撤销影响五轴独立。</p>
      {learningScenario.response.composition ? <div className="analyst-learning-layers"><div><span>原子 Skill</span><strong>{learningScenario.response.composition.atomicSkillRefs.length}</strong><small>{learningScenario.response.composition.atomicSkillRefs.map((item) => `${item.resourceId}@${item.revision}`).join("、")}</small></div><div><span>Logic</span><strong>{learningScenario.response.composition.logicRevisionRef.resourceId}</strong><small>v{learningScenario.response.composition.logicRevisionRef.revision}</small></div><div><span>数字同事绑定</span><strong>{learningScenario.response.composition.roleBindings.length}</strong><small>{learningScenario.response.composition.roleBindings.map((item) => `${item.roleRef.resourceId} → ${item.assigneeRef.resourceId}`).join("、")}</small></div></div> : <p className="task-cockpit-approval-boundary">{learningScenario.response.blockers.map((item) => item.code).join("、")}；未制造 Skill、Logic、角色或知识事实。</p>}
      <ol className="analyst-learning-stages">{learningScenario.response.stages.map((stage) => <li className={`is-${stage.status}`} key={stage.stageId}><span>{LEARNING_STAGE_LABELS[stage.stageId]}</span><strong>{stage.status}</strong><p>{stage.contribution}</p><small>{stage.exactRefs.length ? `${stage.exactRefs.length} 个 exact ref` : stage.blockers.map((item) => item.code).join("、")}</small></li>)}</ol>
      <div className="analyst-learning-ledger" aria-label="治理与撤销守恒"><div><span>EffectReview</span><strong>{learningScenario.response.ledger.reviewsObserved}/{learningScenario.response.ledger.reviewsExpected}</strong></div><div><span>Candidate</span><strong>{learningScenario.response.ledger.candidatesObserved}/{learningScenario.response.ledger.candidatesExpected}</strong></div><div><span>Promotion</span><strong>{learningScenario.response.ledger.promotionsObserved}/{learningScenario.response.ledger.promotionsExpected}</strong></div><div><span>Citation</span><strong>{learningScenario.response.ledger.citationsObserved}/{learningScenario.response.ledger.citationsExpected}</strong></div><div><span>历史 Exposure 保留</span><strong>{learningScenario.response.ledger.retainedExposures}/{learningScenario.response.ledger.historicalExposures}</strong></div><div><span>影响 refs</span><strong>{learningScenario.response.ledger.impactRefsObserved}/{learningScenario.response.ledger.impactRefsExpected}</strong></div></div>
      <div className="analyst-learning-axes">{learningScenario.response.outcomeAxes.map((axis) => <article className={`is-${axis.status}`} key={axis.axisId}><span>{axis.axisId}</span><strong>{axis.status}</strong><p>{axis.exactRef ? `${axis.exactRef.resourceType} · v${axis.exactRef.revision}` : axis.blocker?.code}</p></article>)}</div>
      <p className="task-cockpit-approval-boundary">Candidate pending/approved/promoted 与知识 active/stale/revoked/expired 不混淆；approve ≠ promote。命令：submit=false · approve=false · promote=false · publish=false · revoke=false。</p>
    </section> : null}
    <div className={`analyst-tabs${investigationEnabled ? " has-investigation" : ""}`} role="tablist" aria-label="经营参谋只读视图">{(investigationEnabled ? (["investigation", ...response.views.map((item) => item.viewId)] as AnalystTabId[]) : response.views.map((item) => item.viewId)).map((tabId, index, tabs) => { const item = tabId === "investigation" ? undefined : response.views.find((candidate) => candidate.viewId === tabId); return <button id={`analyst-tab-${tabId}`} aria-controls={`analyst-panel-${tabId}`} type="button" role="tab" aria-selected={selected === tabId} tabIndex={selected === tabId ? 0 : -1} key={tabId} onClick={() => setSelected(tabId)} onKeyDown={(event) => { if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return; event.preventDefault(); const nextIndex = event.key === "Home" ? 0 : event.key === "End" ? tabs.length - 1 : (index + (event.key === "ArrowRight" ? 1 : -1) + tabs.length) % tabs.length; setSelected(tabs[nextIndex]!); event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>("button")[nextIndex]?.focus(); }}><strong>{tabId === "investigation" ? "生意探究" : LABELS[tabId]}</strong><span>{item?.status ?? "read-only"}</span></button>; })}</div>
    {selected === "investigation" ? <BusinessInvestigationTab id="analyst-panel-investigation" labelledBy="analyst-tab-investigation" client={investigationClient} /> : view ? <section id={`analyst-panel-${selected}`} aria-labelledby={`analyst-tab-${selected}`} className="analyst-panel" role="tabpanel" aria-label={LABELS[selected]}><header><div><span>{view.viewId}</span><h2>{LABELS[view.viewId]}</h2></div><strong className={`content-campaign-status is-${view.status}`}>{view.status === "ready" ? "同截止面可读" : "失败关闭"}</strong></header><div className="analyst-readiness-grid">{view.readinessAxes.map((axis) => <article key={axis.axis} className={`is-${axis.status}`}><strong>{axis.axis}</strong><span>{axis.status}</span><p>{axis.exactRef ? `${axis.exactRef.resourceType} · r${axis.exactRef.revision}` : "无 exact authority"}</p></article>)}</div><section className="analyst-metrics">{view.metrics.length ? view.metrics.map((metric) => <article key={metric.metricId} className={`is-${metric.status}`}><header><strong>{metric.metricId}</strong><span>{metric.status}</span></header>{metric.status === "ready" ? <><b>{metric.value} {metric.unit}</b><p>{metric.grain} · {metric.window} · {metric.timezone}</p><small>denominator {metric.denominator} · lineage {metric.lineageId}</small></> : <p>当前值未知，不以 0 代替。</p>}</article>) : <p>当前没有可挂接的经营指标；可信空与 blocked/unknown 分开表达。</p>}</section><aside className="media-studio-blockers"><h3>阻断与下一证据</h3>{view.blockers.length ? view.blockers.map((item) => <div key={item.code}><strong>{item.code}</strong><span>{item.dependency}</span><p>{item.requiredAction}</p></div>) : <p>本视图当前无 blocker。</p>}<section><h3>专业贡献归因</h3><ContributionLineage value={{ atomicSkillRef: null, logicRef: null, coworker: null, workshopContribution: CONTRIBUTIONS[view.viewId] }} /><p>当前只读 View 没有 exact AgentRun、SkillBinding 或 LogicRevision；保持 unknown，不把 Analyst authority 冒充数字同事运行事实。</p></section><section><h3>决策摘要</h3><p>{view.status === "ready" ? "当前 exact refs 与同截止面指标可读。" : "依赖 authority 不完整，本视图失败关闭。"}</p></section><section><h3>关键假设和不确定性</h3><p>相关不等于归因，归因不等于因果；页面不展示模型私有思维链，也不授权计划物化或业务动作。</p></section></aside></section> : null}
    <footer className="content-campaign-footnote"><span>租户 {response.tenant.orgId}/{response.tenant.projectId}</span><span>统一 cutoff {new Date(response.dataCutoff).toLocaleString("zh-CN", { hour12: false })}</span><span>unknown 不显示 0</span></footer>
  </div> : null;
  return <section className="analyst-page" aria-label="经营参谋只读视图"><div className="content-campaign-toolbar"><span>Analyst v2 · GrowthPlan exact-binding read model</span><button type="button" onClick={load}>重新读取</button></div><AsyncStateBoundary state={stateFor(phase)} dataCutoff={response?.dataCutoff} action={phase === "failed" ? <button type="button" onClick={load}>重新读取</button> : undefined}>{content}</AsyncStateBoundary><AsyncJobDrawer load={loadAsyncJobs} /></section>;
}
