import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { ContentCampaignPage } from "./ContentCampaignPage";

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
const cutoff = "2026-08-24T13:00:00Z";
const ref = (resourceType: string, resourceId: string, value = "a") => ({ resourceType, resourceId, revision: 1, contentHash: `sha256:${value.repeat(64)}`, receiptId: `receipt-${resourceId}` });
const blocked = { schemaVersion: "aos.ecommerce-workshop.content-campaign-view/v1" as const, tenant: { orgId: "org-org", projectId: "dev-project" }, evaluatedAt: cutoff, dataCutoff: cutoff, readiness: "degraded" as const, slices: (["plan", "calendar", "content"] as const).map((sliceId) => ({ sliceId, status: "blocked" as const, dataCutoff: cutoff, authorityRefs: [], items: [], blockers: [{ code: `CANONICAL_${sliceId.toUpperCase()}_AUTHORITY_NOT_AVAILABLE`, dependency: `ecommerce.${sliceId}`, requiredAction: "接入 exact authority" }], countLedger: { eligible: 0, attached: 0, unmatched: 0, conflicted: 0 } })), page: { limit: 100, count: 0, hasMore: false as const, nextCursor: null } };
const ready = { ...blocked, slices: [{ sliceId: "plan" as const, status: "ready" as const, dataCutoff: cutoff, authorityRefs: [ref("CampaignRevision", "campaign-1")], items: [ref("CampaignRevision", "campaign-1")], blockers: [], countLedger: { eligible: 1, attached: 1, unmatched: 0, conflicted: 0 } }, { sliceId: "calendar" as const, status: "ready" as const, dataCutoff: cutoff, authorityRefs: [], items: [], blockers: [], countLedger: { eligible: 0, attached: 0, unmatched: 0, conflicted: 0 } }, { sliceId: "content" as const, status: "ready" as const, dataCutoff: cutoff, authorityRefs: [ref("MasterContentIntentRevision", "intent-1")], items: [ref("MasterContentIntentRevision", "intent-1"), { ...ref("ContentVariant" as const, "variant-1", "c"), resourceType: "ContentVariant" as const, revision: 1 as const, intentRef: ref("MasterContentIntentRevision", "intent-1"), masterArtifactRef: { artifactId: "master-1", contentHash: `sha256:${"b".repeat(64)}` }, variantArtifactRef: { artifactId: "variant-1", contentHash: `sha256:${"c".repeat(64)}` }, relationId: "relation-1", relationType: "variant_of" as const }], blockers: [], countLedger: { eligible: 2, attached: 2, unmatched: 0, conflicted: 0 } }], page: { limit: 100, count: 3, hasMore: false as const, nextCursor: null } };

describe("ContentCampaignPage", () => { let host: HTMLDivElement; let root: Root; beforeEach(() => { host = document.createElement("div"); document.body.appendChild(host); root = createRoot(host); }); afterEach(() => { act(() => root.unmount()); host.remove(); vi.restoreAllMocks(); });
  it("blocked 时保持三栏证据且无批准/排期/发布写入口", async () => { await act(async () => root.render(<ContentCampaignPage client={{ getContentCampaignView: vi.fn().mockResolvedValue(blocked) }} />)); expect(host.querySelectorAll(".content-campaign-slice")).toHaveLength(3); expect(host.textContent).toContain("失败关闭"); expect(host.textContent).toContain("CANONICAL_PLAN_AUTHORITY_NOT_AVAILABLE"); expect(host.textContent).toContain("无写入口"); expect(host.textContent).not.toMatch(/批准并发布|保存草稿|编辑排期|自动拆解/); });
  it("非空 exact facts 与 ContentVariant lineage 可切换读取", async () => { await act(async () => root.render(<ContentCampaignPage client={{ getContentCampaignView: vi.fn().mockResolvedValue(ready) }} />)); expect(host.textContent).toContain("CampaignRevision"); const contentButton = [...host.querySelectorAll<HTMLButtonElement>(".content-campaign-slice")].find((item) => item.textContent?.includes("主内容与变体"))!; await act(async () => contentButton.click()); expect(host.textContent).toContain("ContentVariant"); expect(host.textContent).toContain("variant_of"); expect(host.textContent).toContain("Master → Variant"); });
  it("可信空与读取失败不伪造成示例业务数据", async () => { const empty = { ...blocked, slices: blocked.slices.map((item) => ({ ...item, status: "ready" as const, blockers: [] })) }; await act(async () => root.render(<ContentCampaignPage client={{ getContentCampaignView: vi.fn().mockResolvedValue(empty) }} />)); expect(host.textContent).toContain("可信空集合"); expect(host.textContent).not.toContain("七夕促销"); await act(async () => root.render(<ContentCampaignPage client={{ getContentCampaignView: vi.fn().mockRejectedValue(new Error("offline")) }} />)); expect(host.textContent).toContain("读取失败"); });
});
