import { useEffect, useRef, useState } from "react";

import { EcommerceWorkshopClientError, ecommerceWorkshopClient, type CreatorBusinessStage, type CreatorGrowthSlice, type CreatorGrowthViewResponse } from "../../api/ecommerceWorkshop";
import { AsyncStateBoundary, type AsyncState } from "./AsyncStateBoundary";

type Client = Pick<typeof ecommerceWorkshopClient, "getCreatorGrowthView">;
type Phase = "loading" | "ready" | "empty" | "forbidden" | "failed";
const LABELS: Record<CreatorBusinessStage, string> = { candidate: "候选", outreach: "邀约准备", contract: "合同", delivery: "履约", relationship: "关系" };
const TYPES: Record<CreatorBusinessStage, string> = { candidate: "Candidate · Match", outreach: "OutreachBatch · StartLedger", contract: "Contract · TermDiff", delivery: "Delivery Evidence", relationship: "Relationship Assessment" };
const stateFor = (phase: Phase): AsyncState => phase === "ready" || phase === "empty" ? "ready" : phase;
const short = (value: string) => value.length > 32 ? `${value.slice(0, 14)}…${value.slice(-11)}` : value;

export function CreatorGrowthPage({ client = ecommerceWorkshopClient }: { client?: Client }) {
  const [phase, setPhase] = useState<Phase>("loading"); const [response, setResponse] = useState<CreatorGrowthViewResponse | null>(null); const [selected, setSelected] = useState<CreatorBusinessStage>("candidate"); const request = useRef(0);
  const load = () => { const id = ++request.current; setPhase("loading"); setResponse(null); void client.getCreatorGrowthView().then((next) => { if (id !== request.current) return; setResponse(next); setSelected(next.slices.find((item) => item.status === "blocked")?.businessStage ?? next.slices.find((item) => item.authorityRefs.length)?.businessStage ?? "candidate"); setPhase(next.page.count === 0 && next.slices.every((item) => item.status === "ready") ? "empty" : "ready"); }, (error: unknown) => { if (id === request.current) setPhase(error instanceof EcommerceWorkshopClientError && (error.status === 401 || error.status === 403) ? "forbidden" : "failed"); }); };
  useEffect(() => { load(); return () => { request.current += 1; }; }, [client]);
  const slice: CreatorGrowthSlice | undefined = response?.slices.find((item) => item.businessStage === selected); const ready = response?.slices.filter((item) => item.status === "ready").length ?? 0; const blockers = response?.slices.reduce((sum, item) => sum + item.blockers.length, 0) ?? 0;
  const content = response && slice ? <div className="creator-growth-read-model">
    <section className="creator-growth-axis"><div><span>工作流阶段轴</span><strong>发现 → 证据 → 匹配 → 批次准备 → 启动</strong></div><div><span>业务阶段轴</span><strong>候选 → 邀约 → 合同 → 履约 → 关系</strong></div><div><span>权威读取</span><strong>{ready}/5</strong></div><div><span>独立阻断</span><strong>{blockers}</strong></div></section>
    <section className="content-campaign-readonly"><span aria-hidden="true">◇</span><div><h2>达人增长 · 权威只读</h2><p>两条阶段轴正交；Observation ≠ Decision，accepted ≠ SIGNED，PRELIMINARY ≠ 成熟关系。</p></div><strong>无写入口</strong></section>
    <div className="content-campaign-board creator-growth-board"><aside className="content-campaign-nav"><header><h2>业务阶段</h2><span>{5 - ready} 项阻断</span></header>{response.slices.map((item) => <button type="button" key={item.businessStage} className={`content-campaign-slice is-${item.status}${item.businessStage === selected ? " is-selected" : ""}`} onClick={() => setSelected(item.businessStage)}><strong>{LABELS[item.businessStage]}</strong><small>{TYPES[item.businessStage]}</small><span>{item.authorityRefs.length} exact facts</span></button>)}</aside>
      <main className="content-campaign-detail"><header><div><span>{slice.businessStage}</span><h2>{LABELS[slice.businessStage]}</h2></div><strong className={`content-campaign-status is-${slice.status}`}>{slice.status === "ready" ? "权威读取可用" : "失败关闭"}</strong></header><section className="creator-growth-phases">{slice.workflowPhases.map((item) => <span key={item}>{item}</span>)}</section><section className="content-campaign-ledger"><div><span>输入</span><strong>{slice.countLedger.input}</strong></div><div><span>合格</span><strong>{slice.countLedger.eligible}</strong></div><div><span>待复核</span><strong>{slice.countLedger.needsReview}</strong></div><div><span>未知</span><strong>{slice.countLedger.unknown}</strong></div></section><section className="content-campaign-items">{slice.authorityRefs.length ? slice.authorityRefs.map((item) => <article className="content-campaign-item" key={`${item.resourceType}:${item.resourceId}:${item.revision}`}><header><strong>{item.resourceType}</strong><span>r{item.revision}</span></header><p>{item.resourceId}</p><dl><div><dt>Exact hash</dt><dd>{short(item.contentHash)}</dd></div><div><dt>Receipt</dt><dd>{short(item.receiptId)}</dd></div><div><dt>工作流阶段</dt><dd>{item.workflowPhase}</dd></div><div><dt>PII</dt><dd>{item.piiRefs.length ? `${item.piiRefs.length} 个受控 ref` : "未返回"}</dd></div></dl></article>) : <p>当前没有可挂接事实；可信空与阻断由右侧证据区分。</p>}</section></main>
      <aside className="content-campaign-evidence"><header><h2>证据链 · 边界</h2><span>{slice.blockers.length} blocker</span></header>{slice.blockers.length ? <ul>{slice.blockers.map((item) => <li key={item.code}><strong>{item.code}</strong><span>{item.dependency}</span><p>{item.requiredAction}</p></li>)}</ul> : <div className="content-campaign-evidence-clear"><strong>{slice.authorityRefs.length ? "当前读取链闭合" : "可信空集合"}</strong><p>只证明当前 cutoff 的 canonical reader，不授权邀约、签署、寄样、佣金或关系变更。</p></div>}<section><h3>决策摘要</h3><p>{slice.status === "blocked" ? "缺少 exact authority，当前阶段失败关闭。" : "exact authority、Receipt 与数量账本可读取。"}</p></section><section><h3>关键假设和不确定性</h3><p>PII 只显示受控引用；页面不复制联系方式、合同正文、地址或账号 secret。</p></section></aside></div>
    <footer className="content-campaign-footnote"><span>租户 {response.tenant.orgId}/{response.tenant.projectId}</span><span>统一 cutoff {new Date(response.dataCutoff).toLocaleString("zh-CN", { hour12: false })}</span><span>无后续页：是</span></footer>
  </div> : null;
  return <section className="creator-growth-page" aria-label="达人增长工作台只读视图"><div className="content-campaign-toolbar"><span>Creator Growth v1 · canonical read model</span><button type="button" onClick={load}>重新读取</button></div><AsyncStateBoundary state={stateFor(phase)} dataCutoff={response?.dataCutoff} action={phase === "failed" ? <button type="button" onClick={load}>重新读取</button> : undefined}>{content}</AsyncStateBoundary></section>;
}
