import { useEffect, useRef, useState } from "react";

import { CREATOR_PREPARE_SCHEMA_VERSION, EcommerceWorkshopClientError, ecommerceWorkshopClient, type CreatorBusinessStage, type CreatorContributionViewResponse, type CreatorGrowthSlice, type CreatorGrowthViewResponse, type ThreeModuleClosureContributionViewResponse } from "../../api/ecommerceWorkshop";
import { CREATOR_LIFECYCLE_SCHEMA_VERSION, type CreatorLifecycleViewResponse } from "../../api/ecommerceWorkshop";
import { AsyncStateBoundary, type AsyncState } from "./AsyncStateBoundary";
import { ThreeModuleClosureCard, unavailableThreeModuleClosure } from "./ThreeModuleClosureCard";

type Client = Pick<typeof ecommerceWorkshopClient, "getCreatorGrowthView" | "getCreatorContributionView"> & Partial<Pick<typeof ecommerceWorkshopClient, "getCreatorLifecycleView" | "getThreeModuleClosureContributionView">>;
type Phase = "loading" | "ready" | "empty" | "forbidden" | "failed";
const LABELS: Record<CreatorBusinessStage, string> = { candidate: "候选", outreach: "邀约准备", contract: "合同", delivery: "履约", relationship: "关系" };
const TAB_LABELS: Record<CreatorBusinessStage, string> = { candidate: "达人库", outreach: "招募漏斗", contract: "商务签约", delivery: "履约效果", relationship: "长期关系" };
const TYPES: Record<CreatorBusinessStage, string> = { candidate: "Candidate · Match", outreach: "OutreachBatch · StartLedger", contract: "Contract · TermDiff", delivery: "Delivery Evidence", relationship: "Relationship Assessment" };
const stateFor = (phase: Phase): AsyncState => phase === "ready" || phase === "empty" ? "ready" : phase;
const short = (value: string) => value.length > 32 ? `${value.slice(0, 14)}…${value.slice(-11)}` : value;
const unavailableContribution = (next: CreatorGrowthViewResponse): CreatorContributionViewResponse => ({
  schemaVersion: CREATOR_PREPARE_SCHEMA_VERSION,
  tenant: next.tenant,
  evaluatedAt: next.evaluatedAt,
  atomicSkillRefs: [],
  logicRef: null,
  primaryColleague: "导购顾问",
  collaboratorColleagues: ["数据参谋", "内容官", "活动策划师"],
  latestBatch: null,
  blockers: ["CREATOR_PREPARE_AUTHORITY_UNAVAILABLE", "CREATOR_BATCH_PREPARATION_NOT_AVAILABLE"],
  allowedCommands: [],
  externalEffectsAllowed: false,
});
const unavailableLifecycle = (next: CreatorGrowthViewResponse): CreatorLifecycleViewResponse => ({
  schemaVersion: CREATOR_LIFECYCLE_SCHEMA_VERSION, tenant: next.tenant, evaluatedAt: next.evaluatedAt,
  latestStart: null, ledger: { eligibleItems: 0, lanes: 0, prepared: 0, accepted: 0, applied: 0, failed: 0, unknown: 0, disputed: 0, completed: 0 },
  contracts: [], deliveries: [], relationships: [], blockers: ["CREATOR_LIFECYCLE_AUTHORITY_UNAVAILABLE", "CREATOR_BATCH_START_NOT_AVAILABLE"],
  allowedCommands: [], externalEffectsAllowed: false,
});

export function CreatorGrowthPage({ client = ecommerceWorkshopClient }: { client?: Client }) {
  const [phase, setPhase] = useState<Phase>("loading"); const [response, setResponse] = useState<CreatorGrowthViewResponse | null>(null); const [contribution, setContribution] = useState<CreatorContributionViewResponse | null>(null); const [lifecycle, setLifecycle] = useState<CreatorLifecycleViewResponse | null>(null); const [closure, setClosure] = useState<ThreeModuleClosureContributionViewResponse | null>(null); const [selected, setSelected] = useState<CreatorBusinessStage>("candidate"); const request = useRef(0);
  const load = () => { const id = ++request.current; setPhase("loading"); setResponse(null); setContribution(null); setLifecycle(null); setClosure(null); void Promise.all([client.getCreatorGrowthView(), client.getCreatorContributionView().catch(() => null), client.getCreatorLifecycleView?.().catch(() => null) ?? Promise.resolve(null), client.getThreeModuleClosureContributionView?.("creator").catch(() => null) ?? Promise.resolve(null)]).then(([next, nextContribution, nextLifecycle, nextClosure]) => { if (id !== request.current) return; setResponse(next); setContribution(nextContribution ?? unavailableContribution(next)); setLifecycle(nextLifecycle ?? unavailableLifecycle(next)); setClosure(nextClosure ?? unavailableThreeModuleClosure("creator", next.tenant, next.evaluatedAt)); setSelected(next.slices.find((item) => item.status === "blocked")?.businessStage ?? next.slices.find((item) => item.authorityRefs.length)?.businessStage ?? "candidate"); setPhase(next.page.count === 0 && next.slices.every((item) => item.status === "ready") ? "empty" : "ready"); }, (error: unknown) => { if (id === request.current) setPhase(error instanceof EcommerceWorkshopClientError && (error.status === 401 || error.status === 403) ? "forbidden" : "failed"); }); };
  useEffect(() => { load(); return () => { request.current += 1; }; }, [client]);
  const slice: CreatorGrowthSlice | undefined = response?.slices.find((item) => item.businessStage === selected); const ready = response?.slices.filter((item) => item.status === "ready").length ?? 0; const blockers = response?.slices.reduce((sum, item) => sum + item.blockers.length, 0) ?? 0;
  const content = response && contribution && lifecycle && closure && slice ? <div className="creator-growth-read-model">
    <details className="creator-growth-audit-context"><summary>治理轴、专业贡献与生命周期审计</summary>
    <section className="creator-growth-axis"><div><span>工作流阶段轴</span><strong>发现 → 证据 → 匹配 → 批次准备 → 启动</strong></div><div><span>业务阶段轴</span><strong>候选 → 邀约 → 合同 → 履约 → 关系</strong></div><div><span>权威读取</span><strong>{ready}/5</strong></div><div><span>独立阻断</span><strong>{blockers}</strong></div></section>
    <section className="content-campaign-readonly"><span aria-hidden="true">◇</span><div><h2>达人增长 · 权威只读</h2><p>两条阶段轴正交；Observation ≠ Decision，accepted ≠ SIGNED，PRELIMINARY ≠ 成熟关系。</p></div><strong>无写入口</strong></section>
    <section className="creator-contribution" aria-label="达人方法与数字同事贡献"><header><div><span>原子 Skill → Logic → 数字同事 → 工作台贡献</span><h2>{contribution.primaryColleague}主责的达人匹配编排</h2></div><strong>{contribution.latestBatch?.lifecycle === "frozen" ? "批次已冻结" : contribution.latestBatch ? "仅准备，未触达" : "等待批次准备"}</strong></header><div className="creator-contribution-flow"><div><span>原子 Skill</span><strong>{contribution.atomicSkillRefs.length || 6} 项</strong><small>{contribution.atomicSkillRefs.length ? contribution.atomicSkillRefs.map((item) => item.resourceId).join(" · ") : "exact refs 尚未挂接"}</small></div><div><span>领域 Logic</span><strong>{contribution.logicRef?.resourceId ?? "ecommerce-creator-match"}</strong><small>{contribution.logicRef ? `r${contribution.logicRef.revision}` : "等待 exact publication"}</small></div><div><span>数字同事</span><strong>{contribution.primaryColleague}</strong><small>协作：{contribution.collaboratorColleagues.join("、")}</small></div><div><span>工作台贡献</span><strong>{contribution.latestBatch ? `${contribution.latestBatch.ledger.input} 个输入` : "可信空"}</strong><small>prepare 0 触达 · 0 Action · 0 Lease</small></div></div>{contribution.blockers.length ? <p className="creator-contribution-warning">当前阻断：{contribution.blockers.join("、")}</p> : <p className="creator-contribution-clear">exact refs 与数量账本已闭合；外部动作仍未授权。</p>}</section>
    <section className="creator-lifecycle-authority" aria-label="达人显式启动与合作生命周期"><header><div><span>显式 Start → 独立 Action lane → 合同 → 履约 → 关系</span><h2>治理编译已与外部执行分离</h2></div><strong>{lifecycle.latestStart ? "治理批次已建立" : "等待显式启动"}</strong></header><div className="creator-lifecycle-ledger"><div><span>独立 lane</span><strong>{lifecycle.ledger.lanes}</strong><small>私信 / 寄样 / 签约 / 佣金</small></div><div><span>已完成</span><strong>{lifecycle.ledger.completed}</strong><small>仅 applied + failed</small></div><div><span>partial / unknown</span><strong>{lifecycle.ledger.accepted + lifecycle.ledger.unknown + lifecycle.ledger.disputed}</strong><small>不并入完成</small></div><div><span>合作 lineage</span><strong>{lifecycle.contracts.length} / {lifecycle.deliveries.length} / {lifecycle.relationships.length}</strong><small>合同 / 履约 / 关系</small></div></div>{lifecycle.latestStart?.lanes.length ? <ul className="creator-lifecycle-lanes">{lifecycle.latestStart.lanes.map((lane) => <li key={lane.laneId}><strong>{lane.actionKind}</strong><span>{lane.resolvedOutcome ?? lane.outcome}</span><small>{short(lane.bindingHash)}</small></li>)}</ul> : <p className="creator-contribution-warning">当前阻断：{lifecycle.blockers.join("、")}</p>}<footer>外部副作用：禁止 · 页面无批量发送、寄样、签约或改佣金按钮</footer></section>
    <ThreeModuleClosureCard value={closure} />
    </details>
    <div className="content-campaign-board creator-growth-board"><aside className="content-campaign-nav"><header><h2>业务阶段</h2><span>{5 - ready} 项阻断</span></header>{response.slices.map((item) => <button type="button" key={item.businessStage} className={`content-campaign-slice is-${item.status}${item.businessStage === selected ? " is-selected" : ""}`} onClick={() => setSelected(item.businessStage)}><strong>{LABELS[item.businessStage]}</strong><small>{TYPES[item.businessStage]}</small><span>{item.authorityRefs.length} exact facts</span></button>)}</aside>
      <section className="content-campaign-detail" aria-label="达人增长详情"><header><div><span>{slice.businessStage}</span><h2>{LABELS[slice.businessStage]}</h2></div><strong className={`content-campaign-status is-${slice.status}`}>{slice.status === "ready" ? "权威读取可用" : "失败关闭"}</strong></header><section className="creator-growth-phases">{slice.workflowPhases.map((item) => <span key={item}>{item}</span>)}</section><section className="content-campaign-ledger"><div><span>输入</span><strong>{slice.countLedger.input}</strong></div><div><span>合格</span><strong>{slice.countLedger.eligible}</strong></div><div><span>待复核</span><strong>{slice.countLedger.needsReview}</strong></div><div><span>未知</span><strong>{slice.countLedger.unknown}</strong></div></section><section className="content-campaign-items">{slice.authorityRefs.length ? slice.authorityRefs.map((item) => <article className="content-campaign-item" key={`${item.resourceType}:${item.resourceId}:${item.revision}`}><header><strong>{item.resourceType}</strong><span>r{item.revision}</span></header><p>{item.resourceId}</p><dl><div><dt>Exact hash</dt><dd>{short(item.contentHash)}</dd></div><div><dt>Receipt</dt><dd>{short(item.receiptId)}</dd></div><div><dt>工作流阶段</dt><dd>{item.workflowPhase}</dd></div><div><dt>PII</dt><dd>{item.piiRefs.length ? `${item.piiRefs.length} 个受控 ref` : "未返回"}</dd></div></dl></article>) : <p>当前没有可挂接事实；可信空与阻断由右侧证据区分。</p>}</section></section>
      <aside className="content-campaign-evidence"><header><h2>证据链 · 边界</h2><span>{slice.blockers.length} blocker</span></header>{slice.blockers.length ? <ul>{slice.blockers.map((item) => <li key={item.code}><strong>{item.code}</strong><span>{item.dependency}</span><p>{item.requiredAction}</p></li>)}</ul> : <div className="content-campaign-evidence-clear"><strong>{slice.authorityRefs.length ? "当前读取链闭合" : "可信空集合"}</strong><p>只证明当前 cutoff 的 canonical reader，不授权邀约、签署、寄样、佣金或关系变更。</p></div>}<section><h3>决策摘要</h3><p>{slice.status === "blocked" ? "缺少 exact authority，当前阶段失败关闭。" : "exact authority、Receipt 与数量账本可读取。"}</p></section><section><h3>关键假设和不确定性</h3><p>PII 只显示受控引用；页面不复制联系方式、合同正文、地址或账号 secret。</p></section></aside></div>
    <footer className="content-campaign-footnote"><span>租户 {response.tenant.orgId}/{response.tenant.projectId}</span><span>统一 cutoff {new Date(response.dataCutoff).toLocaleString("zh-CN", { hour12: false })}</span><span>无后续页：是</span></footer>
  </div> : null;
  return <section className="creator-growth-page" aria-label="达人增长工作台只读视图"><nav className="creator-growth-toolbar" aria-label="达人增长主视图"><div>{(["candidate", "outreach", "contract", "delivery", "relationship"] as const).map((stage) => <button type="button" className={selected === stage ? "is-active" : ""} key={stage} onClick={() => setSelected(stage)}>{TAB_LABELS[stage]}</button>)}</div><span>canonical read-only</span><button type="button" onClick={load}>重新读取</button></nav><AsyncStateBoundary state={stateFor(phase)} dataCutoff={response?.dataCutoff} action={phase === "failed" ? <button type="button" onClick={load}>重新读取</button> : undefined}>{content}</AsyncStateBoundary></section>;
}
