import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { CustomerContactContributionViewResponse, CustomerLifecycleContributionViewResponse, CustomerViewResponse } from "../../api/ecommerceWorkshop";
import { CustomerPage } from "./CustomerPage";

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
const ids = ["customer", "segment", "journey", "dialogue"] as const;
const axes = ["customer_lite", "consent", "segment", "journey", "dialogue", "outreach_batch"] as const;
const cutoff = "2026-08-24T08:00:00Z";
const blocked: CustomerViewResponse = { schemaVersion: "aos.ecommerce-workshop.customer-view/v1", tenant: { orgId: "org-org", projectId: "dev-project" }, resourceRevision: 1, evaluatedAt: cutoff, dataCutoff: cutoff, readiness: "degraded", views: ids.map((viewId) => { const blocker = { code: `CUSTOMER_${viewId.toUpperCase()}_AUTHORITY_NOT_AVAILABLE`, dependency: viewId, requiredAction: "attach exact privacy-safe authority" }; return { viewId, status: "blocked", resourceRevision: 1, dataCutoff: cutoff, readinessAxes: axes.map((axis) => ({ axis, status: "blocked", exactRef: null, blockers: [blocker] })), items: [], authorityRefs: [], blockers: [blocker], countLedger: { input: 0, eligible: 0, excluded: 0, unknown: 0, deduplicated: 0 } }; }), page: { limit: 100, count: 0, hasMore: false, nextCursor: null } };
const contribution: CustomerLifecycleContributionViewResponse = { schemaVersion: "aos.ecommerce-workshop.customer-lifecycle/v1", tenant: { orgId: "org-org", projectId: "dev-project" }, evaluatedAt: cutoff, atomicSkillIds: ["build-evidence-pack", "segment-entities", "consent-and-purpose-check", "needs-discovery", "customer-journey-plan", "response-or-outreach-draft", "verify-claims", "review-outcomes"], logicId: "ecommerce-customer-relationship", primaryColleague: "私域管家", collaboratorColleagues: ["内容官", "客服专员", "导购顾问", "数据参谋"], consentPolicyCount: 0, segmentCount: 0, journeyCount: 0, dialogueCount: 0, latestBatch: null, blockers: ["CUSTOMER_BATCH_EXTERNAL_POLICY_AUTHORITY_RESOLVER_UNAVAILABLE", "CUSTOMER_CONTACT_RESOLUTION_NOT_AUTHORIZED", "CUSTOMER_DIALOGUE_START_NOT_AUTHORIZED"], allowedCommands: ["CREATE_CUSTOMER_CONSENT_POLICY", "CREATE_CUSTOMER_SEGMENT", "CREATE_CUSTOMER_JOURNEY", "CREATE_CUSTOMER_DIALOGUE", "PREPARE_CUSTOMER_DIALOGUE_BATCH", "FREEZE_CUSTOMER_DIALOGUE_BATCH"], contactResolutionAllowed: false, startAllowed: false, sendAllowed: false, externalEffectsAllowed: false };
const contact: CustomerContactContributionViewResponse = { schemaVersion: "aos.ecommerce-workshop.customer-contact-governance/v1", tenant: { orgId: "org-org", projectId: "dev-project" }, evaluatedAt: cutoff, atomicSkillIds: ["build-evidence-pack", "segment-entities", "consent-and-purpose-check", "needs-discovery", "customer-journey-plan", "response-or-outreach-draft", "verify-claims", "review-outcomes"], logicId: "ecommerce-customer-relationship", primaryColleague: "私域管家", collaboratorColleagues: ["内容官", "客服专员", "导购顾问", "数据参谋"], latestStart: null, ledger: { frozenEligible: 0, reserved: 0, skippedWithdrawn: 0, cancelled: 0, accepted: 0, applied: 0, failed: 0, unknown: 0, disputed: 0 }, frequencyPolicyCount: 0, withdrawalCount: 0, blockers: ["CUSTOMER_CONTACT_GOVERNANCE_NOT_PREPARED"], allowedCommands: ["CREATE_CUSTOMER_FREQUENCY_POLICY", "RECORD_CUSTOMER_CONSENT_WITHDRAWAL", "START_CUSTOMER_DIALOGUE_BATCH_GOVERNANCE", "RECORD_CUSTOMER_DISPATCH_OBSERVATION"], permitRedemptionAllowed: false, contactResolutionAllowed: false, providerDispatchAllowed: false, sendAllowed: false, externalEffectsAllowed: false };
const client = () => ({ getCustomerView: vi.fn().mockResolvedValue(blocked), getCustomerLifecycleContributionView: vi.fn().mockResolvedValue(contribution), getCustomerContactContributionView: vi.fn().mockResolvedValue(contact) });

describe("CustomerPage", () => {
  let host: HTMLDivElement; let root: Root;
  beforeEach(() => { host = document.createElement("div"); document.body.appendChild(host); root = createRoot(host); });
  afterEach(() => { act(() => root.unmount()); host.remove(); });
  it("展示四视图六轴、贡献链与受控触达治理且没有写入口", async () => { await act(async () => root.render(<CustomerPage client={client()} />)); expect(host.querySelectorAll('[role="tab"]')).toHaveLength(4); expect(host.querySelectorAll(".customer-readiness article")).toHaveLength(6); expect(host.textContent).toContain("原子 Skill → Logic → 数字同事"); expect(host.textContent).toContain("ecommerce-customer-relationship"); expect(host.textContent).toContain("私域管家"); expect(host.textContent).toContain("不解析联系方式、不启动、不发送"); expect(host.textContent).toContain("Start、频控、撤回竞态与触达预检"); expect(host.textContent).toContain("Permit 兑换 0 · 联系方式解析 0 · Provider 0 · 发送 0 · 外部副作用 0"); expect(host.textContent).toContain("写入口"); expect(Array.from(host.querySelectorAll("button")).map((item) => item.textContent).join(" ")).not.toMatch(/导入客户|新建触达|构建分群|编辑旅程|准备批次|冻结批次|开始发送|兑换 Permit/); });
  it("以中文待核对和未绑定状态对齐客户视觉上下文条", async () => { await act(async () => root.render(<CustomerPage client={client()} />)); const strip = host.querySelector(".customer-context-strip"); expect(strip?.textContent).toContain("客户状态待核对"); expect(strip?.textContent).toContain("负责人未绑定"); expect(strip?.textContent).toContain("只读计划 · 客户产物"); expect(strip?.textContent).not.toMatch(/4,207|高价值\s+[1-9]|潜力\s+[1-9]|触达任务/); expect(strip?.querySelector("button")?.textContent).toBe("重新读取"); });
  it("主业务区以中文行动说明替代英文后端诊断字段", async () => { await act(async () => root.render(<CustomerPage client={client()} />)); const next = host.querySelector(".media-studio-blockers"); expect(next?.textContent).toContain("补充同租户、同数据截止的客户最小化正式数据"); expect(next?.textContent).toContain("客户关系正式数据来源"); expect(next?.querySelector(":scope > div > strong")?.textContent).not.toMatch(/attach|provide|authority/i); expect(next?.querySelector("details")?.textContent).toContain("attach exact privacy-safe authority"); });
  it("切换旅程视图仍只呈现可信空", async () => { await act(async () => root.render(<CustomerPage client={client()} />)); const tab = Array.from(host.querySelectorAll<HTMLButtonElement>('[role="tab"]')).find((item) => item.textContent?.includes("生命周期旅程")); act(() => tab?.click()); expect(host.querySelector('[role="tabpanel"]')?.textContent).toContain("当前没有可披露的客户最小投影"); });
  it("支持方向键沿四视图循环", async () => { await act(async () => root.render(<CustomerPage client={client()} />)); const tabs = host.querySelectorAll<HTMLButtonElement>('[role="tab"]'); act(() => tabs[0]?.dispatchEvent(new KeyboardEvent("keydown", { key: "ArrowRight", bubbles: true }))); const panel = host.querySelector<HTMLElement>('[role="tabpanel"]'); expect(panel?.getAttribute("aria-label")).toBe("客户分群"); expect(tabs[1]?.tabIndex).toBe(0); expect(tabs[1]?.getAttribute("aria-controls")).toBe(panel?.id); expect(panel?.getAttribute("aria-labelledby")).toBe(tabs[1]?.id); });
  it("主投影成功时补充投影失败不会拖垮四视图", async () => { const partialClient = { getCustomerView: vi.fn().mockResolvedValue(blocked), getCustomerLifecycleContributionView: vi.fn().mockRejectedValue(new Error("supplement unavailable")), getCustomerContactContributionView: vi.fn().mockRejectedValue(new Error("supplement unavailable")) }; await act(async () => root.render(<CustomerPage client={partialClient} />)); expect(host.querySelectorAll('[role="tab"]')).toHaveLength(4); expect(host.querySelectorAll(".customer-readiness article")).toHaveLength(6); expect(host.textContent).not.toContain("正式服务未返回可验证客户投影"); expect(host.textContent).toContain("CUSTOMER_LIFECYCLE_CONTRIBUTION_UNAVAILABLE"); expect(host.textContent).toContain("CUSTOMER_CONTACT_CONTRIBUTION_UNAVAILABLE"); expect(host.textContent).toContain("Permit 兑换 0 · 联系方式解析 0 · Provider 0 · 发送 0 · 外部副作用 0"); });
  it("正式读取失败时仍保留视觉稿三栏骨架且不注入客户事实", async () => { const failedClient = { getCustomerView: vi.fn().mockRejectedValue(new Error("offline")), getCustomerLifecycleContributionView: vi.fn().mockRejectedValue(new Error("offline")), getCustomerContactContributionView: vi.fn().mockRejectedValue(new Error("offline")) }; await act(async () => root.render(<CustomerPage client={failedClient} />)); expect(host.querySelectorAll('[role="tab"]')).toHaveLength(4); expect(host.querySelectorAll(".customer-readiness article")).toHaveLength(6); expect(host.textContent).toContain("正式服务未返回可验证客户投影"); expect(host.textContent).toContain("不以演示客户、联系方式或 0 值补齐"); expect(host.textContent).not.toContain("张某兰"); });
  it("读取失败时保留任务、只读计划、客户产物与分层同位结构且动作返回安全预检", async () => { const failedClient = { getCustomerView: vi.fn().mockRejectedValue(new Error("offline")), getCustomerLifecycleContributionView: vi.fn().mockRejectedValue(new Error("offline")), getCustomerContactContributionView: vi.fn().mockRejectedValue(new Error("offline")) }; await act(async () => root.render(<CustomerPage client={failedClient} />)); expect(host.textContent).toContain("今日任务与客户分群"); expect(host.textContent).toContain("客户关系处理计划"); expect(host.textContent).toContain("可回链产物"); expect(host.textContent).toContain("客户分层结果"); expect(host.textContent).toContain("CUSTOMER_VIEW_READ_FAILED"); const controls = [...host.querySelectorAll<HTMLButtonElement>(".customer-failure-actions button")]; expect(controls).toHaveLength(2); expect(controls.every((button) => !button.disabled)).toBe(true); act(() => controls[1]?.click()); expect(host.querySelector('[role="status"]')?.textContent).toContain("未创建任务或触发客户触达"); expect(host.textContent).not.toMatch(/4,207|沉睡客户唤醒|VIP 复购推荐|34\/67|张姐/); });
  it("读取失败时四个只读视图仍可点击和键盘切换", async () => { const failedClient = { getCustomerView: vi.fn().mockRejectedValue(new Error("offline")), getCustomerLifecycleContributionView: vi.fn().mockRejectedValue(new Error("offline")), getCustomerContactContributionView: vi.fn().mockRejectedValue(new Error("offline")) }; await act(async () => root.render(<CustomerPage client={failedClient} />)); const tabs = host.querySelectorAll<HTMLButtonElement>('.customer-failure-taskrail [role="tab"]'); expect(tabs).toHaveLength(4); expect([...tabs].every((tab) => !tab.disabled)).toBe(true); await act(async () => tabs[2]!.click()); expect(host.querySelector('[role="tabpanel"]')?.getAttribute("aria-label")).toBe("生命周期旅程"); expect(tabs[2]!.getAttribute("aria-selected")).toBe("true"); await act(async () => tabs[2]!.dispatchEvent(new KeyboardEvent("keydown", { key: "End", bubbles: true }))); expect(host.querySelector('[role="tabpanel"]')?.getAttribute("aria-label")).toBe("对话与批次"); expect(host.textContent).toContain("正式服务未返回可验证客户投影"); });
});
