import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import type { WorkshopSharedContextResponse } from "../../api/ecommerceWorkshop";
import { EcommerceWorkshopSharedContext } from "./EcommerceWorkshopSharedContext";

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
const token = `ctx_${"a".repeat(40)}`; const hash = `sha256:${"a".repeat(64)}`; const ref = { authority: "task-authority", resourceType: "TaskRevision", resourceId: "task-1", revision: 3, contentHash: hash, receiptId: "receipt-1" };
const ready: WorkshopSharedContextResponse = { schemaVersion: "aos.ecommerce-workshop.shared-context/v1", tenant: { orgId: "org-org", projectId: "dev-project" }, context: { contextId: token, status: "ready", sourceModuleId: "ecommerce.task-cockpit", sourceViewId: "task", sourceRoute: "/workshop/task-cockpit", primaryRef: ref, relatedRefs: [], purpose: "review", permissionDecisionRef: { ...ref, resourceId: "permission-1" }, disclosurePolicyRef: { ...ref, resourceId: "policy-1" }, markings: ["public"], disclosure: "allowed", evaluatedAt: "2026-08-24T08:00:00Z", dataCutoff: "2026-08-24T08:00:00Z", expiresAt: "2026-08-24T09:00:00Z", freshness: "fresh", readiness: "ready", filterSummary: null, lineageRefs: [], blockers: [] }, timeline: [{ eventKey: "event-1", eventType: "task", sourceRef: ref, authoritySequence: 1, occurredAt: "2026-08-24T08:00:00Z", recordedAt: "2026-08-24T08:00:00Z", actorKind: "system", safeSummary: "任务已接受", status: "accepted", reasonCode: null, causationRef: null, correlationRef: null, attempt: null, receiptRef: null, originalRefs: [], late: false, duplicate: false, superseded: false, unknown: false, reconciled: false, stale: false }], navigationTargets: [{ targetId: "target_abcdefghijklmnop", status: "available", moduleId: "ecommerce.customer", viewId: "customer", route: "/workshop/customer", subjectRef: ref, filterSummary: "同一任务", focusAnchor: null, scrollAnchor: null, blockers: [] }], page: { limit: 100, count: 1, hasMore: false, nextCursor: null } };

describe("EcommerceWorkshopSharedContext", () => {
  let host: HTMLDivElement; let root: Root; beforeEach(() => { host = document.createElement("div"); document.body.appendChild(host); root = createRoot(host); }); afterEach(() => { act(() => root.unmount()); host.remove(); });
  it("无 token 不读取，坏 token 失败关闭", async () => { const getSharedContext = vi.fn(); await act(async () => root.render(<EcommerceWorkshopSharedContext contextId={null} client={{ getSharedContext }} />)); expect(host.textContent).toBe(""); await act(async () => root.render(<EcommerceWorkshopSharedContext contextId="bad/token" client={{ getSharedContext }} />)); expect(host.textContent).toContain("共享上下文不可用"); expect(getSharedContext).not.toHaveBeenCalled(); });
  it("呈现对象 rail、timeline 与仅服务端 target 链接", async () => { const getSharedContext = vi.fn().mockResolvedValue(ready); await act(async () => root.render(<EcommerceWorkshopSharedContext contextId={token} client={{ getSharedContext }} />)); expect(host.textContent).toContain("TaskRevision · task-1 · r3"); expect(host.textContent).toContain("任务已接受"); const link = host.querySelector<HTMLAnchorElement>('nav[aria-label="共享上下文导航"] a')!; expect(link.getAttribute("href")).toBe(`/workshop/customer?context=${token}&target=target_abcdefghijklmnop`); expect(link.tabIndex).toBe(0); expect(link.getAttribute("aria-current")).toBeNull(); expect(host.querySelectorAll("h1")).toHaveLength(0); });
  it("只对 query 中 exact target 标记当前 location", async () => { const getSharedContext = vi.fn().mockResolvedValue(ready); await act(async () => root.render(<EcommerceWorkshopSharedContext contextId={token} currentTargetId="target_abcdefghijklmnop" client={{ getSharedContext }} />)); const link = host.querySelector<HTMLAnchorElement>('nav[aria-label="共享上下文导航"] a')!; expect(link.getAttribute("aria-current")).toBe("location"); expect(host.querySelectorAll('[aria-current="page"]')).toHaveLength(0); });
});
