import { useEffect, useRef, useState } from "react";

import { EcommerceWorkshopClientError, ecommerceWorkshopClient, type FullVideoScenarioContribution, type MediaStudioSliceId, type MediaStudioViewResponse } from "../../api/ecommerceWorkshop";
import { AsyncStateBoundary, type AsyncState } from "./AsyncStateBoundary";

type Client = Pick<typeof ecommerceWorkshopClient, "getMediaStudioView"> & Partial<Pick<typeof ecommerceWorkshopClient, "getMediaStudioFullProductionScenario">>;
type Phase = "loading" | "ready" | "empty" | "forbidden" | "failed";
const LABELS: Record<MediaStudioSliceId, string> = { context: "生产上下文", execution: "职责与执行", delivery: "交付与复盘" };
const TAB_LABELS: Record<MediaStudioSliceId, string> = { context: "种草文案", execution: "短视频", delivery: "数字人直播" };
const stateFor = (phase: Phase): AsyncState => phase === "ready" || phase === "empty" ? "ready" : phase;
const STATUS_LABELS: Record<string, string> = { ready: "可读取", target: "等待条件", blocked: "等待条件", unknown: "待核对", partial: "部分可用", failed: "读取失败", running: "执行中", succeeded: "已完成", cancelled: "已取消" };
const AXIS_LABELS: Record<string, string> = { module: "业务模块", capability: "生产能力", assignee: "负责人", provider: "生产服务", budget: "预算", publication: "发布条件" };
const labelStatus = (value: string) => STATUS_LABELS[value] ?? value;
const short = (value: string) => value.length > 32 ? `${value.slice(0, 14)}…${value.slice(-11)}` : value;

export function MediaStudioPage({ client = ecommerceWorkshopClient }: { client?: Client }) {
  const [phase, setPhase] = useState<Phase>("loading"); const [response, setResponse] = useState<MediaStudioViewResponse | null>(null); const [fullScenario, setFullScenario] = useState<FullVideoScenarioContribution | null>(null); const [selected, setSelected] = useState<MediaStudioSliceId>("context"); const request = useRef(0);
  const load = () => { const id = ++request.current; setPhase("loading"); setResponse(null); setFullScenario(null); const scenario = client.getMediaStudioFullProductionScenario ? client.getMediaStudioFullProductionScenario() : Promise.resolve(null); void Promise.all([client.getMediaStudioView(), scenario]).then(([next, nextScenario]) => { if (id !== request.current) return; setResponse(next); setFullScenario(nextScenario); setSelected(next.slices.find((item) => item.status === "blocked")?.sliceId ?? "context"); setPhase(next.page.count === 0 && next.slices.every((item) => item.status === "ready") ? "empty" : "ready"); }, (error: unknown) => { if (id === request.current) setPhase(error instanceof EcommerceWorkshopClientError && (error.status === 401 || error.status === 403) ? "forbidden" : "failed"); }); };
  useEffect(() => { load(); return () => { request.current += 1; }; }, [client]);
  const slice = response?.slices.find((item) => item.sliceId === selected); const blocked = response?.slices.reduce((sum, item) => sum + item.blockers.length, 0) ?? 0; const readyAxes = response?.slices.reduce((sum, item) => sum + item.countLedger.ready, 0) ?? 0;
  const content = response && slice ? <div className="media-studio-read-model">
    <details className="media-studio-audit-context">
      <summary>全过程治理与累计审计</summary>
      <div className="media-studio-audit-stack">
    <section className="media-lifecycle" aria-label="媒体生命周期">{response.lifecycle ? response.lifecycle.lifecycle.map((node) => <span className={`is-${node.status}`} key={node.nodeId}><strong>{node.label}</strong><small>{labelStatus(node.status)}</small></span>) : ["准备", "冻结与确认", "编排与审批", "启动与执行", "评审与退回", "交付与发布", "对账与效果"].map((label) => <span className="is-blocked" key={label}><strong>{label}</strong><small>等待条件</small></span>)}</section>
    <section className="creator-growth-axis"><div><span>只读切片</span><strong>3</strong></div><div><span>Ready 轴</span><strong>{readyAxes}/18</strong></div><div><span>独立阻断</span><strong>{blocked}</strong></div><div><span>写入口</span><strong>0</strong></div></section>
    <section className="content-campaign-readonly"><span aria-hidden="true">◇</span><div><h2>媒体生产 · 权威只读</h2><p>target ≠ achieved；Provider submitted ≠ delivered；published、settled 与 effect-reviewed 分轴。</p></div><strong>无写入口</strong></section>
    {fullScenario ? <section className="full-video-scenario" aria-label="完整短视频生产与故障恢复场景">
      <header><div><span>完整生产链 · 只读</span><h2>短视频生产与故障恢复</h2></div><strong>{labelStatus(fullScenario.status)}</strong></header>
      <p>原子 Skill → Logic 编排 → 数字同事绑定 → 工作台贡献；FULL 表示八类专业责任完整，不表示固定八个 Agent 或自动执行。</p>
      <div className="full-video-root"><div><span>生产根</span><strong>{fullScenario.rootBriefRef ? `${fullScenario.rootBriefRef.resourceId} · r${fullScenario.rootBriefRef.revision}` : "exact Brief 未提供"}</strong></div><div><span>TaskRun</span><strong>{fullScenario.taskRunRef?.resourceId ?? "未授权"}</strong></div><div><span>Binding</span><strong>{fullScenario.fullProductionBindingHash ? short(fullScenario.fullProductionBindingHash) : "失败关闭"}</strong></div><div><span>Logic / 原子 Skill</span><strong>{fullScenario.composition ? `${fullScenario.composition.logicRevisionRef.resourceId} / ${fullScenario.composition.atomicSkillRefs.length}` : "等待 exact composition"}</strong></div></div>
      <div className="full-video-ledger" aria-label="FULL视频数量守恒"><span>职责 <strong>{fullScenario.ledger.responsibilitiesObserved}/8</strong></span><span>阶段 <strong>{fullScenario.ledger.stagesObserved}/7</strong></span><span>Artifact <strong>{fullScenario.ledger.artifactsObserved}/{fullScenario.ledger.artifactsExpected}</strong></span><span>四门 <strong>{fullScenario.ledger.mediaGatesObserved}/4</strong></span><span>故障证据 <strong>{fullScenario.ledger.faultCasesObserved}/9</strong></span><span>Usage <strong>{fullScenario.ledger.usageBucketsObserved}/{fullScenario.ledger.usageBucketsExpected}</strong></span></div>
      <section><h3>七阶段生产链</h3><div className="full-video-stage-grid">{fullScenario.stages.map((stage) => <article className={`is-${stage.status}`} key={stage.stageId}><header><strong>{stage.stageId}</strong><span>{stage.status}</span></header><p>{stage.contribution}</p><small>{stage.exactRefs.length ? `${stage.exactRefs.length} exact refs` : stage.blocker?.code}</small></article>)}</div></section>
      <section><h3>八专业责任 · 非固定 Agent</h3><div className="full-video-responsibility-grid">{fullScenario.responsibilities.map((item) => <article className={`is-${item.status}`} key={item.responsibilityId}><header><strong>{item.label}</strong><span>{item.status}</span></header><p>{item.assigneeRef?.resourceId ?? item.blocker?.code}</p><small>{item.skillBindingRef?.resourceId ?? "无隐式绑定"}{item.independentReviewRequired ? " · 独立审核" : ""}</small></article>)}</div></section>
      <section><h3>故障恢复矩阵</h3><div className="full-video-fault-grid">{fullScenario.faultRecovery.map((fault) => <article className={`is-${fault.status}`} key={fault.faultId}><header><strong>{fault.faultId}</strong><span>{fault.status}</span></header><p>{fault.recoveryDecision}</p><small>自动重试：关闭 · {fault.authorityRefs.length ? `${fault.authorityRefs.length} durable refs` : fault.blocker?.code}</small></article>)}</div></section>
      <section><h3>命令边界</h3><div className="media-command-grid">{Object.entries(fullScenario.commands).map(([command]) => <article key={command}><strong>{command}</strong><span>不可执行</span><small>GET-only / external effects off</small></article>)}</div></section>
      <small>阻断：{fullScenario.blockers.map((item) => item.code).join("、")} · Provider、发布、结算与 Release 均未执行</small>
    </section> : null}
    {response.cumulativeGateSet ? <section className="content-campaign-items" aria-label="媒体生产累计验收">
      <header><strong>媒体生产累计验收 · 十一项独立证据</strong><span>{labelStatus(response.cumulativeGateSet.overallStatus)}</span></header>
      <article className="content-campaign-item"><header><strong>{response.cumulativeGateSet.releaseRevision}</strong><span>工程证据不等于运营放行</span></header>
        <p>原子 Skill → Logic 编排 → 数字同事绑定 → 工作台贡献；每栏独立对账，不按测试总数取多数。</p>
        <div className="media-command-grid">{response.cumulativeGateSet.gates.map((gate) => <article className={`is-${gate.status}`} key={gate.gateId}><strong>{gate.gateId}</strong><span>{gate.status}</span><small>{gate.reasonCode}</small></article>)}</div>
        <small>外部副作用：关闭 · Release：关闭 · 阻断：{response.cumulativeGateSet.blockerCodes.join("、")}</small>
      </article>
    </section> : null}
    <section className="content-campaign-items" aria-label="发布候选影响Action与Receipt贡献">
      <header><strong>Candidate → Impact → Action → Receipt → Handoff</strong><span>{response.publishStatus}</span></header>
      {response.publishContributions.length ? response.publishContributions.map((item) => <article className="content-campaign-item" key={item.action.proposalId}>
        <header><strong>{item.candidate.familyId} · {item.candidate.platform}</strong><span>{item.action.status}</span></header>
        <p>{item.candidate.variantRef.resourceId} · {item.candidate.profile}</p>
        <dl><div><dt>Candidate / Gate</dt><dd>{short(item.candidate.variantRef.contentHash)} / {item.candidate.gateSetRef.resourceId}</dd></div><div><dt>Impact</dt><dd>{item.impact.readiness} · {short(item.impact.actionBindingHash)}</dd></div><div><dt>Logic</dt><dd>{item.impact.logicRef.resourceId}</dd></div><div><dt>原子 Skill</dt><dd>{item.impact.atomicSkillRefs.length}</dd></div><div><dt>Action</dt><dd>{item.action.proposalId} · approval {item.action.approvalCount}</dd></div><div><dt>Receipt</dt><dd>{item.receipt ? `${item.receipt.status} / ${item.receipt.providerOutcome ?? "unobserved"}` : "尚无 Receipt"}</dd></div><div><dt>Handoff</dt><dd>{item.handoff.status} · 仅最小披露</dd></div><div><dt>外部副作用</dt><dd>关闭</dd></div></dl>
        <small>{item.blockerCodes.join("、") || "canonical facts 已对齐；仍不代表发布授权"}</small>
      </article>) : <p>{response.publishBlockers.map((item) => item.code).join("；") || "当前没有 canonical 发布候选。"}</p>}
    </section>
    <section className="content-campaign-items" aria-label="媒体 Provider Job 贡献">
      <header><strong>原子 Skill → Logic 编排 → 数字同事 → 工作台贡献</strong><span>{response.providerJobsStatus}</span></header>
      {response.providerJobs.length ? response.providerJobs.map((job) => <article className="content-campaign-item" key={job.jobId}>
        <header><strong>{job.primaryColleague} · {job.status}</strong><span>seq {job.sequence}</span></header>
        <p>{job.jobId}</p>
        <dl><div><dt>原子能力</dt><dd>{job.atomicCapabilityRef.resourceId}</dd></div><div><dt>Logic / TaskRun</dt><dd>{job.logicRef.resourceId}</dd></div><div><dt>数字同事绑定</dt><dd>{job.colleagueBindingRef.resourceId}</dd></div><div><dt>Provider / Model</dt><dd>{job.providerRef.resourceId} / {job.modelRef.resourceId}</dd></div><div><dt>扫描证据</dt><dd>{job.scanRefs.length}</dd></div><div><dt>外部副作用</dt><dd>关闭</dd></div></dl>
        <small>协作：{job.collaboratorColleagues.join("、")}{job.blockerCodes.length ? `；阻断：${job.blockerCodes.join("、")}` : ""}</small>
      </article>) : <p>{response.providerJobBlockers.map((item) => item.code).join("；") || "当前没有 Provider Job。"}</p>}
    </section>
    <section className="content-campaign-items" aria-label="媒体容量预算用量与结算">
      <header><strong>Capacity / Budget / Usage / Cancel / Settlement</strong><span>{response.mediaFinanceStatus}</span></header>
      {response.mediaFinance.length ? response.mediaFinance.map((item) => <article className="content-campaign-item" key={item.financeId}>
        <header><strong>{item.projectedCurrency} {item.projectedMinMinor}–{item.projectedMaxMinor}</strong><span>{item.settlementStatus}</span></header>
        <p>{item.jobId} · v{item.version}</p>
        <dl><div><dt>Capacity</dt><dd>{item.reservationsActive ? "reserved" : "inactive"}</dd></div><div><dt>Budget</dt><dd>{item.budgetReservationRef.resourceId}</dd></div><div><dt>取消</dt><dd>{item.cancelOutcome ?? "未请求"}</dd></div><div><dt>费用结论</dt><dd>{item.feeConclusion}</dd></div><div><dt>币种桶</dt><dd>{item.currencyBuckets.length}</dd></div><div><dt>外部副作用</dt><dd>关闭</dd></div></dl>
        {item.currencyBuckets.map((bucket) => <small key={bucket.currency}>{bucket.currency}：已计量 {bucket.measuredMinor} / 预估 {bucket.estimatedMinor} / 待核对 {bucket.unknownCount} / 调整 {bucket.adjustmentMinor} / 退款 {bucket.refundMinor} / 余量 {bucket.residualMinor ?? "待核对"}</small>)}
        {item.blockerCodes.length ? <small>阻断：{item.blockerCodes.join("、")}</small> : null}
      </article>) : <p>{response.mediaFinanceBlockers.map((item) => item.code).join("；") || "当前没有媒体财务 attempt。"}</p>}
    </section>
      </div>
    </details>
    <section className="media-studio-summary-metrics" aria-label="多媒体生产权威摘要">
      {response.slices.map((item) => <article key={item.sliceId}><span>{TAB_LABELS[item.sliceId]}</span><strong>{item.status === "ready" ? item.authorityRefs.length : "待核对"}</strong><small>{item.status === "ready" ? "正式引用可回链" : "数据来源未闭合"}</small></article>)}
      <article><span>整体成交贡献</span><strong>待核对</strong><small>当前合同未提供该指标</small></article>
    </section>
    <div className="media-studio-tabs" role="tablist" aria-label="媒体只读切片">{response.slices.map((item, index) => <button id={`media-studio-tab-${item.sliceId}`} aria-controls={`media-studio-panel-${item.sliceId}`} role="tab" aria-selected={selected === item.sliceId} tabIndex={selected === item.sliceId ? 0 : -1} type="button" key={item.sliceId} onClick={() => setSelected(item.sliceId)} onKeyDown={(event) => { if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return; event.preventDefault(); const nextIndex = event.key === "Home" ? 0 : event.key === "End" ? response.slices.length - 1 : (index + (event.key === "ArrowRight" ? 1 : -1) + response.slices.length) % response.slices.length; setSelected(response.slices[nextIndex]!.sliceId); event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>("button")[nextIndex]?.focus(); }}><strong>{TAB_LABELS[item.sliceId]}</strong><span>{labelStatus(item.status)}</span></button>)}</div>
    <section id={`media-studio-panel-${selected}`} aria-labelledby={`media-studio-tab-${selected}`} className="media-studio-panel" role="tabpanel"><header><div><span>当前内容类型</span><h2>{LABELS[slice.sliceId]}</h2></div><strong className={`content-campaign-status is-${slice.status}`}>{slice.status === "ready" ? "正式数据可读" : "等待数据"}</strong></header>
      {response.lifecycle ? <section className="media-lifecycle-contribution" aria-label="媒体生命周期贡献">
        {selected === "context" ? <><div className="media-context-card"><span>生产上下文</span><strong>正式生产上下文已读取</strong><small>第 {response.lifecycle.contextRevision} 版 · 仅供当前页面核对</small><details><summary>查看数据审计信息</summary><p>{response.lifecycle.contextId} · {response.lifecycle.taskId} · {short(response.lifecycle.contextHash)}</p></details></div><div className="media-command-grid">{response.lifecycle.commandCapabilities.map((command, index) => <article key={command.commandId}><strong>受控操作 {index + 1}</strong><span>当前不可执行</span><small>尚未满足正式操作条件</small><details><summary>查看数据审计信息</summary><p>{command.commandId} · {command.reasonCode}{command.expectedVersion ? ` · expected v${command.expectedVersion}` : ""}</p></details></article>)}</div></> : null}
        {selected === "execution" ? <><div className="media-responsibility-grid">{response.lifecycle.responsibilities.map((responsibility) => <article className={`is-${responsibility.status}`} key={responsibility.slotId}><header><strong>{responsibility.label}</strong><span>{labelStatus(responsibility.status)}</span></header><p>承担当前内容生产环节</p><small>{responsibility.assigneeId ? "负责人已绑定" : "负责人尚未绑定"}</small><details><summary>查看数据审计信息</summary><p>{responsibility.responsibilityType}</p><p>{responsibility.requiredCapabilityIds.join(" · ")}</p><p>{responsibility.assigneeId ? `${responsibility.assigneeKind} · ${responsibility.assigneeId} · v${responsibility.assigneeVersion}` : responsibility.blockerCodes.join("、")}</p></details></article>)}</div><div className="media-stage-list">{response.lifecycle.stages.length ? response.lifecycle.stages.map((stage, index) => <article key={`${stage.stageId}:${stage.taskRunId}:${stage.attempt}`}><header><strong>生产阶段 {index + 1}</strong><span>{labelStatus(stage.status)}</span></header><p>内容生产责任与服务已按当前上下文挂接。</p><small>第 {stage.attempt} 次执行记录</small><details><summary>查看数据审计信息</summary><p>{stage.stageId} · {stage.capabilityRef.resourceId} → {stage.colleagueBindingRef.resourceId} → {stage.providerRef.resourceId}</p><p>{stage.taskRunId} · {stage.providerJobId}</p></details></article>) : <p>当前生产上下文尚无可归因阶段。</p>}</div></> : null}
        {selected === "delivery" ? <><div className="media-artifact-grid">{response.lifecycle.artifactFamilies.length ? response.lifecycle.artifactFamilies.map((family, index) => <article key={family.familyId}><header><strong>交付成果组 {index + 1}</strong><span>{labelStatus(family.topologyStatus)}</span></header><p>成果 {family.memberCount} 项 · 冲突 {family.conflictCount} 项 · 质量门 {family.gateSetCount} 项</p><small>复核事项 {family.issueCount} 项 · 最新质量状态 {labelStatus(family.latestGateReadiness ?? "unknown")}</small><details><summary>查看数据审计信息</summary><p>{family.familyId}</p></details></article>) : <p>当前生产任务尚无交付成果。</p>}</div><div className="media-issue-list">{response.lifecycle.reviewIssues.length ? response.lifecycle.reviewIssues.map((issue, index) => <article key={`${issue.issueId}:${issue.version}`}><header><strong>复核事项 {index + 1}</strong><span>{labelStatus(issue.status)}</span></header><p>该成果需要回到指定生产阶段复核。</p><small>已形成 {issue.returnDecisionCount} 次退回决定</small><details><summary>查看数据审计信息</summary><p>{issue.issueId} · {issue.severity} · {issue.artifactId} → {issue.returnStage}</p><p>{short(issue.artifactHash)}</p></details></article>) : <p>当前没有复核事项；可信空不等于已发布。</p>}</div></> : null}
      </section> : <aside className="media-studio-blockers media-studio-task-lane"><header><div><small>文案任务</small><h3>任务列表</h3></div><span>{response.lifecycleBlockers.length} 项待核验</span></header><section className="media-studio-task-empty"><strong>当前没有可审阅文案任务</strong><p>生产上下文未闭合，不用演示素材补齐任务列表。</p></section>{response.lifecycleBlockers.map((item) => <details key={item.code}><summary>查看数据审计信息</summary><span>{item.dependency}</span><p>{item.requiredAction}</p><code>{item.code}</code></details>)}</aside>}
      <div className="media-studio-center">{slice.status === "blocked" ? <section className="media-studio-production-empty"><span>当前内容类型</span><strong>等待生产上下文</strong><p>当前只显示目标与缺口；未形成可审阅内容、版本或交付结果。</p></section> : null}<div className="media-readiness-grid">{slice.readinessAxes.map((axis) => <article key={axis.axis} className={`is-${axis.status}`}><header><strong>{AXIS_LABELS[axis.axis] ?? "业务条件"}</strong><span>{labelStatus(axis.status)}</span></header>{axis.exactRef ? <p>正式数据已挂接</p> : <p>暂无可验证来源</p>}<small>{axis.gaps.length ? "需要补充正式业务数据" : "正式数据来源已校验"}</small><details><summary>查看数据审计信息</summary><p>{axis.exactRef ? `${axis.exactRef.resourceType} · ${short(axis.exactRef.contentHash)}` : axis.targetContractRef ?? "未提供目标数据契约"}</p><p>{axis.gaps.join("；") || "无缺口"}</p></details></article>)}</div><section className="content-campaign-items">{slice.authorityRefs.length ? slice.authorityRefs.map((item) => <article className="content-campaign-item" key={`${item.resourceType}:${item.resourceId}:${item.revision}`}><header><strong>正式媒体数据</strong><span>第 {item.revision} 版</span></header><p>该记录已通过当前租户的数据边界校验。</p><details><summary>查看数据审计信息</summary><dl><div><dt>数据类型</dt><dd>{item.resourceType}</dd></div><div><dt>数据编号</dt><dd>{item.resourceId}</dd></div><div><dt>内容摘要</dt><dd>{short(item.contentHash)}</dd></div><div><dt>回读凭证</dt><dd>{short(item.receiptId)}</dd></div></dl></details></article>) : <p>当前没有可挂接的媒体业务数据；空数据与待补条件分开表达。</p>}</section></div><aside className="media-studio-blockers media-studio-advice-lane"><section className="media-studio-advice-empty"><small>内容官建议</small><strong>尚无可回链内容建议</strong><p>建议必须来自可验证数据与同一截止面的证据。</p></section><h3>所需条件与下一步</h3>{slice.blockers.length ? slice.blockers.map((item) => <details key={item.code}><summary>补充正式生产数据</summary><span>当前不能形成可交付内容</span><p>{item.requiredAction}</p><p>{item.dependency}</p><p><code>{item.code}</code></p></details>) : <p>本内容类型当前没有待补条件。</p>}</aside></section>
    <footer className="content-campaign-footnote"><span>租户 {response.tenant.orgId}/{response.tenant.projectId}</span><span>统一数据截止 {new Date(response.dataCutoff).toLocaleString("zh-CN", { hour12: false })}</span><span>当前为单页视图</span></footer>
  </div> : null;
  return <section className="media-studio-page" aria-label="多媒体工作台只读视图"><button className="media-studio-reload-control" type="button" onClick={load}>重新读取</button><div className="content-campaign-toolbar media-studio-context-strip"><span>栖月汇微商城</span><span>内容官（负责人未绑定）</span><span>场景：未绑定</span><small>{response ? `数据截止 ${new Date(response.dataCutoff).toLocaleString("zh-CN", { hour12: false })}` : "数据截止未验证"}</small><b>今日计划：待核对</b></div><AsyncStateBoundary state={stateFor(phase)} dataCutoff={response?.dataCutoff} action={phase === "failed" ? <button type="button" onClick={load}>重新读取</button> : undefined}>{content}</AsyncStateBoundary></section>;
}
