import { useEffect, useRef, useState } from "react";

import { EcommerceWorkshopClientError, ecommerceWorkshopClient, type FullVideoScenarioContribution, type MediaStudioSliceId, type MediaStudioViewResponse } from "../../api/ecommerceWorkshop";
import { AsyncStateBoundary, type AsyncState } from "./AsyncStateBoundary";

type Client = Pick<typeof ecommerceWorkshopClient, "getMediaStudioView"> & Partial<Pick<typeof ecommerceWorkshopClient, "getMediaStudioFullProductionScenario">>;
type Phase = "loading" | "ready" | "empty" | "forbidden" | "failed";
const LABELS: Record<MediaStudioSliceId, string> = { context: "生产上下文", execution: "职责与执行", delivery: "交付与复盘" };
const TAB_LABELS: Record<MediaStudioSliceId, string> = { context: "种草文案", execution: "短视频", delivery: "数字人直播" };
const stateFor = (phase: Phase): AsyncState => phase === "ready" || phase === "empty" ? "ready" : phase;
const short = (value: string) => value.length > 32 ? `${value.slice(0, 14)}…${value.slice(-11)}` : value;

export function MediaStudioPage({ client = ecommerceWorkshopClient }: { client?: Client }) {
  const [phase, setPhase] = useState<Phase>("loading"); const [response, setResponse] = useState<MediaStudioViewResponse | null>(null); const [fullScenario, setFullScenario] = useState<FullVideoScenarioContribution | null>(null); const [selected, setSelected] = useState<MediaStudioSliceId>("context"); const request = useRef(0);
  const load = () => { const id = ++request.current; setPhase("loading"); setResponse(null); setFullScenario(null); const scenario = client.getMediaStudioFullProductionScenario ? client.getMediaStudioFullProductionScenario() : Promise.resolve(null); void Promise.all([client.getMediaStudioView(), scenario]).then(([next, nextScenario]) => { if (id !== request.current) return; setResponse(next); setFullScenario(nextScenario); setSelected(next.slices.find((item) => item.status === "blocked")?.sliceId ?? "context"); setPhase(next.page.count === 0 && next.slices.every((item) => item.status === "ready") ? "empty" : "ready"); }, (error: unknown) => { if (id === request.current) setPhase(error instanceof EcommerceWorkshopClientError && (error.status === 401 || error.status === 403) ? "forbidden" : "failed"); }); };
  useEffect(() => { load(); return () => { request.current += 1; }; }, [client]);
  const slice = response?.slices.find((item) => item.sliceId === selected); const blocked = response?.slices.reduce((sum, item) => sum + item.blockers.length, 0) ?? 0; const readyAxes = response?.slices.reduce((sum, item) => sum + item.countLedger.ready, 0) ?? 0;
  const content = response && slice ? <div className="media-studio-read-model">
    <details className="media-studio-audit-context">
      <summary>全过程治理与累计审计</summary>
      <div className="media-studio-audit-stack">
    <section className="media-lifecycle" aria-label="媒体生命周期">{response.lifecycle ? response.lifecycle.lifecycle.map((node) => <span className={`is-${node.status}`} key={node.nodeId}><strong>{node.label}</strong><small>{node.status}</small></span>) : ["prepare", "freeze / confirm", "compile / approve", "start / run", "review / return", "deliver / publish", "reconcile / effect"].map((label) => <span className="is-blocked" key={label}><strong>{label}</strong><small>blocked</small></span>)}</section>
    <section className="creator-growth-axis"><div><span>只读切片</span><strong>3</strong></div><div><span>Ready 轴</span><strong>{readyAxes}/18</strong></div><div><span>独立阻断</span><strong>{blocked}</strong></div><div><span>写入口</span><strong>0</strong></div></section>
    <section className="content-campaign-readonly"><span aria-hidden="true">◇</span><div><h2>媒体生产 · 权威只读</h2><p>target ≠ achieved；Provider submitted ≠ delivered；published、settled 与 effect-reviewed 分轴。</p></div><strong>无写入口</strong></section>
    {fullScenario ? <section className="full-video-scenario" aria-label="FULL短视频生产与故障恢复场景">
      <header><div><span>W8-05 · exact-bound GET-only</span><h2>FULL 短视频生产 · 故障恢复</h2></div><strong>{fullScenario.status} / NO RELEASE</strong></header>
      <p>原子 Skill → Logic 编排 → 数字同事绑定 → 工作台贡献；FULL 表示八类专业责任完整，不表示固定八个 Agent 或自动执行。</p>
      <div className="full-video-root"><div><span>生产根</span><strong>{fullScenario.rootBriefRef ? `${fullScenario.rootBriefRef.resourceId} · r${fullScenario.rootBriefRef.revision}` : "exact Brief 未提供"}</strong></div><div><span>TaskRun</span><strong>{fullScenario.taskRunRef?.resourceId ?? "未授权"}</strong></div><div><span>Binding</span><strong>{fullScenario.fullProductionBindingHash ? short(fullScenario.fullProductionBindingHash) : "失败关闭"}</strong></div><div><span>Logic / 原子 Skill</span><strong>{fullScenario.composition ? `${fullScenario.composition.logicRevisionRef.resourceId} / ${fullScenario.composition.atomicSkillRefs.length}` : "等待 exact composition"}</strong></div></div>
      <div className="full-video-ledger" aria-label="FULL视频数量守恒"><span>职责 <strong>{fullScenario.ledger.responsibilitiesObserved}/8</strong></span><span>阶段 <strong>{fullScenario.ledger.stagesObserved}/7</strong></span><span>Artifact <strong>{fullScenario.ledger.artifactsObserved}/{fullScenario.ledger.artifactsExpected}</strong></span><span>四门 <strong>{fullScenario.ledger.mediaGatesObserved}/4</strong></span><span>故障证据 <strong>{fullScenario.ledger.faultCasesObserved}/9</strong></span><span>Usage <strong>{fullScenario.ledger.usageBucketsObserved}/{fullScenario.ledger.usageBucketsExpected}</strong></span></div>
      <section><h3>七阶段生产链</h3><div className="full-video-stage-grid">{fullScenario.stages.map((stage) => <article className={`is-${stage.status}`} key={stage.stageId}><header><strong>{stage.stageId}</strong><span>{stage.status}</span></header><p>{stage.contribution}</p><small>{stage.exactRefs.length ? `${stage.exactRefs.length} exact refs` : stage.blocker?.code}</small></article>)}</div></section>
      <section><h3>八专业责任 · 非固定 Agent</h3><div className="full-video-responsibility-grid">{fullScenario.responsibilities.map((item) => <article className={`is-${item.status}`} key={item.responsibilityId}><header><strong>{item.label}</strong><span>{item.status}</span></header><p>{item.assigneeRef?.resourceId ?? item.blocker?.code}</p><small>{item.skillBindingRef?.resourceId ?? "无隐式绑定"}{item.independentReviewRequired ? " · 独立审核" : ""}</small></article>)}</div></section>
      <section><h3>故障恢复矩阵</h3><div className="full-video-fault-grid">{fullScenario.faultRecovery.map((fault) => <article className={`is-${fault.status}`} key={fault.faultId}><header><strong>{fault.faultId}</strong><span>{fault.status}</span></header><p>{fault.recoveryDecision}</p><small>自动重试：关闭 · {fault.authorityRefs.length ? `${fault.authorityRefs.length} durable refs` : fault.blocker?.code}</small></article>)}</div></section>
      <section><h3>命令边界</h3><div className="media-command-grid">{Object.entries(fullScenario.commands).map(([command]) => <article key={command}><strong>{command}</strong><span>不可执行</span><small>GET-only / external effects off</small></article>)}</div></section>
      <small>阻断：{fullScenario.blockers.map((item) => item.code).join("、")} · Provider、发布、结算与 Release 均未执行</small>
    </section> : null}
    {response.cumulativeGateSet ? <section className="content-campaign-items" aria-label="W7媒体累计十一栏验收门">
      <header><strong>W7 累计门 · 十一栏独立证据</strong><span>{response.cumulativeGateSet.overallStatus}</span></header>
      <article className="content-campaign-item"><header><strong>{response.cumulativeGateSet.releaseRevision}</strong><span>工程证据不等于运营放行</span></header>
        <p>原子 Skill → Logic 编排 → 数字同事绑定 → 工作台贡献；每栏独立对账，不按测试总数取多数。</p>
        <div className="media-command-grid">{response.cumulativeGateSet.gates.map((gate) => <article className={`is-${gate.status}`} key={gate.gateId}><strong>{gate.gateId}</strong><span>{gate.status}</span><small>{gate.reasonCode}</small></article>)}</div>
        <small>外部副作用：关闭 · Release：关闭 · 阻断：{response.cumulativeGateSet.blockerCodes.join("、")}</small>
      </article>
    </section> : null}
    <section className="content-campaign-items" aria-label="发布候选影响Action与Receipt贡献">
      <header><strong>Candidate → Impact → Action → Receipt → Handoff</strong><span>{response.publishStatus}</span></header>
      {response.publishContributions.length ? response.publishContributions.map((item) => <article className="content-campaign-item" key={item.action.proposalId}>
        <header><strong>{item.candidate.familyId} · {item.candidate.platform}</strong><span>{item.action.status}</span></header>
        <p>{item.candidate.variantRef.resourceId} · {item.candidate.profile}</p>
        <dl><div><dt>Candidate / Gate</dt><dd>{short(item.candidate.variantRef.contentHash)} / {item.candidate.gateSetRef.resourceId}</dd></div><div><dt>Impact</dt><dd>{item.impact.readiness} · {short(item.impact.actionBindingHash)}</dd></div><div><dt>Logic</dt><dd>{item.impact.logicRef.resourceId}</dd></div><div><dt>原子 Skill</dt><dd>{item.impact.atomicSkillRefs.length}</dd></div><div><dt>Action</dt><dd>{item.action.proposalId} · approval {item.action.approvalCount}</dd></div><div><dt>Receipt</dt><dd>{item.receipt ? `${item.receipt.status} / ${item.receipt.providerOutcome ?? "unobserved"}` : "尚无 Receipt"}</dd></div><div><dt>Handoff</dt><dd>{item.handoff.status} · 仅最小披露</dd></div><div><dt>外部副作用</dt><dd>关闭</dd></div></dl>
        <small>{item.blockerCodes.join("、") || "canonical facts 已对齐；仍不代表发布授权"}</small>
      </article>) : <p>{response.publishBlockers.map((item) => item.code).join("；") || "当前没有 canonical 发布候选。"}</p>}
    </section>
    <section className="content-campaign-items" aria-label="媒体 Provider Job 贡献">
      <header><strong>原子 Skill → Logic 编排 → 数字同事 → 工作台贡献</strong><span>{response.providerJobsStatus}</span></header>
      {response.providerJobs.length ? response.providerJobs.map((job) => <article className="content-campaign-item" key={job.jobId}>
        <header><strong>{job.primaryColleague} · {job.status}</strong><span>seq {job.sequence}</span></header>
        <p>{job.jobId}</p>
        <dl><div><dt>原子能力</dt><dd>{job.atomicCapabilityRef.resourceId}</dd></div><div><dt>Logic / TaskRun</dt><dd>{job.logicRef.resourceId}</dd></div><div><dt>数字同事绑定</dt><dd>{job.colleagueBindingRef.resourceId}</dd></div><div><dt>Provider / Model</dt><dd>{job.providerRef.resourceId} / {job.modelRef.resourceId}</dd></div><div><dt>扫描证据</dt><dd>{job.scanRefs.length}</dd></div><div><dt>外部副作用</dt><dd>关闭</dd></div></dl>
        <small>协作：{job.collaboratorColleagues.join("、")}{job.blockerCodes.length ? `；阻断：${job.blockerCodes.join("、")}` : ""}</small>
      </article>) : <p>{response.providerJobBlockers.map((item) => item.code).join("；") || "当前没有 Provider Job。"}</p>}
    </section>
    <section className="content-campaign-items" aria-label="媒体容量预算用量与结算">
      <header><strong>Capacity / Budget / Usage / Cancel / Settlement</strong><span>{response.mediaFinanceStatus}</span></header>
      {response.mediaFinance.length ? response.mediaFinance.map((item) => <article className="content-campaign-item" key={item.financeId}>
        <header><strong>{item.projectedCurrency} {item.projectedMinMinor}–{item.projectedMaxMinor}</strong><span>{item.settlementStatus}</span></header>
        <p>{item.jobId} · v{item.version}</p>
        <dl><div><dt>Capacity</dt><dd>{item.reservationsActive ? "reserved" : "inactive"}</dd></div><div><dt>Budget</dt><dd>{item.budgetReservationRef.resourceId}</dd></div><div><dt>取消</dt><dd>{item.cancelOutcome ?? "未请求"}</dd></div><div><dt>费用结论</dt><dd>{item.feeConclusion}</dd></div><div><dt>币种桶</dt><dd>{item.currencyBuckets.length}</dd></div><div><dt>外部副作用</dt><dd>关闭</dd></div></dl>
        {item.currencyBuckets.map((bucket) => <small key={bucket.currency}>{bucket.currency}：measured {bucket.measuredMinor} / estimated {bucket.estimatedMinor} / unknown {bucket.unknownCount} / adjustment {bucket.adjustmentMinor} / refund {bucket.refundMinor} / residual {bucket.residualMinor ?? "unknown"}</small>)}
        {item.blockerCodes.length ? <small>阻断：{item.blockerCodes.join("、")}</small> : null}
      </article>) : <p>{response.mediaFinanceBlockers.map((item) => item.code).join("；") || "当前没有媒体财务 attempt。"}</p>}
    </section>
      </div>
    </details>
    <section className="media-studio-summary-metrics" aria-label="多媒体生产权威摘要">
      {response.slices.map((item) => <article key={item.sliceId}><span>{TAB_LABELS[item.sliceId]}</span><strong>{item.status === "ready" ? item.authorityRefs.length : "unknown"}</strong><small>{item.status === "ready" ? "exact authority refs" : "权威未闭合"}</small></article>)}
      <article><span>整体 GMV 贡献</span><strong>unknown</strong><small>当前合同未提供该指标</small></article>
    </section>
    <div className="media-studio-tabs" role="tablist" aria-label="媒体只读切片">{response.slices.map((item, index) => <button id={`media-studio-tab-${item.sliceId}`} aria-controls={`media-studio-panel-${item.sliceId}`} role="tab" aria-selected={selected === item.sliceId} tabIndex={selected === item.sliceId ? 0 : -1} type="button" key={item.sliceId} onClick={() => setSelected(item.sliceId)} onKeyDown={(event) => { if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return; event.preventDefault(); const nextIndex = event.key === "Home" ? 0 : event.key === "End" ? response.slices.length - 1 : (index + (event.key === "ArrowRight" ? 1 : -1) + response.slices.length) % response.slices.length; setSelected(response.slices[nextIndex]!.sliceId); event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>("button")[nextIndex]?.focus(); }}><strong>{TAB_LABELS[item.sliceId]}</strong><span>{item.status}</span></button>)}</div>
    <section id={`media-studio-panel-${selected}`} aria-labelledby={`media-studio-tab-${selected}`} className="media-studio-panel" role="tabpanel"><header><div><span>{slice.sliceId}</span><h2>{LABELS[slice.sliceId]}</h2></div><strong className={`content-campaign-status is-${slice.status}`}>{slice.status === "ready" ? "权威读取可用" : "失败关闭"}</strong></header>
      {response.lifecycle ? <section className="media-lifecycle-contribution" aria-label="媒体生命周期贡献">
        {selected === "context" ? <><div className="media-context-card"><span>冻结生产上下文</span><strong>{response.lifecycle.contextId} · r{response.lifecycle.contextRevision}</strong><small>Task {response.lifecycle.taskId} · {short(response.lifecycle.contextHash)}</small></div><div className="media-command-grid">{response.lifecycle.commandCapabilities.map((command) => <article key={command.commandId}><strong>{command.commandId}</strong><span>不可执行</span><small>{command.reasonCode}{command.expectedVersion ? ` · expected v${command.expectedVersion}` : ""}</small></article>)}</div></> : null}
        {selected === "execution" ? <><div className="media-responsibility-grid">{response.lifecycle.responsibilities.map((responsibility) => <article className={`is-${responsibility.status}`} key={responsibility.slotId}><header><strong>{responsibility.label}</strong><span>{responsibility.status}</span></header><p>{responsibility.responsibilityType}</p><small>{responsibility.requiredCapabilityIds.join(" · ")}</small><small>{responsibility.assigneeId ? `${responsibility.assigneeKind} · ${responsibility.assigneeId} · v${responsibility.assigneeVersion}` : responsibility.blockerCodes.join("、")}</small></article>)}</div><div className="media-stage-list">{response.lifecycle.stages.length ? response.lifecycle.stages.map((stage) => <article key={`${stage.stageId}:${stage.taskRunId}:${stage.attempt}`}><header><strong>{stage.stageId}</strong><span>{stage.status}</span></header><p>{stage.capabilityRef.resourceId} → {stage.colleagueBindingRef.resourceId} → {stage.providerRef.resourceId}</p><small>TaskRun {stage.taskRunId} · attempt {stage.attempt} · ProviderJob {stage.providerJobId}</small></article>) : <p>当前冻结上下文尚无可归因 Stage。</p>}</div></> : null}
        {selected === "delivery" ? <><div className="media-artifact-grid">{response.lifecycle.artifactFamilies.length ? response.lifecycle.artifactFamilies.map((family) => <article key={family.familyId}><header><strong>{family.familyId}</strong><span>{family.topologyStatus}</span></header><p>成员 {family.memberCount} · 冲突 {family.conflictCount} · Gate {family.gateSetCount}</p><small>最新 Gate {family.latestGateReadiness ?? "unknown"} · Issue {family.issueCount}</small></article>) : <p>当前 TaskRun 尚无 Artifact Family。</p>}</div><div className="media-issue-list">{response.lifecycle.reviewIssues.length ? response.lifecycle.reviewIssues.map((issue) => <article key={`${issue.issueId}:${issue.version}`}><header><strong>{issue.issueId} · {issue.severity}</strong><span>{issue.status}</span></header><p>{issue.artifactId} → {issue.returnStage}</p><small>Return Decision {issue.returnDecisionCount} · {short(issue.artifactHash)}</small></article>) : <p>当前没有 Review Issue；可信空不等于已发布。</p>}</div></> : null}
      </section> : <aside className="media-studio-blockers"><h3>生命周期聚合失败关闭</h3>{response.lifecycleBlockers.map((item) => <div key={item.code}><strong>{item.code}</strong><span>{item.dependency}</span><p>{item.requiredAction}</p></div>)}</aside>}
      <div className="media-studio-center"><div className="media-readiness-grid">{slice.readinessAxes.map((axis) => <article key={axis.axis} className={`is-${axis.status}`}><header><strong>{axis.axis}</strong><span>{axis.status}</span></header>{axis.exactRef ? <p>{axis.exactRef.resourceType} · {short(axis.exactRef.contentHash)}</p> : <p>{axis.targetContractRef ?? "无 exact authority"}</p>}<small>{axis.gaps.join("；") || "exact authority 已校验"}</small></article>)}</div><section className="content-campaign-items">{slice.authorityRefs.length ? slice.authorityRefs.map((item) => <article className="content-campaign-item" key={`${item.resourceType}:${item.resourceId}:${item.revision}`}><header><strong>{item.resourceType}</strong><span>r{item.revision}</span></header><p>{item.resourceId}</p><dl><div><dt>Exact hash</dt><dd>{short(item.contentHash)}</dd></div><div><dt>Receipt</dt><dd>{short(item.receiptId)}</dd></div></dl></article>) : <p>当前没有可挂接的媒体 authority；可信空与 target/blocked 不混淆。</p>}</section></div><aside className="media-studio-blockers"><h3>阻断与所需证据</h3>{slice.blockers.length ? slice.blockers.map((item) => <div key={item.code}><strong>{item.code}</strong><span>{item.dependency}</span><p>{item.requiredAction}</p></div>) : <p>本切片当前无 blocker。</p>}</aside></section>
    <footer className="content-campaign-footnote"><span>租户 {response.tenant.orgId}/{response.tenant.projectId}</span><span>统一 cutoff {new Date(response.dataCutoff).toLocaleString("zh-CN", { hour12: false })}</span><span>无后续页：是</span></footer>
  </div> : null;
  return <section className="media-studio-page" aria-label="多媒体工作台只读视图"><button className="media-studio-reload-control" type="button" onClick={load}>重新读取</button><div className="content-campaign-toolbar media-studio-context-strip"><span>栖月汇微商城</span><span>内容官（owner 未绑定）</span><span>场景：未绑定</span><small>{response ? `cutoff ${new Date(response.dataCutoff).toLocaleString("zh-CN", { hour12: false })}` : "cutoff 未验证"}</small><b>今日计划：unknown</b></div><AsyncStateBoundary state={stateFor(phase)} dataCutoff={response?.dataCutoff} action={phase === "failed" ? <button type="button" onClick={load}>重新读取</button> : undefined}>{content}</AsyncStateBoundary></section>;
}
