import { useEffect, useRef, useState } from "react";

import { EcommerceWorkshopClientError, ecommerceWorkshopClient, type PriceDispositionContributionViewResponse, type PriceGovernanceViewId, type PriceGovernanceViewResponse, type PriceResearchContributionViewResponse, type RemedyScenarioOutcomeAxisId, type RemedyScenarioStageId, type ThreeModuleClosureContributionViewResponse } from "../../api/ecommerceWorkshop";
import { AsyncStateBoundary, type AsyncState } from "./AsyncStateBoundary";
import { ThreeModuleClosureCard, unavailableThreeModuleClosure } from "./ThreeModuleClosureCard";

type Client = Pick<typeof ecommerceWorkshopClient, "getPriceGovernanceView"> & Partial<Pick<typeof ecommerceWorkshopClient, "getPriceResearchContributionView" | "getPriceDispositionContributionView" | "getThreeModuleClosureContributionView">>;
type Phase = "loading" | "ready" | "empty" | "forbidden" | "failed";
const LABELS: Record<PriceGovernanceViewId, string> = { governance: "同款价格治理", competitor: "竞品比价", schedule: "调度控制台" };
const AXIS_LABELS = { collection: "采集证据", match: "同款判定", policy_case: "策略与 Case", notification: "通知就绪", advice_handoff: "建议交接", repricing: "自动调价" } as const;
const stateFor = (phase: Phase): AsyncState => phase === "ready" || phase === "empty" ? "ready" : phase;
const unavailableContribution = (next: PriceGovernanceViewResponse): PriceResearchContributionViewResponse => ({ schemaVersion: "aos.ecommerce-workshop.price-research/v1", tenant: next.tenant, evaluatedAt: next.evaluatedAt, atomicSkillRefs: [], logicRef: null, primaryColleague: "数据参谋", collaboratorColleagues: ["活动策划师", "导购顾问"], latestBatch: null, blockers: ["PRICE_RESEARCH_BATCH_NOT_AVAILABLE"], allowedCommands: ["PREPARE_PRICE_RESEARCH_BATCH", "FREEZE_PRICE_RESEARCH_BATCH"], externalEffectsAllowed: false });
const unavailableDisposition = (next: PriceGovernanceViewResponse): PriceDispositionContributionViewResponse => ({ schemaVersion: "aos.ecommerce-workshop.price-disposition/v1", tenant: next.tenant, evaluatedAt: next.evaluatedAt, atomicSkillIds: ["compile-price-case", "prepare-price-advice", "prepare-price-notice", "prepare-price-handoff", "evaluate-reprice-specialized-gate"], logicId: "ecommerce-price-governance", primaryColleague: "数据参谋", collaboratorColleagues: ["活动策划师", "导购顾问"], caseCount: 0, dispositionCounts: { internal_advice: 0, external_notice: 0, module_handoff: 0, repricing: 0 }, latestDisposition: null, latestObservation: null, blockers: ["PRICE_DISPOSITION_AUTHORITY_UNAVAILABLE", "PRICE_CASE_NOT_AVAILABLE", "PRICE_DISPOSITION_NOT_AVAILABLE", "PRICE_NOTICE_OPERATIONAL_AUTHORITY_NOT_GRANTED", "PRICE_REPRICE_OPERATIONAL_AUTHORITY_NOT_GRANTED"], allowedCommands: ["COMPILE_PRICE_CASE", "CREATE_PRICE_DISPOSITION_CONTRACT", "PREPARE_PRICE_DISPOSITION", "FREEZE_PRICE_DISPOSITION", "RECORD_PRICE_DISPOSITION_OBSERVATION"], repricingEnabled: false, externalEffectsAllowed: false });
const DISPOSITION_LABELS = { internal_advice: "内部建议", external_notice: "外部通知", module_handoff: "模块交接", repricing: "调价" } as const;
const REMEDY_STAGE_LABELS: Record<RemedyScenarioStageId, string> = { price_observation: "价格异常", match_decision: "同款判定", price_case: "PriceCase", affected_orders: "受影响订单", operation_case: "OperationCase", customer_handoff: "客户补救交接", contact_permit: "联系许可", action_outcomes: "动作结果", effect_review: "效果复核" };
const REMEDY_AXIS_LABELS: Record<RemedyScenarioOutcomeAxisId, string> = { repricing_applied: "调价已应用", refund_compensation_submitted: "退款/补偿已提交", customer_message_accepted: "客户消息已接受", operation_case_resolved: "运营 Case 已解决", effect_mature: "效果已成熟" };

export function PriceGovernancePage({ client = ecommerceWorkshopClient }: { client?: Client }) {
  const [phase, setPhase] = useState<Phase>("loading");
  const [response, setResponse] = useState<PriceGovernanceViewResponse | null>(null);
  const [contribution, setContribution] = useState<PriceResearchContributionViewResponse | null>(null);
  const [disposition, setDisposition] = useState<PriceDispositionContributionViewResponse | null>(null);
  const [closure, setClosure] = useState<ThreeModuleClosureContributionViewResponse | null>(null);
  const [selected, setSelected] = useState<PriceGovernanceViewId>("governance");
  const request = useRef(0);
  const load = () => {
    const id = ++request.current; setPhase("loading"); setResponse(null); setContribution(null); setDisposition(null); setClosure(null);
    void Promise.all([client.getPriceGovernanceView(), client.getPriceResearchContributionView?.().catch(() => null) ?? Promise.resolve(null), client.getPriceDispositionContributionView?.().catch(() => null) ?? Promise.resolve(null), client.getThreeModuleClosureContributionView?.("price").catch(() => null) ?? Promise.resolve(null)]).then(([next, nextContribution, nextDisposition, nextClosure]) => { if (id !== request.current) return; setResponse(next); setContribution(nextContribution ?? unavailableContribution(next)); setDisposition(nextDisposition ?? unavailableDisposition(next)); setClosure(nextClosure ?? unavailableThreeModuleClosure("price", next.tenant, next.evaluatedAt)); setSelected(next.views.find((item) => item.status === "blocked")?.viewId ?? "governance"); setPhase(next.page.count === 0 && next.views.every((item) => item.status === "ready") ? "empty" : "ready"); }, (error: unknown) => { if (id === request.current) setPhase(error instanceof EcommerceWorkshopClientError && (error.status === 401 || error.status === 403) ? "forbidden" : "failed"); });
  };
  useEffect(() => { load(); return () => { request.current += 1; }; }, [client]);
  const view = response?.views.find((item) => item.viewId === selected);
  const comparable = response?.views.reduce((sum, item) => sum + item.countLedger.eligible, 0) ?? 0;
  const total = response?.views.reduce((sum, item) => sum + item.countLedger.input, 0) ?? 0;
  const content = response && view ? <div className="price-governance-read-model">
    <details className="price-governance-audit-context">
      <summary>价格治理全过程与累计审计</summary>
      <div className="price-governance-audit-stack">
    <section className="price-governance-hero"><div><span>价格治理驾驶舱 · exact evidence</span><h2>用统一报价口径审视市场价格，而不是自动改价</h2><p>Observation 与 Match Decision 分离；陈旧、未许可、初步匹配或 original 不可达均不计可比异常。</p></div><strong>只读 · 调价禁用</strong></section>
    <section className="creator-growth-axis"><div><span>只读视图</span><strong>3</strong></div><div><span>可比报价</span><strong>{comparable}/{total}</strong></div><div><span>资源 revision</span><strong>r{response.resourceRevision}</strong></div><div><span>写入口</span><strong>0</strong></div></section>
    {contribution ? <section className="creator-contribution-card" aria-label="价格治理数字同事贡献"><header><div><span>原子 Skill → Logic → 数字同事</span><h3>{contribution.primaryColleague}主责价格调研</h3></div><strong>{contribution.latestBatch?.lifecycle ?? "未准备"}</strong></header><p>{contribution.atomicSkillRefs.length ? `${contribution.atomicSkillRefs.length} 个原子 Skill 由 ${contribution.logicRef?.resourceId ?? "未知 Logic"} 编排` : "当前未挂接 exact Skill/Logic authority，保持失败关闭。"}</p><div className="creator-contribution-grid"><span>协作：{contribution.collaboratorColleagues.join("、")}</span><span>批次：{contribution.latestBatch ? `${contribution.latestBatch.ledger.eligible}/${contribution.latestBatch.ledger.input} eligible` : "无可信批次"}</span><span>外部效果：0</span><span>ResearchJob：0</span></div><small>{contribution.blockers.length ? contribution.blockers.join(" · ") : "exact contribution chain ready"}</small></section> : null}
    {disposition ? <section className="price-disposition-card" aria-label="价格处置分门贡献"><header><div><span>PriceCase → typed contract → exact gate</span><h3>价格通知、建议、交接与调价严格分门</h3></div><strong>只读预检</strong></header><p>{disposition.atomicSkillIds.length} 个原子 Skill 经 {disposition.logicId} 编排，由{disposition.primaryColleague}主责；任何分门都不直接授予执行权。</p><div className="price-disposition-grid">{(Object.keys(DISPOSITION_LABELS) as Array<keyof typeof DISPOSITION_LABELS>).map((kind) => <article key={kind} className={`is-${kind}`}><span>{DISPOSITION_LABELS[kind]}</span><strong>{disposition.dispositionCounts[kind]}</strong><small>{kind === "repricing" ? "专业门关闭 · executionAllowed=false" : kind === "external_notice" ? "通知 authority 未授予" : kind === "module_handoff" ? "仅内部 Envelope 草案" : "仅建议草案"}</small></article>)}</div><footer><span>PriceCase：{disposition.caseCount}</span><span>通知发送：0</span><span>调价：0</span><span>外部效果：0</span></footer><small>{disposition.blockers.length ? disposition.blockers.join(" · ") : "exact disposition chain ready"}</small></section> : null}
    {response.remedyScenario ? <section className="remedy-scenario-card" aria-label="价格异常客户补救同链贡献"><header><div><span>价格异常 → PriceCase → OperationCase → 客户补救</span><h3>一个 exact 根串起运营 Case 与客户补救，但不展开受保护正文</h3></div><strong>失败关闭 · 无外部效果</strong></header><div className="remedy-scenario-binding"><span>原子 Skill → Logic 编排 → 数字同事绑定 → 工作台贡献</span><strong>{response.remedyScenario.rootCaseRef ? `${response.remedyScenario.rootCaseRef.resourceId} · r${response.remedyScenario.rootCaseRef.revision}` : "缺少 PriceCase exact 根"}</strong><small>{response.remedyScenario.remedyBindingHash ? `binding ${response.remedyScenario.remedyBindingHash.slice(0, 12)}…` : "binding 未建立"}</small></div><div className="remedy-scenario-stages">{response.remedyScenario.stages.map((stage, index) => <article key={stage.stageId} className={`is-${stage.status}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{REMEDY_STAGE_LABELS[stage.stageId]}</strong><small>{stage.status === "ready" ? `${stage.exactRefs.length} exact ref` : stage.blockers[0]?.code ?? "unknown"}</small></article>)}</div><div className="remedy-scenario-ledger"><div><span>受影响订单</span><strong>{response.remedyScenario.ledger.affectedOrdersObserved}/{response.remedyScenario.ledger.affectedOrdersExpected}</strong></div><div><span>合格客户</span><strong>{response.remedyScenario.ledger.eligibleCustomersObserved}/{response.remedyScenario.ledger.eligibleCustomersExpected}</strong></div><div><span>动作结果</span><strong>{response.remedyScenario.ledger.actionsReady}/{response.remedyScenario.ledger.actionsExpected}</strong></div><div><span>受保护联系正文</span><strong>未解析</strong></div></div><div className="remedy-scenario-axes">{response.remedyScenario.outcomeAxes.map((axis) => <article key={axis.axisId} className={`is-${axis.status}`}><strong>{REMEDY_AXIS_LABELS[axis.axisId]}</strong><span>{axis.status}</span><small>{axis.exactRef ? `${axis.exactRef.resourceType} · r${axis.exactRef.revision}` : axis.blocker?.code ?? "unknown"}</small></article>)}</div><footer><span>调价 0</span><span>退款/补偿提交 0</span><span>客户消息发送 0</span><span>Case 关闭 0</span><span>外部效果 0</span></footer></section> : null}
    {closure ? <ThreeModuleClosureCard value={closure} /> : null}
      </div>
    </details>
    <div className="price-governance-tabs" role="tablist" aria-label="价格治理只读视图">{response.views.map((item, index) => <button id={`price-governance-tab-${item.viewId}`} aria-controls={`price-governance-panel-${item.viewId}`} type="button" role="tab" aria-selected={selected === item.viewId} tabIndex={selected === item.viewId ? 0 : -1} key={item.viewId} onClick={() => setSelected(item.viewId)} onKeyDown={(event) => { if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return; event.preventDefault(); const nextIndex = event.key === "Home" ? 0 : event.key === "End" ? response.views.length - 1 : (index + (event.key === "ArrowRight" ? 1 : -1) + response.views.length) % response.views.length; setSelected(response.views[nextIndex]!.viewId); event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>("button")[nextIndex]?.focus(); }}><strong>{LABELS[item.viewId]}</strong><span>{item.status}</span></button>)}</div>
    <section id={`price-governance-panel-${selected}`} aria-labelledby={`price-governance-tab-${selected}`} className="price-governance-panel" role="tabpanel" aria-label={LABELS[selected]}><header><div><span>{view.viewId}</span><h2>{LABELS[view.viewId]}</h2></div><strong className={`content-campaign-status is-${view.status}`}>{view.status === "ready" ? "同截止面可读" : "失败关闭"}</strong></header>
      <div className="price-governance-readiness">{view.readinessAxes.map((axis) => <article key={axis.axis} className={`is-${axis.status}`}><strong>{AXIS_LABELS[axis.axis]}</strong><span>{axis.status}</span><p>{axis.exactRef ? `${axis.exactRef.resourceType} · r${axis.exactRef.revision}` : axis.axis === "repricing" ? "R4 专业门未开启" : "无 exact authority"}</p></article>)}</div>
      <section className="price-observations">{view.observations.length ? view.observations.map((item) => <article key={`${item.observationRef.resourceId}:${item.observationRef.revision}`} className={`is-${item.comparability}`}><header><div><strong>{item.market}</strong><span>{item.comparability} · {item.matchStatus}</span></div>{item.amount === null ? <b>未知，不以 0 代替</b> : <b>{item.quoteBasis.currency} {item.amount}</b>}</header><dl><div><dt>报价口径</dt><dd>{item.quoteBasis.basis} · {item.quoteBasis.quantity} {item.quoteBasis.unit}</dd></div><div><dt>税 / 运费</dt><dd>{item.quoteBasis.tax} / {item.quoteBasis.shipping}</dd></div><div><dt>新鲜度 / 许可</dt><dd>{item.freshness} / {item.license}</dd></div><div><dt>原始证据</dt><dd>{item.originalRefs.length + item.mergedOriginalRefs.length}</dd></div></dl><small>{item.quoteBasis.promotionCondition} · {new Date(item.observedAt).toLocaleString("zh-CN", { hour12: false })}</small></article>) : <p>当前没有可挂接的价格 Observation；可信空与 blocked/unknown 分开表达。</p>}</section>
      <aside className="media-studio-blockers"><h3>阻断与下一证据</h3>{view.blockers.length ? view.blockers.map((item) => <div key={item.code}><strong>{item.code}</strong><span>{item.dependency}</span><p>{item.requiredAction}</p></div>) : <p>本视图当前无 blocker。</p>}</aside>
    </section>
    <footer className="content-campaign-footnote"><span>租户 {response.tenant.orgId}/{response.tenant.projectId}</span><span>统一 cutoff {new Date(response.dataCutoff).toLocaleString("zh-CN", { hour12: false })}</span><span>repricing disabled</span></footer>
  </div> : null;
  return <section className="price-governance-page" aria-label="价格治理只读视图"><div className="content-campaign-toolbar price-governance-context-strip"><span>栖月汇 · 品牌 unknown · 核心 SKU unknown</span><span>数据参谋（owner 未绑定）+ 活动策划师 + 导购顾问</span><small>{response ? `监测策略 r${response.resourceRevision}` : "监测策略未验证"}</small><b>{response ? `${response.views.filter((item) => item.status === "blocked").length} 个视图待复核` : "待复核 unknown"}</b><button type="button" onClick={load}>刷新数据</button></div><AsyncStateBoundary state={stateFor(phase)} dataCutoff={response?.dataCutoff} action={phase === "failed" ? <button type="button" onClick={load}>重新读取</button> : undefined}>{content}</AsyncStateBoundary></section>;
}
