import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { PriceGovernanceViewResponse } from "../../api/ecommerceWorkshop";
import { PriceGovernancePage } from "./PriceGovernancePage";

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

const ids = ["governance", "competitor", "schedule"] as const;
const axes = ["collection", "match", "policy_case", "notification", "advice_handoff", "repricing"] as const;
const cutoff = "2026-08-24T08:00:00Z";
const blocked: PriceGovernanceViewResponse = { schemaVersion: "aos.ecommerce-workshop.price-governance-view/v1", tenant: { orgId: "org-org", projectId: "dev-project" }, resourceRevision: 1, evaluatedAt: cutoff, dataCutoff: cutoff, readiness: "degraded", views: ids.map((viewId) => { const blocker = { code: `PRICE_${viewId.toUpperCase()}_AUTHORITY_NOT_AVAILABLE`, dependency: viewId, requiredAction: "attach exact licensed authority" }; return { viewId, status: "blocked", resourceRevision: 1, dataCutoff: cutoff, readinessAxes: axes.map((axis) => axis === "repricing" ? { axis, status: "disabled", exactRef: null, blockers: [{ code: "PRICE_REPRICING_DISABLED", dependency: "R4", requiredAction: "complete specialized gate" }] } : { axis, status: "blocked", exactRef: null, blockers: [blocker] }), observations: [], authorityRefs: [], blockers: [blocker], countLedger: { input: 0, eligible: 0, excluded: 0, needsReview: 0, unknown: 0, deduplicated: 0 } }; }), page: { limit: 100, count: 0, hasMore: false, nextCursor: null } };
const remedyBlocked: PriceGovernanceViewResponse = { ...blocked, schemaVersion: "aos.ecommerce-workshop.price-governance-view/v2", remedyScenario: { schemaVersion: "aos.ecommerce-workshop.remedy-scenario/v1", status: "blocked", rootCaseRef: null, remedyBindingHash: null, evaluatedAt: cutoff, stages: (["price_observation", "match_decision", "price_case", "affected_orders", "operation_case", "customer_handoff", "contact_permit", "action_outcomes", "effect_review"] as const).map((stageId) => ({ stageId, status: "blocked", exactRefs: [], contribution: "等待 exact authority", blockers: [{ code: "PRICE_CASE_EXACT_ROOT_REQUIRED", dependency: "price-case", requiredAction: "provide exact root" }] })), ledger: { affectedOrdersExpected: 0, affectedOrdersObserved: 0, eligibleCustomersExpected: 0, eligibleCustomersObserved: 0, actionsExpected: 5, actionsReady: 0, actionsBlocked: 5, actionsUnknown: 0 }, outcomeAxes: (["repricing_applied", "refund_compensation_submitted", "customer_message_accepted", "operation_case_resolved", "effect_mature"] as const).map((axisId) => ({ axisId, status: "blocked", exactRef: null, blocker: { code: "PRICE_CASE_EXACT_ROOT_REQUIRED", dependency: "price-case", requiredAction: "provide exact root" } })), blockers: [{ code: "PRICE_CASE_EXACT_ROOT_REQUIRED", dependency: "price-case", requiredAction: "provide exact root" }], commands: { reprice: false, refundOrCompensate: false, sendMessage: false, resolveCase: false }, protectedContactResolved: false, externalEffectsAllowed: false } };

describe("PriceGovernancePage", () => {
  let host: HTMLDivElement; let root: Root;
  beforeEach(() => { host = document.createElement("div"); document.body.appendChild(host); root = createRoot(host); });
  afterEach(() => { act(() => root.unmount()); host.remove(); });
  it("展示三视图六轴且调价恒禁用", async () => { await act(async () => root.render(<PriceGovernancePage client={{ getPriceGovernanceView: vi.fn().mockResolvedValue(blocked) }} />)); expect(host.querySelectorAll('[role="tab"]')).toHaveLength(3); expect(host.querySelectorAll(".price-governance-readiness article")).toHaveLength(6); expect(host.textContent).toContain("调价禁用"); expect(host.textContent).toContain("写入口"); expect(Array.from(host.querySelectorAll("button")).map((item) => item.textContent).join(" ")).not.toMatch(/开始采集|批准策略|发送通知|执行调价/); });
  it("以诚实只读上下文对齐视觉稿状态条", async () => { await act(async () => root.render(<PriceGovernancePage client={{ getPriceGovernanceView: vi.fn().mockResolvedValue(blocked) }} />)); const strip = host.querySelector(".price-governance-context-strip"); expect(strip?.textContent).toContain("品牌 unknown"); expect(strip?.textContent).toContain("owner 未绑定"); expect(strip?.textContent).toContain("3 个视图待复核"); expect(strip?.querySelector("button")?.textContent).toBe("刷新数据"); expect(strip?.textContent).not.toMatch(/异常商品\s*[1-9]|自动调价|执行调价/); });
  it("贡献 authority 缺失时展示数据参谋链且不制造动作", async () => { await act(async () => root.render(<PriceGovernancePage client={{ getPriceGovernanceView: vi.fn().mockResolvedValue(blocked), getPriceResearchContributionView: vi.fn().mockRejectedValue(new Error("not installed")) }} />)); expect(host.querySelector('[aria-label="价格治理数字同事贡献"]')?.textContent).toContain("数据参谋主责价格调研"); expect(host.textContent).toContain("原子 Skill → Logic → 数字同事"); expect(host.textContent).toContain("外部效果：0"); expect(host.textContent).toContain("ResearchJob：0"); });
  it("四类价格处置分门展示且不生成执行按钮", async () => { await act(async () => root.render(<PriceGovernancePage client={{ getPriceGovernanceView: vi.fn().mockResolvedValue(blocked) }} />)); const card = host.querySelector('[aria-label="价格处置分门贡献"]'); expect(card?.querySelectorAll("article")).toHaveLength(4); expect(card?.textContent).toContain("内部建议"); expect(card?.textContent).toContain("外部通知"); expect(card?.textContent).toContain("模块交接"); expect(card?.textContent).toContain("专业门关闭 · executionAllowed=false"); expect(Array.from(card?.querySelectorAll("button") ?? [])).toHaveLength(0); });
  it("切换竞品视图不制造零价格", async () => { await act(async () => root.render(<PriceGovernancePage client={{ getPriceGovernanceView: vi.fn().mockResolvedValue(blocked) }} />)); const tab = Array.from(host.querySelectorAll<HTMLButtonElement>('[role="tab"]')).find((item) => item.textContent?.includes("竞品比价")); act(() => tab?.click()); expect(host.querySelector('[role="tabpanel"]')?.textContent).toContain("当前没有可挂接的价格 Observation"); });
  it("支持方向键沿三视图循环", async () => { await act(async () => root.render(<PriceGovernancePage client={{ getPriceGovernanceView: vi.fn().mockResolvedValue(blocked) }} />)); const tabs = host.querySelectorAll<HTMLButtonElement>('[role="tab"]'); act(() => tabs[0]?.dispatchEvent(new KeyboardEvent("keydown", { key: "ArrowRight", bubbles: true }))); const panel = host.querySelector<HTMLElement>('[role="tabpanel"]'); expect(panel?.getAttribute("aria-label")).toBe("竞品比价"); expect(tabs[1]?.tabIndex).toBe(0); expect(tabs[1]?.getAttribute("aria-controls")).toBe(panel?.id); expect(panel?.getAttribute("aria-labelledby")).toBe(tabs[1]?.id); });
  it("展示九阶段五独立结果轴且不解析联系方式或生成动作", async () => { await act(async () => root.render(<PriceGovernancePage client={{ getPriceGovernanceView: vi.fn().mockResolvedValue(remedyBlocked) }} />)); const card = host.querySelector('[aria-label="价格异常客户补救同链贡献"]'); expect(card?.querySelectorAll(".remedy-scenario-stages article")).toHaveLength(9); expect(card?.querySelectorAll(".remedy-scenario-axes article")).toHaveLength(5); expect(card?.textContent).toContain("原子 Skill → Logic 编排 → 数字同事绑定 → 工作台贡献"); expect(card?.textContent).toContain("受保护联系正文未解析"); expect(card?.textContent).toContain("客户消息发送 0"); expect(Array.from(card?.querySelectorAll("button") ?? [])).toHaveLength(0); });
});
