import { describe, expect, it } from "vitest";
import { OPERATIONAL_CAPABILITIES, evaluateWorkshopOperationalReleaseDecision, type OperationalReleaseEvidence } from "./workshopOperationalReleaseDecision";
import type { ExactReleaseRef } from "./workshopCumulativeReleaseGate";

const hash = "a".repeat(64); const commit = "b".repeat(40); const cutoff = "2026-08-26T08:00:00+08:00"; const evaluatedAt = "2026-08-26T08:30:00+08:00";
const ref = (resourceType = "EvidencePack", resourceId = "evidence"): ExactReleaseRef => ({ resourceType, resourceId, revision: 1, contentHash: hash });
const complete = (): OperationalReleaseEvidence => {
  const candidateRef = ref("ReleaseCandidateRevision", "candidate-1");
  return {
    evaluatedAt,
    candidate: { candidateRef, gitCommit: commit, gitClean: true, authorityRevision: "AOS-000281", artifactHash: hash, bundleRef: ref("BundleRevision", "bundle-1"), installationRef: ref("InstallationRevision", "installation-1"), openApiHash: hash, alembicHead: "w7_006", configHash: hash, cutoffAt: cutoff, immutable: true },
    cumulativeGate: { status: "ready", evidenceRef: ref("CumulativeGateEvidence", "w8-11"), candidateRef, cutoffAt: cutoff, exact: true },
    capabilities: OPERATIONAL_CAPABILITIES.map((capability) => ({ capabilityId: capability.id, risk: capability.risk, status: "ready", candidateRef, cutoffAt: cutoff, owner: `owner:${capability.id}`, approver: `approver:${capability.id}`, applicableGateIds: ["contract", "tenant"], evidenceRefs: [ref("EvidencePack", `${capability.id}:contract`), ref("EvidencePack", `${capability.id}:tenant`)], positiveRef: ref("PositiveEvidence", capability.id), negativeRef: ref("NegativeEvidence", capability.id), blockers: [], nextAllowedAction: "rollout-stage-1", notApplicable: null })),
    blockerCounts: { p0: 0, p1: 0, criticalVulnerabilities: 0, highVulnerabilities: 0, openIncidents: 0, unknownExternalActions: 0 },
    approval: { approvalRef: ref("ReleaseApproval", "approval-1"), candidateRef, decision: "go", capabilityIds: OPERATIONAL_CAPABILITIES.map((item) => item.id), maker: "user:maker", checker: "user:checker", approver: "user:approver", issuedAt: "2026-08-26T08:10:00+08:00", expiresAt: "2026-08-26T10:00:00+08:00", revokedAt: null, residualRiskAcceptanceRef: ref("ResidualRiskAcceptance", "risk-1") },
    rollout: { cohort: "internal-canary", audience: "approved operators", windowStart: "2026-08-26T09:00:00+08:00", windowEnd: "2026-08-26T10:00:00+08:00", observationMinutes: 30, stopConditions: ["critical-alert", "tenant-isolation-drift"], killOwner: "oncall:kill", rollbackOwner: "oncall:rollback", failForwardOwner: "oncall:forward", compensationOwner: "oncall:compensation", onCallOwner: "oncall:primary", supportPlanRef: ref("SupportPlan", "support-1"), auditRetentionRef: ref("AuditRetentionPolicy", "audit-1"), postReleaseVerificationRef: ref("VerificationPlan", "verify-1") },
    decisionReceipt: { receiptRef: ref("ReleaseDecisionReceipt", "decision-1"), candidateRef, decision: "go", cutoffAt: cutoff, exact: true },
  };
};

describe("evaluateWorkshopOperationalReleaseDecision", () => {
  it("fails closed without evidence and disables every release command", () => { const result = evaluateWorkshopOperationalReleaseDecision({}); expect(result.decision).toBe("no_go"); expect(result.capabilitiesBlocked).toBe(8); expect(Object.values(result.commands).every((value) => value === false)).toBe(true); });
  it("accepts one complete same-candidate operational contract", () => { expect(evaluateWorkshopOperationalReleaseDecision(complete())).toMatchObject({ decision: "go", capabilitiesReady: 8, capabilitiesBlocked: 0, candidateState: "exact", cumulativeState: "ready", approvalState: "valid", rolloutState: "complete", receiptState: "exact", blockerCodes: [] }); });
  it("requires each unique capability", () => { const evidence = complete(); evidence.capabilities = evidence.capabilities!.slice(1); evidence.capabilities.push({ ...evidence.capabilities[0], capabilityId: "content_campaign" }); const result = evaluateWorkshopOperationalReleaseDecision(evidence); expect(result.blockerCodes).toContain("OPERATIONAL_CAPABILITY_TASK_ORCHESTRATION_REQUIRED"); expect(result.blockerCodes).toContain("OPERATIONAL_CAPABILITY_CONTENT_CAMPAIGN_REQUIRED"); });
  it("rejects ready evidence from another candidate", () => { const evidence = complete(); evidence.capabilities![0].candidateRef = ref("ReleaseCandidateRevision", "other"); expect(evaluateWorkshopOperationalReleaseDecision(evidence).blockerCodes).toContain("OPERATIONAL_CAPABILITY_TASK_ORCHESTRATION_POSITIVE_EVIDENCE_REQUIRED"); });
  it("does not treat an undocumented N/A as skipped success", () => { const evidence = complete(); evidence.capabilities![1].status = "not_applicable"; evidence.capabilities![1].notApplicable = { scope: "", reason: "skip", owner: "", approver: "", evidenceRef: null }; expect(evaluateWorkshopOperationalReleaseDecision(evidence).blockerCodes).toContain("OPERATIONAL_CAPABILITY_CONTENT_CAMPAIGN_NOT_APPLICABLE_EVIDENCE_REQUIRED"); });
  it("propagates W8-11 RED", () => { const evidence = complete(); evidence.cumulativeGate!.status = "blocked"; expect(evaluateWorkshopOperationalReleaseDecision(evidence).blockerCodes).toContain("OPERATIONAL_W8_11_CUMULATIVE_GREEN_REQUIRED"); });
  it("blocks incidents vulnerabilities and unknown external actions", () => { const evidence = complete(); evidence.blockerCounts = { p0: 0, p1: 1, criticalVulnerabilities: 2, highVulnerabilities: 0, openIncidents: 1, unknownExternalActions: 3 }; expect(evaluateWorkshopOperationalReleaseDecision(evidence).blockerCodes).toContain("OPERATIONAL_RELEASE_BLOCKERS_OPEN"); });
  it("requires distinct maker-checker and a live non-revoked approval", () => { const evidence = complete(); evidence.approval!.checker = evidence.approval!.maker; evidence.approval!.revokedAt = "2026-08-26T08:20:00+08:00"; expect(evaluateWorkshopOperationalReleaseDecision(evidence).blockerCodes).toContain("OPERATIONAL_RELEASE_APPROVAL_REQUIRED"); });
  it("requires rollout stop rollback on-call and post-release plans", () => { const evidence = complete(); evidence.rollout!.stopConditions = []; evidence.rollout!.rollbackOwner = ""; evidence.rollout!.postReleaseVerificationRef = null; expect(evaluateWorkshopOperationalReleaseDecision(evidence).blockerCodes).toContain("OPERATIONAL_RELEASE_ROLLOUT_ROLLBACK_REQUIRED"); });
  it("requires exact same-candidate GO Decision Receipt", () => { const evidence = complete(); evidence.decisionReceipt!.decision = "no_go"; evidence.decisionReceipt!.exact = false; expect(evaluateWorkshopOperationalReleaseDecision(evidence).blockerCodes).toContain("OPERATIONAL_RELEASE_DECISION_RECEIPT_REQUIRED"); });
});
