import { apiGet, apiPost } from "../client";
import type { CompileStageTemplateInput, ConfirmMediaProfileInput, CreateArtifactRelationInput, CreateEvalContractInput, CreateImpactPreviewInput, CreateResponsibilityPlanInput, CreateReviewIssueInput, CreateStageTemplateInput, CreateTaskBriefInput, ProductionStartInput, ResolveReviewIssueInput, ReturnReviewIssueInput, ReviseEvalContractInput, ReviseImpactPreviewInput, ReviseResponsibilityPlanInput, ReviseStageTemplateInput } from "./contracts";
import { parseArtifactFamily, parseArtifactFamilyList, parseArtifactRelation, parseArtifactRelationList, parseBriefList, parseBundleList, parseContractMigrationDecisionList, parseEvalContract, parseEvalContractList, parseImpactPreview, parseImpactPreviewList, parseMediaGateProfileList, parseMediaGateSetList, parseProductionContextList, parseProductionStartDecision, parseProductionStartDecisionList, parseProfileConfirmation, parseProfileConfirmationList, parseProfileRecommendationList, parseResponsibilityPlan, parseResponsibilityPlanList, parseReturnDecision, parseReviewIssue, parseReviewIssueList, parseStageCompilation, parseStageTemplate, parseStageTemplateList, parseTaskBrief } from "./parser";
import { parseEvalContractDiff } from "./parser";

const ROOT="/v1/aip/production-contracts";
function keyHeaders(key:string){if(!key.trim())throw new Error("Idempotency-Key 不能为空");return{"Idempotency-Key":key};}
export const aipProductionContracts={
  async listProductionContexts(){return parseProductionContextList(await apiGet<unknown>(`${ROOT}/production-contexts`));},
  async listImpactPreviews(){return parseImpactPreviewList(await apiGet<unknown>(`${ROOT}/impact-previews`));},
  async getImpactPreview(previewId:string,revision?:number){return parseImpactPreview(await apiGet<unknown>(`${ROOT}/impact-previews/${encodeURIComponent(previewId)}${revision?`?revision=${revision}`:""}`));},
  async createImpactPreview(input:CreateImpactPreviewInput,key:string){return parseImpactPreview(await apiPost<unknown>(`${ROOT}/impact-previews`,input,keyHeaders(key)));},
  async reviseImpactPreview(previewId:string,input:ReviseImpactPreviewInput,key:string){return parseImpactPreview(await apiPost<unknown>(`${ROOT}/impact-previews/${encodeURIComponent(previewId)}/revisions`,input,keyHeaders(key)));},
  async freezeImpactPreview(previewId:string,expectedVersion:number,key:string){return parseImpactPreview(await apiPost<unknown>(`${ROOT}/impact-previews/${encodeURIComponent(previewId)}/freeze`,{expectedVersion},keyHeaders(key)));},
  async startProduction(input:ProductionStartInput,key:string){return parseProductionStartDecision(await apiPost<unknown>(`${ROOT}/production-runs/start`,input,keyHeaders(key)));},
  async listProductionStartDecisions(){return parseProductionStartDecisionList(await apiGet<unknown>(`${ROOT}/production-start-decisions`));},
  async getProductionStartDecision(decisionId:string){return parseProductionStartDecision(await apiGet<unknown>(`${ROOT}/production-start-decisions/${encodeURIComponent(decisionId)}`));},
  async listBriefs(){return parseBriefList(await apiGet<unknown>(`${ROOT}/task-briefs`));},
  async listBundles(){return parseBundleList(await apiGet<unknown>(`${ROOT}/evidence-bundles`));},
  async createBrief(input:CreateTaskBriefInput,key:string){return parseTaskBrief(await apiPost<unknown>(`${ROOT}/task-briefs`,input,keyHeaders(key)));},
  async freezeBrief(briefId:string,expectedVersion:number,key:string){return parseTaskBrief(await apiPost<unknown>(`${ROOT}/task-briefs/${encodeURIComponent(briefId)}/freeze`,{expectedVersion},keyHeaders(key)));},
  async listEvalContracts(){return parseEvalContractList(await apiGet<unknown>(`${ROOT}/eval-contracts`));},
  async getEvalContract(contractId:string,revision?:number){return parseEvalContract(await apiGet<unknown>(`${ROOT}/eval-contracts/${encodeURIComponent(contractId)}${revision?`?revision=${revision}`:""}`));},
  async diffEvalContract(contractId:string,fromRevision:number,toRevision:number){if(fromRevision<1||toRevision<1||fromRevision===toRevision)throw new Error("Diff 修订必须不同且大于 0");return parseEvalContractDiff(await apiGet<unknown>(`${ROOT}/eval-contracts/${encodeURIComponent(contractId)}/diff?fromRevision=${fromRevision}&toRevision=${toRevision}`));},
  async createEvalContract(input:CreateEvalContractInput,key:string){return parseEvalContract(await apiPost<unknown>(`${ROOT}/eval-contracts`,input,keyHeaders(key)));},
  async reviseEvalContract(contractId:string,input:ReviseEvalContractInput,key:string){return parseEvalContract(await apiPost<unknown>(`${ROOT}/eval-contracts/${encodeURIComponent(contractId)}/revisions`,input,keyHeaders(key)));},
  async freezeEvalContract(contractId:string,expectedVersion:number,key:string){return parseEvalContract(await apiPost<unknown>(`${ROOT}/eval-contracts/${encodeURIComponent(contractId)}/freeze`,{expectedVersion},keyHeaders(key)));},
  async listResponsibilityPlans(){return parseResponsibilityPlanList(await apiGet<unknown>(`${ROOT}/responsibility-plans`));},
  async listProfileRecommendations(){return parseProfileRecommendationList(await apiGet<unknown>(`${ROOT}/responsibility-profile/recommendations`));},
  async listProfileConfirmations(){return parseProfileConfirmationList(await apiGet<unknown>(`${ROOT}/responsibility-profile/confirmations`));},
  async confirmMediaProfile(input:ConfirmMediaProfileInput,key:string,recommendationEtag:string){if(!recommendationEtag.trim())throw new Error("If-Match 不能为空");return parseProfileConfirmation(await apiPost<unknown>(`${ROOT}/responsibility-profile/media-confirmations`,input,{...keyHeaders(key),"If-Match":recommendationEtag}));},
  async getResponsibilityPlan(planId:string,revision?:number){return parseResponsibilityPlan(await apiGet<unknown>(`${ROOT}/responsibility-plans/${encodeURIComponent(planId)}${revision?`?revision=${revision}`:""}`));},
  async createResponsibilityPlan(input:CreateResponsibilityPlanInput,key:string){return parseResponsibilityPlan(await apiPost<unknown>(`${ROOT}/responsibility-plans`,input,keyHeaders(key)));},
  async reviseResponsibilityPlan(planId:string,input:ReviseResponsibilityPlanInput,key:string){return parseResponsibilityPlan(await apiPost<unknown>(`${ROOT}/responsibility-plans/${encodeURIComponent(planId)}/revisions`,input,keyHeaders(key)));},
  async freezeResponsibilityPlan(planId:string,expectedVersion:number,key:string){return parseResponsibilityPlan(await apiPost<unknown>(`${ROOT}/responsibility-plans/${encodeURIComponent(planId)}/freeze`,{expectedVersion},keyHeaders(key)));},
  async listStageTemplates(){return parseStageTemplateList(await apiGet<unknown>(`${ROOT}/stage-templates`));},
  async getStageTemplate(templateId:string,revision?:number){return parseStageTemplate(await apiGet<unknown>(`${ROOT}/stage-templates/${encodeURIComponent(templateId)}${revision?`?revision=${revision}`:""}`));},
  async createStageTemplate(input:CreateStageTemplateInput,key:string){return parseStageTemplate(await apiPost<unknown>(`${ROOT}/stage-templates`,input,keyHeaders(key)));},
  async reviseStageTemplate(templateId:string,input:ReviseStageTemplateInput,key:string){return parseStageTemplate(await apiPost<unknown>(`${ROOT}/stage-templates/${encodeURIComponent(templateId)}/revisions`,input,keyHeaders(key)));},
  async freezeStageTemplate(templateId:string,expectedVersion:number,key:string){return parseStageTemplate(await apiPost<unknown>(`${ROOT}/stage-templates/${encodeURIComponent(templateId)}/freeze`,{expectedVersion},keyHeaders(key)));},
  async compileStageTemplate(templateId:string,input:CompileStageTemplateInput,key:string){return parseStageCompilation(await apiPost<unknown>(`${ROOT}/stage-templates/${encodeURIComponent(templateId)}/compile`,input,keyHeaders(key)));},
  async listArtifactRelations(){return parseArtifactRelationList(await apiGet<unknown>(`${ROOT}/artifact-relations`));},
  async createArtifactRelation(input:CreateArtifactRelationInput,key:string){return parseArtifactRelation(await apiPost<unknown>(`${ROOT}/artifact-relations`,input,keyHeaders(key)));},
  async listArtifactFamilies(){return parseArtifactFamilyList(await apiGet<unknown>(`${ROOT}/artifact-families`));},
  async getArtifactFamily(familyId:string){return parseArtifactFamily(await apiGet<unknown>(`${ROOT}/artifact-families/${encodeURIComponent(familyId)}`));},
  async listMediaGateProfiles(){return parseMediaGateProfileList(await apiGet<unknown>(`${ROOT}/media-gate-profiles`));},
  async listMediaGateSets(){return parseMediaGateSetList(await apiGet<unknown>(`${ROOT}/media-gate-sets`));},
  async listContractMigrationDecisions(){return parseContractMigrationDecisionList(await apiGet<unknown>(`${ROOT}/contract-migration-decisions`));},
  async listReviewIssues(){return parseReviewIssueList(await apiGet<unknown>(`${ROOT}/review-issues`));},
  async getReviewIssue(issueId:string){return parseReviewIssue(await apiGet<unknown>(`${ROOT}/review-issues/${encodeURIComponent(issueId)}`));},
  async createReviewIssue(input:CreateReviewIssueInput,key:string){return parseReviewIssue(await apiPost<unknown>(`${ROOT}/review-issues`,input,keyHeaders(key)));},
  async resolveReviewIssue(issueId:string,input:ResolveReviewIssueInput,key:string){return parseReviewIssue(await apiPost<unknown>(`${ROOT}/review-issues/${encodeURIComponent(issueId)}/resolve`,input,keyHeaders(key)));},
  async returnReviewIssue(issueId:string,input:ReturnReviewIssueInput,key:string){return parseReturnDecision(await apiPost<unknown>(`${ROOT}/review-issues/${encodeURIComponent(issueId)}/return`,input,keyHeaders(key)));},
};
export * from "./contracts";
