import type { ActionProposalExactRef, ArtifactFamily, ArtifactFamilyCandidateGroup, ArtifactFamilyCandidateStatus, ArtifactFamilyListResponse, ArtifactFamilyMember, ArtifactFamilyRole, ArtifactFamilySelectionDecision, ArtifactRelation, ArtifactRelationListResponse, ArtifactRelationType, AssigneeKind, ContractBlocker, ContractCoverage, ContractLifecycle, ContractReadiness, EvalContractListResponse, EvalContractRevision, EvidenceBundleListResponse, EvidenceBundleRevision, ExactArtifactRef, ExactRevisionRef, ImpactAssessment, ImpactDimension, ImpactPreviewListResponse, ImpactPreviewRevision, ImpactQuality, MergeDecision, MutableAuthorityRef, ProductionContextListResponse, ProductionContextRevision, ProductionStartDecision, ProductionStartDecisionListResponse, ProductionStartStatus, ProfileConfirmationListResponse, ProfileConfirmationReceipt, ProfileRecommendationListResponse, ProfileRecommendationRevision, ProjectedCostRange, ProjectedDurationRange, ResourceRef, ResponsibilityPlanListResponse, ResponsibilityPlanRevision, ResponsibilityProfile, ResponsibilitySlot, ReturnDecision, ReviewIssue, ReviewIssueListResponse, ReviewIssueStatus, ReviewSeverity, StageCompilationResult, StageDefinition, StageTemplateListResponse, StageTemplateRevision, TaskBriefListResponse, TaskBriefRevision, Tenant } from "./contracts";
import type { EvalContractDiff } from "./contracts";

function object(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} 必须是对象`); return value as Record<string, unknown>; }
function string(value: unknown, label: string): string { if (typeof value !== "string" || !value) throw new Error(`${label} 必须是非空字符串`); return value; }
function number(value: unknown, label: string): number { if (typeof value !== "number" || !Number.isInteger(value) || value < 0) throw new Error(`${label} 必须是非负整数`); return value; }
function sha(value: unknown, label: string): string { const result=string(value,label); if (!/^[0-9a-f]{64}$/.test(result)) throw new Error(`${label} 非 SHA-256`); return result; }
function array(value: unknown, label: string): unknown[] { if (!Array.isArray(value)) throw new Error(`${label} 必须是数组`); return value; }
function tenant(value: unknown): Tenant { const raw=object(value,"tenant"); return {orgId:string(raw.orgId,"tenant.orgId"),projectId:string(raw.projectId,"tenant.projectId")}; }
function resource(value: unknown, label: string): ResourceRef { const raw=object(value,label); const revision=raw.revision; if (revision!==null && typeof revision!=="string") throw new Error(`${label}.revision 必须是字符串或 null`); return {resourceType:string(raw.resourceType,`${label}.resourceType`),resourceId:string(raw.resourceId,`${label}.resourceId`),revision,authority:string(raw.authority,`${label}.authority`)}; }
function exact(value: unknown, label: string): ExactRevisionRef { const raw=object(value,label); const revision=number(raw.revision,`${label}.revision`); if (revision<1) throw new Error(`${label}.revision 必须大于 0`); return {resourceType:string(raw.resourceType,`${label}.resourceType`),resourceId:string(raw.resourceId,`${label}.resourceId`),revision,contentHash:sha(raw.contentHash,`${label}.contentHash`)}; }
function records(value: unknown, label: string): Record<string, unknown>[] { return array(value,label).map((item,index)=>object(item,`${label}[${index}]`)); }
function nullableExact(value: unknown, label: string): ExactRevisionRef|null { return value===null ? null : exact(value,label); }
function enumValue<T extends string>(value: unknown,label:string,values:readonly T[]):T { const result=string(value,label) as T; if(!values.includes(result)) throw new Error(`${label} 非法`); return result; }
function strings(value:unknown,label:string):string[] { return array(value,label).map((item,index)=>string(item,`${label}[${index}]`)); }
function blockers(value:unknown):ContractBlocker[] { return array(value,"blockers").map((item,index)=>{const raw=object(item,`blockers[${index}]`);return{code:string(raw.code,`blockers[${index}].code`),message:string(raw.message,`blockers[${index}].message`),resourceRef:nullableExact(raw.resourceRef,`blockers[${index}].resourceRef`)}}); }
function stringRecord(value:unknown,label:string):Record<string,string> { const raw=object(value,label); return Object.fromEntries(Object.entries(raw).map(([key,item])=>[key,string(item,`${label}.${key}`)])); }
function thresholdRecord(value:unknown):Record<string,number> { const raw=object(value,"severityThresholds"); if(!Object.keys(raw).length) throw new Error("severityThresholds 不能为空"); return Object.fromEntries(Object.entries(raw).map(([key,item])=>{if(typeof item!=="number"||item<0||item>1) throw new Error(`severityThresholds.${key} 必须在 0..1`);return[key,item]})); }
function nullableString(value:unknown,label:string):string|null { return value===null ? null : string(value,label); }
function nullableMoney(value:unknown,label:string):string|null {if(value===null)return null;const result=typeof value==="number"?String(value):string(value,label);if(!/^\d+(?:\.\d+)?$/.test(result))throw new Error(`${label} 必须是非负金额`);return result;}
function exactArtifact(value:unknown,label:string):ExactArtifactRef { const raw=object(value,label);return{artifactId:string(raw.artifactId,`${label}.artifactId`),contentHash:sha(raw.contentHash,`${label}.contentHash`) }; }
function nullableResource(value:unknown,label:string):ResourceRef|null { return value===null ? null : resource(value,label); }
function mutable(value:unknown,label:string):MutableAuthorityRef { const raw=object(value,label),version=number(raw.version,`${label}.version`);if(version<1)throw new Error(`${label}.version 必须大于 0`);return{resourceType:string(raw.resourceType,`${label}.resourceType`),resourceId:string(raw.resourceId,`${label}.resourceId`),version}; }
function proposal(value:unknown,label:string):ActionProposalExactRef { const raw=object(value,label),version=number(raw.version,`${label}.version`);if(version<1)throw new Error(`${label}.version 必须大于 0`);return{proposalId:string(raw.proposalId,`${label}.proposalId`),version,proposalHash:sha(raw.proposalHash,`${label}.proposalHash`)}; }
function profile(value:unknown,label:string):ResponsibilityProfile{return enumValue<ResponsibilityProfile>(value,label,["LITE","STANDARD","FULL"]);}
function projectedCost(value:unknown,label:string):ProjectedCostRange {const raw=object(value,label),unknownCodes=strings(raw.unknownCodes,`${label}.unknownCodes`),lowerAmount=nullableMoney(raw.lowerAmount,`${label}.lowerAmount`),upperAmount=nullableMoney(raw.upperAmount,`${label}.upperAmount`),confidence=enumValue<ProjectedCostRange["confidence"]>(raw.confidence,`${label}.confidence`,["high","medium","low","unknown"]);if(unknownCodes.length&&(lowerAmount!==null||upperAmount!==null||confidence!=="unknown"))throw new Error(`${label} 未知成本不得伪装为数值`);if(!unknownCodes.length&&(lowerAmount===null||upperAmount===null||confidence==="unknown"||Number(upperAmount)<Number(lowerAmount)))throw new Error(`${label} 已知成本区间非法`);return{profile:profile(raw.profile,`${label}.profile`),currency:string(raw.currency,`${label}.currency`),componentCount:number(raw.componentCount,`${label}.componentCount`),priceSnapshotRefs:array(raw.priceSnapshotRefs,`${label}.priceSnapshotRefs`).map((item,index)=>exact(item,`${label}.priceSnapshotRefs[${index}]`)),lowerAmount,upperAmount,assumptions:strings(raw.assumptions,`${label}.assumptions`),unknownCodes,confidence,expiresAt:string(raw.expiresAt,`${label}.expiresAt`)};}
function projectedDuration(value:unknown,label:string):ProjectedDurationRange {const raw=object(value,label),unknownCodes=strings(raw.unknownCodes,`${label}.unknownCodes`),lower=raw.lowerSeconds===null?null:number(raw.lowerSeconds,`${label}.lowerSeconds`),upper=raw.upperSeconds===null?null:number(raw.upperSeconds,`${label}.upperSeconds`);if(unknownCodes.length&&(lower!==null||upper!==null))throw new Error(`${label} 未知时长不得伪装为数值`);if(!unknownCodes.length&&(lower===null||upper===null||upper<lower))throw new Error(`${label} 已知时长区间非法`);return{lowerSeconds:lower,upperSeconds:upper,assumptions:strings(raw.assumptions,`${label}.assumptions`),unknownCodes};}

export function parseProfileRecommendation(value:unknown):ProfileRecommendationRevision {const raw=object(value,"ProfileRecommendationRevision"),revision=number(raw.revision,"revision"),candidateRaw=object(raw.candidateTemplateRefs,"candidateTemplateRefs"),candidateTemplateRefs={LITE:exact(candidateRaw.LITE,"candidateTemplateRefs.LITE"),STANDARD:exact(candidateRaw.STANDARD,"candidateTemplateRefs.STANDARD"),FULL:exact(candidateRaw.FULL,"candidateTemplateRefs.FULL")};if(revision<1)throw new Error("recommendation revision 必须大于 0");return{tenant:tenant(raw.tenant),recommendationId:string(raw.recommendationId,"recommendationId"),revision,subjectRef:exact(raw.subjectRef,"subjectRef"),recommendedProfile:profile(raw.recommendedProfile,"recommendedProfile"),candidateTemplateRefs,selectedTemplateRef:exact(raw.selectedTemplateRef,"selectedTemplateRef"),policyRef:exact(raw.policyRef,"policyRef"),riskLevel:number(raw.riskLevel,"riskLevel"),channelCount:number(raw.channelCount,"channelCount"),reasonCodes:strings(raw.reasonCodes,"reasonCodes"),unknownCodes:strings(raw.unknownCodes,"unknownCodes"),dependencyRefs:array(raw.dependencyRefs,"dependencyRefs").map((item,index)=>exact(item,`dependencyRefs[${index}]`)),projectedCostRanges:array(raw.projectedCostRanges,"projectedCostRanges").map((item,index)=>projectedCost(item,`projectedCostRanges[${index}]`)),projectedDuration:raw.projectedDuration===null?null:projectedDuration(raw.projectedDuration,"projectedDuration"),assumptions:strings(raw.assumptions,"assumptions"),confidence:enumValue<ProfileRecommendationRevision["confidence"]>(raw.confidence,"confidence",["high","medium","low","unknown"]),readiness:enumValue<ProfileRecommendationRevision["readiness"]>(raw.readiness,"readiness",["ready","blocked","stale","unknown"]),blockers:strings(raw.blockers,"blockers"),snapshotHash:sha(raw.snapshotHash,"snapshotHash"),contentHash:sha(raw.contentHash,"contentHash"),expiresAt:string(raw.expiresAt,"expiresAt"),createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};}
export function parseProfileRecommendationList(value:unknown):ProfileRecommendationListResponse {const raw=object(value,"ProfileRecommendationListResponse"),items=array(raw.items,"items").map(parseProfileRecommendation),count=number(raw.count,"count");if(count!==items.length)throw new Error("ProfileRecommendation count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}
export function parseProfileConfirmation(value:unknown):ProfileConfirmationReceipt {const raw=object(value,"ProfileConfirmationReceipt"),revision=number(raw.recommendationRevision,"recommendationRevision");if(revision<1)throw new Error("recommendationRevision 必须大于 0");return{tenant:tenant(raw.tenant),confirmationId:string(raw.confirmationId,"confirmationId"),recommendationId:string(raw.recommendationId,"recommendationId"),recommendationRevision:revision,recommendationHash:sha(raw.recommendationHash,"recommendationHash"),selectedProfile:profile(raw.selectedProfile,"selectedProfile"),selectedTemplateRef:exact(raw.selectedTemplateRef,"selectedTemplateRef"),policyRef:exact(raw.policyRef,"policyRef"),recommendationEtag:raw.recommendationEtag===null?null:sha(raw.recommendationEtag,"recommendationEtag"),idempotencyKey:nullableString(raw.idempotencyKey,"idempotencyKey"),selectedProjectedCostRanges:array(raw.selectedProjectedCostRanges,"selectedProjectedCostRanges").map((item,index)=>projectedCost(item,`selectedProjectedCostRanges[${index}]`)),actor:string(raw.actor,"actor"),reason:string(raw.reason,"reason"),contentHash:sha(raw.contentHash,"contentHash"),createdAt:string(raw.createdAt,"createdAt")};}
export function parseProfileConfirmationList(value:unknown):ProfileConfirmationListResponse {const raw=object(value,"ProfileConfirmationListResponse"),items=array(raw.items,"items").map(parseProfileConfirmation),count=number(raw.count,"count");if(count!==items.length)throw new Error("ProfileConfirmation count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}

export function parseTaskBrief(value: unknown): TaskBriefRevision {
  const raw=object(value,"TaskBriefRevision"); const lifecycle=string(raw.lifecycle,"lifecycle") as TaskBriefRevision["lifecycle"];
  if (!["draft","frozen","withdrawn","superseded"].includes(lifecycle)) throw new Error("lifecycle 非法");
  const revision=number(raw.revision,"revision"), version=number(raw.version,"version"); if (revision<1||version<1) throw new Error("revision/version 必须大于 0");
  return {tenant:tenant(raw.tenant),briefId:string(raw.briefId,"briefId"),taskId:string(raw.taskId,"taskId"),revision,version,briefType:string(raw.briefType,"briefType"),schemaRef:resource(raw.schemaRef,"schemaRef"),spec:object(raw.spec,"spec"),contentHash:sha(raw.contentHash,"contentHash"),lifecycle,createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};
}

export function parseBriefList(value: unknown): TaskBriefListResponse { const raw=object(value,"TaskBriefListResponse"), items=array(raw.items,"items").map(parseTaskBrief), count=number(raw.count,"count"); if(count!==items.length) throw new Error("Brief count 与 items 不一致"); return {tenant:tenant(raw.tenant),items,count}; }

function parseBundle(value: unknown): EvidenceBundleRevision {
  const raw=object(value,"EvidenceBundleRevision"), coverage=string(raw.coverage,"coverage") as EvidenceBundleRevision["coverage"], freshness=string(raw.freshness,"freshness") as EvidenceBundleRevision["freshness"];
  if(!["complete","partial","blocked","unknown"].includes(coverage)||!["fresh","stale","blocked","unknown"].includes(freshness)||raw.lifecycle!=="frozen") throw new Error("EvidenceBundle 状态非法");
  return {tenant:tenant(raw.tenant),bundleId:string(raw.bundleId,"bundleId"),revision:number(raw.revision,"revision"),briefRef:exact(raw.briefRef,"briefRef"),subjectRefs:array(raw.subjectRefs,"subjectRefs").map((item,index)=>resource(item,`subjectRefs[${index}]`)),cutoffAt:string(raw.cutoffAt,"cutoffAt"),itemRefs:array(raw.itemRefs,"itemRefs").map((item,index)=>exact(item,`itemRefs[${index}]`)),coverage,missing:records(raw.missing,"missing"),conflicts:records(raw.conflicts,"conflicts"),uncertainties:records(raw.uncertainties,"uncertainties"),freshness,marking:array(raw.marking,"marking").map((item,index)=>string(item,`marking[${index}]`)),licenseSummary:object(raw.licenseSummary,"licenseSummary"),contentHash:sha(raw.contentHash,"contentHash"),lifecycle:"frozen",createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt"),revoked:raw.revoked===true,revokeReason:raw.revokeReason===null||raw.revokeReason===undefined?null:string(raw.revokeReason,"revokeReason")};
}

export function parseBundleList(value: unknown): EvidenceBundleListResponse { const raw=object(value,"EvidenceBundleListResponse"), items=array(raw.items,"items").map(parseBundle), count=number(raw.count,"count"); if(count!==items.length) throw new Error("Bundle count 与 items 不一致"); return {tenant:tenant(raw.tenant),items,count}; }

export function parseEvalContract(value:unknown):EvalContractRevision {
  const raw=object(value,"EvalContractRevision"), revision=number(raw.revision,"revision"), version=number(raw.version,"version"); if(revision<1||version<1) throw new Error("revision/version 必须大于 0");
  return {tenant:tenant(raw.tenant),contractId:string(raw.contractId,"contractId"),revision,version,suiteRef:exact(raw.suiteRef,"suiteRef"),publicationRef:nullableExact(raw.publicationRef,"publicationRef"),releaseGateRef:nullableExact(raw.releaseGateRef,"releaseGateRef"),artifactSchemaRef:resource(raw.artifactSchemaRef,"artifactSchemaRef"),severityThresholds:thresholdRecord(raw.severityThresholds),gatePolicy:object(raw.gatePolicy,"gatePolicy"),returnMapping:stringRecord(raw.returnMapping,"returnMapping"),overridePolicy:object(raw.overridePolicy,"overridePolicy"),contentHash:sha(raw.contentHash,"contentHash"),lifecycle:enumValue<ContractLifecycle>(raw.lifecycle,"lifecycle",["draft","frozen","withdrawn","superseded"]),readiness:enumValue<ContractReadiness>(raw.readiness,"readiness",["ready","blocked","stale","unknown"]),blockers:blockers(raw.blockers),createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};
}
export function parseEvalContractList(value:unknown):EvalContractListResponse { const raw=object(value,"EvalContractListResponse"),items=array(raw.items,"items").map(parseEvalContract),count=number(raw.count,"count");if(count!==items.length)throw new Error("EvalContract count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count}; }
export function parseEvalContractDiff(value:unknown):EvalContractDiff {
  const raw=object(value,"EvalContractDiff"),fromRevision=number(raw.fromRevision,"fromRevision"),toRevision=number(raw.toRevision,"toRevision");
  if(fromRevision<1||toRevision<1||fromRevision===toRevision)throw new Error("EvalContract Diff 修订必须不同且大于 0");
  const changes=array(raw.changes,"changes").map((item,index)=>{const change=object(item,`changes[${index}]`);return{field:string(change.field,`changes[${index}].field`),label:string(change.label,`changes[${index}].label`),before:change.before,after:change.after,impact:string(change.impact,`changes[${index}].impact`)}});
  const changeCount=number(raw.changeCount,"changeCount");if(changeCount!==changes.length)throw new Error("EvalContract Diff changeCount 与 changes 不一致");
  return{tenant:tenant(raw.tenant),contractId:string(raw.contractId,"contractId"),fromRevision,toRevision,fromContentHash:sha(raw.fromContentHash,"fromContentHash"),toContentHash:sha(raw.toContentHash,"toContentHash"),changes,changeCount,summary:string(raw.summary,"summary")};
}

function assignee(value:unknown,label:string){const raw=object(value,label),version=number(raw.version,`${label}.version`);if(version<1)throw new Error(`${label}.version 必须大于 0`);return{kind:enumValue<AssigneeKind>(raw.kind,`${label}.kind`,["agent_instance","human_principal","tool_binding","provider_capability_binding"]),resourceId:string(raw.resourceId,`${label}.resourceId`),version}};
function slot(value:unknown,index:number):ResponsibilitySlot {const label=`slots[${index}]`,raw=object(value,label),requiredCapabilityIds=strings(raw.requiredCapabilityIds,`${label}.requiredCapabilityIds`);if(!requiredCapabilityIds.length)throw new Error(`${label}.requiredCapabilityIds 不能为空`);return{slotId:string(raw.slotId,`${label}.slotId`),responsibilityType:string(raw.responsibilityType,`${label}.responsibilityType`),requiredCapabilityIds,inputSchemaRef:resource(raw.inputSchemaRef,`${label}.inputSchemaRef`),outputSchemaRef:resource(raw.outputSchemaRef,`${label}.outputSchemaRef`),gateRefs:array(raw.gateRefs,`${label}.gateRefs`).map((item,i)=>exact(item,`${label}.gateRefs[${i}]`)),returnStage:string(raw.returnStage,`${label}.returnStage`),assignee:assignee(raw.assignee,`${label}.assignee`)}};
function merge(value:unknown,index:number):MergeDecision {const label=`mergeDecisions[${index}]`,raw=object(value,label);return{sourceSlotIds:strings(raw.sourceSlotIds,`${label}.sourceSlotIds`),targetSlotId:string(raw.targetSlotId,`${label}.targetSlotId`),reason:string(raw.reason,`${label}.reason`),mergedResponsibilityTypes:strings(raw.mergedResponsibilityTypes,`${label}.mergedResponsibilityTypes`)}};
export function parseResponsibilityPlan(value:unknown):ResponsibilityPlanRevision {const raw=object(value,"ResponsibilityPlanRevision"),revision=number(raw.revision,"revision"),version=number(raw.version,"version"),rawSlots=array(raw.slots,"slots"),profileRecommendationRef=raw.profileRecommendationRef===undefined?null:nullableExact(raw.profileRecommendationRef,"profileRecommendationRef"),profileConfirmationId=raw.profileConfirmationId===undefined?null:nullableString(raw.profileConfirmationId,"profileConfirmationId"),mergePolicyRef=raw.mergePolicyRef===undefined?null:nullableExact(raw.mergePolicyRef,"mergePolicyRef"),mergeDecisionReceiptIds=raw.mergeDecisionReceiptIds===undefined?[]:strings(raw.mergeDecisionReceiptIds,"mergeDecisionReceiptIds");if(revision<1||version<1)throw new Error("revision/version 必须大于 0");if(!rawSlots.length)throw new Error("slots 不能为空");if(profileRecommendationRef)requireExactType(profileRecommendationRef,"ProfileRecommendationRevision","profileRecommendationRef");if(mergePolicyRef)requireExactType(mergePolicyRef,"MergePolicyRevision","mergePolicyRef");if(mergeDecisionReceiptIds.length!==new Set(mergeDecisionReceiptIds).size)throw new Error("mergeDecisionReceiptIds 必须唯一");return{tenant:tenant(raw.tenant),planId:string(raw.planId,"planId"),revision,version,profile:string(raw.profile,"profile"),templateRef:exact(raw.templateRef,"templateRef"),slots:rawSlots.map(slot),mergeDecisions:array(raw.mergeDecisions,"mergeDecisions").map(merge),profileRecommendationRef,profileConfirmationId,mergePolicyRef,mergeDecisionReceiptIds,coverage:enumValue<ContractCoverage>(raw.coverage,"coverage",["complete","partial","blocked","unknown"]),uncoveredSlots:strings(raw.uncoveredSlots,"uncoveredSlots"),contentHash:sha(raw.contentHash,"contentHash"),lifecycle:enumValue<ContractLifecycle>(raw.lifecycle,"lifecycle",["draft","frozen","withdrawn","superseded"]),readiness:enumValue<ContractReadiness>(raw.readiness,"readiness",["ready","blocked","stale","unknown"]),blockers:blockers(raw.blockers),createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};}
export function parseResponsibilityPlanList(value:unknown):ResponsibilityPlanListResponse {const raw=object(value,"ResponsibilityPlanListResponse"),items=array(raw.items,"items").map(parseResponsibilityPlan),count=number(raw.count,"count");if(count!==items.length)throw new Error("ResponsibilityPlan count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}

function parseStage(value:unknown,index:number):StageDefinition {
  const label=`stages[${index}]`,raw=object(value,label),applicabilityRaw=object(raw.applicability,`${label}.applicability`);
  const kind=enumValue<"always"|"profile_in">(applicabilityRaw.kind,`${label}.applicability.kind`,["always","profile_in"]);
  const profiles=strings(applicabilityRaw.profiles,`${label}.applicability.profiles`);
  if((kind==="always"&&profiles.length)||(kind==="profile_in"&&!profiles.length))throw new Error(`${label}.applicability 非受控谓词`);
  const requiredSlotIds=strings(raw.requiredSlotIds,`${label}.requiredSlotIds`);if(!requiredSlotIds.length)throw new Error(`${label}.requiredSlotIds 不能为空`);
  return{stageId:string(raw.stageId,`${label}.stageId`),title:string(raw.title,`${label}.title`),dependsOn:strings(raw.dependsOn,`${label}.dependsOn`),applicability:{kind,profiles},requiredSlotIds,inputSchemaRef:resource(raw.inputSchemaRef,`${label}.inputSchemaRef`),outputSchemaRef:resource(raw.outputSchemaRef,`${label}.outputSchemaRef`),gateRefs:array(raw.gateRefs,`${label}.gateRefs`).map((item,i)=>exact(item,`${label}.gateRefs[${i}]`)),checkpointPolicy:object(raw.checkpointPolicy,`${label}.checkpointPolicy`),retryPolicy:object(raw.retryPolicy,`${label}.retryPolicy`),compensationPolicy:object(raw.compensationPolicy,`${label}.compensationPolicy`)};
}
export function parseStageTemplate(value:unknown):StageTemplateRevision {
  const raw=object(value,"StageTemplateRevision"),revision=number(raw.revision,"revision"),version=number(raw.version,"version"),lifecycle=enumValue<ContractLifecycle>(raw.lifecycle,"lifecycle",["draft","frozen","withdrawn","superseded"]),sealedBy=nullableString(raw.sealedBy,"sealedBy"),sealedAt=nullableString(raw.sealedAt,"sealedAt"),sealHash=raw.sealHash===null?null:sha(raw.sealHash,"sealHash"),rawStages=array(raw.stages,"stages");
  if(revision<1||version<1||!rawStages.length)throw new Error("StageTemplate revision/version/stages 非法");
  const sealed=sealedBy!==null&&sealedAt!==null&&sealHash!==null;if((lifecycle==="frozen")!==sealed)throw new Error("StageTemplate seal 与 lifecycle 不一致");
  return{tenant:tenant(raw.tenant),templateId:string(raw.templateId,"templateId"),revision,version,profile:string(raw.profile,"profile"),sourceBundleRef:exact(raw.sourceBundleRef,"sourceBundleRef"),stages:rawStages.map(parseStage),contentHash:sha(raw.contentHash,"contentHash"),lifecycle,sealedBy,sealedAt,sealHash,readiness:enumValue<ContractReadiness>(raw.readiness,"readiness",["ready","blocked","stale","unknown"]),blockers:blockers(raw.blockers),createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};
}
export function parseStageTemplateList(value:unknown):StageTemplateListResponse {const raw=object(value,"StageTemplateListResponse"),items=array(raw.items,"items").map(parseStageTemplate),count=number(raw.count,"count");if(count!==items.length)throw new Error("StageTemplate count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}
export function parseStageCompilation(value:unknown):StageCompilationResult {const raw=object(value,"StageCompilationResult"),normalizedStageIds=strings(raw.normalizedStageIds,"normalizedStageIds"),applicableStageIds=strings(raw.applicableStageIds,"applicableStageIds"),notApplicableStageIds=strings(raw.notApplicableStageIds,"notApplicableStageIds");if(new Set(normalizedStageIds).size!==normalizedStageIds.length||new Set([...applicableStageIds,...notApplicableStageIds]).size!==normalizedStageIds.length)throw new Error("StageCompilation stage 集合非法");return{tenant:tenant(raw.tenant),taskId:string(raw.taskId,"taskId"),templateRef:requireExactType(exact(raw.templateRef,"templateRef"),"StageTemplateRevision","templateRef"),responsibilityPlanRef:requireExactType(exact(raw.responsibilityPlanRef,"responsibilityPlanRef"),"ResponsibilityPlanRevision","responsibilityPlanRef"),productionContextRef:requireExactType(exact(raw.productionContextRef,"productionContextRef"),"ProductionContextRevision","productionContextRef"),planRef:requireExactType(exact(raw.planRef,"planRef"),"PlanRevision","planRef"),compilerVersion:string(raw.compilerVersion,"compilerVersion"),inputHash:sha(raw.inputHash,"inputHash"),compilationHash:sha(raw.compilationHash,"compilationHash"),normalizedStageIds,applicableStageIds,notApplicableStageIds,createdAt:string(raw.createdAt,"createdAt")};}

export function parseArtifactRelation(value:unknown):ArtifactRelation {const raw=object(value,"ArtifactRelation");return{tenant:tenant(raw.tenant),relationId:string(raw.relationId,"relationId"),relationType:enumValue<ArtifactRelationType>(raw.relationType,"relationType",["family_member","variant_of","supersedes","derived_from"]),fromArtifact:exactArtifact(raw.fromArtifact,"fromArtifact"),toArtifact:exactArtifact(raw.toArtifact,"toArtifact"),reason:string(raw.reason,"reason"),createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};}
export function parseArtifactRelationList(value:unknown):ArtifactRelationListResponse {const raw=object(value,"ArtifactRelationListResponse"),items=array(raw.items,"items").map(parseArtifactRelation),count=number(raw.count,"count");if(count!==items.length)throw new Error("ArtifactRelation count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}
function nullableArtifact(value:unknown,label:string):ExactArtifactRef|null{return value===null?null:exactArtifact(value,label);}
function positive(value:unknown,label:string):number{const result=number(value,label);if(result<1)throw new Error(`${label} 必须大于 0`);return result;}
function parseArtifactFamilyMember(value:unknown,index:number):ArtifactFamilyMember{const raw=object(value,`members[${index}]`);return{artifactRef:exactArtifact(raw.artifactRef,`members[${index}].artifactRef`),familyRevision:positive(raw.familyRevision,`members[${index}].familyRevision`),role:enumValue<ArtifactFamilyRole>(raw.role,`members[${index}].role`,["family_manifest","preview","draft","master","variant"]),artifactType:string(raw.artifactType,`members[${index}].artifactType`),profile:string(raw.profile,`members[${index}].profile`),platform:string(raw.platform,`members[${index}].platform`),renditionSpecHash:sha(raw.renditionSpecHash,`members[${index}].renditionSpecHash`),lineageRefs:array(raw.lineageRefs,`members[${index}].lineageRefs`).map((item,lineageIndex)=>exact(item,`members[${index}].lineageRefs[${lineageIndex}]`)),masterRef:nullableArtifact(raw.masterRef,`members[${index}].masterRef`),supersedesRef:nullableArtifact(raw.supersedesRef,`members[${index}].supersedesRef`),approvalStatus:enumValue<ArtifactFamilyMember["approvalStatus"]>(raw.approvalStatus,`members[${index}].approvalStatus`,["not_approved","approved","unknown"]),executionStatus:enumValue<ArtifactFamilyMember["executionStatus"]>(raw.executionStatus,`members[${index}].executionStatus`,["not_executed","executed","unknown"]),createdAt:string(raw.createdAt,`members[${index}].createdAt`)}};
function parseArtifactFamilyGroup(value:unknown,index:number):ArtifactFamilyCandidateGroup{const raw=object(value,`candidateGroups[${index}]`);return{selectionKey:string(raw.selectionKey,`candidateGroups[${index}].selectionKey`),role:enumValue<ArtifactFamilyRole>(raw.role,`candidateGroups[${index}].role`,["family_manifest","preview","draft","master","variant"]),artifactType:string(raw.artifactType,`candidateGroups[${index}].artifactType`),profile:string(raw.profile,`candidateGroups[${index}].profile`),platform:string(raw.platform,`candidateGroups[${index}].platform`),renditionSpecHash:sha(raw.renditionSpecHash,`candidateGroups[${index}].renditionSpecHash`),candidates:array(raw.candidates,`candidateGroups[${index}].candidates`).map((item,candidateIndex)=>exactArtifact(item,`candidateGroups[${index}].candidates[${candidateIndex}]`)),selectedRef:nullableArtifact(raw.selectedRef,`candidateGroups[${index}].selectedRef`),status:enumValue<ArtifactFamilyCandidateStatus>(raw.status,`candidateGroups[${index}].status`,["current","conflict","selected"])}};
function parseArtifactFamilyDecision(value:unknown,index:number):ArtifactFamilySelectionDecision{const raw=object(value,`selectionDecisions[${index}]`);return{familyId:string(raw.familyId,`selectionDecisions[${index}].familyId`),selectionKey:string(raw.selectionKey,`selectionDecisions[${index}].selectionKey`),revision:positive(raw.revision,`selectionDecisions[${index}].revision`),expectedFamilyVersion:positive(raw.expectedFamilyVersion,`selectionDecisions[${index}].expectedFamilyVersion`),selectedRef:exactArtifact(raw.selectedRef,`selectionDecisions[${index}].selectedRef`),candidateRefs:array(raw.candidateRefs,`selectionDecisions[${index}].candidateRefs`).map((item,candidateIndex)=>exactArtifact(item,`selectionDecisions[${index}].candidateRefs[${candidateIndex}]`)),candidateSetHash:sha(raw.candidateSetHash,`selectionDecisions[${index}].candidateSetHash`),policyRef:exact(raw.policyRef,`selectionDecisions[${index}].policyRef`),reason:string(raw.reason,`selectionDecisions[${index}].reason`),decisionHash:sha(raw.decisionHash,`selectionDecisions[${index}].decisionHash`),actor:string(raw.actor,`selectionDecisions[${index}].actor`),createdAt:string(raw.createdAt,`selectionDecisions[${index}].createdAt`)}};
export function parseArtifactFamily(value:unknown):ArtifactFamily{const raw=object(value,"ArtifactFamily");return{tenant:tenant(raw.tenant),familyId:string(raw.familyId,"familyId"),version:positive(raw.version,"version"),currentRevision:positive(raw.currentRevision,"currentRevision"),manifestRef:exactArtifact(raw.manifestRef,"manifestRef"),members:array(raw.members,"members").map(parseArtifactFamilyMember),candidateGroups:array(raw.candidateGroups,"candidateGroups").map(parseArtifactFamilyGroup),selectionDecisions:array(raw.selectionDecisions,"selectionDecisions").map(parseArtifactFamilyDecision),topologyStatus:enumValue<ArtifactFamily["topologyStatus"]>(raw.topologyStatus,"topologyStatus",["empty","current","conflict"]),updatedAt:string(raw.updatedAt,"updatedAt")};}
export function parseArtifactFamilyList(value:unknown):ArtifactFamilyListResponse{const raw=object(value,"ArtifactFamilyListResponse"),items=array(raw.items,"items").map(parseArtifactFamily),count=number(raw.count,"count");if(count!==items.length)throw new Error("ArtifactFamily count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}

export function parseReviewIssue(value:unknown):ReviewIssue {const raw=object(value,"ReviewIssue"),version=number(raw.version,"version");if(version<1)throw new Error("ReviewIssue version 必须大于 0");return{tenant:tenant(raw.tenant),issueId:string(raw.issueId,"issueId"),ruleRef:exact(raw.ruleRef,"ruleRef"),severity:enumValue<ReviewSeverity>(raw.severity,"severity",["info","warning","error","critical"]),artifactRef:exactArtifact(raw.artifactRef,"artifactRef"),evalReportRef:exact(raw.evalReportRef,"evalReportRef"),location:object(raw.location,"location"),evidenceRefs:array(raw.evidenceRefs,"evidenceRefs").map((item,i)=>exact(item,`evidenceRefs[${i}]`)),suggestedFix:string(raw.suggestedFix,"suggestedFix"),returnStage:string(raw.returnStage,"returnStage"),status:enumValue<ReviewIssueStatus>(raw.status,"status",["open","resolved","returned","superseded"]),version,createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt"),updatedBy:string(raw.updatedBy,"updatedBy"),updatedAt:string(raw.updatedAt,"updatedAt")};}
export function parseReviewIssueList(value:unknown):ReviewIssueListResponse {const raw=object(value,"ReviewIssueListResponse"),items=array(raw.items,"items").map(parseReviewIssue),count=number(raw.count,"count");if(count!==items.length)throw new Error("ReviewIssue count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}
export function parseReturnDecision(value:unknown):ReturnDecision {const raw=object(value,"ReturnDecision"),issueVersion=number(raw.issueVersion,"issueVersion"),attempt=number(raw.attempt,"attempt"),impactDecisions=array(raw.impactDecisions,"impactDecisions").map((value,index)=>{const item=object(value,`impactDecisions[${index}]`);return{stepKey:string(item.stepKey,"stepKey"),action:enumValue<"invalidate"|"reuse">(item.action,"action",["invalidate","reuse"]),reason:string(item.reason,"reason")};}),impactReadiness=enumValue<"exact"|"legacy_unavailable">(raw.impactReadiness,"impactReadiness",["exact","legacy_unavailable"]);if(issueVersion<1||attempt<1||(impactReadiness==="exact")!==(impactDecisions.length>0))throw new Error("ReturnDecision version/attempt/impact 非法");return{tenant:tenant(raw.tenant),decisionId:string(raw.decisionId,"decisionId"),issueId:string(raw.issueId,"issueId"),issueVersion,runId:string(raw.runId,"runId"),stepKey:string(raw.stepKey,"stepKey"),stepRunId:string(raw.stepRunId,"stepRunId"),attempt,attemptIdempotencyKey:string(raw.attemptIdempotencyKey,"attemptIdempotencyKey"),reason:string(raw.reason,"reason"),impactDecisions,impactReadiness,decisionHash:sha(raw.decisionHash,"decisionHash"),actor:string(raw.actor,"actor"),createdAt:string(raw.createdAt,"createdAt")};}

function impactDimension(value:unknown,label:string):ImpactDimension {
  const raw=object(value,label),quality=enumValue<ImpactQuality>(raw.quality,`${label}.quality`,["measured","estimated","unknown"]),sourceRefs=array(raw.sourceRefs,`${label}.sourceRefs`).map((item,index)=>resource(item,`${label}.sourceRefs[${index}]`)),cutoffAt=nullableString(raw.cutoffAt,`${label}.cutoffAt`);
  if(quality==="unknown"&&raw.value!==null)throw new Error(`${label} unknown 不得携带数值`);
  if(quality!=="unknown"&&(raw.value===null||!sourceRefs.length||cutoffAt===null))throw new Error(`${label} measured/estimated 必须携带 value、sourceRefs 与 cutoffAt`);
  return{quality,value:raw.value??null,sourceRefs,cutoffAt,details:object(raw.details,`${label}.details`)};
}
function impact(value:unknown):ImpactAssessment {const raw=object(value,"impact");return{objectScope:impactDimension(raw.objectScope,"impact.objectScope"),channelScope:impactDimension(raw.channelScope,"impact.channelScope"),cost:impactDimension(raw.cost,"impact.cost"),budget:impactDimension(raw.budget,"impact.budget"),risks:impactDimension(raw.risks,"impact.risks"),reversibility:impactDimension(raw.reversibility,"impact.reversibility"),approvalChain:impactDimension(raw.approvalChain,"impact.approvalChain"),rateCapacityKill:impactDimension(raw.rateCapacityKill,"impact.rateCapacityKill")};}
function requireExactType(ref:ExactRevisionRef,expected:string,label:string){if(ref.resourceType!==expected)throw new Error(`${label} 必须引用 ${expected}`);return ref;}
export function parseImpactPreview(value:unknown):ImpactPreviewRevision {
  const raw=object(value,"ImpactPreviewRevision"),revision=number(raw.revision,"revision"),version=number(raw.version,"version"),lifecycle=enumValue<ContractLifecycle>(raw.lifecycle,"lifecycle",["draft","frozen","withdrawn","superseded"]),readiness=enumValue<ContractReadiness>(raw.readiness,"readiness",["ready","blocked","stale","unknown"]),parsedBlockers=blockers(raw.blockers),frozenBy=nullableString(raw.frozenBy,"frozenBy"),frozenAt=nullableString(raw.frozenAt,"frozenAt");
  if(revision<1||version<1)throw new Error("ImpactPreview revision/version 必须大于 0");
  if((frozenBy===null)!==(frozenAt===null)||(lifecycle==="frozen")!==(frozenBy!==null))throw new Error("ImpactPreview frozen 元数据与 lifecycle 不一致");
  if((readiness==="ready"&&parsedBlockers.length)||(readiness!=="ready"&&!parsedBlockers.length))throw new Error("ImpactPreview readiness 与 blockers 不一致");
  const productionContextRef=raw.productionContextRef===undefined?null:nullableExact(raw.productionContextRef,"productionContextRef");
  if(productionContextRef)requireExactType(productionContextRef,"ProductionContextRevision","productionContextRef");
  const modelRouteRef=nullableExact(raw.modelRouteRef,"modelRouteRef"),runtimePolicyRef=nullableExact(raw.runtimePolicyRef,"runtimePolicyRef");
  if((modelRouteRef===null)!==(runtimePolicyRef===null))throw new Error("modelRouteRef/runtimePolicyRef 必须成对");
  if(modelRouteRef)requireExactType(modelRouteRef,"ModelRouteRevision","modelRouteRef");
  if(runtimePolicyRef)requireExactType(runtimePolicyRef,"RuntimePolicyRevision","runtimePolicyRef");
  const capabilityRef=nullableExact(raw.capabilityRef,"capabilityRef");if(capabilityRef)requireExactType(capabilityRef,"CapabilityRevision","capabilityRef");
  const bindingRefs=array(raw.bindingRefs,"bindingRefs").map((item,index)=>mutable(item,`bindingRefs[${index}]`));
  if(bindingRefs.some(ref=>!["AgentInstance","SkillBinding","CapabilityBinding"].includes(ref.resourceType)))throw new Error("bindingRefs 类型非法");
  const accountRef=raw.accountRef===null?null:mutable(raw.accountRef,"accountRef");
  if(accountRef&&!['AccountBinding','ChannelAccountBinding','ShopAccountBinding'].includes(accountRef.resourceType))throw new Error("accountRef 类型非法");
  return{tenant:tenant(raw.tenant),previewId:string(raw.previewId,"previewId"),revision,version,taskId:string(raw.taskId,"taskId"),planRef:requireExactType(exact(raw.planRef,"planRef"),"PlanRevision","planRef"),productionContextRef,briefRef:requireExactType(exact(raw.briefRef,"briefRef"),"TaskBriefRevision","briefRef"),evidenceBundleRef:requireExactType(exact(raw.evidenceBundleRef,"evidenceBundleRef"),"EvidenceBundleRevision","evidenceBundleRef"),evalContractRef:requireExactType(exact(raw.evalContractRef,"evalContractRef"),"EvalContractRevision","evalContractRef"),responsibilityPlanRef:requireExactType(exact(raw.responsibilityPlanRef,"responsibilityPlanRef"),"ResponsibilityPlanRevision","responsibilityPlanRef"),stageTemplateRef:requireExactType(exact(raw.stageTemplateRef,"stageTemplateRef"),"StageTemplateRevision","stageTemplateRef"),modelRouteRef,runtimePolicyRef,bindingRefs,capabilityRef,accountRef,impact:impact(raw.impact),expiresAt:string(raw.expiresAt,"expiresAt"),contentHash:sha(raw.contentHash,"contentHash"),dependencySnapshotHash:sha(raw.dependencySnapshotHash,"dependencySnapshotHash"),actionBindingHash:sha(raw.actionBindingHash,"actionBindingHash"),lifecycle,readiness,blockers:parsedBlockers,frozenBy,frozenAt,createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};
}
export function parseImpactPreviewList(value:unknown):ImpactPreviewListResponse {const raw=object(value,"ImpactPreviewListResponse"),items=array(raw.items,"items").map(parseImpactPreview),count=number(raw.count,"count");if(count!==items.length)throw new Error("ImpactPreview count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}

export function parseProductionContext(value:unknown):ProductionContextRevision {const raw=object(value,"ProductionContextRevision"),revision=number(raw.revision,"revision"),productionProfileRef=raw.productionProfileRef===undefined?null:nullableExact(raw.productionProfileRef,"productionProfileRef"),preparationRef=nullableExact(raw.preparationRef,"preparationRef");if(revision<1)throw new Error("ProductionContext revision 必须大于 0");if(productionProfileRef)requireExactType(productionProfileRef,"ProductionProfileRevision","productionProfileRef");if(preparationRef)requireExactType(preparationRef,"PreparationReceipt","preparationRef");return{tenant:tenant(raw.tenant),contextId:string(raw.contextId,"contextId"),revision,taskId:string(raw.taskId,"taskId"),briefRef:requireExactType(exact(raw.briefRef,"briefRef"),"TaskBriefRevision","briefRef"),evidenceBundleRef:requireExactType(exact(raw.evidenceBundleRef,"evidenceBundleRef"),"EvidenceBundleRevision","evidenceBundleRef"),evalContractRef:requireExactType(exact(raw.evalContractRef,"evalContractRef"),"EvalContractRevision","evalContractRef"),responsibilityPlanRef:requireExactType(exact(raw.responsibilityPlanRef,"responsibilityPlanRef"),"ResponsibilityPlanRevision","responsibilityPlanRef"),productionProfileRef,preparationRef,profile:string(raw.profile,"profile"),dependencySnapshot:records(raw.dependencySnapshot,"dependencySnapshot"),dependencySnapshotHash:sha(raw.dependencySnapshotHash,"dependencySnapshotHash"),contentHash:sha(raw.contentHash,"contentHash"),lifecycle:enumValue<ContractLifecycle>(raw.lifecycle,"lifecycle",["draft","frozen","withdrawn","superseded"]),readiness:enumValue<ContractReadiness>(raw.readiness,"readiness",["ready","blocked","stale","unknown"]),blockers:blockers(raw.blockers),createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};}
export function parseProductionContextList(value:unknown):ProductionContextListResponse {const raw=object(value,"ProductionContextListResponse"),items=array(raw.items,"items").map(parseProductionContext),count=number(raw.count,"count");if(count!==items.length)throw new Error("ProductionContext count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}

export function parseProductionStartDecision(value:unknown):ProductionStartDecision {
  const raw=object(value,"ProductionStartDecision"),status=enumValue<ProductionStartStatus>(raw.status,"status",["started","blocked","stale","unknown"]),parsedBlockers=blockers(raw.blockers),taskRunRef=nullableResource(raw.taskRunRef,"taskRunRef");
  if(status==="started"&&(!taskRunRef||taskRunRef.resourceType!=="TaskRun"||parsedBlockers.length))throw new Error("started Decision 必须携带 TaskRun 且无 blockers");
  if(status!=="started"&&(taskRunRef!==null||!parsedBlockers.length))throw new Error("未启动 Decision 必须携带 blockers 且无 TaskRun");
  const productionContextRef=raw.productionContextRef===undefined?null:nullableExact(raw.productionContextRef,"productionContextRef");if(productionContextRef)requireExactType(productionContextRef,"ProductionContextRevision","productionContextRef");
  return{tenant:tenant(raw.tenant),decisionId:string(raw.decisionId,"decisionId"),status,taskId:string(raw.taskId,"taskId"),productionContextRef,planRef:requireExactType(exact(raw.planRef,"planRef"),"PlanRevision","planRef"),previewRef:requireExactType(exact(raw.previewRef,"previewRef"),"ImpactPreviewRevision","previewRef"),actionProposalRef:proposal(raw.actionProposalRef,"actionProposalRef"),dependencySnapshotHash:sha(raw.dependencySnapshotHash,"dependencySnapshotHash"),blockers:parsedBlockers,taskRunRef,createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};
}
export function parseProductionStartDecisionList(value:unknown):ProductionStartDecisionListResponse {const raw=object(value,"ProductionStartDecisionListResponse"),items=array(raw.items,"items").map(parseProductionStartDecision),count=number(raw.count,"count");if(count!==items.length)throw new Error("ProductionStartDecision count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}
