import type { AssigneeKind, ContractBlocker, ContractCoverage, ContractLifecycle, ContractReadiness, EvalContractListResponse, EvalContractRevision, EvidenceBundleListResponse, EvidenceBundleRevision, ExactRevisionRef, MergeDecision, ResourceRef, ResponsibilityPlanListResponse, ResponsibilityPlanRevision, ResponsibilitySlot, TaskBriefListResponse, TaskBriefRevision, Tenant } from "./contracts";

function object(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} 必须是对象`); return value as Record<string, unknown>; }
function string(value: unknown, label: string): string { if (typeof value !== "string" || !value) throw new Error(`${label} 必须是非空字符串`); return value; }
function number(value: unknown, label: string): number { if (typeof value !== "number" || !Number.isInteger(value) || value < 0) throw new Error(`${label} 必须是非负整数`); return value; }
function sha(value: unknown, label: string): string { const result=string(value,label); if (!/^[0-9a-f]{64}$/.test(result)) throw new Error(`${label} 非 SHA-256`); return result; }
function array(value: unknown, label: string): unknown[] { if (!Array.isArray(value)) throw new Error(`${label} 必须是数组`); return value; }
function tenant(value: unknown): Tenant { const raw=object(value,"tenant"); return {orgId:string(raw.orgId,"tenant.orgId"),projectId:string(raw.projectId,"tenant.projectId")}; }
function resource(value: unknown, label: string): ResourceRef { const raw=object(value,label); const revision=raw.revision; if (revision!==null && typeof revision!=="string") throw new Error(`${label}.revision 必须是字符串或 null`); return {resourceType:string(raw.resourceType,`${label}.resourceType`),resourceId:string(raw.resourceId,`${label}.resourceId`),revision,authority:string(raw.authority,`${label}.authority`)}; }
function exact(value: unknown, label: string): ExactRevisionRef { const raw=object(value,label); const revision=number(raw.revision,`${label}.revision`); if (revision<1) throw new Error(`${label}.revision 必须大于 0`); return {resourceType:string(raw.resourceType,`${label}.resourceType`),resourceId:string(raw.resourceId,`${label}.resourceId`),revision,contentHash:sha(raw.contentHash,`${label}.contentHash`)}; }
function records(value: unknown, label: string): Record<string, unknown>[] { return array(value,label).map((item,index)=>object(item,`${label}[${index}]`)); }
function nullableExact(value: unknown, label: string): ExactRevisionRef|null { return value===null ? null : exact(value,label); }
function enumValue<T extends string>(value: unknown,label:string,values:readonly T[]):T { const result=string(value,label) as T; if(!values.includes(result)) throw new Error(`${label} 非法`); return result; }
function strings(value:unknown,label:string):string[] { return array(value,label).map((item,index)=>string(item,`${label}[${index}]`)); }
function blockers(value:unknown):ContractBlocker[] { return array(value,"blockers").map((item,index)=>{const raw=object(item,`blockers[${index}]`);return{code:string(raw.code,`blockers[${index}].code`),message:string(raw.message,`blockers[${index}].message`),resourceRef:nullableExact(raw.resourceRef,`blockers[${index}].resourceRef`)}}); }
function stringRecord(value:unknown,label:string):Record<string,string> { const raw=object(value,label); return Object.fromEntries(Object.entries(raw).map(([key,item])=>[key,string(item,`${label}.${key}`)])); }
function thresholdRecord(value:unknown):Record<string,number> { const raw=object(value,"severityThresholds"); if(!Object.keys(raw).length) throw new Error("severityThresholds 不能为空"); return Object.fromEntries(Object.entries(raw).map(([key,item])=>{if(typeof item!=="number"||item<0||item>1) throw new Error(`severityThresholds.${key} 必须在 0..1`);return[key,item]})); }

export function parseTaskBrief(value: unknown): TaskBriefRevision {
  const raw=object(value,"TaskBriefRevision"); const lifecycle=string(raw.lifecycle,"lifecycle") as TaskBriefRevision["lifecycle"];
  if (!["draft","frozen","withdrawn","superseded"].includes(lifecycle)) throw new Error("lifecycle 非法");
  const revision=number(raw.revision,"revision"), version=number(raw.version,"version"); if (revision<1||version<1) throw new Error("revision/version 必须大于 0");
  return {tenant:tenant(raw.tenant),briefId:string(raw.briefId,"briefId"),taskId:string(raw.taskId,"taskId"),revision,version,briefType:string(raw.briefType,"briefType"),schemaRef:resource(raw.schemaRef,"schemaRef"),spec:object(raw.spec,"spec"),contentHash:sha(raw.contentHash,"contentHash"),lifecycle,createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};
}

export function parseBriefList(value: unknown): TaskBriefListResponse { const raw=object(value,"TaskBriefListResponse"), items=array(raw.items,"items").map(parseTaskBrief), count=number(raw.count,"count"); if(count!==items.length) throw new Error("Brief count 与 items 不一致"); return {tenant:tenant(raw.tenant),items,count}; }

function parseBundle(value: unknown): EvidenceBundleRevision {
  const raw=object(value,"EvidenceBundleRevision"), coverage=string(raw.coverage,"coverage") as EvidenceBundleRevision["coverage"], freshness=string(raw.freshness,"freshness") as EvidenceBundleRevision["freshness"];
  if(!["complete","partial","blocked","unknown"].includes(coverage)||!["fresh","stale","blocked","unknown"].includes(freshness)||raw.lifecycle!=="frozen") throw new Error("EvidenceBundle 状态非法");
  return {tenant:tenant(raw.tenant),bundleId:string(raw.bundleId,"bundleId"),revision:number(raw.revision,"revision"),briefRef:exact(raw.briefRef,"briefRef"),subjectRefs:array(raw.subjectRefs,"subjectRefs").map((item,index)=>resource(item,`subjectRefs[${index}]`)),cutoffAt:string(raw.cutoffAt,"cutoffAt"),itemRefs:array(raw.itemRefs,"itemRefs").map((item,index)=>exact(item,`itemRefs[${index}]`)),coverage,missing:records(raw.missing,"missing"),conflicts:records(raw.conflicts,"conflicts"),uncertainties:records(raw.uncertainties,"uncertainties"),freshness,marking:array(raw.marking,"marking").map((item,index)=>string(item,`marking[${index}]`)),licenseSummary:object(raw.licenseSummary,"licenseSummary"),contentHash:sha(raw.contentHash,"contentHash"),lifecycle:"frozen",createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};
}

export function parseBundleList(value: unknown): EvidenceBundleListResponse { const raw=object(value,"EvidenceBundleListResponse"), items=array(raw.items,"items").map(parseBundle), count=number(raw.count,"count"); if(count!==items.length) throw new Error("Bundle count 与 items 不一致"); return {tenant:tenant(raw.tenant),items,count}; }

export function parseEvalContract(value:unknown):EvalContractRevision {
  const raw=object(value,"EvalContractRevision"), revision=number(raw.revision,"revision"), version=number(raw.version,"version"); if(revision<1||version<1) throw new Error("revision/version 必须大于 0");
  return {tenant:tenant(raw.tenant),contractId:string(raw.contractId,"contractId"),revision,version,suiteRef:exact(raw.suiteRef,"suiteRef"),publicationRef:nullableExact(raw.publicationRef,"publicationRef"),releaseGateRef:nullableExact(raw.releaseGateRef,"releaseGateRef"),artifactSchemaRef:resource(raw.artifactSchemaRef,"artifactSchemaRef"),severityThresholds:thresholdRecord(raw.severityThresholds),gatePolicy:object(raw.gatePolicy,"gatePolicy"),returnMapping:stringRecord(raw.returnMapping,"returnMapping"),overridePolicy:object(raw.overridePolicy,"overridePolicy"),contentHash:sha(raw.contentHash,"contentHash"),lifecycle:enumValue<ContractLifecycle>(raw.lifecycle,"lifecycle",["draft","frozen","withdrawn","superseded"]),readiness:enumValue<ContractReadiness>(raw.readiness,"readiness",["ready","blocked","stale","unknown"]),blockers:blockers(raw.blockers),createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};
}
export function parseEvalContractList(value:unknown):EvalContractListResponse { const raw=object(value,"EvalContractListResponse"),items=array(raw.items,"items").map(parseEvalContract),count=number(raw.count,"count");if(count!==items.length)throw new Error("EvalContract count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count}; }

function assignee(value:unknown,label:string){const raw=object(value,label),version=number(raw.version,`${label}.version`);if(version<1)throw new Error(`${label}.version 必须大于 0`);return{kind:enumValue<AssigneeKind>(raw.kind,`${label}.kind`,["agent_instance","human_principal","tool_binding","provider_capability_binding"]),resourceId:string(raw.resourceId,`${label}.resourceId`),version}};
function slot(value:unknown,index:number):ResponsibilitySlot {const label=`slots[${index}]`,raw=object(value,label),requiredCapabilityIds=strings(raw.requiredCapabilityIds,`${label}.requiredCapabilityIds`);if(!requiredCapabilityIds.length)throw new Error(`${label}.requiredCapabilityIds 不能为空`);return{slotId:string(raw.slotId,`${label}.slotId`),responsibilityType:string(raw.responsibilityType,`${label}.responsibilityType`),requiredCapabilityIds,inputSchemaRef:resource(raw.inputSchemaRef,`${label}.inputSchemaRef`),outputSchemaRef:resource(raw.outputSchemaRef,`${label}.outputSchemaRef`),gateRefs:array(raw.gateRefs,`${label}.gateRefs`).map((item,i)=>exact(item,`${label}.gateRefs[${i}]`)),returnStage:string(raw.returnStage,`${label}.returnStage`),assignee:assignee(raw.assignee,`${label}.assignee`)}};
function merge(value:unknown,index:number):MergeDecision {const label=`mergeDecisions[${index}]`,raw=object(value,label);return{sourceSlotIds:strings(raw.sourceSlotIds,`${label}.sourceSlotIds`),targetSlotId:string(raw.targetSlotId,`${label}.targetSlotId`),reason:string(raw.reason,`${label}.reason`),mergedResponsibilityTypes:strings(raw.mergedResponsibilityTypes,`${label}.mergedResponsibilityTypes`)}};
export function parseResponsibilityPlan(value:unknown):ResponsibilityPlanRevision {const raw=object(value,"ResponsibilityPlanRevision"),revision=number(raw.revision,"revision"),version=number(raw.version,"version"),rawSlots=array(raw.slots,"slots");if(revision<1||version<1)throw new Error("revision/version 必须大于 0");if(!rawSlots.length)throw new Error("slots 不能为空");return{tenant:tenant(raw.tenant),planId:string(raw.planId,"planId"),revision,version,profile:string(raw.profile,"profile"),templateRef:exact(raw.templateRef,"templateRef"),slots:rawSlots.map(slot),mergeDecisions:array(raw.mergeDecisions,"mergeDecisions").map(merge),coverage:enumValue<ContractCoverage>(raw.coverage,"coverage",["complete","partial","blocked","unknown"]),uncoveredSlots:strings(raw.uncoveredSlots,"uncoveredSlots"),contentHash:sha(raw.contentHash,"contentHash"),lifecycle:enumValue<ContractLifecycle>(raw.lifecycle,"lifecycle",["draft","frozen","withdrawn","superseded"]),readiness:enumValue<ContractReadiness>(raw.readiness,"readiness",["ready","blocked","stale","unknown"]),blockers:blockers(raw.blockers),createdBy:string(raw.createdBy,"createdBy"),createdAt:string(raw.createdAt,"createdAt")};}
export function parseResponsibilityPlanList(value:unknown):ResponsibilityPlanListResponse {const raw=object(value,"ResponsibilityPlanListResponse"),items=array(raw.items,"items").map(parseResponsibilityPlan),count=number(raw.count,"count");if(count!==items.length)throw new Error("ResponsibilityPlan count 与 items 不一致");return{tenant:tenant(raw.tenant),items,count};}
