"""Domain router aggregates generated from domain_manifest.json.

Run ``python scripts/generate_domain_aggregates.py --check`` to detect drift.
DO NOT EDIT MANUALLY — edit the manifest and regenerate instead.
"""
from __future__ import annotations

from importlib import import_module

from fastapi import APIRouter


ROUTER_SPECS: dict[str, tuple[tuple[str, str], ...]] = {
    "infra": (
        ('aos_api.routers.health', 'router'),
        ('aos_api.routers.metrics', 'router'),
        ('aos_api.routers.plugins', 'router'),
        ('aos_api.routers.platform_integrations', 'router'),
        ('aos_api.routers.runtime_write', 'router'),
        ('aos_api.routers.analytics', 'router'),
        ('aos_api.routers.ssl_health_snooze_marketplace', 'router'),
        ('aos_api.routers.linter_foundry_rules', 'router'),
        ('aos_api.routers.autoscale_telemetry_volume_cop', 'router'),
        ('aos_api.routers.tracing_perf_geo_map', 'router'),
        ('aos_api.routers.vertex_geo_ts_process_hyperauto', 'router'),
        ('aos_api.routers.dicom_workshop_docintel', 'router'),
        ('aos_api.routers.es_sap_stream', 'router'),
        ('aos_api.vs_module_interface_router', 'router'),
        ('aos_api.vs_events_router', 'router'),
        ('aos_api.vs_event_idempotent_router', 'router'),
        ('aos_api.es_auto_ontology_gen_router', 'router'),
        ('aos_api.vs_timeseries_set_router', 'router'),
        ('aos_api.es_sap_batch_import_router', 'router'),
        ('aos_api.es_derived_element_intel_router', 'router'),
        ('aos_api.routers.asset_bundles', 'router'),
        ('aos_api.routers.bundle_compositions', 'router'),
        ('aos_api.routers.bundle_installations', 'router'),
        ('aos_api.routers.integration_cases', 'router'),
    ),
    "admin": (
        ('aos_api.routers.auth_oidc', 'router'),
        ('aos_api.routers.authz', 'router'),
        ('aos_api.routers.orgs', 'router'),
        ('aos_api.routers.ops_tenants', 'router'),
        ('aos_api.routers.ops_ttl', 'router'),
        ('aos_api.routers.workspaces', 'router'),
        ('aos_api.routers.cap_and_markings', 'router'),
        ('aos_api.au_policy_hot_reload_router', 'router'),
    ),
    "system": (
        ('aos_api.routers.me', 'router'),
        ('aos_api.routers.otp', 'router'),
        ('aos_api.routers.ops_version_matrix', 'router'),
        ('aos_api.routers.ops_local', 'router'),
    ),
    "agent": (
        ('aos_api.routers.buddy', 'router'),
        ('aos_api.routers.agent_health_migration_webhook', 'router'),
        ('aos_api.routers.phase6_agents', 'router'),
    ),
    "workshop": (
        ('aos_api.routers.modules', 'router'),
        ('aos_api.routers.workshop_phase1', 'router'),
        ('aos_api.routers.actions', 'router'),
        ('aos_api.routers.drafts', 'router'),
        ('aos_api.routers.gantt', 'router'),
        ('aos_api.routers.action_enhancements', 'router'),
        ('aos_api.routers.action_params', 'router'),
        ('aos_api.routers.action_further', 'router'),
        ('aos_api.routers.action_webhook', 'router'),
        ('aos_api.routers.action_finale', 'router'),
        ('aos_api.routers.compute_module', 'router'),
        ('aos_api.routers.compute_module_extras', 'router'),
        ('aos_api.routers.compute_module_publish', 'router'),
        ('aos_api.routers.dev_tooling', 'router'),
        ('aos_api.routers.media_references', 'router'),
        ('aos_api.routers.media_set_browser_interaction', 'router'),
        ('aos_api.routers.media_sets', 'router'),
        ('aos_api.routers.action_rules', 'router'),
        ('aos_api.routers.action_visual_editor', 'router'),
        ('aos_api.routers.integration_maintenance', 'router'),
        ('aos_api.routers.scheduling', 'router'),
        ('aos_api.routers.scheduling_rules_lint', 'router'),
        ('aos_api.routers.web_ide', 'router'),
        ('aos_api.routers.workshop_compute_api', 'router'),
        ('aos_api.routers.ds_context_menu', 'router'),
        ('aos_api.routers.pp_toolbar_settings', 'router'),
        ('aos_api.routers.ms_header_extractor', 'router'),
        ('aos_api.af_action_types_router', 'router'),
        ('aos_api.af_capabilities_router', 'router'),
        ('aos_api.af_edit_counter_router', 'router'),
        ('aos_api.af_edited_marker_router', 'router'),
        ('aos_api.af_oma_editor_router', 'router'),
        ('aos_api.af_param_help_router', 'router'),
        ('aos_api.at_action_apply_perm_router', 'router'),
        ('aos_api.at_edit_only_mode_router', 'router'),
        ('aos_api.at_marketplace_types_router', 'router'),
        ('aos_api.at_notification_link_router', 'router'),
        ('aos_api.at_notification_permission_router', 'router'),
        ('aos_api.at_side_effect_perm_router', 'router'),
        ('aos_api.ds_backtick_search_router', 'router'),
        ('aos_api.ds_inline_upload_router', 'router'),
        ('aos_api.ms_create_pipeline_menu_router', 'router'),
        ('aos_api.ms_file_add_router', 'router'),
        ('aos_api.pp_chart_drag_select_router', 'router'),
        ('aos_api.pp_chart_pan_router', 'router'),
        ('aos_api.pp_cross_project_flow_router', 'router'),
        ('aos_api.pp_mediasets_code_router', 'router'),
        ('aos_api.pp_parse_paths_router', 'router'),
        ('aos_api.pp_role_permission_router', 'router'),
        ('aos_api.pp_toolbar_share_router', 'router'),
        ('aos_api.wk_conditional_section_router', 'router'),
        ('aos_api.wk_widget_permission_router', 'router'),
        ('aos_api.ds_schedule_panel_router', 'router'),
        ('aos_api.ds_share_move_rename_router', 'router'),
        ('aos_api.ds_stream_preview_router', 'router'),
        ('aos_api.ds_stream_tag_router', 'router'),
        ('aos_api.ds_schema_infer_router', 'router'),
        ('aos_api.ds_edit_schema_view_router', 'router'),
        ('aos_api.ds_col_autocomplete_router', 'router'),
        ('aos_api.ds_keyboard_shortcut_router', 'router'),
        ('aos_api.ds_resize_panel_router', 'router'),
        ('aos_api.ds_same_name_logic_router', 'router'),
        ('aos_api.ds_sql_draft_router', 'router'),
        ('aos_api.pp_incremental_perf_router', 'router'),
        ('aos_api.pp_schema_infer_router', 'router'),
        ('aos_api.pp_advanced_schedule_router', 'router'),
        ('aos_api.pp_schedule_troubleshoot_router', 'router'),
        ('aos_api.pp_schedule_best_practice_router', 'router'),
        ('aos_api.pp_schedule_template_router', 'router'),
        ('aos_api.pp_classify_tag_router', 'router'),
        ('aos_api.pp_propagate_view_router', 'router'),
        ('aos_api.pp_org_tag_router', 'router'),
        ('aos_api.pp_tag_reapproval_router', 'router'),
        ('aos_api.pp_io_classify_router', 'router'),
        ('aos_api.pp_schedule_coloring_router', 'router'),
        ('aos_api.pp_folder_convention_router', 'router'),
        ('aos_api.pp_dev_best_practice_router', 'router'),
        ('aos_api.pp_prod_pipeline_build_router', 'router'),
        ('aos_api.pp_connect_stream_router', 'router'),
        ('aos_api.ms_small_file_shortcut_router', 'router'),
        ('aos_api.ms_docintel_dlq_router', 'router'),
        ('aos_api.ms_latency_policy_router', 'router'),
        ('aos_api.ms_transcript_postproc_router', 'router'),
        ('aos_api.ms_transcript_output_router', 'router'),
        ('aos_api.ms_audio_import_path_router', 'router'),
        ('aos_api.ms_primary_key_router', 'router'),
        ('aos_api.af_archetypes_toggle_router', 'router'),
        ('aos_api.at_param_desc_router', 'router'),
        ('aos_api.at_value_source_router', 'router'),
        ('aos_api.at_rule_order_conflict_router', 'router'),
        ('aos_api.at_oma_7tab_router', 'router'),
        ('aos_api.at_archetypes_toggle_router', 'router'),
        ('aos_api.at_edit_count_warn_router', 'router'),
        ('aos_api.at_edited_marker_router', 'router'),
        ('aos_api.at_func_op_types_router', 'router'),
        ('aos_api.at_func_onboarding_router', 'router'),
        ('aos_api.ca_platform_facade_router', 'router'),
        ('aos_api.ca_heavy_capability_router', 'router'),
        ('aos_api.sc_logic_change_trigger_router', 'router'),
        ('aos_api.sc_calendar_view_router', 'router'),
        ('aos_api.sc_readonly_dynamic_router', 'router'),
        ('aos_api.sc_dynamic_drag_drop_router', 'router'),
        ('aos_api.rl_rule_workflow_router', 'router'),
        ('aos_api.rl_transform_pipeline_rule_router', 'router'),
        ('aos_api.rl_workshop_integration_router', 'router'),
        ('aos_api.wk_overlay_router', 'router'),
        ('aos_api.wk_object_table_advanced_router', 'router'),
        ('aos_api.ms_java_transform_integration_router', 'router'),
        ('aos_api.ms_form_parser_router', 'router'),
        ('aos_api.ms_multi_sheet_output_router', 'router'),
        ('aos_api.ms_incremental_process_router', 'router'),
        ('aos_api.ms_error_dataframe_router', 'router'),
        ('aos_api.ms_spark_mem_config_router', 'router'),
        ('aos_api.ms_api_javadoc_router', 'router'),
        ('aos_api.wk_embedded_copilot_router', 'router'),
    ),
    "ontology": (
        ('aos_api.routers.object_sets', 'router'),
        ('aos_api.routers.object_storage_indexing', 'router'),
        ('aos_api.routers.ontology', 'router'),
        ('aos_api.routers.ontology_governance', 'router'),
        ('aos_api.routers.ontology_management', 'router'),
        ('aos_api.routers.ontology_data_layer', 'router'),
        ('aos_api.routers.oe_enhancements', 'router'),
        ('aos_api.routers.object_editing', 'router'),
        ('aos_api.routers.oma_editor', 'router'),
        ('aos_api.routers.type_system', 'router'),
        ('aos_api.routers.funnel', 'router'),
        ('aos_api.routers.funnel_mappings', 'router'),
        ('aos_api.routers.ontology_roles', 'router'),
        ('aos_api.routers.ontology_outputs', 'router'),
        ('aos_api.routers.csv_ontology_export_action_metrics', 'router'),
        ('aos_api.routers.multi_language', 'router'),
        ('aos_api.routers.object_views', 'router'),
        ('aos_api.routers.object_explorer', 'router'),
        ('aos_api.routers.multi_source', 'router'),
        ('aos_api.routers.materialized_access_control', 'router'),
        ('aos_api.routers.incremental_sync', 'router'),
        ('aos_api.routers.ob_index_debug', 'router'),
        ('aos_api.ob_agg_precision_router', 'router'),
        ('aos_api.ob_monitor_notify_router', 'router'),
        ('aos_api.ob_stream_permission_router', 'router'),
        ('aos_api.oc_destructive_confirm_router', 'router'),
        ('aos_api.oc_global_search_router', 'router'),
        ('aos_api.oc_metric_toggle_router', 'router'),
        ('aos_api.oc_org_level_toggle_router', 'router'),
        ('aos_api.oc_permission_migration_router', 'router'),
        ('aos_api.oc_sidebar_filter_router', 'router'),
        ('aos_api.oe_admin_config_router', 'router'),
        ('aos_api.oe_app_sidebar_router', 'router'),
        ('aos_api.oe_column_config_router', 'router'),
        ('aos_api.oe_pivot_linked_router', 'router'),
        ('aos_api.oe_compare_objects_router', 'router'),
        ('aos_api.oe_metadata_state_router', 'router'),
        ('aos_api.oe_render_hint_router', 'router'),
        ('aos_api.oe_gotham_integration_router', 'router'),
        ('aos_api.oe_linked_view_router', 'router'),
        ('aos_api.oe_version_mgmt_router', 'router'),
        ('aos_api.oe_comment_system_router', 'router'),
        ('aos_api.oc_model_aiml_router', 'router'),
        ('aos_api.oc_audit_edit_dialog_router', 'router'),
        ('aos_api.oc_task_model_router', 'router'),
        ('aos_api.oc_review_view_router', 'router'),
        ('aos_api.oc_compute_attribution_router', 'router'),
        ('aos_api.oc_cross_ontology_migrate_router', 'router'),
        ('aos_api.oc_ontology_switcher_router', 'router'),
        ('aos_api.ob_billion_throughput_router', 'router'),
        ('aos_api.ob_osv1_osv2_router', 'router'),
        ('aos_api.ob_batch_reindex_router', 'router'),
        ('aos_api.ob_index_monitor_router', 'router'),
        ('aos_api.ob_object_monitor_router', 'router'),
        ('aos_api.ob_realtime_eval_router', 'router'),
        ('aos_api.ob_monitor_to_action_router', 'router'),
        ('aos_api.ob_monitor_activity_router', 'router'),
        ('aos_api.ob_granular_policy_router', 'router'),
        ('aos_api.ob_edit_history_router', 'router'),
        ('aos_api.ob_inline_edit_router', 'router'),
        ('aos_api.if_interface_metadata_router', 'router'),
        ('aos_api.oc_shared_ontology_router', 'router'),
        ('aos_api.zz_property_editor_router', 'router'),
        ('aos_api.zz_function_type_editor_router', 'router'),
        ('aos_api.zz_multi_source_heterogeneous_router', 'router'),
        ('aos_api.zz_graph_health_router', 'router'),
        ('aos_api.routers.phase4_ontology_types', 'router'),
        ('aos_api.routers.phase4_ontology_branches', 'router'),
        ('aos_api.routers.phase4_ontology_wikis', 'router'),
        ('aos_api.routers.phase4_ontology_functions', 'router'),
        ('aos_api.routers.phase4_ontology_actions', 'router'),
        ('aos_api.routers.phase4_ontology_links', 'router'),
    ),
    "aip": (
        ('aos_api.routers.wave_ext', 'router'),
        ('aos_api.routers.llm_routing', 'router'),
        ('aos_api.routers.llm_node_agent_proxy', 'router'),
        ('aos_api.routers.llm_extras', 'router'),
        ('aos_api.routers.logic', 'router'),
        ('aos_api.routers.evals', 'router'),
        ('aos_api.routers.file_processing', 'router'),
        ('aos_api.routers.tool_registry', 'router'),
        ('aos_api.routers.aip_nodes', 'router'),
        ('aos_api.routers.aip_extras', 'router'),
        ('aos_api.routers.aip_assist', 'router'),
        ('aos_api.routers.logic_flows', 'router'),
        ('aos_api.routers.l4_automation', 'router'),
        ('aos_api.routers.decision_audit', 'router'),
        ('aos_api.aip_langgraph_runtime_router', 'router'),
        ('aos_api.aip_propose_edits_router', 'router'),
        ('aos_api.aip_wiki_field_router', 'router'),
        ('aos_api.aip_logic_state_router', 'router'),
        ('aos_api.aip_logic_version_router', 'router'),
        ('aos_api.aip_debug_cot_router', 'router'),
        ('aos_api.aip_debug_tools_router', 'router'),
        ('aos_api.aip_eval_crud_router', 'router'),
        ('aos_api.aip_eval_gate_router', 'router'),
        ('aos_api.aip_eval_cross_model_router', 'router'),
        ('aos_api.aip_eval_dashboard_router', 'router'),
        ('aos_api.aip_eval_rag_router', 'router'),
        ('aos_api.aip_eval_gen_router', 'router'),
        ('aos_api.aip_eval_tool_router', 'router'),
        ('aos_api.aip_l4_gate_router', 'router'),
        ('aos_api.aip_l4_circuit_router', 'router'),
        ('aos_api.aip_app_state_router', 'router'),
        ('aos_api.aip_rag_context_router', 'router'),
        ('aos_api.aip_long_memory_router', 'router'),
        ('aos_api.aip_trace_logic_router', 'router'),
        ('aos_api.aip_metrics_router', 'router'),
        ('aos_api.aip_obs_dashboard_router', 'router'),
        ('aos_api.aip_alerts_router', 'router'),
        ('aos_api.aip_model_catalog_router', 'router'),
        ('aos_api.aip_model_capacity_router', 'router'),
        ('aos_api.aip_model_lifecycle_router', 'router'),
        ('aos_api.model_provider_credential_router', 'router'),
        ('aos_api.provider_security_router', 'router'),
        ('aos_api.provider_call_log_router', 'router'),
        ('aos_api.model_router_config_router', 'router'),
        ('aos_api.module_events_router', 'router'),
        ('aos_api.aip_assist_context_router', 'router'),
        ('aos_api.aip_assist_perms_router', 'router'),
        ('aos_api.aip_analyst_chart_router', 'router'),
        ('aos_api.aip_analyst_explore_router', 'router'),
        ('aos_api.aip_docintel_parse_router', 'router'),
        ('aos_api.aip_docintel_extract_router', 'router'),
        ('aos_api.aip_docintel_semantic_router', 'router'),
        ('aos_api.routers.phase3_aip_assist', 'router'),
        ('aos_api.routers.phase3_aip_agents', 'router'),
        ('aos_api.routers.phase3_aip_capabilities', 'router'),
        ('aos_api.routers.aip_tasks', 'router'),
        ('aos_api.routers.aip_actions', 'router'),
        ('aos_api.routers.phase3_aip_tools', 'router'),
        ('aos_api.routers.phase3_aip_drafts', 'router'),
        ('aos_api.routers.phase3_aip_lineage', 'router'),
        ('aos_api.routers.aip_analyst', 'router'),
        ('aos_api.routers.aip_logic_graphs', 'router'),
        ('aos_api.routers.aip_logic_runs', 'router'),
        ('aos_api.routers.aip_logic_publications', 'router'),
        ('aos_api.routers.aip_eval_authority', 'router'),
        ('aos_api.routers.aip_release_publications', 'router'),
        ('aos_api.routers.aip_lineage_authority', 'router'),
    ),
    "data": (
        ('aos_api.routers.builds', 'router'),
        ('aos_api.routers.shell_core', 'router'),
        ('aos_api.routers.sql_console', 'router'),
        ('aos_api.routers.writeback', 'router'),
        ('aos_api.routers.data_transaction', 'router'),
        ('aos_api.routers.expectation', 'router'),
        ('aos_api.routers.lineage', 'router'),
        ('aos_api.routers.lineage_views', 'router'),
        ('aos_api.routers.pipelines', 'router'),
        ('aos_api.routers.transforms', 'router'),
        ('aos_api.routers.python_functions', 'router'),
        ('aos_api.routers.functions', 'router'),
        ('aos_api.routers.function_types', 'router'),
        ('aos_api.routers.functions_dev_tools', 'router'),
        ('aos_api.routers.pipeline_outputs', 'router'),
        ('aos_api.routers.pipeline_type_semantics', 'router'),
        ('aos_api.routers.pipeline_builder_extra', 'router'),
        ('aos_api.routers.pipeline_canvas_extras', 'router'),
        ('aos_api.routers.pipeline_ui_components', 'router'),
        ('aos_api.routers.triggers_and_link_output', 'router'),
        ('aos_api.routers.code_collaboration', 'router'),
        ('aos_api.routers.column_impact', 'router'),
        ('aos_api.routers.connection_cdc_schedule', 'router'),
        ('aos_api.routers.data_connection_admin', 'router'),
        ('aos_api.routers.data_connection_extras', 'router'),
        ('aos_api.routers.data_connection_export', 'router'),
        ('aos_api.routers.data_connection_webhook', 'router'),
        ('aos_api.routers.data_connection_security', 'router'),
        ('aos_api.routers.lineage_visualization', 'router'),
        ('aos_api.routers.data_health', 'router'),
        ('aos_api.routers.data_health_plus', 'router'),
        ('aos_api.routers.data_health_integration', 'router'),
        ('aos_api.routers.dataset_preview_health', 'router'),
        ('aos_api.routers.functions_runtime', 'router'),
        ('aos_api.routers.timeseries_sap_functions', 'router'),
        ('aos_api.routers.dc_completion_strategy', 'router'),
        ('aos_api.routers.dc_stream_mgmt', 'router'),
        ('aos_api.routers.dc_erp_crm', 'router'),
        ('aos_api.routers.di_view_lineage', 'router'),
        ('aos_api.routers.di_task_debug', 'router'),
        ('aos_api.routers.dl_build_strategy', 'router'),
        ('aos_api.routers.dl_build_preview', 'router'),
        ('aos_api.routers.dl_dep_order', 'router'),
        ('aos_api.routers.dl_stale_diagnosis', 'router'),
        ('aos_api.routers.pb_build_vs_deploy', 'router'),
        ('aos_api.routers.pb_build_profiles', 'router'),
        ('aos_api.routers.pb_task_groups', 'router'),
        ('aos_api.routers.pb_health_checks', 'router'),
        ('aos_api.routers.cr_branch_menu', 'router'),
        ('aos_api.routers.cr_pipeline_review', 'router'),
        ('aos_api.routers.id_py_transform_preview', 'router'),
        ('aos_api.routers.id_build_panel', 'router'),
        ('aos_api.routers.id_build_status', 'router'),
        ('aos_api.bd_dep_task_abort_router', 'router'),
        ('aos_api.bd_force_build_router', 'router'),
        ('aos_api.bd_freshness_router', 'router'),
        ('aos_api.cr_build_affected_router', 'router'),
        ('aos_api.cr_default_branch_router', 'router'),
        ('aos_api.cr_fallback_branch_router', 'router'),
        ('aos_api.cr_impact_analysis_router', 'router'),
        ('aos_api.dc_agent_yaml_router', 'router'),
        ('aos_api.dc_app_state_router', 'router'),
        ('aos_api.dc_curl_import_router', 'router'),
        ('aos_api.dc_export_tasks_router', 'router'),
        ('aos_api.dc_stream_preview_router', 'router'),
        ('aos_api.dc_sync_troubleshoot_router', 'router'),
        ('aos_api.dc_test_connection_router', 'router'),
        ('aos_api.dc_webhook_source_router', 'router'),
        ('aos_api.di_auto_dedup_router', 'router'),
        ('aos_api.di_auto_register_router', 'router'),
        ('aos_api.di_compression_toggle_router', 'router'),
        ('aos_api.di_consistency_guarantee_router', 'router'),
        ('aos_api.di_data_consistency_router', 'router'),
        ('aos_api.di_dataset_branch_router', 'router'),
        ('aos_api.di_db_schema_table_router', 'router'),
        ('aos_api.di_export_config_router', 'router'),
        ('aos_api.di_external_access_router', 'router'),
        ('aos_api.di_external_transforms_router', 'router'),
        ('aos_api.di_force_build_router', 'router'),
        ('aos_api.di_freshness_detect_router', 'router'),
        ('aos_api.di_hot_cold_storage_router', 'router'),
        ('aos_api.di_key_by_router', 'router'),
        ('aos_api.di_latency_sampling_router', 'router'),
        ('aos_api.di_live_archive_router', 'router'),
        ('aos_api.di_logic_change_trigger_router', 'router'),
        ('aos_api.di_output_path_router', 'router'),
        ('aos_api.di_partition_control_router', 'router'),
        ('aos_api.di_permission_roles_router', 'router'),
        ('aos_api.di_primary_key_config_router', 'router'),
        ('aos_api.di_reset_stream_router', 'router'),
        ('aos_api.di_s3_api_router', 'router'),
        ('aos_api.di_source_based_transform_router', 'router'),
        ('aos_api.di_spark_engine_router', 'router'),
        ('aos_api.di_stream_schema_router', 'router'),
        ('aos_api.di_streaming_latency_router', 'router'),
        ('aos_api.di_text_extraction_router', 'router'),
        ('aos_api.di_third_party_access_router', 'router'),
        ('aos_api.di_transforms_external_router', 'router'),
        ('aos_api.di_view_creation_router', 'router'),
        ('aos_api.di_virtual_storage_router', 'router'),
        ('aos_api.di_virtual_table_router', 'router'),
        ('aos_api.dl_branch_aware_router', 'router'),
        ('aos_api.dl_chart_tools_router', 'router'),
        ('aos_api.dl_dataset_preview_300_router', 'router'),
        ('aos_api.dl_faq_troubleshoot_router', 'router'),
        ('aos_api.dl_flow_animation_router', 'router'),
        ('aos_api.dl_node_indicators_router', 'router'),
        ('aos_api.dl_permission_coloring_router', 'router'),
        ('aos_api.dl_permission_simulation_router', 'router'),
        ('aos_api.dl_plan_management_router', 'router'),
        ('aos_api.dl_property_histogram_router', 'router'),
        ('aos_api.dl_related_artifacts_router', 'router'),
        ('aos_api.dl_share_permission_router', 'router'),
        ('aos_api.dl_stale_coloring_router', 'router'),
        ('aos_api.dl_svg_export_router', 'router'),
        ('aos_api.dl_user_permission_view_router', 'router'),
        ('aos_api.fn_pipeline_status_router', 'router'),
        ('aos_api.id_feature_matrix_router', 'router'),
        ('aos_api.id_osdk_react_router', 'router'),
        ('aos_api.pb_add_data_modes_router', 'router'),
        ('aos_api.pb_ai_functions_router', 'router'),
        ('aos_api.pb_branch_activity_router', 'router'),
        ('aos_api.pb_branch_version_router', 'router'),
        ('aos_api.pb_color_groups_router', 'router'),
        ('aos_api.pb_data_expectations_router', 'router'),
        ('aos_api.pb_detail_sidebar_router', 'router'),
        ('aos_api.pb_export_java_router', 'router'),
        ('aos_api.pb_fp_growth_router', 'router'),
        ('aos_api.pb_history_records_router', 'router'),
        ('aos_api.pb_marketplace_pkg_router', 'router'),
        ('aos_api.pb_override_dataset_router', 'router'),
        ('aos_api.pb_param_system_router', 'router'),
        ('aos_api.pb_show_hide_nodes_router', 'router'),
        ('aos_api.pb_snapshot_incremental_router', 'router'),
        ('aos_api.pb_structured_semi_router', 'router'),
        ('aos_api.pb_transform_library_router', 'router'),
        ('aos_api.pb_unit_test_router', 'router'),
        ('aos_api.pb_view_switch_router', 'router'),
        ('aos_api.pb_virtual_data_gen_router', 'router'),
        ('aos_api.di_stream_alert_router', 'router'),
        ('aos_api.di_monitor_rule_router', 'router'),
        ('aos_api.di_notif_sub_router', 'router'),
        ('aos_api.di_checkpoint_ft_router', 'router'),
        ('aos_api.di_backing_ds_router', 'router'),
        ('aos_api.di_live_log_router', 'router'),
        ('aos_api.di_schema_config_router', 'router'),
        ('aos_api.di_detail_subpanel_router', 'router'),
        ('aos_api.dh_health_summary_router', 'router'),
        ('aos_api.dh_troubleshoot_guide_router', 'router'),
        ('aos_api.dl_ontology_browse_router', 'router'),
        ('aos_api.dl_history_detail_router', 'router'),
        ('aos_api.dl_save_open_chart_router', 'router'),
        ('aos_api.dl_share_link_router', 'router'),
        ('aos_api.pb_breaking_change_detect_router', 'router'),
        ('aos_api.cr_model_dev_repo_router', 'router'),
        ('aos_api.cr_doc_assist_router', 'router'),
        ('aos_api.cr_pr_review_router', 'router'),
        ('aos_api.cr_code_review_req_router', 'router'),
        ('aos_api.cr_dataset_alias_router', 'router'),
        ('aos_api.cr_multi_artifact_router', 'router'),
        ('aos_api.cr_artifact_credential_router', 'router'),
        ('aos_api.cr_artifact_registry_router', 'router'),
        ('aos_api.cr_ai_error_enhance_router', 'router'),
        ('aos_api.cr_aip_template_recommend_router', 'router'),
        ('aos_api.mt_code_reuse_router', 'router'),
        ('aos_api.id_shell_terminal_router', 'router'),
        ('aos_api.id_key_binding_router', 'router'),
        ('aos_api.id_vsix_install_router', 'router'),
        ('aos_api.id_command_palette_router', 'router'),
        ('aos_api.id_python_snippet_router', 'router'),
        ('aos_api.id_refresh_token_router', 'router'),
        ('aos_api.id_install_python_env_router', 'router'),
        ('aos_api.id_public_extension_router', 'router'),
        ('aos_api.di_virtual_table_create_router', 'router'),
        ('aos_api.dh_escalate_router', 'router'),
        ('aos_api.pb_expr_func_index_router', 'router'),
        ('aos_api.cr_transform_repo_router', 'router'),
        ('aos_api.cr_editor_context_menu_router', 'router'),
        ('aos_api.cr_spark_profiles_router', 'router'),
        ('aos_api.cr_docker_artifact_publish_router', 'router'),
        ('aos_api.cr_code_autocomplete_router', 'router'),
        ('aos_api.mt_python_transform_df_router', 'router'),
        ('aos_api.mt_java_transform_api_router', 'router'),
        ('aos_api.mt_r_transform_router', 'router'),
        ('aos_api.mt_spark_version_mgmt_router', 'router'),
        ('aos_api.mt_unit_test_router', 'router'),
        ('aos_api.mt_data_expectations_router', 'router'),
        ('aos_api.id_geospatial_framework_router', 'router'),
        ('aos_api.id_vertex_digital_twin_router', 'router'),
        ('aos_api.id_timeseries_router', 'router'),
        ('aos_api.routers.phase5_pipelines', 'router'),
        ('aos_api.routers.phase5_schedules', 'router'),
        ('aos_api.routers.phase5_datasets', 'router'),
        ('aos_api.routers.phase6_connectors', 'router'),
        ('aos_api.routers.phase6_sources', 'router'),
        ('aos_api.routers.phase6_schemas', 'router'),
        ('aos_api.routers.phase6_syncs', 'router'),
        ('aos_api.routers.phase6_media_sets', 'router'),
        ('aos_api.routers.phase6_documents', 'router'),
    ),
    "model": (
        ('aos_api.routers.gantt_ml_drag_pricing', 'router'),
        ('aos_api.gs_ontology_geo_router', 'router'),
        ('aos_api.gs_geospatial_framework_router', 'router'),
        ('aos_api.gs_coord_projection_router', 'router'),
        ('aos_api.gs_map_layer_overlay_router', 'router'),
        ('aos_api.gs_map_template_router', 'router'),
        ('aos_api.gs_digital_twin_engine_router', 'router'),
        ('aos_api.gs_causal_analysis_router', 'router'),
        ('aos_api.gs_realtime_situation_router', 'router'),
        ('aos_api.gs_timeseries_object_type_router', 'router'),
        ('aos_api.gs_sensor_data_model_router', 'router'),
        ('aos_api.routers.model_catalog', 'router'),
        ('aos_api.routers.model_providers', 'router'),
        ('aos_api.routers.model_routes', 'router'),
        ('aos_api.routers.model_capacity', 'router'),
    ),
    "apollo": (
        ('aos_api.cp_multi_spoke_monitor_router', 'router'),
        ('aos_api.hs_remote_dispatch_router', 'router'),
        ('aos_api.hs_status_report_back_router', 'router'),
        ('aos_api.fr2_incremental_package_router', 'router'),
        ('aos_api.cp_realtime_situation_router', 'router'),
        ('aos_api.cp_alert_router', 'router'),
        ('aos_api.routers.phase7_hub_spokes', 'router'),
        ('aos_api.routers.phase7_releases', 'router'),
        ('aos_api.routers.phase7_ferry', 'router'),
    ),
}


def _create_domain_router(domain: str, tag: str) -> APIRouter:
    """Import every child before registration, preserving manifest order."""
    aggregate = APIRouter(prefix="", tags=[tag])
    children = [
        getattr(import_module(module), attribute)
        for module, attribute in ROUTER_SPECS[domain]
    ]
    for child in children:
        aggregate.include_router(child)
    return aggregate


def create_infra_router() -> APIRouter:
    """Create the Infra aggregate in manifest order."""
    return _create_domain_router("infra", "Infra")


def create_admin_router() -> APIRouter:
    """Create the Admin aggregate in manifest order."""
    return _create_domain_router("admin", "Admin")


def create_system_router() -> APIRouter:
    """Create the System aggregate in manifest order."""
    return _create_domain_router("system", "System")


def create_agent_router() -> APIRouter:
    """Create the Agent aggregate in manifest order."""
    return _create_domain_router("agent", "Agent")


def create_workshop_router() -> APIRouter:
    """Create the Workshop aggregate in manifest order."""
    return _create_domain_router("workshop", "Workshop")


def create_ontology_router() -> APIRouter:
    """Create the Ontology aggregate in manifest order."""
    return _create_domain_router("ontology", "Ontology")


def create_aip_router() -> APIRouter:
    """Create the AIP aggregate in manifest order."""
    return _create_domain_router("aip", "AIP")


def create_data_router() -> APIRouter:
    """Create the Data aggregate in manifest order."""
    return _create_domain_router("data", "Data")


def create_model_router() -> APIRouter:
    """Create the Model aggregate in manifest order."""
    return _create_domain_router("model", "Model")


def create_apollo_router() -> APIRouter:
    """Create the Apollo aggregate in manifest order."""
    return _create_domain_router("apollo", "Apollo")


DOMAIN_ROUTERS = {
    "infra": create_infra_router,
    "admin": create_admin_router,
    "system": create_system_router,
    "agent": create_agent_router,
    "workshop": create_workshop_router,
    "ontology": create_ontology_router,
    "aip": create_aip_router,
    "data": create_data_router,
    "model": create_model_router,
    "apollo": create_apollo_router,
}
