"""Domain router aggregates — group all routers into 10 domain-level APIRouters.

Auto-generated by scripts/generate_domain_aggregates.py.
DO NOT EDIT MANUALLY — edit the generator script instead.
"""
from __future__ import annotations

from fastapi import APIRouter


def create_ontology_router() -> APIRouter:
    """Ontology domain: 72 routers."""
    r = APIRouter(prefix="", tags=["Ontology"])

    # -- from aos_api.routers import xxx --
    from aos_api.routers import (
        object_sets,
        object_storage_indexing,
        ontology,
        ontology_governance,
        ontology_management,
        ontology_data_layer,
        oe_enhancements,
        object_editing,
        oma_editor,
        type_system,
        funnel,
        funnel_mappings,
        ontology_roles,
        ontology_outputs,
        csv_ontology_export_action_metrics,
    )
    from aos_api.routers import (
        multi_language,
        object_views,
        object_explorer,
        multi_source,
        materialized_access_control,
        incremental_sync,
        ob_index_debug,
    )
    for m in [
        object_sets, object_storage_indexing, ontology, ontology_governance, ontology_management, ontology_data_layer, oe_enhancements, object_editing,
        oma_editor, type_system, funnel, funnel_mappings, ontology_roles, ontology_outputs, csv_ontology_export_action_metrics, multi_language,
        object_views, object_explorer, multi_source, materialized_access_control, incremental_sync, ob_index_debug,
    ]:
        r.include_router(m.router)

    # -- W4 routers (from aos_api.xxx_router import router as ...) --
    from aos_api.ob_agg_precision_router import router as ob_agg_precision_router
    from aos_api.ob_monitor_notify_router import router as ob_monitor_notify_router
    from aos_api.ob_stream_permission_router import router as ob_stream_permission_router
    from aos_api.oc_destructive_confirm_router import router as oc_destructive_confirm_router
    from aos_api.oc_global_search_router import router as oc_global_search_router
    from aos_api.oc_metric_toggle_router import router as oc_metric_toggle_router
    from aos_api.oc_org_level_toggle_router import router as oc_org_level_toggle_router
    from aos_api.oc_permission_migration_router import router as oc_permission_migration_router
    from aos_api.oc_sidebar_filter_router import router as oc_sidebar_filter_router
    from aos_api.oe_admin_config_router import router as oe_admin_config_router
    from aos_api.oe_app_sidebar_router import router as oe_app_sidebar_router
    from aos_api.oe_column_config_router import router as oe_column_config_router
    from aos_api.oe_pivot_linked_router import router as oe_pivot_linked_router
    from aos_api.oe_compare_objects_router import router as oe_compare_objects_router
    from aos_api.oe_metadata_state_router import router as oe_metadata_state_router
    from aos_api.oe_render_hint_router import router as oe_render_hint_router
    from aos_api.oe_gotham_integration_router import router as oe_gotham_integration_router
    from aos_api.oe_linked_view_router import router as oe_linked_view_router
    from aos_api.oe_version_mgmt_router import router as oe_version_mgmt_router
    from aos_api.oe_comment_system_router import router as oe_comment_system_router
    from aos_api.oc_model_aiml_router import router as oc_model_aiml_router
    from aos_api.oc_audit_edit_dialog_router import router as oc_audit_edit_dialog_router
    from aos_api.oc_task_model_router import router as oc_task_model_router
    from aos_api.oc_review_view_router import router as oc_review_view_router
    from aos_api.oc_compute_attribution_router import router as oc_compute_attribution_router
    from aos_api.oc_cross_ontology_migrate_router import router as oc_cross_ontology_migrate_router
    from aos_api.oc_ontology_switcher_router import router as oc_ontology_switcher_router
    from aos_api.ob_billion_throughput_router import router as ob_billion_throughput_router
    from aos_api.ob_osv1_osv2_router import router as ob_osv1_osv2_router
    from aos_api.ob_batch_reindex_router import router as ob_batch_reindex_router
    from aos_api.ob_index_monitor_router import router as ob_index_monitor_router
    from aos_api.ob_object_monitor_router import router as ob_object_monitor_router
    from aos_api.ob_realtime_eval_router import router as ob_realtime_eval_router
    from aos_api.ob_monitor_to_action_router import router as ob_monitor_to_action_router
    from aos_api.ob_monitor_activity_router import router as ob_monitor_activity_router
    from aos_api.ob_granular_policy_router import router as ob_granular_policy_router
    from aos_api.ob_edit_history_router import router as ob_edit_history_router
    from aos_api.ob_inline_edit_router import router as ob_inline_edit_router
    from aos_api.if_interface_metadata_router import router as if_interface_metadata_router
    from aos_api.oc_shared_ontology_router import router as oc_shared_ontology_router
    from aos_api.zz_property_editor_router import router as zz_property_editor_router
    from aos_api.zz_function_type_editor_router import router as zz_function_type_editor_router
    from aos_api.zz_multi_source_heterogeneous_router import router as zz_multi_source_heterogeneous_router
    from aos_api.zz_graph_health_router import router as zz_graph_health_router
    for m in [
        ob_agg_precision_router, ob_monitor_notify_router, ob_stream_permission_router, oc_destructive_confirm_router, oc_global_search_router, oc_metric_toggle_router, oc_org_level_toggle_router, oc_permission_migration_router,
        oc_sidebar_filter_router, oe_admin_config_router, oe_app_sidebar_router, oe_column_config_router, oe_pivot_linked_router, oe_compare_objects_router, oe_metadata_state_router, oe_render_hint_router,
        oe_gotham_integration_router, oe_linked_view_router, oe_version_mgmt_router, oe_comment_system_router, oc_model_aiml_router, oc_audit_edit_dialog_router, oc_task_model_router, oc_review_view_router,
        oc_compute_attribution_router, oc_cross_ontology_migrate_router, oc_ontology_switcher_router, ob_billion_throughput_router, ob_osv1_osv2_router, ob_batch_reindex_router, ob_index_monitor_router, ob_object_monitor_router,
        ob_realtime_eval_router, ob_monitor_to_action_router, ob_monitor_activity_router, ob_granular_policy_router, ob_edit_history_router, ob_inline_edit_router, if_interface_metadata_router, oc_shared_ontology_router,
        zz_property_editor_router, zz_function_type_editor_router, zz_multi_source_heterogeneous_router, zz_graph_health_router,
    ]:
        r.include_router(m)

    # -- Phase routers (from aos_api.routers.xxx import router as ...) --
    from aos_api.routers.phase4_ontology_types import router as phase4_ontology_types_router
    from aos_api.routers.phase4_ontology_branches import router as phase4_ontology_branches_router
    from aos_api.routers.phase4_ontology_wikis import router as phase4_ontology_wikis_router
    from aos_api.routers.phase4_ontology_functions import router as phase4_ontology_functions_router
    from aos_api.routers.phase4_ontology_actions import router as phase4_ontology_actions_router
    from aos_api.routers.phase4_ontology_links import router as phase4_ontology_links_router
    for m in [
        phase4_ontology_types_router, phase4_ontology_branches_router, phase4_ontology_wikis_router, phase4_ontology_functions_router, phase4_ontology_actions_router, phase4_ontology_links_router,
    ]:
        r.include_router(m)

    return r

def create_workshop_router() -> APIRouter:
    """Workshop domain: 115 routers."""
    r = APIRouter(prefix="", tags=["Workshop"])

    # -- from aos_api.routers import xxx --
    from aos_api.routers import (
        modules,
        workshop_phase1,
        actions,
        drafts,
        gantt,
        action_enhancements,
        action_params,
        action_further,
        action_webhook,
        action_finale,
        compute_module,
        compute_module_extras,
        compute_module_publish,
        dev_tooling,
        media_references,
    )
    from aos_api.routers import (
        media_set_browser_interaction,
        media_sets,
        action_rules,
        action_visual_editor,
        integration_maintenance,
        scheduling,
        scheduling_rules_lint,
        web_ide,
        workshop_compute_api,
        ds_context_menu,
        pp_toolbar_settings,
        ms_header_extractor,
    )
    for m in [
        modules, workshop_phase1, actions, drafts, gantt, action_enhancements, action_params, action_further,
        action_webhook, action_finale, compute_module, compute_module_extras, compute_module_publish, dev_tooling, media_references, media_set_browser_interaction,
        media_sets, action_rules, action_visual_editor, integration_maintenance, scheduling, scheduling_rules_lint, web_ide, workshop_compute_api,
        ds_context_menu, pp_toolbar_settings, ms_header_extractor,
    ]:
        r.include_router(m.router)

    # -- W4 routers (from aos_api.xxx_router import router as ...) --
    from aos_api.af_action_types_router import router as af_action_types_router
    from aos_api.af_capabilities_router import router as af_capabilities_router
    from aos_api.af_edit_counter_router import router as af_edit_counter_router
    from aos_api.af_edited_marker_router import router as af_edited_marker_router
    from aos_api.af_oma_editor_router import router as af_oma_editor_router
    from aos_api.af_param_help_router import router as af_param_help_router
    from aos_api.at_action_apply_perm_router import router as at_action_apply_perm_router
    from aos_api.at_edit_only_mode_router import router as at_edit_only_mode_router
    from aos_api.at_marketplace_types_router import router as at_marketplace_types_router
    from aos_api.at_notification_link_router import router as at_notification_link_router
    from aos_api.at_notification_permission_router import router as at_notification_permission_router
    from aos_api.at_side_effect_perm_router import router as at_side_effect_perm_router
    from aos_api.ds_backtick_search_router import router as ds_backtick_search_router
    from aos_api.ds_inline_upload_router import router as ds_inline_upload_router
    from aos_api.ms_create_pipeline_menu_router import router as ms_create_pipeline_menu_router
    from aos_api.ms_file_add_router import router as ms_file_add_router
    from aos_api.pp_chart_drag_select_router import router as pp_chart_drag_select_router
    from aos_api.pp_chart_pan_router import router as pp_chart_pan_router
    from aos_api.pp_cross_project_flow_router import router as pp_cross_project_flow_router
    from aos_api.pp_mediasets_code_router import router as pp_mediasets_code_router
    from aos_api.pp_parse_paths_router import router as pp_parse_paths_router
    from aos_api.pp_role_permission_router import router as pp_role_permission_router
    from aos_api.pp_toolbar_share_router import router as pp_toolbar_share_router
    from aos_api.wk_conditional_section_router import router as wk_conditional_section_router
    from aos_api.wk_widget_permission_router import router as wk_widget_permission_router
    from aos_api.ds_schedule_panel_router import router as ds_schedule_panel_router
    from aos_api.ds_share_move_rename_router import router as ds_share_move_rename_router
    from aos_api.ds_stream_preview_router import router as ds_stream_preview_router
    from aos_api.ds_stream_tag_router import router as ds_stream_tag_router
    from aos_api.ds_schema_infer_router import router as ds_schema_infer_router
    from aos_api.ds_edit_schema_view_router import router as ds_edit_schema_view_router
    from aos_api.ds_col_autocomplete_router import router as ds_col_autocomplete_router
    from aos_api.ds_keyboard_shortcut_router import router as ds_keyboard_shortcut_router
    from aos_api.ds_resize_panel_router import router as ds_resize_panel_router
    from aos_api.ds_same_name_logic_router import router as ds_same_name_logic_router
    from aos_api.ds_sql_draft_router import router as ds_sql_draft_router
    from aos_api.pp_incremental_perf_router import router as pp_incremental_perf_router
    from aos_api.pp_schema_infer_router import router as pp_schema_infer_router
    from aos_api.pp_advanced_schedule_router import router as pp_advanced_schedule_router
    from aos_api.pp_schedule_troubleshoot_router import router as pp_schedule_troubleshoot_router
    from aos_api.pp_schedule_best_practice_router import router as pp_schedule_best_practice_router
    from aos_api.pp_schedule_template_router import router as pp_schedule_template_router
    from aos_api.pp_classify_tag_router import router as pp_classify_tag_router
    from aos_api.pp_propagate_view_router import router as pp_propagate_view_router
    from aos_api.pp_org_tag_router import router as pp_org_tag_router
    from aos_api.pp_tag_reapproval_router import router as pp_tag_reapproval_router
    from aos_api.pp_io_classify_router import router as pp_io_classify_router
    from aos_api.pp_schedule_coloring_router import router as pp_schedule_coloring_router
    from aos_api.pp_folder_convention_router import router as pp_folder_convention_router
    from aos_api.pp_dev_best_practice_router import router as pp_dev_best_practice_router
    from aos_api.pp_prod_pipeline_build_router import router as pp_prod_pipeline_build_router
    from aos_api.pp_connect_stream_router import router as pp_connect_stream_router
    from aos_api.ms_small_file_shortcut_router import router as ms_small_file_shortcut_router
    from aos_api.ms_docintel_dlq_router import router as ms_docintel_dlq_router
    from aos_api.ms_latency_policy_router import router as ms_latency_policy_router
    from aos_api.ms_transcript_postproc_router import router as ms_transcript_postproc_router
    from aos_api.ms_transcript_output_router import router as ms_transcript_output_router
    from aos_api.ms_audio_import_path_router import router as ms_audio_import_path_router
    from aos_api.ms_primary_key_router import router as ms_primary_key_router
    from aos_api.af_archetypes_toggle_router import router as af_archetypes_toggle_router
    from aos_api.at_param_desc_router import router as at_param_desc_router
    from aos_api.at_value_source_router import router as at_value_source_router
    from aos_api.at_rule_order_conflict_router import router as at_rule_order_conflict_router
    from aos_api.at_oma_7tab_router import router as at_oma_7tab_router
    from aos_api.at_archetypes_toggle_router import router as at_archetypes_toggle_router
    from aos_api.at_edit_count_warn_router import router as at_edit_count_warn_router
    from aos_api.at_edited_marker_router import router as at_edited_marker_router
    from aos_api.at_func_op_types_router import router as at_func_op_types_router
    from aos_api.at_func_onboarding_router import router as at_func_onboarding_router
    from aos_api.ca_platform_facade_router import router as ca_platform_facade_router
    from aos_api.ca_heavy_capability_router import router as ca_heavy_capability_router
    from aos_api.sc_logic_change_trigger_router import router as sc_logic_change_trigger_router
    from aos_api.sc_calendar_view_router import router as sc_calendar_view_router
    from aos_api.sc_readonly_dynamic_router import router as sc_readonly_dynamic_router
    from aos_api.sc_dynamic_drag_drop_router import router as sc_dynamic_drag_drop_router
    from aos_api.rl_rule_workflow_router import router as rl_rule_workflow_router
    from aos_api.rl_transform_pipeline_rule_router import router as rl_transform_pipeline_rule_router
    from aos_api.rl_workshop_integration_router import router as rl_workshop_integration_router
    from aos_api.wk_overlay_router import router as wk_overlay_router
    from aos_api.wk_object_table_advanced_router import router as wk_object_table_advanced_router
    from aos_api.ms_java_transform_integration_router import router as ms_java_transform_integration_router
    from aos_api.ms_form_parser_router import router as ms_form_parser_router
    from aos_api.ms_multi_sheet_output_router import router as ms_multi_sheet_output_router
    from aos_api.ms_incremental_process_router import router as ms_incremental_process_router
    from aos_api.ms_error_dataframe_router import router as ms_error_dataframe_router
    from aos_api.ms_spark_mem_config_router import router as ms_spark_mem_config_router
    from aos_api.ms_api_javadoc_router import router as ms_api_javadoc_router
    from aos_api.wk_embedded_copilot_router import router as wk_embedded_copilot_router
    for m in [
        af_action_types_router, af_capabilities_router, af_edit_counter_router, af_edited_marker_router, af_oma_editor_router, af_param_help_router, at_action_apply_perm_router, at_edit_only_mode_router,
        at_marketplace_types_router, at_notification_link_router, at_notification_permission_router, at_side_effect_perm_router, ds_backtick_search_router, ds_inline_upload_router, ms_create_pipeline_menu_router, ms_file_add_router,
        pp_chart_drag_select_router, pp_chart_pan_router, pp_cross_project_flow_router, pp_mediasets_code_router, pp_parse_paths_router, pp_role_permission_router, pp_toolbar_share_router, wk_conditional_section_router,
        wk_widget_permission_router, ds_schedule_panel_router, ds_share_move_rename_router, ds_stream_preview_router, ds_stream_tag_router, ds_schema_infer_router, ds_edit_schema_view_router, ds_col_autocomplete_router,
        ds_keyboard_shortcut_router, ds_resize_panel_router, ds_same_name_logic_router, ds_sql_draft_router, pp_incremental_perf_router, pp_schema_infer_router, pp_advanced_schedule_router, pp_schedule_troubleshoot_router,
        pp_schedule_best_practice_router, pp_schedule_template_router, pp_classify_tag_router, pp_propagate_view_router, pp_org_tag_router, pp_tag_reapproval_router, pp_io_classify_router, pp_schedule_coloring_router,
        pp_folder_convention_router, pp_dev_best_practice_router, pp_prod_pipeline_build_router, pp_connect_stream_router, ms_small_file_shortcut_router, ms_docintel_dlq_router, ms_latency_policy_router, ms_transcript_postproc_router,
        ms_transcript_output_router, ms_audio_import_path_router, ms_primary_key_router, af_archetypes_toggle_router, at_param_desc_router, at_value_source_router, at_rule_order_conflict_router, at_oma_7tab_router,
        at_archetypes_toggle_router, at_edit_count_warn_router, at_edited_marker_router, at_func_op_types_router, at_func_onboarding_router, ca_platform_facade_router, ca_heavy_capability_router, sc_logic_change_trigger_router,
        sc_calendar_view_router, sc_readonly_dynamic_router, sc_dynamic_drag_drop_router, rl_rule_workflow_router, rl_transform_pipeline_rule_router, rl_workshop_integration_router, wk_overlay_router, wk_object_table_advanced_router,
        ms_java_transform_integration_router, ms_form_parser_router, ms_multi_sheet_output_router, ms_incremental_process_router, ms_error_dataframe_router, ms_spark_mem_config_router, ms_api_javadoc_router, wk_embedded_copilot_router,
    ]:
        r.include_router(m)

    return r

def create_aip_router() -> APIRouter:
    """AIP domain: 60 routers."""
    r = APIRouter(prefix="", tags=["AIP"])

    # -- from aos_api.routers import xxx --
    from aos_api.routers import (
        wave_ext,
        llm_routing,
        llm_node_agent_proxy,
        llm_extras,
        logic,
        evals,
        file_processing,
        tool_registry,
        aip_nodes,
        aip_extras,
        aip_assist,
        logic_flows,
        l4_automation,
        decision_audit,
    )
    for m in [
        wave_ext, llm_routing, llm_node_agent_proxy, llm_extras, logic, evals, file_processing, tool_registry,
        aip_nodes, aip_extras, aip_assist, logic_flows, l4_automation, decision_audit,
    ]:
        r.include_router(m.router)

    # -- AIP routers (from aos_api import xxx → .router) --
    from aos_api import aip_langgraph_runtime_router
    from aos_api import aip_propose_edits_router
    from aos_api import aip_wiki_field_router
    from aos_api import aip_logic_state_router
    from aos_api import aip_logic_version_router
    from aos_api import aip_debug_cot_router
    from aos_api import aip_debug_tools_router
    from aos_api import aip_eval_crud_router
    from aos_api import aip_eval_gate_router
    from aos_api import aip_eval_cross_model_router
    from aos_api import aip_eval_dashboard_router
    from aos_api import aip_eval_rag_router
    from aos_api import aip_eval_gen_router
    from aos_api import aip_eval_tool_router
    from aos_api import aip_l4_gate_router
    from aos_api import aip_l4_circuit_router
    from aos_api import aip_app_state_router
    from aos_api import aip_rag_context_router
    from aos_api import aip_long_memory_router
    from aos_api import aip_trace_logic_router
    from aos_api import aip_metrics_router
    from aos_api import aip_obs_dashboard_router
    from aos_api import aip_alerts_router
    from aos_api import aip_model_catalog_router
    from aos_api import aip_model_capacity_router
    from aos_api import aip_model_lifecycle_router
    from aos_api import model_provider_credential_router
    from aos_api import provider_security_router
    from aos_api import provider_call_log_router
    from aos_api import model_router_config_router
    from aos_api import module_events_router
    from aos_api import aip_assist_context_router
    from aos_api import aip_assist_perms_router
    from aos_api import aip_analyst_chart_router
    from aos_api import aip_analyst_explore_router
    from aos_api import aip_docintel_parse_router
    from aos_api import aip_docintel_extract_router
    from aos_api import aip_docintel_semantic_router
    for m in [
        aip_langgraph_runtime_router, aip_propose_edits_router, aip_wiki_field_router, aip_logic_state_router, aip_logic_version_router, aip_debug_cot_router, aip_debug_tools_router, aip_eval_crud_router,
        aip_eval_gate_router, aip_eval_cross_model_router, aip_eval_dashboard_router, aip_eval_rag_router, aip_eval_gen_router, aip_eval_tool_router, aip_l4_gate_router, aip_l4_circuit_router,
        aip_app_state_router, aip_rag_context_router, aip_long_memory_router, aip_trace_logic_router, aip_metrics_router, aip_obs_dashboard_router, aip_alerts_router, aip_model_catalog_router,
        aip_model_capacity_router, aip_model_lifecycle_router, model_provider_credential_router, provider_security_router, provider_call_log_router, model_router_config_router, module_events_router, aip_assist_context_router,
        aip_assist_perms_router, aip_analyst_chart_router, aip_analyst_explore_router, aip_docintel_parse_router, aip_docintel_extract_router, aip_docintel_semantic_router,
    ]:
        r.include_router(m.router)

    # -- Phase routers (from aos_api.routers.xxx import router as ...) --
    from aos_api.routers.phase3_aip_assist import router as phase3_aip_assist_router
    from aos_api.routers.phase3_aip_agents import router as phase3_aip_agents_router
    from aos_api.routers.phase3_aip_capabilities import router as phase3_aip_capabilities_router
    from aos_api.routers.phase3_aip_logic import router as phase3_aip_logic_router
    from aos_api.routers.phase3_aip_tools import router as phase3_aip_tools_router
    from aos_api.routers.phase3_aip_drafts import router as phase3_aip_drafts_router
    from aos_api.routers.phase3_aip_lineage import router as phase3_aip_lineage_router
    from aos_api.routers.aip_analyst import router as aip_analyst_router
    for m in [
        phase3_aip_assist_router, phase3_aip_agents_router, phase3_aip_capabilities_router, phase3_aip_logic_router, phase3_aip_tools_router, phase3_aip_drafts_router, phase3_aip_lineage_router, aip_analyst_router,
    ]:
        r.include_router(m)

    return r

def create_data_router() -> APIRouter:
    """Data domain: 199 routers."""
    r = APIRouter(prefix="", tags=["Data"])

    # -- from aos_api.routers import xxx --
    from aos_api.routers import (
        builds,
        shell_core,
        sql_console,
        writeback,
        data_transaction,
        expectation,
        lineage,
        lineage_views,
        pipelines,
        transforms,
        python_functions,
        functions,
        function_types,
        functions_dev_tools,
        pipeline_outputs,
    )
    from aos_api.routers import (
        pipeline_type_semantics,
        pipeline_builder_extra,
        pipeline_canvas_extras,
        pipeline_ui_components,
        triggers_and_link_output,
        code_collaboration,
        column_impact,
        connection_cdc_schedule,
        data_connection_admin,
        data_connection_extras,
        data_connection_export,
        data_connection_webhook,
        data_connection_security,
        lineage_visualization,
        data_health,
    )
    from aos_api.routers import (
        data_health_plus,
        data_health_integration,
        dataset_preview_health,
        functions_runtime,
        timeseries_sap_functions,
        dc_completion_strategy,
        dc_stream_mgmt,
        dc_erp_crm,
        di_view_lineage,
        di_task_debug,
        dl_build_strategy,
        dl_build_preview,
        dl_dep_order,
        dl_stale_diagnosis,
        pb_build_vs_deploy,
    )
    from aos_api.routers import (
        pb_build_profiles,
        pb_task_groups,
        pb_health_checks,
        cr_branch_menu,
        cr_pipeline_review,
        id_py_transform_preview,
        id_build_panel,
        id_build_status,
    )
    for m in [
        builds, shell_core, sql_console, writeback, data_transaction, expectation, lineage, lineage_views,
        pipelines, transforms, python_functions, functions, function_types, functions_dev_tools, pipeline_outputs, pipeline_type_semantics,
        pipeline_builder_extra, pipeline_canvas_extras, pipeline_ui_components, triggers_and_link_output, code_collaboration, column_impact, connection_cdc_schedule, data_connection_admin,
        data_connection_extras, data_connection_export, data_connection_webhook, data_connection_security, lineage_visualization, data_health, data_health_plus, data_health_integration,
        dataset_preview_health, functions_runtime, timeseries_sap_functions, dc_completion_strategy, dc_stream_mgmt, dc_erp_crm, di_view_lineage, di_task_debug,
        dl_build_strategy, dl_build_preview, dl_dep_order, dl_stale_diagnosis, pb_build_vs_deploy, pb_build_profiles, pb_task_groups, pb_health_checks,
        cr_branch_menu, cr_pipeline_review, id_py_transform_preview, id_build_panel, id_build_status,
    ]:
        r.include_router(m.router)

    # -- W4 routers (from aos_api.xxx_router import router as ...) --
    from aos_api.bd_dep_task_abort_router import router as bd_dep_task_abort_router
    from aos_api.bd_force_build_router import router as bd_force_build_router
    from aos_api.bd_freshness_router import router as bd_freshness_router
    from aos_api.cr_build_affected_router import router as cr_build_affected_router
    from aos_api.cr_default_branch_router import router as cr_default_branch_router
    from aos_api.cr_fallback_branch_router import router as cr_fallback_branch_router
    from aos_api.cr_impact_analysis_router import router as cr_impact_analysis_router
    from aos_api.dc_agent_yaml_router import router as dc_agent_yaml_router
    from aos_api.dc_app_state_router import router as dc_app_state_router
    from aos_api.dc_curl_import_router import router as dc_curl_import_router
    from aos_api.dc_export_tasks_router import router as dc_export_tasks_router
    from aos_api.dc_stream_preview_router import router as dc_stream_preview_router
    from aos_api.dc_sync_troubleshoot_router import router as dc_sync_troubleshoot_router
    from aos_api.dc_test_connection_router import router as dc_test_connection_router
    from aos_api.dc_webhook_source_router import router as dc_webhook_source_router
    from aos_api.di_auto_dedup_router import router as di_auto_dedup_router
    from aos_api.di_auto_register_router import router as di_auto_register_router
    from aos_api.di_compression_toggle_router import router as di_compression_toggle_router
    from aos_api.di_consistency_guarantee_router import router as di_consistency_guarantee_router
    from aos_api.di_data_consistency_router import router as di_data_consistency_router
    from aos_api.di_dataset_branch_router import router as di_dataset_branch_router
    from aos_api.di_db_schema_table_router import router as di_db_schema_table_router
    from aos_api.di_export_config_router import router as di_export_config_router
    from aos_api.di_external_access_router import router as di_external_access_router
    from aos_api.di_external_transforms_router import router as di_external_transforms_router
    from aos_api.di_force_build_router import router as di_force_build_router
    from aos_api.di_freshness_detect_router import router as di_freshness_detect_router
    from aos_api.di_hot_cold_storage_router import router as di_hot_cold_storage_router
    from aos_api.di_key_by_router import router as di_key_by_router
    from aos_api.di_latency_sampling_router import router as di_latency_sampling_router
    from aos_api.di_live_archive_router import router as di_live_archive_router
    from aos_api.di_logic_change_trigger_router import router as di_logic_change_trigger_router
    from aos_api.di_output_path_router import router as di_output_path_router
    from aos_api.di_partition_control_router import router as di_partition_control_router
    from aos_api.di_permission_roles_router import router as di_permission_roles_router
    from aos_api.di_primary_key_config_router import router as di_primary_key_config_router
    from aos_api.di_reset_stream_router import router as di_reset_stream_router
    from aos_api.di_s3_api_router import router as di_s3_api_router
    from aos_api.di_source_based_transform_router import router as di_source_based_transform_router
    from aos_api.di_spark_engine_router import router as di_spark_engine_router
    from aos_api.di_stream_schema_router import router as di_stream_schema_router
    from aos_api.di_streaming_latency_router import router as di_streaming_latency_router
    from aos_api.di_text_extraction_router import router as di_text_extraction_router
    from aos_api.di_third_party_access_router import router as di_third_party_access_router
    from aos_api.di_transforms_external_router import router as di_transforms_external_router
    from aos_api.di_view_creation_router import router as di_view_creation_router
    from aos_api.di_virtual_storage_router import router as di_virtual_storage_router
    from aos_api.di_virtual_table_router import router as di_virtual_table_router
    from aos_api.dl_branch_aware_router import router as dl_branch_aware_router
    from aos_api.dl_chart_tools_router import router as dl_chart_tools_router
    from aos_api.dl_dataset_preview_300_router import router as dl_dataset_preview_300_router
    from aos_api.dl_faq_troubleshoot_router import router as dl_faq_troubleshoot_router
    from aos_api.dl_flow_animation_router import router as dl_flow_animation_router
    from aos_api.dl_node_indicators_router import router as dl_node_indicators_router
    from aos_api.dl_permission_coloring_router import router as dl_permission_coloring_router
    from aos_api.dl_permission_simulation_router import router as dl_permission_simulation_router
    from aos_api.dl_plan_management_router import router as dl_plan_management_router
    from aos_api.dl_property_histogram_router import router as dl_property_histogram_router
    from aos_api.dl_related_artifacts_router import router as dl_related_artifacts_router
    from aos_api.dl_share_permission_router import router as dl_share_permission_router
    from aos_api.dl_stale_coloring_router import router as dl_stale_coloring_router
    from aos_api.dl_svg_export_router import router as dl_svg_export_router
    from aos_api.dl_user_permission_view_router import router as dl_user_permission_view_router
    from aos_api.fn_pipeline_status_router import router as fn_pipeline_status_router
    from aos_api.id_feature_matrix_router import router as id_feature_matrix_router
    from aos_api.id_osdk_react_router import router as id_osdk_react_router
    from aos_api.pb_add_data_modes_router import router as pb_add_data_modes_router
    from aos_api.pb_ai_functions_router import router as pb_ai_functions_router
    from aos_api.pb_branch_activity_router import router as pb_branch_activity_router
    from aos_api.pb_branch_version_router import router as pb_branch_version_router
    from aos_api.pb_color_groups_router import router as pb_color_groups_router
    from aos_api.pb_data_expectations_router import router as pb_data_expectations_router
    from aos_api.pb_detail_sidebar_router import router as pb_detail_sidebar_router
    from aos_api.pb_export_java_router import router as pb_export_java_router
    from aos_api.pb_fp_growth_router import router as pb_fp_growth_router
    from aos_api.pb_history_records_router import router as pb_history_records_router
    from aos_api.pb_marketplace_pkg_router import router as pb_marketplace_pkg_router
    from aos_api.pb_override_dataset_router import router as pb_override_dataset_router
    from aos_api.pb_param_system_router import router as pb_param_system_router
    from aos_api.pb_show_hide_nodes_router import router as pb_show_hide_nodes_router
    from aos_api.pb_snapshot_incremental_router import router as pb_snapshot_incremental_router
    from aos_api.pb_structured_semi_router import router as pb_structured_semi_router
    from aos_api.pb_transform_library_router import router as pb_transform_library_router
    from aos_api.pb_unit_test_router import router as pb_unit_test_router
    from aos_api.pb_view_switch_router import router as pb_view_switch_router
    from aos_api.pb_virtual_data_gen_router import router as pb_virtual_data_gen_router
    from aos_api.di_stream_alert_router import router as di_stream_alert_router
    from aos_api.di_monitor_rule_router import router as di_monitor_rule_router
    from aos_api.di_notif_sub_router import router as di_notif_sub_router
    from aos_api.di_checkpoint_ft_router import router as di_checkpoint_ft_router
    from aos_api.di_backing_ds_router import router as di_backing_ds_router
    from aos_api.di_live_log_router import router as di_live_log_router
    from aos_api.di_schema_config_router import router as di_schema_config_router
    from aos_api.di_detail_subpanel_router import router as di_detail_subpanel_router
    from aos_api.dh_health_summary_router import router as dh_health_summary_router
    from aos_api.dh_troubleshoot_guide_router import router as dh_troubleshoot_guide_router
    from aos_api.dl_ontology_browse_router import router as dl_ontology_browse_router
    from aos_api.dl_history_detail_router import router as dl_history_detail_router
    from aos_api.dl_save_open_chart_router import router as dl_save_open_chart_router
    from aos_api.dl_share_link_router import router as dl_share_link_router
    from aos_api.pb_breaking_change_detect_router import router as pb_breaking_change_detect_router
    from aos_api.cr_model_dev_repo_router import router as cr_model_dev_repo_router
    from aos_api.cr_doc_assist_router import router as cr_doc_assist_router
    from aos_api.cr_pr_review_router import router as cr_pr_review_router
    from aos_api.cr_code_review_req_router import router as cr_code_review_req_router
    from aos_api.cr_dataset_alias_router import router as cr_dataset_alias_router
    from aos_api.cr_multi_artifact_router import router as cr_multi_artifact_router
    from aos_api.cr_artifact_credential_router import router as cr_artifact_credential_router
    from aos_api.cr_artifact_registry_router import router as cr_artifact_registry_router
    from aos_api.cr_ai_error_enhance_router import router as cr_ai_error_enhance_router
    from aos_api.cr_aip_template_recommend_router import router as cr_aip_template_recommend_router
    from aos_api.mt_code_reuse_router import router as mt_code_reuse_router
    from aos_api.id_shell_terminal_router import router as id_shell_terminal_router
    from aos_api.id_key_binding_router import router as id_key_binding_router
    from aos_api.id_vsix_install_router import router as id_vsix_install_router
    from aos_api.id_command_palette_router import router as id_command_palette_router
    from aos_api.id_python_snippet_router import router as id_python_snippet_router
    from aos_api.id_refresh_token_router import router as id_refresh_token_router
    from aos_api.id_install_python_env_router import router as id_install_python_env_router
    from aos_api.id_public_extension_router import router as id_public_extension_router
    from aos_api.di_virtual_table_create_router import router as di_virtual_table_create_router
    from aos_api.dh_escalate_router import router as dh_escalate_router
    from aos_api.pb_expr_func_index_router import router as pb_expr_func_index_router
    from aos_api.cr_transform_repo_router import router as cr_transform_repo_router
    from aos_api.cr_editor_context_menu_router import router as cr_editor_context_menu_router
    from aos_api.cr_spark_profiles_router import router as cr_spark_profiles_router
    from aos_api.cr_docker_artifact_publish_router import router as cr_docker_artifact_publish_router
    from aos_api.cr_code_autocomplete_router import router as cr_code_autocomplete_router
    from aos_api.mt_python_transform_df_router import router as mt_python_transform_df_router
    from aos_api.mt_java_transform_api_router import router as mt_java_transform_api_router
    from aos_api.mt_r_transform_router import router as mt_r_transform_router
    from aos_api.mt_spark_version_mgmt_router import router as mt_spark_version_mgmt_router
    from aos_api.mt_unit_test_router import router as mt_unit_test_router
    from aos_api.mt_data_expectations_router import router as mt_data_expectations_router
    from aos_api.id_geospatial_framework_router import router as id_geospatial_framework_router
    from aos_api.id_vertex_digital_twin_router import router as id_vertex_digital_twin_router
    from aos_api.id_timeseries_router import router as id_timeseries_router
    for m in [
        bd_dep_task_abort_router, bd_force_build_router, bd_freshness_router, cr_build_affected_router, cr_default_branch_router, cr_fallback_branch_router, cr_impact_analysis_router, dc_agent_yaml_router,
        dc_app_state_router, dc_curl_import_router, dc_export_tasks_router, dc_stream_preview_router, dc_sync_troubleshoot_router, dc_test_connection_router, dc_webhook_source_router, di_auto_dedup_router,
        di_auto_register_router, di_compression_toggle_router, di_consistency_guarantee_router, di_data_consistency_router, di_dataset_branch_router, di_db_schema_table_router, di_export_config_router, di_external_access_router,
        di_external_transforms_router, di_force_build_router, di_freshness_detect_router, di_hot_cold_storage_router, di_key_by_router, di_latency_sampling_router, di_live_archive_router, di_logic_change_trigger_router,
        di_output_path_router, di_partition_control_router, di_permission_roles_router, di_primary_key_config_router, di_reset_stream_router, di_s3_api_router, di_source_based_transform_router, di_spark_engine_router,
        di_stream_schema_router, di_streaming_latency_router, di_text_extraction_router, di_third_party_access_router, di_transforms_external_router, di_view_creation_router, di_virtual_storage_router, di_virtual_table_router,
        dl_branch_aware_router, dl_chart_tools_router, dl_dataset_preview_300_router, dl_faq_troubleshoot_router, dl_flow_animation_router, dl_node_indicators_router, dl_permission_coloring_router, dl_permission_simulation_router,
        dl_plan_management_router, dl_property_histogram_router, dl_related_artifacts_router, dl_share_permission_router, dl_stale_coloring_router, dl_svg_export_router, dl_user_permission_view_router, fn_pipeline_status_router,
        id_feature_matrix_router, id_osdk_react_router, pb_add_data_modes_router, pb_ai_functions_router, pb_branch_activity_router, pb_branch_version_router, pb_color_groups_router, pb_data_expectations_router,
        pb_detail_sidebar_router, pb_export_java_router, pb_fp_growth_router, pb_history_records_router, pb_marketplace_pkg_router, pb_override_dataset_router, pb_param_system_router, pb_show_hide_nodes_router,
        pb_snapshot_incremental_router, pb_structured_semi_router, pb_transform_library_router, pb_unit_test_router, pb_view_switch_router, pb_virtual_data_gen_router, di_stream_alert_router, di_monitor_rule_router,
        di_notif_sub_router, di_checkpoint_ft_router, di_backing_ds_router, di_live_log_router, di_schema_config_router, di_detail_subpanel_router, dh_health_summary_router, dh_troubleshoot_guide_router,
        dl_ontology_browse_router, dl_history_detail_router, dl_save_open_chart_router, dl_share_link_router, pb_breaking_change_detect_router, cr_model_dev_repo_router, cr_doc_assist_router, cr_pr_review_router,
        cr_code_review_req_router, cr_dataset_alias_router, cr_multi_artifact_router, cr_artifact_credential_router, cr_artifact_registry_router, cr_ai_error_enhance_router, cr_aip_template_recommend_router, mt_code_reuse_router,
        id_shell_terminal_router, id_key_binding_router, id_vsix_install_router, id_command_palette_router, id_python_snippet_router, id_refresh_token_router, id_install_python_env_router, id_public_extension_router,
        di_virtual_table_create_router, dh_escalate_router, pb_expr_func_index_router, cr_transform_repo_router, cr_editor_context_menu_router, cr_spark_profiles_router, cr_docker_artifact_publish_router, cr_code_autocomplete_router,
        mt_python_transform_df_router, mt_java_transform_api_router, mt_r_transform_router, mt_spark_version_mgmt_router, mt_unit_test_router, mt_data_expectations_router, id_geospatial_framework_router, id_vertex_digital_twin_router,
        id_timeseries_router,
    ]:
        r.include_router(m)

    # -- Phase routers (from aos_api.routers.xxx import router as ...) --
    from aos_api.routers.phase5_pipelines import router as phase5_pipelines_router
    from aos_api.routers.phase5_schedules import router as phase5_schedules_router
    from aos_api.routers.phase5_datasets import router as phase5_datasets_router
    from aos_api.routers.phase6_connectors import router as phase6_connectors_router
    from aos_api.routers.phase6_sources import router as phase6_sources_router
    from aos_api.routers.phase6_schemas import router as phase6_schemas_router
    from aos_api.routers.phase6_syncs import router as phase6_syncs_router
    from aos_api.routers.phase6_media_sets import router as phase6_media_sets_router
    from aos_api.routers.phase6_documents import router as phase6_documents_router
    for m in [
        phase5_pipelines_router, phase5_schedules_router, phase5_datasets_router, phase6_connectors_router, phase6_sources_router, phase6_schemas_router, phase6_syncs_router, phase6_media_sets_router,
        phase6_documents_router,
    ]:
        r.include_router(m)

    return r

def create_model_router() -> APIRouter:
    """Model domain: 15 routers."""
    r = APIRouter(prefix="", tags=["Model"])

    # -- from aos_api.routers import xxx --
    from aos_api.routers import (
        gantt_ml_drag_pricing,
    )
    for m in [
        gantt_ml_drag_pricing,
    ]:
        r.include_router(m.router)

    # -- W4 routers (from aos_api.xxx_router import router as ...) --
    from aos_api.gs_ontology_geo_router import router as gs_ontology_geo_router
    from aos_api.gs_geospatial_framework_router import router as gs_geospatial_framework_router
    from aos_api.gs_coord_projection_router import router as gs_coord_projection_router
    from aos_api.gs_map_layer_overlay_router import router as gs_map_layer_overlay_router
    from aos_api.gs_map_template_router import router as gs_map_template_router
    from aos_api.gs_digital_twin_engine_router import router as gs_digital_twin_engine_router
    from aos_api.gs_causal_analysis_router import router as gs_causal_analysis_router
    from aos_api.gs_realtime_situation_router import router as gs_realtime_situation_router
    from aos_api.gs_timeseries_object_type_router import router as gs_timeseries_object_type_router
    from aos_api.gs_sensor_data_model_router import router as gs_sensor_data_model_router
    for m in [
        gs_ontology_geo_router, gs_geospatial_framework_router, gs_coord_projection_router, gs_map_layer_overlay_router, gs_map_template_router, gs_digital_twin_engine_router, gs_causal_analysis_router, gs_realtime_situation_router,
        gs_timeseries_object_type_router, gs_sensor_data_model_router,
    ]:
        r.include_router(m)

    # -- Phase routers (from aos_api.routers.xxx import router as ...) --
    from aos_api.routers.model_catalog import router as phase2_model_catalog_router
    from aos_api.routers.model_providers import router as phase2_model_providers_router
    from aos_api.routers.model_routes import router as phase2_model_routes_router
    from aos_api.routers.model_capacity import router as phase2_model_capacity_router
    for m in [
        phase2_model_catalog_router, phase2_model_providers_router, phase2_model_routes_router, phase2_model_capacity_router,
    ]:
        r.include_router(m)

    return r

def create_admin_router() -> APIRouter:
    """Admin domain: 8 routers."""
    r = APIRouter(prefix="", tags=["Admin"])

    # -- from aos_api.routers import xxx --
    from aos_api.routers import (
        auth_oidc,
        authz,
        orgs,
        ops_tenants,
        ops_ttl,
        workspaces,
        cap_and_markings,
    )
    for m in [
        auth_oidc, authz, orgs, ops_tenants, ops_ttl, workspaces, cap_and_markings,
    ]:
        r.include_router(m.router)

    # -- W4 routers (from aos_api.xxx_router import router as ...) --
    from aos_api.au_policy_hot_reload_router import router as au_policy_hot_reload_router
    for m in [
        au_policy_hot_reload_router,
    ]:
        r.include_router(m)

    return r

def create_infra_router() -> APIRouter:
    """Infra domain: 20 routers."""
    r = APIRouter(prefix="", tags=["Infra"])

    # -- from aos_api.routers import xxx --
    from aos_api.routers import (
        health,
        metrics,
        plugins,
        platform_integrations,
        runtime_write,
        analytics,
        ssl_health_snooze_marketplace,
        linter_foundry_rules,
        autoscale_telemetry_volume_cop,
        tracing_perf_geo_map,
        vertex_geo_ts_process_hyperauto,
        dicom_workshop_docintel,
        es_sap_stream,
    )
    for m in [
        health, metrics, plugins, platform_integrations, runtime_write, analytics, ssl_health_snooze_marketplace, linter_foundry_rules,
        autoscale_telemetry_volume_cop, tracing_perf_geo_map, vertex_geo_ts_process_hyperauto, dicom_workshop_docintel, es_sap_stream,
    ]:
        r.include_router(m.router)

    # -- W4 routers (from aos_api.xxx_router import router as ...) --
    from aos_api.vs_module_interface_router import router as vs_module_interface_router
    from aos_api.vs_events_router import router as vs_events_router
    from aos_api.vs_event_idempotent_router import router as vs_event_idempotent_router
    from aos_api.es_auto_ontology_gen_router import router as es_auto_ontology_gen_router
    from aos_api.vs_timeseries_set_router import router as vs_timeseries_set_router
    from aos_api.es_sap_batch_import_router import router as es_sap_batch_import_router
    from aos_api.es_derived_element_intel_router import router as es_derived_element_intel_router
    for m in [
        vs_module_interface_router, vs_events_router, vs_event_idempotent_router, es_auto_ontology_gen_router, vs_timeseries_set_router, es_sap_batch_import_router, es_derived_element_intel_router,
    ]:
        r.include_router(m)

    return r

def create_agent_router() -> APIRouter:
    """Agent domain: 3 routers."""
    r = APIRouter(prefix="", tags=["Agent"])

    # -- from aos_api.routers import xxx --
    from aos_api.routers import (
        buddy,
        agent_health_migration_webhook,
    )
    for m in [
        buddy, agent_health_migration_webhook,
    ]:
        r.include_router(m.router)

    # -- Phase 6 agents (from aos_api.routers.phase6_agents import router as ...) --
    from aos_api.routers.phase6_agents import router as phase6_agents_router
    r.include_router(phase6_agents_router)

    return r

def create_system_router() -> APIRouter:
    """System domain: 4 routers."""
    r = APIRouter(prefix="", tags=["System"])

    # -- from aos_api.routers import xxx --
    from aos_api.routers import (
        me,
        otp,
        ops_version_matrix,
        ops_local,
    )
    for m in [
        me, otp, ops_version_matrix, ops_local,
    ]:
        r.include_router(m.router)

    return r

def create_apollo_router() -> APIRouter:
    """Apollo domain: 9 routers."""
    r = APIRouter(prefix="", tags=["Apollo"])

    # -- W4 routers (from aos_api.xxx_router import router as ...) --
    from aos_api.cp_multi_spoke_monitor_router import router as cp_multi_spoke_monitor_router
    from aos_api.hs_remote_dispatch_router import router as hs_remote_dispatch_router
    from aos_api.hs_status_report_back_router import router as hs_status_report_back_router
    from aos_api.fr2_incremental_package_router import router as fr2_incremental_package_router
    from aos_api.cp_realtime_situation_router import router as cp_realtime_situation_router
    from aos_api.cp_alert_router import router as cp_alert_router
    for m in [
        cp_multi_spoke_monitor_router, hs_remote_dispatch_router, hs_status_report_back_router, fr2_incremental_package_router, cp_realtime_situation_router, cp_alert_router,
    ]:
        r.include_router(m)

    # -- Phase routers (from aos_api.routers.xxx import router as ...) --
    from aos_api.routers.phase7_hub_spokes import router as phase7_hub_spokes_router
    from aos_api.routers.phase7_releases import router as phase7_releases_router
    from aos_api.routers.phase7_ferry import router as phase7_ferry_router
    for m in [
        phase7_hub_spokes_router, phase7_releases_router, phase7_ferry_router,
    ]:
        r.include_router(m)

    return r
# ── Domain registry ──
DOMAIN_ROUTERS = {
    "ontology": create_ontology_router,
    "workshop": create_workshop_router,
    "aip": create_aip_router,
    "data": create_data_router,
    "model": create_model_router,
    "admin": create_admin_router,
    "infra": create_infra_router,
    "agent": create_agent_router,
    "system": create_system_router,
    "apollo": create_apollo_router,
}
