"""Domain router aggregates — group 505 routers into 10 domain-level APIRouters.

This file is generated by scripts/generate_domain_aggregates.py from the
DOMAIN_MAP defined in docs/228-结构化风险修复计划.md.
"""
from __future__ import annotations

from fastapi import APIRouter


def create_ontology_router() -> APIRouter:
    """Ontology domain: 84 routers."""
    r = APIRouter(prefix="/v1", tags=["Ontology"])

    # -- aos_api.routers.* --
    from aos_api.routers import (
        ontology,
        ontology_governance,
        ontology_management,
        ontology_data_layer,
        oe_enhancements,
        object_editing,
        oma_editor,
        type_system,
        object_sets,
        object_storage_indexing,
        ontology_roles,
        ontology_outputs,
        object_views,
        object_explorer,
        funnel,
        funnel_mappings,
        multi_language,
        multi_source,
        materialized_access_control,
        incremental_sync,
        csv_ontology_export_action_metrics,
    )
    for m in [ontology, ontology_governance, ontology_management, ontology_data_layer,
              oe_enhancements, object_editing, oma_editor, type_system,
              object_sets, object_storage_indexing, ontology_roles, ontology_outputs,
              object_views, object_explorer, funnel, funnel_mappings,
              multi_language, multi_source, materialized_access_control,
              incremental_sync, csv_ontology_export_action_metrics]:
        r.include_router(m.router)

    return r


def create_workshop_router() -> APIRouter:
    """Workshop domain: 88 routers."""
    r = APIRouter(prefix="/v1", tags=["Workshop"])

    from aos_api.routers import (
        modules, workshop_phase1, gantt, compute_module,
        compute_module_extras, compute_module_publish, drafts,
        dev_tooling, web_ide, workshop_compute_api,
        integration_maintenance, scheduling, scheduling_rules_lint,
        actions, action_enhancements, action_params, action_further,
        action_webhook, action_finale, action_rules, action_visual_editor,
        media_references, media_sets, ms_header_extractor,
        pp_toolbar_settings, ds_context_menu,
    )
    for m in [modules, workshop_phase1, gantt, compute_module,
              compute_module_extras, compute_module_publish, drafts,
              dev_tooling, web_ide, workshop_compute_api,
              integration_maintenance, scheduling, scheduling_rules_lint,
              actions, action_enhancements, action_params, action_further,
              action_webhook, action_finale, action_rules, action_visual_editor,
              media_references, media_sets, ms_header_extractor,
              pp_toolbar_settings, ds_context_menu]:
        r.include_router(m.router)

    return r


def create_aip_router() -> APIRouter:
    """AIP domain: 57 routers."""
    r = APIRouter(prefix="/v1", tags=["AIP"])

    from aos_api.routers import (
        aip_assist, aip_extras, aip_nodes, logic, logic_flows,
        tool_registry, evals, file_processing, decision_audit,
        l4_automation, llm_routing, llm_extras, llm_node_agent_proxy,
    )
    for m in [aip_assist, aip_extras, aip_nodes, logic, logic_flows,
              tool_registry, evals, file_processing, decision_audit,
              l4_automation, llm_routing, llm_extras, llm_node_agent_proxy]:
        r.include_router(m.router)

    return r


def create_data_router() -> APIRouter:
    """Data domain: 150 routers."""
    r = APIRouter(prefix="/v1", tags=["Data"])

    from aos_api.routers import (
        builds, data_connection_admin, data_connection_extras,
        data_connection_export, data_connection_webhook, data_connection_security,
        data_health, data_health_plus, data_health_integration,
        dataset_preview_health, data_transaction,
        lineage, lineage_views, lineage_visualization,
        pipelines, transforms, python_functions, functions,
        function_types, functions_dev_tools, functions_runtime,
        pipeline_outputs, pipeline_type_semantics,
        pipeline_builder_extra, pipeline_canvas_extras, pipeline_ui_components,
        triggers_and_link_output, code_collaboration, column_impact,
        connection_cdc_schedule, shell_core, sql_console,
        writeback, expectation, timeseries_sap_functions,
        dc_completion_strategy, dc_stream_mgmt, dc_erp_crm,
        di_view_lineage, di_task_debug,
        dl_build_strategy, dl_build_preview, dl_dep_order, dl_stale_diagnosis,
        pb_build_vs_deploy, pb_build_profiles, pb_task_groups, pb_health_checks,
        cr_branch_menu, cr_pipeline_review, es_sap_stream,
    )
    for m in [builds, data_connection_admin, data_connection_extras,
              data_connection_export, data_connection_webhook, data_connection_security,
              data_health, data_health_plus, data_health_integration,
              dataset_preview_health, data_transaction,
              lineage, lineage_views, lineage_visualization,
              pipelines, transforms, python_functions, functions,
              function_types, functions_dev_tools, functions_runtime,
              pipeline_outputs, pipeline_type_semantics,
              pipeline_builder_extra, pipeline_canvas_extras, pipeline_ui_components,
              triggers_and_link_output, code_collaboration, column_impact,
              connection_cdc_schedule, shell_core, sql_console,
              writeback, expectation, timeseries_sap_functions,
              dc_completion_strategy, dc_stream_mgmt, dc_erp_crm,
              di_view_lineage, di_task_debug,
              dl_build_strategy, dl_build_preview, dl_dep_order, dl_stale_diagnosis,
              pb_build_vs_deploy, pb_build_profiles, pb_task_groups, pb_health_checks,
              cr_branch_menu, cr_pipeline_review, es_sap_stream]:
        r.include_router(m.router)

    return r


def create_apollo_router() -> APIRouter:
    """Apollo domain: 8 routers (Hub/Spoke/Ferry)."""
    r = APIRouter(prefix="/v1", tags=["Apollo"])
    # Phase 7 routers + cp/hs routers are imported directly from aos_api.*
    from aos_api import phase7_hub_spokes_router, phase7_releases_router, phase7_ferry_router
    for mod in [phase7_hub_spokes_router, phase7_releases_router, phase7_ferry_router]:
        r.include_router(mod)
    return r


def create_agent_router() -> APIRouter:
    """Agent domain: 3 routers."""
    r = APIRouter(prefix="/v1", tags=["Agent"])
    from aos_api.routers import buddy, agent_health_migration_webhook
    from aos_api import phase6_agents_router
    r.include_router(buddy.router)
    r.include_router(agent_health_migration_webhook.router)
    r.include_router(phase6_agents_router)
    return r


def create_model_router() -> APIRouter:
    """Model domain: 10 routers (geospatial, digital twin, ML)."""
    r = APIRouter(prefix="/v1", tags=["Model"])
    from aos_api.routers import gantt_ml_drag_pricing
    r.include_router(gantt_ml_drag_pricing.router)
    return r


def create_admin_router() -> APIRouter:
    """Admin domain: 6 routers (orgs, tenants, workspaces, auth)."""
    r = APIRouter(prefix="/v1", tags=["Admin"])
    from aos_api.routers import orgs, workspaces, authz, auth_oidc, cap_and_markings
    from aos_api import ops_tenants_router as ot
    for mod in [orgs, workspaces, authz, auth_oidc, cap_and_markings]:
        r.include_router(mod.router)
    r.include_router(ot)
    return r


def create_infra_router() -> APIRouter:
    """Infrastructure domain: 14 routers (health, metrics, plugins)."""
    r = APIRouter(prefix="/v1", tags=["Infrastructure"])
    from aos_api.routers import (
        health, metrics, runtime_write, analytics,
        plugins, platform_integrations,
        wave_ext, dicom_workshop_docintel,
        ssl_health_snooze_marketplace, linter_foundry_rules,
        autoscale_telemetry_volume_cop, tracing_perf_geo_map,
        vertex_geo_ts_process_hyperauto,
    )
    for m in [health, metrics, runtime_write, analytics, plugins,
              platform_integrations, wave_ext, dicom_workshop_docintel,
              ssl_health_snooze_marketplace, linter_foundry_rules,
              autoscale_telemetry_volume_cop, tracing_perf_geo_map,
              vertex_geo_ts_process_hyperauto]:
        r.include_router(m.router)
    return r


def create_system_router() -> APIRouter:
    """System domain: 5 routers (me, otp, ops)."""
    r = APIRouter(prefix="/v1", tags=["System"])
    from aos_api.routers import me, otp, ops_local
    from aos_api import ops_version_matrix_router as ov, ops_ttl_router as ottl
    r.include_router(me.router)
    r.include_router(otp.router)
    r.include_router(ops_local.router)
    r.include_router(ov)
    r.include_router(ottl)
    return r
