"""Stable public API for the domain-neutral asset registry."""

from aos_api.asset_registry.canonical_json import canonical_json, canonical_sha256
from aos_api.asset_registry.contracts import (
    BUNDLE_API_VERSION,
    BUNDLE_ID_PATTERN,
    CAPABILITY_PATTERN,
    SHA256_PATTERN,
    BundleArtifact,
    BundleCapabilities,
    BundleConflict,
    BundleDependency,
    BundleEvidence,
    BundleEvidenceStatus,
    BundleEvidenceType,
    BundleExports,
    BundleKind,
    BundleManifest,
    BundleMetadata,
    BundleMigrations,
    BundlePermissions,
    BundleSignature,
    BundleSpec,
    BundleVersionStatus,
    DowngradePolicy,
    LoadedBundle,
)
from aos_api.asset_registry.errors import (
    ERROR_HTTP_STATUS,
    ApprovalStaleError,
    AssetNotFoundError,
    AssetRegistryError,
    AssetRegistryErrorCode,
    BundleVersionImmutableError,
    DependencyConflictError,
    DependencyCycleError,
    DutySeparationRequiredError,
    IdempotencyConflictError,
    ManifestInvalidError,
    PreflightFailedError,
    RevisionConflictError,
    RollbackBlockedError,
    SignatureInvalidError,
    VerificationFailedError,
    VersionInvalidError,
)
from aos_api.asset_registry.manifest_loader import ManifestLoader
from aos_api.asset_registry.registry_service import BundleLoader, RegistryService
from aos_api.asset_registry.registry_store import (
    PostgresRegistryStore,
    RegistryStore,
)
from aos_api.asset_registry.semver import (
    SemVerError,
    parse_range,
    parse_version,
    satisfies,
    select_highest,
)
from aos_api.asset_registry.signature import (
    TrustRoot,
    TrustRootProvider,
    verify_ed25519,
)

__all__ = [
    "BUNDLE_API_VERSION",
    "BUNDLE_ID_PATTERN",
    "CAPABILITY_PATTERN",
    "ERROR_HTTP_STATUS",
    "SHA256_PATTERN",
    "ApprovalStaleError",
    "AssetNotFoundError",
    "AssetRegistryError",
    "AssetRegistryErrorCode",
    "BundleArtifact",
    "BundleCapabilities",
    "BundleConflict",
    "BundleDependency",
    "BundleEvidence",
    "BundleEvidenceStatus",
    "BundleEvidenceType",
    "BundleExports",
    "BundleKind",
    "BundleLoader",
    "BundleManifest",
    "BundleMetadata",
    "BundleMigrations",
    "BundlePermissions",
    "BundleSignature",
    "BundleSpec",
    "BundleVersionImmutableError",
    "BundleVersionStatus",
    "DependencyConflictError",
    "DependencyCycleError",
    "DowngradePolicy",
    "DutySeparationRequiredError",
    "IdempotencyConflictError",
    "LoadedBundle",
    "ManifestInvalidError",
    "ManifestLoader",
    "PostgresRegistryStore",
    "PreflightFailedError",
    "RegistryService",
    "RegistryStore",
    "RevisionConflictError",
    "RollbackBlockedError",
    "SemVerError",
    "SignatureInvalidError",
    "TrustRoot",
    "TrustRootProvider",
    "VerificationFailedError",
    "VersionInvalidError",
    "canonical_json",
    "canonical_sha256",
    "parse_range",
    "parse_version",
    "satisfies",
    "select_highest",
    "verify_ed25519",
]
